### ISSUE TITLE
2021.02.04 - Transparency Depth Sorting

### ISSUE THREAD

**Issue by michaeloldman** [TheGameCreators/GameGuruRepo#1056] opened 2021-04-02 23:38 UTC
These videos demonstrate depth sorting issues with objects using transparency>

This used to work in Classic but seems max can't produce same results atm.

MAX:
https://vimeo.com/532219573
https://vimeo.com/532475986

Horrendous Classic - But the 2 spheres worked!
https://vimeo.com/457429217

System Specs:
Operating System: Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: Z390 UD
Processor: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 32768MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)

**Comment by plemsoft** [comment] 2021-05-07 07:49
@michaeloldman The transparent sort should be fixed in the latest version , could you check and see if this is still a issue, thanks :)

**Comment by michaeloldman** [comment] 2021-05-07 11:42
@plemsoft Much better than before but still has issues as in video.

Previously I had to have the inner ocean single-sided or it had weird effects, like half the ocean disappearing

Currently if I leave the inner ocean single-sided it is much the same in the video, but now if I set the inner ocean double-sided it works much better. But still flickers and randomly culls outer land-mass model.

It will be easier to test if I send the models? I will post over on Discord if you like.

**Comment by LeeBamberTGC** [comment] 2021-05-07 12:21
@michaeloldman That would be great, perhaps even a small FPM so it can be loaded and the issue seen right away

**Comment by michaeloldman** [comment] 2021-05-07 12:23
@LeeBamberTGC have posted models on Discord - can do fpm if you like too :)

**Comment by michaeloldman** [comment] 2021-05-07 13:06
Hi @LeeBamberTGC uploaded info to discord with test map and models :)

**Comment by LeeBamberTGC** [comment] 2021-05-07 15:23
@michaeloldman It looks like there is some Z clashing happening or one object is CULLING the other.  The FPM was great and reproduces the issue perfectly!!

**Comment by LeeBamberTGC** [comment] 2021-05-07 15:25
For now you can set your planets model to no transparency and alpha clipped, this will give you the render you need:
![image](https://user-images.githubusercontent.com/35840583/117472486-d7efe600-af50-11eb-8a23-67935324c4c6.png)

**Comment by michaeloldman** [comment] 2021-05-07 19:29
@LeeBamberTGC - Thanks for looking at this.
The solution is OK, but not giving completely desired result.
It does stop the culling. But:
- When transparency of texture is used, the outer landmass is meant to be semi-transparent as well.
- Using the alpha clip hides the parts that are completely transparent, but the landmass areas are solid
- - whereas the idea was they could be seen through just a tad.

**Comment by michaeloldman** [comment] 2021-05-11 23:08
@LeeBamberTGC - fantastic! Nailed it 👍 
Works a treat now - all it needs is ability to scroll texture across inner ocean and the effect will be complete 🙂 
- I will put that down to an enhancement perhaps....

**Closed** 2021-08-14 07:48 UTC
Labels: fixed, Max
