### ISSUE TITLE
Lost my whole level when renamed it ingame

### ISSUE THREAD

**Issue by davekirk85** [TheGameCreators/GameGuruRepo#2352] opened 2022-03-01 23:36 UTC
So I just renamed the level ingame and it deleted the contents and reverted to a default map, 3 days solid work gone.
Anyway I can sort this? Even the back ups load up with it all gone :/

**Comment by ArgentArts** [comment] 2022-03-02 00:23
Did you try Open Level to see if the old map was there under the old name?

**Comment by UltraVox001** [comment] 2022-03-02 09:39
You are using an Alpha version with all kinds of bugs.
But, even if it was a completely finalized version, you must imperatively create backup copies of all your maps.

Personally, I make manual copies of map files (.fpm).
No software should be trusted.

**Comment by LeeBamberTGC** [comment] 2022-03-02 12:20
@dllllllllllb Trace the steps to reproduce this one, and then we can hand to Preben to resolve if the issue is repeatable.

**Comment by dllllllllllb** [comment] 2022-03-25 11:17
@LeeBamberTGC In the case I managed to reproduce this, it is more of an user error.
Steps to reproduce:
Make a new level
Load, play and save it
Go back to storyboard editor
Save project
Rename level
Quit
Load the project and play level

After renaming the level we should probably force a project save to avoid this.

**Comment by LeeBamberTGC** [comment] 2022-03-25 11:25
@dllllllllllb Thanks for reproducing and the steps :)  Assigned to Preben who is our Storyboard Guy!

**Comment by plemsoft** [comment] 2022-03-25 14:37
@davekirk85 Thanks for reporting this issue , this has been fixed and will be in the next update :)

**Closed** 2022-05-02 11:55 UTC
Labels: bug, Fixed but need confirmation., Max, Medium, Storyboard Editor
