### ISSUE TITLE
GGMax - Bug - CRASH - runtime error from incorrect image path in script CRASHES Max

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#3295] opened 2022-06-13 06:10 UTC
Forgot to update the file path to an image a script was looking for to display on the screen and rather than simply giving me a runtime error popup message like good 'ol GG Classic used to do and carry on my way, MAX **_really_** doesn't like it if it can't find an image, and the program just closes.

**Comment by Teabone3** [comment] 2022-06-13 22:40
I've posted this issue previously: #3181

Its certainly a pretty big issue for me with Max. Since I do a lot of sprite work. I very often get crashes.

**Comment by LeeBamberTGC** [comment] 2022-06-14 09:58
@Kravenwolf @Teabone3 I added an Image Zone, selected an image file, test game worked, then I renamed the image file and ran test game again, there was no crash, and the correct blank image:

![image](https://user-images.githubusercontent.com/35840583/173550577-56f6e009-c054-4c94-a0ff-3f8e19a4fc69.png)

Can you reproduce the above and confirm this is so in the latest version, thanks!

**Comment by LeeBamberTGC** [comment] 2022-06-15 11:16
@Kravenwolf I am assuming then the out of the box stock image zone behavior works fine for you, and the issue is the custom script that crashes. I had a quick look at the load and create calls are OUTSIDE of any function of the script. I recommend looking at the "markers\imageinzone.lua" script for a better way to load an image, assign to a sprite, and where to locate your image files.

**Comment by AmenMoses** [comment] 2022-06-16 17:59
@Lee, the imageinzone doesn't use sprites unless you select the full screen option, and then MAX crashes.

**Comment by ZakJudges** [comment] 2023-01-27 14:55
Hi all, I have not been able to reproduce this issue. I tried a full screen image zone with a path that does not exist, and copied the steps shown in the above video, but did not get any crash. Could someone confirm if they still experience the crash? Thanks!

**Comment by ZakJudges** [comment] 2023-02-16 09:31
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks

**Closed by ZakJudges** 2023-02-16 09:31 UTC
Labels: bug, help wanted, Fixed but need confirmation., Max, CRASH!
