### ISSUE TITLE
GG Max - Demo Games - PLAY GAME

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2405] opened 2022-03-04 20:32 UTC
Just downloaded latest Max version, and thought i would try river raiders.
I selected the demo game, hit play game, but after picking up the pistol, I do not see the pistol in my hand when i fire,

But if i select EDIT game, then click TEST game, i do see the pistol in my hand.

Also, when test playing this game, i noticed one enemy was constantly resurrecting after been killed.

EDIT 1: After testing this on all 3 games were you start with a weapon,, so Island Showdown, Jungle Fever and River Raiders, i selected game, then PLAY game, and every time i started and the pistol i started with was not visible.

EDIT 2: After playing Jungle Fever, i noticed that after picking up extra HP, you ended up with more than Max HP, IS that meant to work like that ?

**Comment by ZakJudges** [comment] 2022-03-08 12:08
Hi @Tum1370, I wasn't able to reproduce the pistol not being visible. Would you be able to verify your files with the updater and let me know if the issue persists? :)

> After playing Jungle Fever, i noticed that after picking up extra HP, you ended up with more than Max HP, IS that meant to work like that ?
@LeeBamberTGC Is this by design or bug? I could add a tick box to the behavior to choose this if you like?

**Comment by LeeBamberTGC** [comment] 2022-03-08 12:14
@ZakJudges It is by design :)

**Comment by Tum1370** [comment] 2022-03-08 12:46
@ZakJudges I had already verified all files using the updater. When I am home I will totally uninstall and reinstall everything and test again.

**Comment by ZakJudges** [comment] 2022-03-08 13:51
@Tum1370 I am using this button to start the game:
![Uploading Screenshot 2022-03-08 135055.png…]()

**Comment by Tum1370** [comment] 2022-03-08 13:56
@ZakJudges ok yes that’s the button I used. 
I will be home in 30 mi s and will uninstall and reinstall and test again.

**Comment by Tum1370** [comment] 2022-03-08 15:44
Well after uninstalling and  reinstalling the whole of Max, i get exactly the same thing. 
No weapon visible when i click play game from the screen you linked. 
I tried recording it but the file was to large and i could not crop it.
Even when i click RELOAD for the weapon, the weapon is invisible.
As you can see from the image below.

![image](https://user-images.githubusercontent.com/66874403/157272675-dee89c5e-262e-4c2a-b840-30a487f9cf66.png)

**Comment by ZakJudges** [comment] 2022-03-08 16:00
@Tum1370 Thank you for the extra info. Does the issue occur if you export the Jungle Fever demo as a standalone? :)

**Comment by Tum1370** [comment] 2022-03-08 16:02
@ZakJudges 
I just added 2 more images from the River Raiders, exactly the same thing.
I will test exporting the game now. and report back.

**Comment by ZakJudges** [comment] 2022-03-08 16:16
@plemsoft I'm having a hard time reproducing this one. Any ideas why the objects don't show ONLY when started from the Hub? To my knowledge, we handle loading the demo maps the same as any other. Is that correct? :)

**Comment by Tum1370** [comment] 2022-03-08 20:12
Just tried Island Showdown, by pressing play from the HUB.
I Have a gun, i can hear the gun, But i just can not see the gun. It also does no damage.

![image](https://user-images.githubusercontent.com/66874403/157317172-2cb9da4b-1143-41ef-bc4b-e8b297c6e7b7.png)

**Comment by LeeBamberTGC** [comment] 2022-03-08 21:24
@Tum1370 With the latest internal build you SHOULD see a gun :)  Bear in mind the PLAY GAME button is still being worked on to get you back where you started, but even so, you should get to play the level okay. Does anyone elsereproduce this?

**Comment by Tum1370** [comment] 2022-03-11 20:09
Just updated to latest version on 11/3/22.
Same thing, i start a game from the HUB by pressing PLAY GAME, and i dont have a gun, even though i can hear it and reload it.
I can not do damage with it though.

![image](https://user-images.githubusercontent.com/66874403/157952296-26bd663c-2ea4-474b-bc29-92a6836289ce.png)

**Comment by Tum1370** [comment] 2022-03-19 09:12
Latest build today, Saturday 19/3.
Still when i press PLAY GAME from the HUB i do not have the weapon visible.

![image](https://user-images.githubusercontent.com/66874403/159115155-699be6ed-9c42-4341-87a8-eb3a4d252a4a.png)

**Comment by Tum1370** [comment] 2022-03-19 10:21
I have just tried everything to fix this issue, 
I uninstalled everything to do with Max.
Cleaned my registry to clear anything to do with Max.
And reinstalled the whole thing.
Yet it still does this problem.

**Comment by LeeBamberTGC** [comment] 2022-03-21 21:12
@ZakJudges Do you want to confirm this is done for this weeks build, thanks!

**Comment by ZakJudges** [comment] 2022-03-22 08:44
@LeeBamberTGC I still haven't been able to sort this yet, since I can't reproduce it, I tried looking at differences between the weapon loading in standalone vs in-editor. The only difference I could see was the ammo pool system doesn't work in standalone when one type of ammo can be used for multiple weapons. Do you have any suggestions for where things might be going wrong? Thanks :)

**Comment by Tum1370** [comment] 2022-03-25 08:52
I just tried a demo game, but this time i did not press the PLAY GAME from the hub, I ticked the "Standalone Test ALL levels" from the storyboard. 
With this ticked, and tried playing the game, I do NOT have a gun.

But if i DONT tick this box in the pic, and just test the single level. I DO have the gun.
Very strange bug.

![Standalone Test](https://user-images.githubusercontent.com/66874403/160087575-b713c984-a6b0-4b94-b5f6-41ff51b76634.jpg)

**Comment by ZakJudges** [comment] 2022-03-25 09:17
Hi @Tum1370, thank you for the extra information, that should help us identify the cause of the issue quicker. We are aiming to have this issue sorted in the first update to MAX after its early access release :)

**Comment by Tum1370** [comment] 2022-03-25 15:32
Another update on this issue.
I have just tried playing a demo game but using another different PLAY GAME option.
This time i used the one from the drop down menu as in the picture.
This time the gun and game was working correctly using this PLAY GAME option.

![Untitled](https://user-images.githubusercontent.com/66874403/160151903-609cfab8-3151-4d72-8507-9d8d5c8f1171.png)

**Comment by ZakJudges** [comment] 2022-03-31 16:08
Hi @Tum1370, could you try out the attached executable, and let me know if it sorts this issue for you? :) 
You will need to replace your existing GameGuruMAX.exe with this one. Note that it is a debug build so will be very slow compared to what you are used to, it would be best to move your normal .exe file, so it can be easily restored later. Thanks!
[GameGuruMAX.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8391200/GameGuruMAX.zip)

**Comment by Tum1370** [comment] 2022-03-31 18:05
I have just tried this and Max will not run when using this version for me.
I am on the Steam version currently,

**Comment by LeeBamberTGC** [comment] 2022-03-31 19:55
@Tum1370 When Zak has a fix in the EXPERIMENTAL build, we will mak it as Fixed But Needs Confirmation here so you know when to check it out officially.  Debug builds often require additional Windows redist files to work propetly alas.

**Comment by Tum1370** [comment] 2022-04-02 07:36
This no gun issue is there on every method I have tried to play the full game.
When playing single level I have a gun.

**Comment by Tum1370** [comment] 2022-04-02 13:57
I just tried the EXE that Zak posted here for me to try.
 I tried this again, after installing an ALL Visual C++ Runtime installer, so that installed every one available up to 2022.
But still even after installing the full package of Runtimes i still get the same error message when trying the debug version.
So am not sure how i could try this version now for Zak.

![image](https://user-images.githubusercontent.com/66874403/161386516-96bc3da8-3806-4205-a0d4-4cf77a0ddf51.png)

**Comment by GraPhiX-Guru** [comment] 2022-04-02 17:12
@Tum1370  download these DLL's and put hem in the same directory as GameGuruMAX.exe https://drive.google.com/file/d/1RjZMuTjZCuz6UqUReR1MMU39-MaIWiMa/view

**Comment by Tum1370** [comment] 2022-04-02 17:31
@GraPhiX-Guru Thanks, That got the EXE working.
@ZakJudges I just tested the EXE you ask me to, First when i downloaded it, windows defender was constantly removing it due to a threat, but after getting it downloaded, i tested it, and still when i hit PLAY GAME i have no weapon visible.

**Comment by Tum1370** [comment] 2022-04-08 18:36
@ZakJudges 
Sorry to tell you but latest build i just download now, this is NOT fixed.
PLAY GAME from hub, still missing a gun.

**Comment by ZakJudges** [comment] 2022-04-11 15:45
@Tum1370 Thanks for getting back to me. It's unlikely the issue is caused by your pc setup since the gun only disappears in one specific scenario. 

@LeeBamberTGC Any chance you could take a look at this one? I'm not sure what else to try :)

**Comment by LeeBamberTGC** [comment] 2022-04-11 15:51
@ZakJudges Are you able to reproduce it on your system Zak?

**Comment by ZakJudges** [comment] 2022-04-11 15:53
@LeeBamberTGC No I haven't been able to reproduce. But I believe there are at least three users seeing this issue

**Comment by LeeBamberTGC** [comment] 2022-04-11 15:56
@ZakJudges I have assigned to me. I have several PCs I can try the above on. If you could post the short version of how I reproduce this so I do not have to read the lot that would help ;)

**Comment by Tum1370** [comment] 2022-04-15 10:46
As a note to everyone, I am using the latest "12th Gen Intel(R) Core(TM) i9-12900K" CPU

Could this be causing me these issues that no one else is getting ?

**Comment by LeeBamberTGC** [comment] 2022-04-19 11:19
@Tum1370 Thanks for the extra info, I think I have an i9 in my NUC, I will check it out.

**Comment by Tum1370** [comment] 2022-04-20 14:02
@LeeBamberTGC 
I think this BUG is now fixed, Preben asked me to try changing the "vrmode=3" to "vrmode=0" in the setting file.
After doing this, i now have the gun visible in the DEMO GAMES, and in my OWN games when i press PLAY GAME from the HUB.

**Closed** 2022-04-20 14:47 UTC
Labels: bug, Max, High, SaveStandAlone
