### ISSUE TITLE
When aiming/shooting guns, water disappears

### ISSUE THREAD

**Issue by Sinergygames** [TheGameCreators/GameGuruRepo#3364] opened 2022-06-27 16:23 UTC
Maybe it a bug or has to do with water height but still, this does not look right and should be fixed.
https://youtu.be/NcvajKUUC3g?t=12

**Comment by Lemuripest93** [comment] 2022-06-27 19:02
Been meaning to report this myself, got the same issue.

**Comment by Necrym59** [comment] 2022-06-28 09:29
Already reported
https://github.com/TheGameCreators/GameGuruRepo/issues/3128

**Comment by ZakJudges** [comment] 2023-02-03 14:48
Closing this issue. Duplicate of #3128

**Closed by ZakJudges** 2023-02-03 14:48 UTC
Labels: bug, Max, High, Rendering
