### ISSUE TITLE
GG Max Install Failed

### ISSUE THREAD

**Issue by carabotm** [TheGameCreators/GameGuruRepo#885] opened 2021-02-07 23:44 UTC
I have tried several times to install GG Max using your min installer.  I tried at least half a dozen timed over a 24 hour period.  I then completely uninstalled whatever part files were installed, rebooted my PC, and tried again with  fresh install.  It still failed.
Here is the message that I got every time.
"GameeGuru Max seems  to have files missing, do you want to run the updater to verify your files?"
To which I replied "Yes" every time, only to have it fail again and again, getting the same message.

I am running Win 10 x64 on my Alienware PC, with Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz, 3601 Mhz, 4 Core(s), 8 Logical Processor(s).  My video adapter is an	NVIDIA GeForce GTX 745.

Please assist.
Thx
Manuel

**Comment by PaulSJ** [comment] 2021-02-10 16:14
Duplicate of #878

**Closed by PaulSJ** 2021-02-10 16:14 UTC
Labels: Max, bug
