### ISSUE TITLE
Easy builder bugs

### ISSUE THREAD

**Issue by mike123yy** [TheGameCreators/GameGuruRepo#4167] opened 2023-02-14 19:40 UTC
I've been trying to use the new easy builder and have come across quite a few bugs.
1.Easy builder crashes and closes quite often, usually when building something more than one story high
2.after saving the building stairs and windows disappear
3.where it shows the textures in the right-hand toolbar the roof texture option is barely showing so it's  un-clickable. Maybe having a scrollbar would help with this problem. I figured my monitor resolution might be the problem but changing to different resolutions didn't make a difference.
4.After exporting my building the ceilings of the building have a jittery effect. It seems to be happening because the upper floor is barely cutting into the ceiling and they're both fighting each other.
5.The texture seemed to be stretching in certain areas. My lower floor textures were fine but the upper floor textures were stretched and warped looking. It seems to be random which textures this happens to.

roof bug
![3](https://user-images.githubusercontent.com/41445779/218839736-ae41bae3-351b-4b14-9ba5-6c81dfd0aa15.jpg)
texture stretching
![2](https://user-images.githubusercontent.com/41445779/218839738-beb073a1-3396-4000-a6cc-d393bf5972af.jpg)
clipping
![1](https://user-images.githubusercontent.com/41445779/218839742-0cfef0f1-ec71-472b-8373-2ee7328a2b5b.jpg)
windows/stairs/doors Disappearing 
![4](https://user-images.githubusercontent.com/41445779/218839729-5750b6e7-780f-4075-9061-80de86905f84.jpg)

**Comment by davetgc** [comment] 2023-02-16 06:22
Hi, could you please post your system specs.

**Comment by mike123yy** [comment] 2023-02-16 14:41
windows 11
rtx 2070 super
i7-7700
16gb ram
1tb ssd

**Comment by ZakJudges** [comment] 2023-03-10 13:09
Hi @mike123yy, thank you for reporting these issues. Just checking if you are on the experimental version of GameGuru Max, or the regular public build? Thanks

**Comment by mike123yy** [comment] 2023-03-10 14:58
Just checked, it looks like I'm using the public preview version. I changed it a while back to use some of the features that were only available on that version. Is that maybe what's causing the issues?

**Comment by ZakJudges** [comment] 2023-03-10 15:56
@mike123yy There have been some fixes since the last public preview was released, it is possible that your crashes and the texture issues have been fixed, as I could not reproduce in the latest experimental build. You can find instructions for accessing the experimental build here: https://github.com/TheGameCreators/GameGuruRepo/issues/3907

**Comment by mike123yy** [comment] 2023-03-10 18:42
I just got done making a pretty large building. It would seem the texture stretching and the clipping through the ceiling seemed to be fixed. I did have it crash Several times when moving to the second story and starting to build their. It didn't happen on the smaller building, it only seems to happen if it's a larger structure with more geometry. The  roof texture box still seems to be getting cut off in the building menu Like in the picture above And it would seem that as long as you use default Windows,doors and stairs that they won't disappear after saving and closing out. Anything that is custom will.

**Comment by mike123yy** [comment] 2023-03-10 18:49
Here's a custom window for testing with the builder.  If you add it to the building and save and close then open the building backup it will disappear
[https://mega.nz/file/WAUjlTQQ#asz6fB7han-uckS2pUOtAAu6ehFiSRb4C4F9Z7Fn9s0](url)

**Comment by ZakJudges** [comment] 2023-03-17 11:46
@mike123yy, thank you for the files and video! Does the roof texture box still get cut off after pressing the 'Reset Texture Settings' button?

**Comment by ZakJudges** [comment] 2023-03-17 13:46
@mike123yy Thank you for reporting these issues. I have added some fixes which should sort them for you. The fixes will be included in the next experimental build on Steam. I did find one crash, which is fixed. However, if you continue to experience any crashes, please could you create a new issue, and include steps to reproduce. A video of what you are doing leading up to the crash is best, but a step by step also works. Thank you :)

**Comment by ZakJudges** [comment] 2023-03-17 15:39
@mike123yy, it is possible that some of the custom textures do not load correctly, causing the box to get cut off. If you could attach them here, or alternatively email me them, I can verify if that is the case. My email is zak@thegamecreators.com. Thank you

**Comment by mike123yy** [comment] 2023-03-17 17:10
Alright, I got a little more time to mess with it. It would seem as long as you put the textures directly into the texture bank folder they load up just fine without cutting off the roof box.That way when you click the reset to default textures it loads up the custom ones as well and has all the boxes showing. I was making separate folders organizing different texture sets inside the folder which seem to be causing the problem for some reason.That works good enough for me now that I know what to do. I can also confirm besides the Windows the custom stairs I was using don't disappear anymore after saving the project and coming back to it. So as long as nothing else pops up I would say these issues are pretty much fixed. Thanks

**Comment by mike123yy** [comment] 2023-03-17 19:23
I spoke too little too soon on the texture stretching and clipping.  Smaller structures won't glitch out the larger ones still seem to have a problem.  It looks fine in the editor but as soon as you export it and do a walkthrough this is what it looks like.  Everything else is working good though
https://youtu.be/xTqz9LsROF8

**Comment by ZakJudges** [comment] 2023-03-24 10:45
Hi @mike123yy, thank you for the testing. Would you be able to send me the .mbf file for the building seen in the video? Hopefully I can use it to reproduce the bug on my end. 

It should be in the Files->entitybank->User->buildingeditor folder 

Thanks :)

**Comment by mike123yy** [comment] 2023-03-24 14:39
I figured I should of kept That. I deleted that building and the others because my list of buildings was getting too long and they were broken anyway. I went ahead and tried to build the same exact building this morning but it's not having the texture stretching or clipping problem. It is having textures put in the wrong place which is another issue but not the other problems. There was an update pushed this morning before I started so maybe it helped something with the other issues.I can send you this building with the texture issues and I will give the building another try to try to reproduce the clipping and stretching results.
Here's the building with the textures in the wrong place.. It's putting brick over the walls and ceilings after the export
https://mega.nz/file/zQdgHaaY#7kx27i5SaZO9G2mnnKL4FK7KTJ9l4KMD9FahCJ-2Zdw

**Comment by ZakJudges** [comment] 2023-03-24 14:45
@mike123yy Thank you for the files, To reproduce the wrong textures being applied, I will need the custom textures that are being used on the building. Could you send those over too? If you'd prefer not to post them here, my email is zak@thegamecreators.com. Thanks :)

**Comment by ZakJudges** [comment] 2023-03-24 15:21
@mike123yy Thank you for the files, I have now been able to reproduce the issue :)

**Comment by LeeBamberTGC** [comment] 2023-04-01 02:25
@mike123yy Many changes to the BE export and smart object loading in RC build. Can you go through and confirm how many of the issues are still extant, thanks!

**Comment by mike123yy** [comment] 2023-04-01 19:39
I've been messing around with this for a little bit now and here's what I got. I tried exporting the current buildings I have too see if they would still be messed up. They seem fine, no stretching or clipping and the textures all seem to be in the right place except for the ceiling on the second floor. For some reason it keeps going back to the brick texture instead of the white textured ceiling I had it set to. I went back and checked to make sure it wasn't set to brick but that doesn't seem to be the case. It doesn't look that bad though with brick for the style of building I'm going for but it is still a bug. As far as the clipping and the stretching textures I can't reproduce them anymore so that seems to be fixed. The doors and windows seem to be staying in their places as well. It could be that the ceiling is bugged out because I built the building before the new update. I will give it a shot on trying to duplicate the building again and see if it happens with the new one. But besides that everything else is looking good!

**Comment by LeeBamberTGC** [comment] 2023-04-02 16:36
@mike123yy Next EXP build has a fix which ensures the doors and windows are not left after you lock and unlock them, which I think finishes off the main smart object issuues. The BE ceiling texture sounds like a smaller issue, maybe you can create a new issue which just covers that with a step by step and we can treat that separately.

**Comment by mike123yy** [comment] 2023-04-02 16:46
All right, sounds like a plan. Everything here is resolved except for the roof as far as I can see anyway. I will open a separate ticket for the roof texture issue. Thanks for the help

**Closed** 2023-04-02 17:07 UTC
Labels: bug, Fixed but need confirmation., Max, Medium, Building Editor
