### ISSUE TITLE
Opening the Object Library and typing quickly will crash Max. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1119] opened 2021-04-30 07:11 UTC
If you leave the color scheme as Blue, the default, it will not crash every time. But changing it any other color scheme, and typing fast in the search bar of the object library will result in a crash.

here is a video.. I only tried to type "asdf" into the search bar. 

https://www.youtube.com/watch?v=Jy4SO00cvu0

**Comment by rvanner** [comment] 2021-04-30 08:05
@Kitakazi Have you checked you are on the very latest internal build? We released another one yesterday that fixed a big crash. I have just tried changing the colour scheme and it did not crash for me.

**Comment by Granada1** [comment] 2021-04-30 10:29
I am not getting this problem, I have my colour scheme back to grey . On the latest build also

**Comment by 3coms** [comment] 2021-04-30 18:00
Hi
Getting the same, plus the scroll speeding up as you can see in the video below. I've got it today (2021_04_30).
https://youtu.be/vXN7MS5lWp0

**Comment by LeeBamberTGC** [comment] 2021-05-04 13:40
We have made some fixes that may relate to this. I am assuming we do not see this because we have stock folders in entitybank. If you can share your entire entitybank (email in confidence directly to me at lee@thegamecreators.com) I can reproduce the exact issue which I suspect is related to LOTS of entitybank sub folders.

**Comment by plemsoft** [comment] 2021-05-04 14:57
@LeeBamberTGC FYI: the crash reported by 3coms was a object that was trying to texture a mesh > 100 , i fixed this with 3coms, im sure Kitakazi crash is related to this. About the "scrolling" of the folder view , this has not been solved.

@3coms Do you know what "folder" name ... was causing the scrolling , perhaps you could try to add one at the time until you see the "scrolling" , thanks for your help :)

**Comment by 3coms** [comment] 2021-05-04 15:13
Hi
@ Preben
Gonna try about the scrolling, I guess both issues are related, it happens
when GGMax get corruption uploading certain meshes.
I'll try to upload entire warzone (b1_all, b2_all, etc) folder in my
entitybank to google drive, I'll send the download link to Lee and you,
when done. Please, remember my internet issues lately, so, it most likely
takes quite time to do. :)

regards
Alvaro aka 3com

**Comment by plemsoft** [comment] 2021-05-04 17:24
@3coms I think the other issues could also has fixed that, it was overwriting the memory, so if it takes that long then just wait until you get the next update so we can check if both issues is fixed :)

**Comment by 3coms** [comment] 2021-05-04 19:53
Hi
OK. Ty for report me. Meantime I'll continue uploading files to google
drive, 49% atm, fingers crossed. LOL
You guys needs these sort of meshes, since now the issue is general, any
non stop mesh in object lib being mouseover, and GGMax instantly close.

**Comment by Kitakazi** [comment] 2021-05-04 22:43
Hello, when I reported the crash I did not have any custom models in my
entitybank only stock assets. I haven't gotten a chance to try again since
then but I will later tonight when I get off work.

**Comment by Kitakazi** [comment] 2021-05-05 01:50
Actually now that I think about it, I might of had a lot of empty subfolders. They were all empty, but the named folders themselves I believe were still there. I have since done a clean installation, so I can't send you just the empty folders :( 
I will in the future copy and paste my main entitybank to Max, and I can send it to you if you want but it's well over 500GB.

**Comment by plemsoft** [comment] 2021-05-05 08:41
@LeeBamberTGC Found the other problem , if you place a entitybank inside the entitybank you got the problem, this has also been fixed so it support entitybank inside the entitybank :)

Both problems are now fixed.

@3coms Got your entitybank and model, and they all worked without crashing in the latest version :)

**Comment by 3coms** [comment] 2021-05-05 09:55
@ Lee and @Preben. Nice work guys, keep up!

**Comment by 3coms** [comment] 2021-05-06 00:03
Bug fixed from my side.
@ Lee and team, You guys rock, nice work, thanks :)

**Closed** 2021-05-06 15:04 UTC
Labels: Max, bug, fixed
