### ISSUE TITLE
Reports still coming through of the black screen for AMD.

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#4333] opened 2023-03-28 00:16 UTC
UPDATE: Until the cause has been reproduced, we have a solution for anyone seeing this with their AMD graphics cards. Just follow these instructions to start using GameGuru MAX:
https://steamcommunity.com/app/1247290/discussions/0/3764481749069937034/

Reports still coming through of the black screen for AMD.
Though some have stated it now works in the editor the Standalone game just goes to a black screen when tested.

**Comment by davetgc** [comment] 2023-03-28 13:48
@synchromesh62 - Did the users mention the cards?

**Comment by synchromesh62** [comment] 2023-03-28 13:54
> @synchromesh62 - Did the users mention the cards?

Not all but the ones that did seem to be the usual 6000 series

**Comment by dennimoto** [comment] 2023-03-29 03:52
Can confirm black screen still on 6900XT.

**Comment by plemsoft** [comment] 2023-03-29 09:15
@dennimoto Could you let me know what driver version you have , and try to disable "AMD FreeSync" and see if that fix the issue, Thanks for your help :)

**Comment by dennimoto** [comment] 2023-03-29 15:10
@plemsoft Driver version is 23.3.2. Disabling FreeSync has no effect.

**Comment by gedgeck** [comment] 2023-03-31 15:47
I can add that RX 7900 XTX (Powerline Red Devil, regular) does have black screen at both editor pane and when playtesting (menus and loading screen are fine, but real gameplay is pitch black with HUD and sounds in background, actions seem to trigger correctly - can take aztec dagger at the corresponding demo, again, just judging by sounds). Adding DXVK dlls to GGM root and 'Tools/Building Editor' dirs fixes this.
The Adrenalin is at 23.3.2 . FreeSync disabled

**Comment by plemsoft** [comment] 2023-04-01 06:00
@gedgeck Thanks for the information , could you make a video so im able to see the areas that are black , perhaps make a video where you create a new terrain (i know it might be black) and then try to edit that level and last try test game , this would really help me see all the places where the problem is , Thanks for your help :)

**Comment by gedgeck** [comment] 2023-04-01 09:50
@plemsoft Here I uploaded some videos for both existing and new levels, with and without DXVK. Last one has GGM Adrenalin settings too for reference

GameGuru MAX RC - AMD Radeon Testing - No DXVK
[https://youtu.be/tcftdSXaSe8](https://youtu.be/tcftdSXaSe8)

GameGuru MAX RC - AMD Radeon Testing - Fresh level, No DXVK
[https://youtu.be/vb0xcxMMB5k](https://youtu.be/vb0xcxMMB5k)

GameGuru MAX RC - AMD Radeon Testing - Existing project, DXVK
[https://youtu.be/yMPEr6tH6Es](https://youtu.be/yMPEr6tH6Es)

GameGuru MAX RC - AMD Radeon Testing - Fresh level, DXVK + Adrenalin settings
[https://youtu.be/Vo0kuZKqlzY](https://youtu.be/Vo0kuZKqlzY)

Let me know if I can assist further

P.S. I didn't know maps pool is shared between projects when I started recording :)

**Comment by plemsoft** [comment] 2023-04-01 11:20
@dennimoto Is this the same you see on 6900XT ?

**Comment by dennimoto** [comment] 2023-04-01 12:56
@plemsoft yes, it is the same.

**Comment by plemsoft** [comment] 2023-04-01 15:33
@gedgeck @dennimoto Thanks for the info , as you can see the interface, in "test game" could you try to disable all post processing and also try to disable any shadows ,perhaps we are able to figure out what shader has the problem then, thanks for your help :)

![postprocessing](https://user-images.githubusercontent.com/18662417/229298630-dc3c0d1d-94a3-4c9f-b252-673084c0249c.jpg)

**Comment by gedgeck** [comment] 2023-04-01 15:53
@plemsoft I tried to set different values for post processing and shadows (min/max/turnoff) but that doesn't help with black screen appearance. Filters (colored one, like 'Burgas' or 'Candle Light') change screen color though

**Comment by dennimoto** [comment] 2023-04-01 21:58
@plemsoft Disabling all post processing and shadows have no effect.
I am able to get everything working with the DXVK work around as @gedgeck has.

**Comment by plemsoft** [comment] 2023-04-02 05:17
@dennimoto @gedgeck Thanks i think i need a renderdoc capture so im able to see exactly what is happening, could any of you try this:

Goto: "https://renderdoc.org/" and download the latest version v1.26. and install.
1. Open RenderDoc.
2. Click tab "Launch Application"
3. Under "Executeable Path" select GameGuruMax.exe from your steam library.
4. Click "Launch"
5. Create a new project in Max click the new level, when your inside Terrain Generator and have the black screen, press "F12" and close Max.
6. Renderdoc will now have captured the data, so in renderdoc select file->"Save Capture As". Zip this file and upload it here or e-mail it to me plemsoft@gmail.com

Thanks for your help :)

![renderdoc](https://user-images.githubusercontent.com/18662417/229332905-c4d70e83-ce0a-4d9a-ab5b-ed1be98fadd2.jpg)

**Comment by dennimoto** [comment] 2023-04-02 05:45
@plemsoft sent to your email as google drive link, file too big for gmail and github.

**Comment by dennimoto** [comment] 2023-04-06 07:51
@plemsoft I'm not sure if this is helpful to you or not, but when I run MAX through RenderDoc with Enable API Validation checked, MAX opens with a "Failed to create graphics device. ERROR: 887a004" dialog, then self terminates.
This does not happen when I have the dxvk dlls in the MAX folder.

**Comment by plemsoft** [comment] 2023-04-07 09:00
@gedgeck @dennimoto To rule out any other software could one of you try a clean boot and see if it works:
https://support.microsoft.com/en-us/topic/how-to-perform-a-clean-boot-in-windows-da2f9573-6eec-00ad-2f8a-a97a1807f3dd
Thanks for your help :)

**Comment by gedgeck** [comment] 2023-04-07 10:22
@plemsoft Disabled all non-microsoft services as described at Windows 11 and still have black screen issue (I couldn't start Steam after disabling some of those extra services and so started GameGuru MAX directly as executable). Yesterday I updated GGM and Adrenalin to 23.4.1 so video drivers are latest (but Adrenalin itself wasn't running when testing)

**Comment by dennimoto** [comment] 2023-04-08 03:43
@plemsoft No difference on a clean boot unfortunately.

**Comment by LeeBamberTGC** [comment] 2023-04-12 00:25
@plemsoft Did the RENDERDOC report from this PC system help in any way?  It should show which GPU call event is rendering out the blackness.

**Comment by LeeBamberTGC** [comment] 2023-04-12 14:22
@plemsoft Good find, we get closer :)  The GGTerrain uses a custom shader, not part of Wicked Engine but created by TGC to do very fast procedural terrains with some fancy virtual texturing tricks.  For possible targets, look at things like:

1. The alignment of constant buffers and sizes, AMD may enforce stricter limits on 32/64 bit alignment or sizes
2. Some other resource may not be reset ready for the terrain rendering phase, or not unset when leaving
3. When working on the partcle draw order, I noticed that Paul (who wrote GGTerrain) often re-used CB slots and did not restore before carrying on the render, so look for terrain using resource indexes that are occupied or not managed

The real clue is that it works on NVIDIA and most AMD card (including my AMD 5 years old card), so it will be something related to a specific AMD architecture limit, so subtle we get away with it but the engine can trip during a perfect storm.

**Comment by gedgeck** [comment] 2023-04-12 15:26
@plemsoft No luck, I'll send you renderdoc from GGM session using that custom shader too

**Comment by dennimoto** [comment] 2023-04-13 05:15
@plemsoft Still black here with the replaced shader.

**Comment by plemsoft** [comment] 2023-04-14 11:08
@gedgeck @dennimoto Do you both have more then one monitor ? , thanks for your help :)

**Comment by gedgeck** [comment] 2023-04-14 11:44
@plemsoft I only have this one ( https://www.philips.co.uk/c-p/27M1N3500LS_00/evnia-gaming-monitor-quad-hd-gaming-monitor ) , connected through DisplayPort 1.4 . Monitor itself has splitter connected to another HDMI output; even though I doubt it matters I'll try to disconnect it to rule out any disturbance in the outer space :)

**Comment by dennimoto** [comment] 2023-04-14 12:24
@plemsoft just one.

**Comment by plemsoft** [comment] 2023-04-14 12:26
@gedgeck @dennimoto Could you try this "GameGuruMAX.exe" (remember to backup the original)
https://drive.google.com/file/d/15jCHtnNMTiWoRNN6kvGbqJJrNoVzbLxP/view?usp=sharing

And try to play the "Switch Escape" demo , what do you see ? , thanks for your help :)

**FYI**: its a debug build so will be slower then normal.

**Comment by gedgeck** [comment] 2023-04-14 12:34
@plemsoft Still have black screen in both editor, gameplay and "Switch Escape" demo. Demo starts with robotic voice and text describing the scene, there is HUD but nothing else visible

**Comment by plemsoft** [comment] 2023-04-14 12:50
@gedgeck What about this one:
https://drive.google.com/file/d/15pl5MDgtddUwshC1vRgGYiFdkIMM6c_K/view?usp=sharing

**Comment by gedgeck** [comment] 2023-04-14 12:58
@plemsoft Nothing new. Maybe you'll set some filters or something else (short changes ingo text in HUD?) so we at least sure something changes? The only change I noticed with debug builds - they are being caught by Windows Defender asking for permission to run unsigned app

**Comment by plemsoft** [comment] 2023-04-14 13:14
@gedgeck Thanks yes it now say DEBUG AMD ... this one also removes postprocessing.
https://drive.google.com/file/d/15sGvL6dO305NAdiOR8TC8e2HK5ruqQs1/view?usp=sharing

**Comment by gedgeck** [comment] 2023-04-14 13:22
@plemsoft I can confirm it now displays DEBUG AMD ISSUE 1.1 over GGM main window and in-game. It seems as high level overlay though and not what is rendering at '3D Level Editor' pane. But that's something to start with :) Still black screen, didn't notice anything else

**Comment by dennimoto** [comment] 2023-04-14 13:37
Likewise, still black.

**Comment by plemsoft** [comment] 2023-04-14 13:37
@gedgeck Another huge chunk removed 1,2!
https://drive.google.com/file/d/15u45sYg5nukYKEEg3Bod6l4c-r8-sW6K/view?usp=sharing

**Comment by gedgeck** [comment] 2023-04-14 13:41
@plemsoft See 1.2 version but still black screen here

**Comment by plemsoft** [comment] 2023-04-14 13:43
@gedgeck Last try for today , this one removed tons of stuff, nearly only object render left, crossed fingers :)
https://drive.google.com/file/d/15uFLGFTJCpSLRB5SK3HyEySIYNK1nGB1/view?usp=sharing

**Comment by dennimoto** [comment] 2023-04-14 13:46
@plemsoft Still black. No change with 1.3.

**Comment by gedgeck** [comment] 2023-04-14 13:55
Confirm what @dennimoto says. I'm not quite familiar with low level render pipeline but it seems renderer itself can't be initialized for whatever surface levels use (like '3D Level Editor' pane). @plemsoft If you can prepare something that skips everything GGM and just does native primitiver render of red cube or something I think we can check if the problem is with GGM internals or AMD rendering (drivers/software/OS level conflicts)

**Comment by plemsoft** [comment] 2023-04-14 14:16
@gedgeck @dennimoto Thanks yes i will need to think more about it and perhaps prepare something simpler :)

**Comment by gedgeck** [comment] 2023-04-14 16:23
@plemsoft Still the same, but thank for the tip, I'll try to play with it this weekend and see if it helps (backup taken)

**Comment by plemsoft** [comment] 2023-04-15 14:04
@gedgeck Wicked now use hlsl6 DX12 so it will be different from the hlsl5 dx11 versions.

Test 1.4 , nearly nothing left:
https://drive.google.com/file/d/15w0iKJ7BhAmtUD5f1IKGCt9e3iYc7LWc/view?usp=sharing

Ensure you load "switch escape" and are in the level editor or everything will just be black (but you should see some of the objects in that level).
If still black, try windows->"restore","maximize" any changes ?

Thanks for your help :)

**Comment by gedgeck** [comment] 2023-04-15 14:24
@plemsoft Now I see bright red background when windows/surfaces switch (between GGM windows, game menus) but not before level starts rendering (at least that's how I perceive it). GGM main window background is pale red now and editor itself is still black. I was resizing windows manually and through window handler buttons but that didn't change rendering
![AMD_test_1_4](https://user-images.githubusercontent.com/7673362/232230317-934f8bc4-7972-4d2f-a85e-2c96e9d265c7.jpg)

P.S. Thanks for short explanation on Wicked

**Comment by gedgeck** [comment] 2023-04-15 17:17
@plemsoft According to this article ( [https://www.pcworld.com/article/393733/rdna-2-deep-dive-inside-amd-radeon-rx-6000-graphics-cards.html](https://www.pcworld.com/article/393733/rdna-2-deep-dive-inside-amd-radeon-rx-6000-graphics-cards.html) ) there are 2 distinctive differences between 5xxx and 6xxx (and further) - ray tracing and infinity cache, can you adjust app tocheck if this might be the issue somehow? I tried to disable Smart Access Memory (SAM) in BIOS already and it didn't help, tried to reverse RAM (DDR5) profile to default (not overclocking) - the same result.

**Comment by plemsoft** [comment] 2023-04-16 06:17
@gedgeck Thanks i will look at those :) , we do know that the driver 22.5.1 is working, if i look at what happened in 22.5.2.

https://www.amd.com/en/support/kb/release-notes/rn-rad-win-22-5-2

Notice this comment:
Known Issues:
* Enhanced Sync may cause a black screen to occur when enabled on some games and system configurations. Any users who may be experiencing issues with Enhanced Sync enabled should disable it as a temporary workaround.

Could you try to disable "Enhanced Sync" and see if that fix it, also they mention some of the additions "DirectX® 11 optimizations for Radeon™ RX 6000 series:" , could you also try to disable any hardware acceleration and see if that works.

Thanks for your help :)

**Comment by plemsoft** [comment] 2023-04-16 07:16
@gedgeck As you suggested this one "test 1.5" removes all RX features from wicked dx11 , it start directly in the editor and only display a white box nothing else:
https://drive.google.com/file/d/162RasokI-9U313zbAZXX9D7Eji5TogvK/view?usp=sharing

Could you try this with "Enhanced Sync" on and off , fingers crossed and thanks for your help :)

![amd15](https://user-images.githubusercontent.com/18662417/232279863-10891000-763e-4dfa-8f01-9c7db1bd1092.jpg)

**Comment by gedgeck** [comment] 2023-04-16 11:36
@plemsoft I tried latest build. GameGuru Hub window flashes and gones quicly and some empty level loads. It still is black. Whenever I try to go back to GameGuru Hub I'm being redirected to that empty/new level again. I tried with 'Enhanced sync' turned on/off globally/locally(GGM only), still the same. My previous screenshot didn't capture it as it was jpg but this new one shows (when zoomed) that some checkery background is rendered, it's not pure black. I'm not sure how I can disable hardware acceleration without uninstalling Adrenalin/GPU drivers completely at Windows. Do you want me to try uninstall Adrenalin?
![not-so-black](https://user-images.githubusercontent.com/7673362/232307176-c278c80c-0f90-46a4-ae32-fcb8993c3f92.png)

**Comment by plemsoft** [comment] 2023-04-16 11:40
@gedgeck Could you try to make a renderdoc from the above screenshot , Thanks for your help :)

**Comment by gedgeck** [comment] 2023-04-16 11:44
@plemsoft Here you are [https://drive.google.com/file/d/19_4d2KbJMBqcV0NHw4ZkdIKrm8VsvCpD/view?usp=sharing](https://drive.google.com/file/d/19_4d2KbJMBqcV0NHw4ZkdIKrm8VsvCpD/view?usp=sharing)

**Comment by LeeBamberTGC** [comment] 2023-04-24 08:29
@plemsoft Let me know if you want me to take over this one, maybe a different pair of eyes can see a solution.

**Comment by plemsoft** [comment] 2023-04-24 15:52
@LeeBamberTGC Yes please have a look its a strange one , the last version tested 1.5 above ONLY have opaque pass and the tonefilter to fill out the last swapchain image , nothing else no custom shaders or prostprocessing, gg shaders... , even then it fails.
If you download the last renderdoc capture : https://drive.google.com/file/d/19_4d2KbJMBqcV0NHw4ZkdIKrm8VsvCpD/view?usp=sharing

And checkout ->present , you will see that the swapchain image is correct , but that is not what is being displayed it only display the imgui stuff and the center is all black ? like this screenshot: https://github.com/TheGameCreators/GameGuruRepo/issues/4333#issuecomment-1510314257

Another thing to note is that at the first frame captured the swapchain image has changed to what the amd users are seeing, so it looks like ->present change the swapchain image somehow ?

**Comment by plemsoft** [comment] 2023-04-26 11:56
@gedgeck @dennimoto Could one of you try this "test 1.6", thanks for your help :)

https://drive.google.com/file/d/1662CQi1Q4SByA9caXF1yGCuZ3UuLO8aD/view?usp=sharing

@LeeBamberTGC FYI: changed imgui to shader model 5, and also removed the outline that was still active in the 1.5 test.

**Comment by LeeBamberTGC** [comment] 2023-04-26 12:27
@gedgeck @dennimoto Also included this final tweak to the latest EXP build too in case Preben's test EXE works for you.

**Comment by dennimoto** [comment] 2023-04-26 12:34
Same here, GUI is fine, workspace is black. All radeon features (eg enhanced sync etc) disabled.

**Comment by LeeBamberTGC** [comment] 2023-04-26 12:44
@gedgeck Can you give me a step by step how to add the DXVK DLLs to the product to get things working on your AMD card?  We will continue looking at this, and eventually fix it, but it might be an idea to see if it is possible to redist the DXVK files as a way to help AMD users on release.  I am using this link as my starting point reading up on DXVK: https://wccftech.com/directx-vulkan-dxvk-2-0-improves-performance-adds-various-fixes-through-vulkan-1-3-graphics-driver/

**Comment by gedgeck** [comment] 2023-04-26 13:00
@LeeBamberTGC @plemsoft There are couple threads at Steam forums, like:

[https://steamcommunity.com/app/1247290/discussions/0/5738182472464125380/](https://steamcommunity.com/app/1247290/discussions/0/5738182472464125380/)
[https://steamcommunity.com/app/1247290/discussions/0/3764481749069937034/](https://steamcommunity.com/app/1247290/discussions/0/3764481749069937034/)

I believe I used 2nd thread approach and it is compact to follow as steps. I also packed it into ZIP which when unzipped at GGM root directory will put all necessary files at places, will attach this.

If you want to build DXVK yourself I'd recommend to follow it's repo README.md at [https://github.com/doitsujin/dxvk](https://github.com/doitsujin/dxvk)
[DXVK.zip](https://github.com/TheGameCreators/GameGuruRepo/files/11333031/DXVK.zip)

**Comment by plemsoft** [comment] 2023-04-26 13:40
@gedgeck @dennimoto Version 1.7 , last try for today, Thanks :)
https://drive.google.com/file/d/168NQJcJJx222Usv1eotKQQ0oaJZQ_KSw/view?usp=sharing
@LeeBamberTGC New swapchain using DXGI_SWAP_EFFECT_FLIP_DISCARD. fingers crossed.

**Comment by gedgeck** [comment] 2023-04-26 13:49
@plemsoft Still don't see the difference but maybe you can spot something new at renderdoc

[https://drive.google.com/file/d/12tlH1nzF0Gxf1b9La5Vec8nbLSIGTvI7/view?usp=sharing](https://drive.google.com/file/d/12tlH1nzF0Gxf1b9La5Vec8nbLSIGTvI7/view?usp=sharing)

**Comment by gedgeck** [comment] 2023-04-26 14:53
@plemsoft That becomes very weird now. I see all UI as plain red now, editor pane is still meshy black though, no box visible

[https://drive.google.com/file/d/1eF6hPXY9RIXQrJA94RR7A3MKbZOpQNrz/view?usp=share_link](https://drive.google.com/file/d/1eF6hPXY9RIXQrJA94RR7A3MKbZOpQNrz/view?usp=share_link)

**Comment by plemsoft** [comment] 2023-04-26 15:18
@gedgeck Yes we need more time to find this issue, Thanks for your help :)

@LeeBamberTGC Last renderdoc , backbuffer clear color is set to red , but still black in the middle, should at least be red everywhere ?

**Comment by plemsoft** [comment] 2023-04-27 09:13
@LeeBamberTGC I will make a workaround for now until we figure it out, using DXVK will make a pull later today :)

**Comment by LeeBamberTGC** [comment] 2023-04-27 11:16
@gedgeck @dennimoto Remove any DXVK files you may have added and try the latest EXP build now on Steam. It adds a workaround that detects specific AMD cards and copies the required DLL files to switch to the DX11->VK solution so users can continue using MAX.  It is not ideal, but will do for now.

**Comment by gedgeck** [comment] 2023-04-27 11:41
@LeeBamberTGC Bad news, it doesn't work either. I deleted DXVK files already at GGM dir, downloaded latest [experimental] build with Steam, verified files to be sure and yet it still shows [mostly] black screen at new games/demos and no DLLs were automatically placed for me

**Comment by LeeBamberTGC** [comment] 2023-04-27 11:47
@gedgeck Can you quickly copy those two files in "shaders" into the root next to the EXE file, and then test?  Just want to make sure that when these files are placed in the correct spot, your issue goes away. Sounds like the issue is that the code did not detect your card type and so did not copy the 2 files from shaders to the root.

**Comment by plemsoft** [comment] 2023-04-27 11:50
@LeeBamberTGC Ups yes RX 7900 was not on my list :)

@gedgeck If you run DxDiag press "Display" what does it say exactly under "Name: " ?

**Comment by gedgeck** [comment] 2023-04-27 11:50
@LeeBamberTGC Yes, if I manually copy them everything works and the early indication is I see GameGuru splash screen at the app start. I see terrain and objects at editor pane and in-game

**Comment by gedgeck** [comment] 2023-04-27 11:53
@plemsoft @LeeBamberTGC It says: `AMD Radeon RX 7900 XTX`. Keep in mind there is also 7900 XT available and as a placeholder you might add anything like "7xy0 XT[X]", where x = [1..9], y = [0,5]

**Comment by plemsoft** [comment] 2023-04-27 11:56
@LeeBamberTGC Might be faster for you just to add "79" to the "amd" , "rx" scan :)

**Comment by LeeBamberTGC** [comment] 2023-04-27 11:58
@plemsoft Making a new EXP build now to get a log of the device name, won't be long :)

**Comment by LeeBamberTGC** [comment] 2023-04-27 11:59
@gedgeck New EXP build, can you run it and send me a shot when you see the messagebox, thanks!

**Comment by plemsoft** [comment] 2023-04-27 12:04
@gedgeck Not sure how many cards actually have this problem, its not all amd cards, this is my current list from Max users:

RX6600m
AMD Radeon RX 6600m
Radeon RX 6950 XT
RX 6900XT
AMD 5600 XT
AMD RX 6800
AMD Radeon RX 7900 XTX

Do you know of any other cards that have the problem ?

**Comment by gedgeck** [comment] 2023-04-27 12:04
@LeeBamberTGC Here you are 
![popup](https://user-images.githubusercontent.com/7673362/234856393-d9b8ee3b-0e37-4605-ac57-16b570ca6be6.jpg)

**Comment by LeeBamberTGC** [comment] 2023-04-27 12:07
@gedgeck Thanks for the shot, I will modify the code to detect this and ensure the files copy.  Give me 10 minutes :)

**Comment by gedgeck** [comment] 2023-04-27 12:08
> @gedgeck Not sure how many cards actually have this problem, its not all amd cards, this is my current list from Max users:
> 
> RX6600m AMD Radeon RX 6600m Radeon RX 6950 XT RX 6900XT AMD 5600 XT AMD RX 6800 AMD Radeon RX 7900 XTX
> 
> Do you know of any other cards that have the problem ?

No, my previous was `NVidia GTX 980 4G` and I don't have friends interested in GGM. I tried to share GGM with my wife through Steam family library sharing but there was some problem running it and I didn't dig too much. She has `AMD RX 6650 XT` so if you think it should work while sharing I can try to check if the problem was/is this same one, now that you leave early access.

@LeeBamberTGC @plemsoft Congratulations by the way!

**Comment by plemsoft** [comment] 2023-04-27 12:11
@gedgeck AMD RX 66?? is already in the list , so that will work after Lee make the change :)

**Comment by LeeBamberTGC** [comment] 2023-04-27 12:11
@plemsoft I have modified the code to capture 79 (and also 89) for the future :)

		/*
		AMD driver bug.
		PE: this is the card i noted had the problem, there might be more :)
		AMD Radeon RX 6600m
		Radeon RX 6950 XT
		RX 6900XT
		AMD 5600 XT
		AMD RX 6800
		AMD Radeon RX 7900
		NOTE: make sure shaders\\d3d11.dll , shaders\\dxgi.dll get copied to the standalone.
		*/
		//if (i == 0) strcpy(cDeviceName, "AMD Radeon RX 7900"); //test one
		if (length > 0)
		{
			//pLog = pLog + cDeviceName;
			//pLog = pLog + "|";
			if (pestrcasestr(cDeviceName, "AMD") || pestrcasestr(cDeviceName, "Radeon") )
			{
				//PE: Take all 6900,5600,6800,6600 RX serie if amd.
				if (pestrcasestr(cDeviceName, "RX"))
				{
					if (pestrcasestr(cDeviceName, "89") || pestrcasestr(cDeviceName, "79") || pestrcasestr(cDeviceName, "69") || pestrcasestr(cDeviceName, "68") || pestrcasestr(cDeviceName, "66"))
					{
						bIsAMDCard = true;
						break;
					}
				}
				else
				{
					//PE: special case for amd 5600 xt
					if(pestrcasestr(cDeviceName, "5600"))
					{
						bIsAMDCard = true;
						break;
					}
				}
			}

**Comment by gedgeck** [comment] 2023-04-27 12:13
> @gedgeck AMD RX 66?? is already in the list , so that will work after Lee make the change :)

You have `6600m`, that's laptop variation I believe. Maybe incode check is aware and matches both, that I can't know. Just mentioned so you are aware

**Comment by LeeBamberTGC** [comment] 2023-04-27 12:13
@gedgeck Try the new EXP build just uploaded. PLease confirm the fix. It will now detect your specific card and ANY 79xx or 89xx cards for the foreseeable.  This entire problem goes away naturally if we move to the latest Wicked Engine (DX12/Vulkan) but for now this solution should at least get users up and running with the minimum of fuss :)  Thanks all for your helps!

**Comment by plemsoft** [comment] 2023-04-27 12:15
> You have `6600m`, that's laptop variation I believe. Maybe incode check is aware and matches both, that I can't know. Just mentioned so you are aware

It already also include "m" version of the series , so should be fine, Thanks for your help with this :)

**Comment by plemsoft** [comment] 2023-04-27 12:37
> I don't see 66xx[m] check at that code snippet

Any card including "amd" or "radeon" that also include "RX" and "66" is included, so "AMD RX 6650 XT" and "AMD Radeon RX 6600m" match this :)

**Comment by LeeBamberTGC** [comment] 2023-04-27 12:43
@gedgeck Thanks for confirming. I am confident to move this to the public build and respond to Steam users who experienced AMD issues, hopefully, they will respond :)  @dennimoto If you can also confirm I can close this and mark the last of the pre-V1 HIGH issues fixed to hit that wonderful ZERO COUNT on RC bugs :)

**Comment by synchromesh62** [comment] 2023-04-27 12:48
Hopefully not interfering here if so then apologies but just a side note that the although the DXVK does work for most with the issue to get the editor up running standalones may still be a problem unless the export is somehow patched for detection.

**Comment by LeeBamberTGC** [comment] 2023-04-27 12:50
@synchromesh62 Good call, and you are right.  Looks like I need to add some more code, at least to copy the files over :)

**Comment by synchromesh62** [comment] 2023-04-27 12:50
> @synchromesh62 It will also works in standalone :)

Awesome .. Sorry had to ask just in case.

**Comment by synchromesh62** [comment] 2023-04-27 13:43
Congrats guys .. 
That one was really nasty.

**Comment by dennimoto** [comment] 2023-04-27 17:51
@LeeBamberTGC Experimental build is working for me now.
The only exception is when running an exported standalone, the first time it is run, gameplay is black screen after the menus. Any thing after the first run is okay. I exported two different demo levels to verify.

**Comment by plemsoft** [comment] 2023-04-28 06:35
> the first time it is run, gameplay is black screen after the menus. Any thing after the first run is okay.

@LeeBamberTGC I think this is defender checking the files the first time they get copied over, we try to load them directly after copy so they could be blocked, try to Sleep(2000) after the copy if they dont already exists :)

**Comment by synchromesh62** [comment] 2023-05-03 09:50
@plemsoft 
@LeeBamberTGC
Just a little bit of additional info i have been able to dig up.
Apparently for the AMD Radeon RX 6500 XT... Max will work perfectly using the older 22.5.1 driver
Any driver above this will give the black screen issue.
The current driver is 23.4.3 so its quite an old one.

**Comment by dennimoto** [comment] 2023-05-03 12:30
I wonder if it would help if a team member could share which version of wicked engine is being used to see if we can run a wicked only demo without any MAX code, the see whether its a "wicked+AMD" issue or a "MAX+AMD" issue???

**Comment by LeeBamberTGC** [comment] 2023-05-03 12:42
@dennimoto The version we are using is from around a year and a half ago, and has changed a LOT since then, basically rewritten to drop DX11 and go full-on DX12.  Not sure if the Wicked repo can step back that far but worth a try if it is there!

**Comment by synchromesh62** [comment] 2023-05-03 14:12
> I tried version 0.56.32 released June 13, 2021. The editor opened to a black screen, so I'm guessing the issue is in wicked engine.

Hmm the fact that Max will work perfectly ( apparently ) using the older 22.5.1 driver for the RX 6500 XT screams driver to me ?

**Comment by dennimoto** [comment] 2023-05-03 14:18
> Hmm the fact that all versions of Max will work perfectly ( apparently ) using the older 22.5.1 driver for the RX 6500 XT screams driver to me .. Possibly a bit of both engine and driver ?

Maybe, but I've not encountered any other dx11 game or app with a problem with the new drivers.

**Comment by plemsoft** [comment] 2023-05-04 05:54
@LeeBamberTGC Added Radeon RX 6700 XT , AMD Radeon RX 6500 XT to the list and Building Editor, made a pull :)

**Comment by Frantic-bookworm** [comment] 2023-05-09 17:18
i have left all my machine details on threads regarding black screen...im using an AMD 6700xt i rolled back to 22.5.1 and GGMax works , my progect is a mess and i will have to start again, but i can confirm that 22.5.1 works with AMD 6700XT cards, i look forward to the full fix to utalise my card

**Comment by LeeBamberTGC** [comment] 2023-05-10 15:31
@Frantic-bookworm and All : Preben's commits are now included in the latest public build, and it also gets the Building Editor running too. Hope this helps more AMD users :)

**Comment by LeeBamberTGC** [comment] 2024-04-07 15:18
@synchromesh62 Finally fixed properly for the next EXP build. It turned out the more recent AMD drivers introduced an "improvement" that made legacy use of RSSetScissorRects a dangerous function to call.  Improved the code around this area to ensure there are no negative TOP/LEFT regions and all DX11 slots cleared.

**Closed** 2024-04-07 15:19 UTC
Labels: bug, Fixed but need confirmation., Max, High, CRASH!

**Comment by synchromesh62** [comment] 2024-04-07 15:41
> @synchromesh62 Finally fixed properly for the next EXP build. It turned out the more recent AMD drivers introduced an "improvement" that made legacy use of RSSetScissorRects a dangerous function to call. Improved the code around this area to ensure there are no negative TOP/LEFT regions and all DX11 slots cleared.

That is Great News !! 
I will keep my eye out for any feedback or new issues if any :)
