### ISSUE TITLE
Weapon thumbnails have been wiped out in the update

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1992] opened 2022-02-08 07:49 UTC
@dllllllllllb Can you check this out please?
![image](https://user-images.githubusercontent.com/1503593/152941475-6db88ee4-e1f8-40d0-b9d9-f70870043eb0.png)

**Comment by UltraVox001** [comment] 2022-02-08 08:38
Weapons are also missing from this build.
The only weapons available are those with Thumbnails present.

**Comment by rvanner** [comment] 2022-02-08 08:41
@LeeBamberTGC Can we get a quick update fix for this today?

**Comment by UltraVox001** [comment] 2022-02-08 09:05
@rvanner @LeeBamberTGC 
There are also big problems with the switches.
They are not visible when added from the "Add" button.
Those placed against a wall disappear in Edit mode. But they are present in the TestLevel.

**Comment by UltraVox001** [comment] 2022-02-08 09:34
Manipulating a Switch is nearly impossible : [Video](https://i.gyazo.com/4ad21d26902ed2e29c6cdb5e61a89a54.mp4).

**Comment by dllllllllllb** [comment] 2022-02-08 09:55
Thumbnails for ladders and most shrubs are also missing. There is a duplicate of "Sewer rat black" which has the same issue.

All weapons seem to be working fine for me, it's just the thumbnails that are missing.

**Comment by UltraVox001** [comment] 2022-02-08 10:02
What "dllllllllllb" says is true. But on a pre-build map, the weapons with the missing thumbnails are also missing. Like on this pre-build map where each table must present the missing weapons.
![Weapons](https://user-images.githubusercontent.com/96718175/152964441-0687810c-16b0-4d1b-ac1a-29730518e52d.jpg)

**Comment by LeeBamberTGC** [comment] 2022-02-08 10:21
All, bear in mind the internal build for this week updated the object management system for Wicked, changed how weapons render into the depth buffer and most weapons where renamed, so you will need to add them back in to existing levels.  Just some notes before we reproduce the aboves.

**Comment by UltraVox001** [comment] 2022-02-08 10:48
@LeeBamberTGC , I take note. :)
Warning : On a new map created with this Build., if you ask to spawn with the following weapons, you appear with invisible weapons. Operational, but invisible :

- Snubnose Revolver
- Melee Combat
- Pocket Knife
- SledgeHammer

Other weapons appear correctly.

**Comment by LeeBamberTGC** [comment] 2022-02-08 11:30
@plemsoft I have bounced this URGENT one to you in case it relates to the recent change to the wicked engine object handling as I suspect it is.   Please re-assign back to me if you determine it is not related to the attach sort stuff, thanks!

**Comment by LeeBamberTGC** [comment] 2022-02-28 12:38
@rvanner You still getting this?

**Closed** 2022-03-01 07:27 UTC
Labels: bug, Urgent, Fixed but need confirmation., Max, Weapons
