### ISSUE TITLE
GameGuru MAX - Save Standalone Button Needs to Stand Out as a Button

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#2447] opened 2022-03-08 20:38 UTC
When you go to save a Standalone game, the Save Test Standalone button blends in so well with the background, especially on a large screen monitor, that it doesn't look like a button at first:

![157320645-f85ee356-45c1-4f10-ade4-ef5d5607c011](https://user-images.githubusercontent.com/36735507/157321374-416a7928-eac2-4882-92c2-f3281033768d.png)

The first time I went to use it, I glanced at the dialog, wondering what I was supposed to click to make my standalone game.

I recommend that the Make Test Standalone button be made to look more like a button ... like this:

![157320899-8da8707d-80ac-4d2f-a4eb-921da2d0e30c](https://user-images.githubusercontent.com/36735507/157321401-174f62c9-3b86-42e9-bd53-78aedd8fa2d1.png)

In fact, there are several buttons in MAX that could use a similar sort of treatment, like the Generate Terrain button you use to finally get to the level editor.

**Comment by dllllllllllb** [comment] 2022-03-09 09:27
This is a Interface Style issue, buttons in most styles blend in with the background too much.

Affected interface styles:
Dark Style
Evening Blue
Green Tea
Moody Red
Purple Haze
Racing Green
Red Lines
Retro Green
Sea Blue
Smart Purple
Striking Yellow
Sunset Red
Tango

**Comment by OldFlak** [comment] 2022-03-19 23:14
Please do not use green or any color for that matter - just make the button darker to suit theme :)

**Comment by ArgentArts** [comment] 2022-03-19 23:16
You're late to the game. They've already made the change. It's darker, just like you wanted.

**Comment by OldFlak** [comment] 2022-03-19 23:24
No it is slightly darker when mouse over it - no difference at all 
The issue is **not fixed** :)

**Comment by ArgentArts** [comment] 2022-03-19 23:30
Strange. It was changed in a previous release. Wonder what changed it back.

**Comment by OldFlak** [comment] 2022-03-19 23:32
Yes, seems to be the norm - fix it, break it - rinse repeat :)

**Comment by OldFlak** [comment] 2022-03-19 23:36
`That's up to TGC to decide. :)`
Heavens no - they have fluffed the UI enough already.

All I am pointing out is the themes need to be respected - they have a habit of bad UI design. :)

**Comment by MonkeyFrogStudio** [comment] 2023-04-02 22:27
Closing this because it appears to be fixed.

**Comment by LeeBamberTGC** [comment] 2023-09-15 20:48
@MonkeyFrogStudio yes I will close this, looks good for new users who do not change the theme:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/cf7397e9-627e-4fd5-a7b0-3431e47cdcab)

We can re-open as a feature request if there is a need to hide the themes that make the button color the same as the backdrop color. We cannot change the existing theme colors of course, as it would spawn new issue reports that they want the old colors back :)

**Closed by LeeBamberTGC** 2023-09-15 20:48 UTC
Labels: bug, Max, Low, UI
