### ISSUE TITLE
GameGuru Max - Bug - Building Editor - Bug 3/6 - Ceiling Bleeds Through

### ISSUE THREAD

**Issue by Lemuripest93** [TheGameCreators/GameGuruRepo#3844] opened 2022-10-19 17:49 UTC
Individual posts by request from #3772

When creating a small room on top of a much bigger room, the roof/ceiling will bleed through to the interior of the building, this can be seen in the video below from 0:30 to 0:31.

Video link from original post: https://youtu.be/XTuWc4HJSe8

**Comment by ZakJudges** [comment] 2022-12-05 15:40
Hi @Lemuripest93, thanks for reporting this issue. I have updated the roof creation, so that it will line up better with the ceilings of floors below:
![Screenshot 2022-12-05 153439](https://user-images.githubusercontent.com/32545391/205678318-799d9494-74de-44c2-b3d7-47ab033f277f.png)

From here, you can then paint the ceiling so that it matches the roof like so:
![Screenshot 2022-12-05 153508](https://user-images.githubusercontent.com/32545391/205678427-120c5e3a-ae47-434b-9093-df8e6a6bcc41.png)
![Screenshot 2022-12-05 153531](https://user-images.githubusercontent.com/32545391/205678435-cbff4fb3-3c9d-416d-8f4b-5c756dfc5c53.png)

We will likely be uploading a new build in the near future. I will post here once it is available and ready to test. Thanks :)

**Comment by ZakJudges** [comment] 2022-12-08 16:48
@Lemuripest93 A new experimental build is available and ready to test :)

**Comment by Lemuripest93** [comment] 2022-12-08 18:41
Really great work! though i can't seem to paint ceilings on buildings with more than one floor, will this be implemented at a later date? not that i need this right away but would be a nice feature.

Example: I still can't change the ceiling on the entrance way in the test building from the video in the OP:
![GGMpaintceil](https://user-images.githubusercontent.com/104637906/206538231-cbc69076-6e44-4e9e-af8c-1457352fd6a8.png)


I can still use this on my apartment complexes and less strangely shaped buildings so that's pretty neat though 👍

**Comment by ZakJudges** [comment] 2022-12-09 14:43
@Lemuripest93 Thanks for confirming, and good find for the painting issue :) 

It seems to be caused by the transparent walls of the layers beneath, blocking the mouse picking in paint mode. I have created a new issue for this :) #3941

**Comment by Lemuripest93** [comment] 2022-12-09 16:54
Thanks a lot, you didn't have to do this right away but i appreciate it👌

**Comment by ZakJudges** [comment] 2023-02-16 09:41
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks

**Closed by ZakJudges** 2023-02-16 09:41 UTC
Labels: bug, Fixed but need confirmation., Max, High, Building Editor
