### ISSUE TITLE
Terrain Generator - grabber is offset on Meash's laptop

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2280] opened 2022-02-25 15:55 UTC
@plemsoft Meash is seeing this on his laptop! Maybe related to aspect ratio?

![image](https://user-images.githubusercontent.com/1503593/155746083-105c6e11-6dd5-4138-b9dd-760d6d1611d8.png)

![image](https://user-images.githubusercontent.com/1503593/155746160-f1a9a5cf-76de-455c-be07-58d7655f19a9.png)

**Comment by plemsoft** [comment] 2022-02-26 14:07
@rvanner Tried a few different resolutions , but could not reproduce , what resolution is he using ?

**Comment by rvanner** [comment] 2022-02-28 09:31
This is from his PC:

![image](https://user-images.githubusercontent.com/1503593/155958929-ebca3990-fd68-4326-9de9-538e48f44acf.png)

**Comment by GraPhiX-Guru** [comment] 2022-02-28 09:41
It could possibly be the DPI scaling, has he tried setting DPI to 100% re start computer and see if it persists, i do not know if MAX is DPI aware but i don't think it is.

**Comment by Granada1** [comment] 2022-02-28 09:53
` do not know if MAX is DPI aware but i don't think it is. `
You can set it in advanced settings 👍

**Comment by rvanner** [comment] 2022-03-01 07:29
@plemsoft We asked Meash to check his DPI settings and found that DPI was set. When we turned it off and re-ran MAX the grabber was in the right location. The problem is that he needs DPI ticked because other areas of the application don't work well without it. So at least you know that DPI off allows it to work but DPI does not.

**Comment by plemsoft** [comment] 2022-03-01 10:01
@rvanner Thanks found and fixed it , i will commit later and set the status to fixed :)

**Comment by plemsoft** [comment] 2022-03-01 13:30
@rvanner This has been fixed and will be in the next update :)

**Closed** 2022-03-02 10:57 UTC
Labels: bug, Fixed but need confirmation., Max, High, Terrain Generator
