### ISSUE TITLE
Black Bacground map

### ISSUE THREAD

**Issue by arubiobote** [TheGameCreators/GameGuruRepo#170] opened 2018-04-17 17:42 UTC
With the new update when you open Gameguru or load any map, the black background appears and you can not see the texture of the floor. In the public preview this did not happen.

<img width="686" alt="gamegurubackground1" src="https://user-images.githubusercontent.com/15078001/38890550-07b07ff6-4282-11e8-9dc4-4b90f3c89ff8.png">

Note: In case it serves someone who has the same error. Although the textures do not appear when generating a new level, if any map is opened before and the new level is generated later, the textures already appear, so the error only occurs initially.

**Comment by LeeBamberTGC** [comment] 2018-04-17 20:12
Can you tell me your CPU and GPU make and model and how much dedicated video memory you have?  Any chance you can save an FPM when you see the black terrain and attach it here, thanks.

**Comment by plemsoft** [comment] 2018-06-20 10:30
The problem is that you have the terrain set to "CUSTOM" without having any custom terrain textures inside the .fpm , try to run your map , and press tab tab and select any terrain to fix it.
After this just save the fpm again and the problem will go away.

I believe you got this problem in a previous PP that might had a problem with saving your custom terrain textures , and then this will follow you in the new versions to.

arubiobote: please test and let me know if we can close this :)

**Comment by LeeBamberTGC** [comment] 2019-06-26 15:15
Yes, this happens when a custom terrain was used but not retained due to the PP process. Closing until it can be reproduced in the latest public build.

**Closed by LeeBamberTGC** 2019-06-26 15:15 UTC
Labels: bug, help wanted
