### ISSUE TITLE
Player falling thru ground [GGMax]

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#2357] opened 2022-03-02 11:36 UTC
I know this is a well-known bug, but this time is happens something curious about my mesh, so, I decide to raise it here, just in case.

Since I'm having issues with my whole mesh and player falling thru ground in test mode, so I decide to do as follow:
1- split model into sections
2- Take section #1 and make the most simple geometry possible, as you can see in the video below.
3- Here is the curious thing, if I place my model into an empty map then the player sink; otherwise if I remove my model from the map then **the player does not sink**.

So, I wonder how a non-complex mesh can change the terrain physics?

https://youtu.be/cPf0Khgn4RQ

**Comment by 3coms** [comment] 2022-03-02 23:32
I've managed to get the mesh over an empty map and the player does not fall thru the ground.
I split it into sections, imported it as OBJ, and place them over a map, and it works ok.
However, I'm getting an "outside of editable area" error (please, refer to the pic below) and the 20 GBs does not help. :)

![Outside_editable_area_GGMax_2022_03_04_pic01](https://user-images.githubusercontent.com/47690174/156467160-3bcd740a-b448-41e7-a49e-f271cb0178bd.png)

No idea how to deal with it; I'm aware I can move all to the center of the area, but why should I do so? if everything is already inside the editable area. :)

**Comment by 3coms** [comment] 2022-03-03 11:29
So, I've moved all the stuff to the very center of the map, but it does not prevent the error msg raising over and over.

![Outside_editable_area_GGMax_2022_03_04_pic02](https://user-images.githubusercontent.com/47690174/156555711-26a31def-2f92-4204-a597-8cb357bfba0b.png)

![Outside_editable_area_GGMax_2022_03_04_pic03](https://user-images.githubusercontent.com/47690174/156555767-d701360e-d477-4936-8441-6f4d4d4b0654.png)

Does GGMax is wrongly taking stuff as out of the redline, and then player fall trhu the ground because of this?

**Comment by plemsoft** [comment] 2022-03-03 12:31
@3coms Its not a error just info.

@rvanner Do you have a better description, so there is no confusing , perhaps like "Camera is outside..." ?

**Comment by 3coms** [comment] 2022-03-03 13:06
@plemsoft 
Yes, but then why did it prevent me to test the level because of this?
Unfortunately, I removed the map where I've prompted about it; when placing a mesh and immediately GGMax crash, and I have to get rid via TM.
As you can see in the pics above it is prompting me even when saving files. :)

**Comment by plemsoft** [comment] 2022-03-03 13:25
@3coms The message is not related to the problem, could you sent me the map that create a crash , and also where the player sink , then im able to try to debug it , thanks for your help :)  plemsoft@plemsoft.com

**Comment by 3coms** [comment] 2022-03-03 13:55
I managed to reproduce the issue, so, perhaps you would like to see the bug in the video below.

https://youtu.be/WgJ40W2JoO0

@plemsoft I've tried to upload it to Google drive, although, there is no stock stuff there, so, I have to send you the whole stuff as well, and it is going to take sometime to upload to google drive with my super-slow connection :)

**Comment by plemsoft** [comment] 2022-03-03 16:26
@3coms I can see that the level takes along time to load and mem. so will wait until i have the level and can see the problem , thanks for your help :)

**Comment by plemsoft** [comment] 2022-03-04 08:29
@3coms I think your running out of memory, could you let me know your system memory 16gb ? , if we dont have memory available to pre allocate working memory for the physics process this would happen. Also if you repeat the action in your first post where the player sink, and post your "Guru-MapEditor.log" it would really help :) , but still like to get the level so im 100% sure where the problem is , thanks for your help :)

**Comment by 3coms** [comment] 2022-03-04 11:15
> @3coms The message is not related to the problem, could you sent me the map that create a crash , and also where the player sink , then im able to try to debug it , thanks for your help :) [plemsoft@plemsoft.com](mailto:plemsoft@plemsoft.com)
> 
> FYI: The issue where it prompt you even when saving is fixed :)

Done. :)
I've sent you 2 download links since the file is a bit huge, so I split the file into 2 parts (part1, part2) both going within the entitybank folder :)
I you need something else. please, let me know. :)

**Comment by 3coms** [comment] 2022-03-04 11:40
@plemsoft 

![sigImage php](https://user-images.githubusercontent.com/47690174/156757126-9df63a11-7133-4d1f-bcc1-57536de7130e.png)

**Comment by plemsoft** [comment] 2022-03-04 11:43
@3coms Thanks i did not get any e-mail with links, did you sent one ? plemsoft@plemsoft.com

**Comment by 3coms** [comment] 2022-03-04 11:55
I re-sent then to you again :)

**Comment by plemsoft** [comment] 2022-03-08 15:50
@3coms I checked your level , and the problem is that you have set the house to BOX collision , and placed the player inside this box , what happens when a objects is stuck inside another, is that bullet will try to resolve it and get the player out of the box, to do this it moves the player, but after moving the player out of the BOX it will be below terrain and then sink.

So short , just set the collision to "polygon" on the house and it will work, or move the player outside the collision box :)

Also about your mem problem , in the objects you sent me. The mem use is not from your meshes but are from the huge 4096x4096 .png images your using. You should really use .dds , did you know that a png texture use 8 times more memory then a .dds BC1 ? , most of your .png texture could be converted to .dds BC1 with no problem, and you would use 8 times less memory.

Hope this answers your questions :)

**Comment by 3coms** [comment] 2022-03-08 22:06
@plemsoft 
Swapping to polygon collision avoids the player falling thru. :)
About the texture res, I've converted every texture to DDS format and half resolution, of course, it minimizes RAM waste as expected. 
Thank you again, much appreciated. :)

**Comment by LeeBamberTGC** [comment] 2022-03-08 22:12
@3coms I do think we can improve this process for future users without requiring technical knowledge,. I have marked it as enhancement so we can keep this on the MAX books

**Comment by 3coms** [comment] 2022-03-08 23:47
It might be a nice solution. :)
As a side note, some sort of "isCharacter" in the importer, might help GGMax to know that you are importing a char and not a table, and so, the importer could show character settings, and char environment, and your model start being treated as a char, and not as a table. :)

**Closed** 2022-04-25 20:11 UTC
Labels: enhancement, Max, Post Early Access
