### ISSUE TITLE
UI Model selection screens

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#1639] opened 2021-12-03 20:21 UTC
![ui1](https://user-images.githubusercontent.com/95015657/144667581-c4296f1c-8a31-4b31-81c0-09f8b5e58959.jpg)

The image for the backdrop on models seems not to be resizing to the available space

Also the selection of none as a backdrop seems to create a white box, not transparent
![ui2](https://user-images.githubusercontent.com/95015657/144667830-e360c3c8-ed03-4e16-9cde-e340d743fceb.jpg)
.

**Comment by rvanner** [comment] 2021-12-06 10:33
@Necrym59 Would you be able to make a video showing this happening? Start the video from within the Character Creator, make the thumbnail and then show it in the Object Library.

**Comment by Necrym59** [comment] 2021-12-06 21:02
Hi rvanner - movie supplied
just for your reference im using a Nvidia Geforce RTX 3080 on a Samsung GSYNC Monitor at 5120x1440 resolution
[ggmax_thumbnails.zip](https://github.com/TheGameCreators/GameGuruRepo/files/7663515/ggmax_thumbnails.zip)
d

**Comment by ZakJudges** [comment] 2022-02-23 09:51
Closing this issue - duplicate of #1597

**Closed by ZakJudges** 2022-02-23 09:51 UTC
Labels: bug, duplicate, graphics/thumbnail, Max, High
