### ISSUE TITLE
Test Game mode causes gg to crash

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#733] opened 2020-04-01 07:40 UTC
I have more problems with the current gg version :/

I verified my files via steam, there is nothing I can do..

This time I dont even get a proper error message..

![2](https://user-images.githubusercontent.com/35990507/78111115-7a5ba280-73fc-11ea-91c2-8575134940c3.JPG)

**Comment by LeeBamberTGC** [comment] 2020-04-02 17:20
Can you produce a small video showing you pressing the LAUNCH button so I can see exactly where this strange error box appears, thanks!  Do you have a second PC you can try GameGuru on?

**Comment by Duchenkuke** [comment] 2020-04-02 18:46
I restrored my old gameguru folder with the december version.. it took me hours to copy everything over so.... unfortunately not. I havent got the time currently...

**Comment by Teabone3** [comment] 2020-04-03 16:28
Test Game as in Test Mode? Its working okay for me on Windows 7.
Is this with an empty map or only your game made in GG?

**Comment by Duchenkuke** [comment] 2020-04-03 17:52
with my game level

**Comment by plemsoft** [comment] 2020-04-04 06:54
@Duchenkuke Just sent me a standalone of your level and i will check what the problem is : plemsoft@plemsoft.com

**Comment by Duchenkuke** [comment] 2020-04-04 07:46
@plemsoft All I can offer is a Steam Key for my Game. It's in closed alpha testing right now.
That would work too ?

**Comment by Duchenkuke** [comment] 2020-04-04 07:49
@plemsoft just sent the key. Hope this counts too ;)

**Comment by plemsoft** [comment] 2020-04-04 07:58
@Duchenkuke Strange did not get any key ? , did you PM it or something else ? ,

**Comment by Duchenkuke** [comment] 2020-04-04 08:42
I send an email to this address

plemsoft@plemsoft.com

**Comment by Duchenkuke** [comment] 2020-04-04 08:44
oh wow... it seems that it did not work...

Hang on I will send the key here 
HD9L0-DIKDT-5N5XW

**Comment by plemsoft** [comment] 2020-04-04 08:53
@Duchenkuke Thanks for the key got it , it is the correct e-mail , strange ? next time just use plemsoft@gmail.com :)

**Comment by Duchenkuke** [comment] 2020-04-04 08:57
Cool! I think your email is fine tho. I clicked on your email here on github and it opened a window. 
I sent the email through that but obviously It didnt send properly. No worries, you got the key now :)
I will not be at home for the rest od the day, If there is anything i will reply asap

**Comment by Duchenkuke** [comment] 2020-04-04 08:58
btw feel free to add me on steam:

[GWINGA] Duchenkuke is the name

**Comment by plemsoft** [comment] 2020-04-06 12:13
@Duchenkuke Awesome game you got going there :)

I been running with a debugger attached and no problems detected, also tried your other reported stuff like load/save ... everything seams to work , so i assume this is the same as with ertlov that was some problems with custom objects. The fixed version will go out soon , so give it a try in that version, and then just open a new issues if you get any problems :)

**Comment by Duchenkuke** [comment] 2020-04-06 15:26
okay thanks for testing Preben :)

**Comment by Duchenkuke** [comment] 2020-04-09 07:04
I have now tested the latest Public Preview and I loaded up my level 1. During loading testgame gg restarted itself. I need some more help please.. I will try to look at where it crashes

**Comment by Duchenkuke** [comment] 2020-04-09 07:08
ok gg restarts at "initializing physics" or after that. It cant load the level.

**Comment by Duchenkuke** [comment] 2020-04-09 07:12
anyway, I will restore my backup and then try a new installation. maybe something went wrong on my part.. idk. I will report later!

At least I dont get no runtime error anymore, instead gg just reloads the level again and throws me back to the editor.

**Comment by plemsoft** [comment] 2020-04-09 08:15
@Duchenkuke Could you post your log files here, that would help :)

**Comment by Duchenkuke** [comment] 2020-04-09 08:25
I'm sorry, I deleted the installation already... 

Right now I am installing everything from scratch to ensure its not an error on my side.
That means: Installing Gameguru (Public Preview) then adding all my custom media (sounds, entities, scripts)

I hope it works this time. If not, I will then try to share the log file :)

**Comment by Duchenkuke** [comment] 2020-04-09 09:01
okay. I did a completely clean install.. still returns to editor
No runtime error but the same issue as I reported earlier
 
where is the log file located?

**Comment by Duchenkuke** [comment] 2020-04-09 09:04
nope. after deleting the scripts I used in that level I still get thrown back to the editor
I always see this image again
![asdsa](https://user-images.githubusercontent.com/35990507/78877972-f0da4f00-7a51-11ea-95c9-f04c29a26a48.JPG)

**Comment by Duchenkuke** [comment] 2020-04-09 09:34
I loaded up a very small level wich really contains just a street and some trees and foliage, and that worked. I will test the other levels now. Maybe there is an entity that causes issues... I dont know! I can only test

**Comment by Duchenkuke** [comment] 2020-04-09 09:37
okay... So I loaded up level 2 from my project and I got this error again..

I would send you my whole gg folder if it wasnt so tedious....

![sadsa](https://user-images.githubusercontent.com/35990507/78880920-60ead400-7a56-11ea-93c5-26de80e83dad.JPG)

**Comment by plemsoft** [comment] 2020-04-09 09:44
@Duchenkuke Fir thing to try:

edit setup.ini and set "drawcalloptimizer=0" and "producelogfiles=1" , then give it another try and let me know , you then find the .log files here:

Game Guru\Guru-MapEditor.log
Game Guru\Guru-MapEditor-last.log

Post those 2 here, from just after the crash.

**Comment by plemsoft** [comment] 2020-04-09 10:15
@Duchenkuke As your issue is about c++ runtime lib. try this:

https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

Download and install the latest version , if your on win10 64 bit take this: "x64: vc_redist.x64.exe".

Then reboot and check if it fix your issue.

**Comment by plemsoft** [comment] 2020-04-09 10:26
@Duchenkuke c++ runtime, and graphic drivers are related so also make sure to update your graphics driver to the latest version.

Remember to reboot each time you try something , as the c++ runtime lib need a reboot to make it work.

**Comment by Duchenkuke** [comment] 2020-04-09 11:20
okay will do ! I will report the results asap

**Comment by Duchenkuke** [comment] 2020-04-09 11:45
[Guru-MapEditor-last.log](https://github.com/TheGameCreators/GameGuruRepo/files/4455922/Guru-MapEditor-last.log)

here are the log files

**Comment by Duchenkuke** [comment] 2020-04-09 11:46
[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/4455926/Guru-MapEditor.log)

[Guru-MapEditor-last.log](https://github.com/TheGameCreators/GameGuruRepo/files/4455927/Guru-MapEditor-last.log)

**Comment by Duchenkuke** [comment] 2020-04-09 11:47
I'll update my graphics driver, hang on

**Comment by Duchenkuke** [comment] 2020-04-09 11:47
and thanks for bearing with me

**Comment by Duchenkuke** [comment] 2020-04-09 12:07
I downloaded the Visual C++ thing and updated my drivers still i get the crash

**Comment by Duchenkuke** [comment] 2020-04-09 12:08
[Guru-MapEditor-last.log](https://github.com/TheGameCreators/GameGuruRepo/files/4456013/Guru-MapEditor-last.log)

**Comment by plemsoft** [comment] 2020-04-09 13:38
@Duchenkuke Checked your log , and your running out of mem:

392662 : get terrian sectors complete                           S:36MB  V: (3603,0) 

(3603,0) This is just to the point where there is no more mem available in 32 bit.

So this is the reason your having problem , i will check more in details where the mem is used and see if there is anything to be done about it , besides removing objects.

I dont have time for this before tomorrow , but will get back to you :)

**Comment by Duchenkuke** [comment] 2020-04-09 14:07
Thank you so far Preben. Strange tho! It worked fine in the previous version.

**Comment by MooKai** [comment] 2020-04-10 01:15
Hello all,

as I have exactly the same problems, here are my logfiles. Maybe it's also the memory problem?
I've updated all drivers + VC++ added, edited the lines in system.ini and yes the level still crash, if I try to test the level.

[Guru-MapEditor.log](https://github.com/TheGameCreators/GameGuruRepo/files/4459359/Guru-MapEditor.log)
[Guru-MapEditor-last.log](https://github.com/TheGameCreators/GameGuruRepo/files/4459360/Guru-MapEditor-last.log)

Thanks for the help. :)

**Comment by MooKai** [comment] 2020-04-10 01:19
"besides removing objects."
I've tried that already, removed 99% of the objects, still crash...

**Comment by plemsoft** [comment] 2020-04-10 08:59
@Duchenkuke 
@MooKai 

Please try this version and let me know if it fix your issues:

https://drive.google.com/file/d/18yICX-oNoBIDqBHCIfQbC1UcNUPLgAZx/view?usp=sharing

Happy Easter to you both , and if we are successful i will get the fix to @LeeBamberTGC  :)

**Comment by Duchenkuke** [comment] 2020-04-10 09:01
will try right away :)

Happy easter to you too!! And thanks for all your work you do for gameguru and its community !

**Comment by Duchenkuke** [comment] 2020-04-10 09:13
youre the best man..

I dont know what you did but my level loads and runs now!!!
I will test more but it seems to work and I am REALLY HAPPY !! Thank you ! :)

**Comment by Duchenkuke** [comment] 2020-04-10 09:17
shadows look so much better too... amazing work.. really.

**Comment by Duchenkuke** [comment] 2020-04-10 09:38
![Guru-MapEditor 2020-04-10 11-18-22-41](https://user-images.githubusercontent.com/35990507/78981163-a45d4500-7b1f-11ea-9bbb-e8173642379b.jpg)

I love how it actually shows the shadow form the hill in the distance now. Really well done!
Also, is there a way to somehow increase the sun light and decrease the ambience light? I have set ambient lighting to zero but its still to bright at the spots the sun doesnt shine at

**Comment by Duchenkuke** [comment] 2020-04-10 09:50
gotta love these shadows!

![Guru-MapEditor 2020-04-10 11-46-53-12](https://user-images.githubusercontent.com/35990507/78981998-6fea8880-7b21-11ea-82e1-ecc87ac82c46.jpg)

![Guru-MapEditor 2020-04-10 11-49-14-69](https://user-images.githubusercontent.com/35990507/78982007-737e0f80-7b21-11ea-9575-23f29f851ef0.jpg)

**Comment by plemsoft** [comment] 2020-04-10 10:13
@Duchenkuke Those shots just show that this little change in shadow just increase the look of your game by 100% , amazing work :)

Yes i can see that what you need now is control of the sun , intensity and color , that would allow you to make the areas the sun hit brighter and you would still be able to lower the brightness/contrast of the hole scene, so i think that control of the sun would allow you to get the result your looking for ?

**Comment by Duchenkuke** [comment] 2020-04-10 10:36
yes, exactly :)

Now I am testing level 2 - first level ran fine!

**Comment by synchromesh62** [comment] 2020-04-10 12:49
@plemsoft 
Hope you don't mind I tried the Mapeditoe.exe as well but am confused .
I noticed static lights now illuminate in  test game and standalone " Without any lightmapping " 
Is this new ? has it been like this a while and I never noticed ?

If its new and now works that way what's the difference between using the static compared to the dynamic ?
BTW ..Light mapper seems pretty amazing right now ..

**Comment by Duchenkuke** [comment] 2020-04-10 13:03
I  think that was a feature bevore already. @synchromesh62

**Comment by synchromesh62** [comment] 2020-04-10 13:16
@Duchenkuke 
I noticed it in the editor but in test game they were still dark ( for me anyway ) 
My reason for asking is if this is the case … Would 50 un lightmapped static lights be better than 50 dynamic ones for example ? unless this is all an accident ..

**Comment by plemsoft** [comment] 2020-04-10 14:29
@synchromesh62 It was a feature i made when adding the new light system a few years back setup.ini "showstaticlightinrealtime=1" , just allow you to see the light in editor before you actually bake the light. Currently i dont think you will see any fps difference if your only using 50 lights, but you need the lightmapper if you want those shadows from static lights :)

**Comment by MooKai** [comment] 2020-04-10 14:46
hello,

I've tested the new mapeditor.exe.... loading.... yes! 
Now it don't crash anymore. :) Thank you :) Great work! 

But here are 2 other bugs which appear only in the final standalone.

1. The fadeout effect not work really well, you can also hear for 0.5 the main menu music....
https://www.youtube.com/watch?v=DsG0JAb2Hy0

Yes, I'm using "allowfragmentation=2" for the mem. cleanup between the levels...

2. The ammo counter doesn't work, after pickup ammo the counter is still at 0.
This happens only in the standalone, in the GG test mode it works.
https://www.youtube.com/watch?v=3HOu9KDy42Q

Happy Easter! And a nice weekend :)

**Comment by plemsoft** [comment] 2020-04-10 14:49
@Duchenkuke You can actually use a spot light to get you some additional light (with color) , just place a spot light way out there where the sun is , the spotlight has a endless range so you should be able to use it like this, give it a try :)

![spotlight](https://user-images.githubusercontent.com/18662417/78999484-07b09c80-7b4b-11ea-988b-a35d9888da43.jpg)

@MooKai i check tomorrow , think its time for a Easter beer :)

**Comment by synchromesh62** [comment] 2020-04-10 14:55
@plemsoft 
LOL I must have had an iffy install. "showstaticlightinrealtime=1"  did indeed show them in the editor view ( top down etc ) but never in actual test or Standalone game. well not for me anyway. 

![S-LIGHT](https://user-images.githubusercontent.com/35708217/78999935-91f50280-7b43-11ea-9ac5-30c222cf648e.png)

**Comment by Duchenkuke** [comment] 2020-04-10 15:15
@MooKai 

I got the first issue too. Wanna know how I fixed it? Just add a little delay to the title music. That does it. No more music playing! A 1 second delay will do!

**Comment by Duchenkuke** [comment] 2020-04-10 15:16
> 
> 
> @Duchenkuke You can actually use a spot light to get you some additional light (with color) , just place a spot light way out there where the sun is , the spotlight has a endless range so you should be able to use it like this, give it a try :)
> 
> ![spotlight](https://user-images.githubusercontent.com/18662417/78999484-07b09c80-7b4b-11ea-988b-a35d9888da43.jpg)
> 
Interesting !

i will check that out!

**Comment by MooKai** [comment] 2020-04-10 15:24
@Duchenkuke yes, I have done that already. :)
But for the fadeout is no workaround... so, I hope they can fix it ... both 

More important is the ammo counter :(
Don't know if its only happen with the DLC Enhanced Weapons, or if the default weapons affected too.

**Comment by Duchenkuke** [comment] 2020-04-10 15:26
strange. I got custom title music too and it works fine for me. Maybe your delay is not big enough?

I didnt test the weapons yet..

@Preben I just tested the spotlight but they dont cast any shadows - Is that changeable? otherwise it looks not as good as normal sunlight

**Comment by MooKai** [comment] 2020-04-10 15:41
missunderstanding.... :)
yes, I know that a delay will fix the sound problem. I've done that before.
In the video is the default GG music without delay to show the bug.

**Comment by Duchenkuke** [comment] 2020-04-10 16:29
ah okay^^ ;)

**Comment by LeeBamberTGC** [comment] 2020-04-10 22:15
@Duchenkuke Can I confirm this original bug "Test Game mode causes gg to crash" as fixed?

**Comment by plemsoft** [comment] 2020-04-11 06:53
@LeeBamberTGC Yes the original fix was confirmed by @Duchenkuke and @MooKai , will close this issue. Just added the fix to GitHub.

@MooKai The ammo will only work if the original weapon that it was designed for is on the level. the .44 ammo is set to be used for the M29s , but will also work for the Mk19T if both weapons are on the level , a simple fix is to just copy the "M29s" into your standalone folder, you dont even have to add it to your level. Or you can make some ammo that refer directly to Mk19T and it will also work. PS: if your releasing please make sure the "M29s" is encrypted :)

**Closed by plemsoft** 2020-04-11 06:53 UTC
Labels: bug, fixed
