### ISSUE TITLE
CineGuru Issues - Zones moving and changing dimensions on level save

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#4718] opened 2023-06-17 06:56 UTC
Trigger zones are moving position and changing size and shape when  a level is saved. This seems worse if the zone boundaries have been previously adjusted.

It becomes worse if several zones are placed.

**Comment by AvengingEagle** [comment] 2023-06-17 12:15
Can confirm I'm experiencing this too. They seem to like moving to the same location as other zones within the level. As seen here: https://youtu.be/lbEYz5T93Ok?t=388

**Comment by LeeBamberTGC** [comment] 2023-06-19 16:53
@AvengingEagle Thanks for the video, great to see CineGuru MAX progress!!  Would like to help prioritise the MAX bugs that might get in your way to completion. I did a quick zone creation and movement test, but as you can imagine I was not able to reproduce the intermittency of the zone shift issue:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/3a1c9da0-57db-4508-b02e-defd2345b8c9)

Maybe you can send the level shown in the video as I suspect if the zone data is corrupt or cross linked in some way I can view this at the back end and see how the data might have got tangled and work out what is responsible.  Feel free to reference other issues in this relating to CineGuru MAX core obstacles!

**Comment by LeeBamberTGC** [comment] 2023-06-21 14:51
@davetgc Possible fix for next EXP build. There was an issue related to corrupt object groups being saved with a level, and then on reloading affecting other entity placement activity on the incorrect assumption some entities related to others and would move them too. Next EXP build detects these corrupt groups and deletes them from the level (back up your levels at all times as this is a new fix and is a destructive act)

**Comment by AvengingEagle** [comment] 2023-06-22 16:44
Have I understood this correctly? The new EXP build will simply delete corrupt object groups, so stuff will potentially start going missing in our levels, rather than not corrupting in the first place?

**Comment by LeeBamberTGC** [comment] 2023-06-23 10:50
@AvengingEagle I would not put it past me :)  Alas no, any objects you place down will remain in the level just fine, it's just that any internal group data that is associated with objects that simply do not exist are deleted from the level, so the next time you save those groups are not associated with dead entities (and by extension do not mess with existing entities that have since been repurposed within the level, thus avoiding the issue yous saw with zones).

As to the original corruption, that still needs to be reproduced, if it still exists. I did a lot of work on Smart Objects around the V1 release and that fixed a lot of nasties around group data and the like, so it may be fixed and older levels are just carrying around some old corruptions.  If you find any group data issues in the meantime, please do post here.

**Comment by davetgc** [comment] 2023-06-23 12:26
I'm still seeing zones changing shape, but they don't appear to be moving anymore.

**Comment by synchromesh62** [comment] 2023-06-23 13:38
Could they also be made to stay to the ground ?
That would probably help deformations. 
We don't need to lift the nodes up in the air any longer like we did in classic or fpsc.

**Comment by davetgc** [comment] 2023-06-23 13:42
I've actually noticed that they sometimes rise up from their original
position. For awhile I thought the hurt script had stopped working, but it
seemed the zone had risen up, I only discovered this when I pressed jump in
the zone and received damage.

**Comment by LeeBamberTGC** [comment] 2023-06-25 11:24
@davetgc Can you attach a small FPM level and a step by step on how I can see the zone shapes moving?  So far, all the zones I have placed down stay put and I have not seen them change shape on me :)

**Comment by davetgc** [comment] 2023-07-04 06:20
@LeeBamberTGC - I will try, but it doesn't seem to be happening in small levels, and is happening less than it did in larger levels. If I can replicate in a default media small level I'll update this.

**Comment by LeeBamberTGC** [comment] 2023-07-10 15:37
@davetgc No worries, we can close this for now and re-open/re-link if this can be reproduced reliably. Even small movements in the zone should not affect most users, but if this can be pinned down, we will know more!

**Closed by LeeBamberTGC** 2023-07-10 15:37 UTC
Labels: bug, Max, Waiting for more information., High, Level Editor
