### ISSUE TITLE
Water rendering in Front of Clouds

### ISSUE THREAD

**Issue by Skevos-Mavros** [TheGameCreators/GameGuruRepo#2105] opened 2022-02-14 05:55 UTC
GGM seems to be rendering water in front of most atmosphere effects (Haze/Fog/Light Streaks/Clouds).  This is most noticeable when up above the clouds (obviously) but is also visible more subtly down at ground level.  It makes distant water "pop" out more than it should.

![2022-02-14 Water Render A](https://user-images.githubusercontent.com/56815299/153807677-912bf044-40db-4079-a0f1-af6f5b2d9eca.jpg)

![2022-02-14 Water Render B](https://user-images.githubusercontent.com/56815299/153807750-7de87f15-94b7-48c9-9ab8-acff14c09bde.jpg)

Thanks!

**Comment by Skevos-Mavros** [comment] 2022-02-20 22:54
Just leaving a note here that this bug is still present in Build 2022.02.18

![GGM Water Rending D 2022-02-18](https://user-images.githubusercontent.com/56815299/154868016-d98348a8-bacb-45f4-8e62-e09370ff2a47.jpg)
![GGM Water Rending C 2022-02-18](https://user-images.githubusercontent.com/56815299/154868018-14ffc8c5-8c53-4501-aa3c-4677bf38fc09.jpg)

**Comment by LeeBamberTGC** [comment] 2022-04-12 22:17
@ThomasJowett Ignore the "water through clouds" part for now, focus on the first screenshot that shows water through haze/light streaks to reproduce and determine why, or discount this as only applying to clouds.

@PaulSJ @plemsoft Feel free to chime in with your own theories here so Thomas can explore and reproduce this distant water effect.

**Comment by PaulSJ** [comment] 2022-04-12 22:29
The water in front of the haze issue is caused by the same thing as issue #2574 once we fix that then this issue will fix itself. The water and clouds is something else though.

**Comment by ThomasJowett** [comment] 2022-04-13 13:43
I changed the name due to prevent this from being a duplicate of #2574

**Closed** 2022-04-26 12:15 UTC
Labels: bug, Fixed but need confirmation., Max, High, Rendering
