### ISSUE TITLE
After yesterday's update when you exit the play test this Lua error is written

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4269] opened 2023-03-20 12:37 UTC

**Comment by SampeyFS** [comment] 2023-03-20 12:37
![error lua](https://user-images.githubusercontent.com/108415264/226340705-686c12e4-e0f8-4ccd-97d3-0c6679b1225a.png)

**Comment by AmenMoses** [comment] 2023-03-20 18:41
Duplicate of #4268

**Comment by davetgc** [comment] 2023-03-21 13:40
Closed as reported #4268. Please use search before posting issues. Thanks,

**Closed by davetgc** 2023-03-21 13:40 UTC
