### ISSUE TITLE
particles emitter changes to what looks like smoke after multiple edits

### ISSUE THREAD

**Issue by Grogadog** [TheGameCreators/GameGuruRepo#754] opened 2020-04-08 17:30 UTC
Decided to learn about particle emitter. After following guide  on forum , finally got my head round it after loads and loads of trial and error to get a camp fire to work how I want it.
Anyway the fault happened several times during this process. What happens is for no apparent after loads of tweeks to .lua and test loads, the emitter emits what looks like smoke, instead of the images it is supposed to. I then save, and come out of GameGuru completely. Restart GameGuru , and all is okay again. Cheers, Grogadog

**Comment by Grogadog** [comment] 2020-04-08 18:09
Have seen a comment on another subject that suggests that emitters are probably not being cleaned up between runs,

**Comment by AmenMoses** [comment] 2020-04-08 19:53
You are correct and it isn't just particle image files, there are many things that are completely cleaned up between test runs.
Personally I save often and reboot GG, always have done.

**Comment by plemsoft** [comment] 2020-04-09 07:59
@Grogadog It would do that if ParticlesLoadImage return -1 , and its not able to load the image for some reason , could you check for this in your script and let me know if this is the problem , thanks :)

**Comment by LeeBamberTGC** [comment] 2020-04-10 22:24
@Grogadog If you can also provide the files necessary for me to reproduce the issue here, with a step by step so I know how to reproduce the issue quickly, I can then get to the heart of the issue and solve it for the next update, thanks!

**Comment by Grogadog** [comment] 2020-04-11 08:22
Hi, Getting the bug to reproduce is not easy.
But the video show various states of the 'fire',
the lua file is the one I used to produce the test result.
the entity is 'fire' from Classics, dungeon, fire.

What I did,
I messed about between the major file for the game I am making gathering
info for test, and used it and video show the fire working, it is the
darker clip with fire working.
made a very basic level just fire and the lua, fire had defaults set except
static mode No, physics on, always active on.
test run the basic level, - edit lua file, (in each iteration I only
altered the
 (-0.9)   with minor changes of the line     .-0.9, .3, -0.01, 0.01, .5,
0.01,  -- end pointing towards  - makes speed and direction ?
I started at 0.01 up to 0.20 (20 changes)
each time doing a test run, bug did not appear. thought it was cured!.
I then went to my game, ran it and the bug appeared, i.e dark clip with
smoke. I had done nothing except swap active levels, doing a automatic save
as I did the swap.
ran it again and the smoke was still there. Closed down GameGuru. Went back
to Steam, launched again , did test run and fire was on no probs.
again did loads of changes to lua file, worked fine each test.
Changed level back to basic level, first run bug appeared , smoke instead
of fire.
closed game guru and back again , okay.

Okay so what I deduce is that just changing the lua file doesn't cause the
problem immediately.
doing multiple changes to file and doing test run seems to fill up the
stack, and each rerun not clearing the stack and/or cache enough.
Changing the level file at this point seems to be the trigger, whether it
would affect other particle emitters I dont know. and whether it was the
size of my 'Castle' level had an effect,

In the .lua file I have made comments, Like I say I am only just starting
using game guru (less than a month), and finding documentation is
difficult, I know about GG forum and steam forums, smallg's files
particulaly helpful, except the inventory system wont work for me.
it works well in test mode but throws errors in standalone! I have removed
it from my level.
Anyway to get back to what I was saying please have a look at the lua file
and tell me whether the comments I made are correct. Also it may be my lack
of expertise in the .lua file I missed something that I should do to avoid
the prob e.g. destroy it, although I dont think that would work lol
If you need more from me , just ask. Hope you can make the bug happen!
Much respect and keep safe at this horrible time,
Steve

mobile 07789 704104

**Comment by AmenMoses** [comment] 2020-04-11 14:27
Can you attach the lua script.

**Comment by Grogadog** [comment] 2020-04-11 15:35
It was attached to previous email, but here it is again, and the original
from which it was adapted.
Cheers.

mobile 07789 704104

**Comment by LeeBamberTGC** [comment] 2020-04-16 14:52
@Grogadog I cannot see the attachment, you need to drag the file into the write area and it will present it as a link so I can download it, thanks!

**Comment by Grogadog** [comment] 2020-04-17 11:07
-- LUA Script - precede every function and global member with lowercase
name of script + '_main'

function flame_emitter_init(e)
local imageFile  = ParticlesLoadImage( "effectbank//particles//flame.dds" )

local emitter = ParticlesGetFreeEmitter()

ParticlesAddEmitterEx( emitter, .5,1, --anim speed, 0 random  angle ,
                  -8,2,-8,8,4,8, -- world coord base size in relation to e
  25, 30, 1, 2, -- start and end size
  -0.01, .3, -0.01, 0.01, .5, 0.01,  -- end pointing towards  - makes speed
and direction ?
  -1, -1, 600, 622, --life of particle
  40, 90, 0, 0, --alpha start and finish
  30, e, 0, imageFile, 64 ) -- 1000 = 1 second of wait between waves! e or
-1, file, frames on image
end


function flame_emitter_main(e)
end
Cheers Steve
mobile 07789 704104

**Comment by AmenMoses** [comment] 2020-04-17 16:15
The loading of the particle sheet needs to be done outside of the _init function and also it is a good idea to control the image number yourself, eg:

local imageFile = ParticlesLoadImage( "effectbank//particles//flame.dds", 5 )

This will always use index 5  so the first time the script runs it will load the file, the next time it will already be loaded so won't need to load it again but won't use up another index.

You can do the same thing with the emitter:

local emitter = emitter or ParticlesGetFreeEmitter()

**Comment by AmenMoses** [comment] 2020-04-17 16:20
Btw, once you have finished with an emitter you should delete it otherwise in a game setting you may run out of free emitters.

**Comment by Grogadog** [comment] 2020-04-17 17:09
Thanks for info.  will try and follow instructions.

In the same level I have two 'log fires' using the same lua file for the
effect, is this okay? Cheers
Steve


mobile 07789 704104

**Comment by LeeBamberTGC** [comment] 2020-04-17 20:22
Yes, any number of entities can use the same LUA script, they will run independently of each other yet share globals that you declare.

**Comment by AmenMoses** [comment] 2020-04-18 12:45
Each entity will require a separate emitter if you want them active together, if they are in different parts of the map you would want to code it such that the emitter is created when the player comes within visual range and is deleted when out of range.

**Comment by Grogadog** [comment] 2020-04-18 13:01
thanks Steve
Keep safe!

mobile 07789 704104

**Comment by plemsoft** [comment] 2020-04-24 09:23
@Grogadog Tried your script and the problem is that your do not specify a image id (like AmenMoses said) , and you also do not delete the image again , so what will happen is that the particle system has 25 free slots for images , 3 are already used , so if you call your script 22 times you get a new image each time and it runs out of available slots.

So to fix this change this line:

local imageFile  = ParticlesLoadImage( "effectbank//particles//flame.dds" )

to:

local imageFile  = ParticlesLoadImage( "effectbank//particles//flame.dds" , 5 )

Also make sure if you have more emitters that use another image , you should give it a new unique id. ( ID 3-25 is available for use ).

Let me know if this fix your issue , thanks :)

**Comment by Grogadog** [comment] 2020-04-24 10:34
Hi Preben, Thank you, yes, i think I understand the principle.
PLEASE PLEASE, help with one question I have spent hours on, How do I make
the evil wizard shoot at me, tried allsorts looked at stock answers. dont
work, please try and make it do it yourself before answering because I
think a recent built may have disturb its logic.
Sorry to be a pain, Wont ask again .
Ignore if you want, will ask on github , if no answer. Thanks
You all do a great job, I have purchased Max , cant wait for the new
finished product.
Keep safe
Grogadog

mobile 07789 704104

**Comment by LeeBamberTGC** [comment] 2020-04-30 14:18
Best any questions not directly related to resolving this specific bug go in the forums, thanks!

**Closed by LeeBamberTGC** 2020-04-30 14:18 UTC
Labels: Answered, bug
