### ISSUE TITLE
GG MAX Booster Animations

### ISSUE THREAD

**Issue by oliamit12** [TheGameCreators/GameGuruRepo#3543] opened 2022-08-03 03:10 UTC
When using the behavior-Play Animation, the character performs spurious actions between animations. i.e. bobbing about or levitating.

**Comment by davetgc** [comment] 2022-08-03 08:18
Can you please post a step by step. I wasn't able to replicate this.

Thanks,

**Comment by oliamit12** [comment] 2022-08-05 20:55
I set a character Aztc slave. I set play animation for behaviour. I then imported the animations from a character I made in CC.
The animations looked fine in CC. The way I used them was RANGE =200, ACTION PLAY = ground_sleep_stand_up, ACTION LOOP = idle_standing_hand_on_hip, iDLE PLAY= sleep_ground_lay_down,   IDLE LOOP = ground_ sleep_idle. The idea being when I approach the character is lying down and stands as I get near(as in Lee's demo on Youtube). It seems to work. The problem is when I retreat, the character lies down but after a second maybe it bobs up into the vertical position (entering the terrain) sort of spins at the belly. It's quick but not unnoticable. It's quite difficult to build a logical sequence with 4 slots. As you really need 5 to have 4.(1 to turn around with, as it were) If you see what I mean. Thanks.

**Comment by LeeBamberTGC** [comment] 2022-08-12 11:58
@oliamit12 I did find a few bugs that would use the wrong animation reference that would show as random animation issues, so this might be fixed. Could not reproduce when following your steps so cannot confirm.  Did manage to create a custom anim set in CC and then apply it to another character from the library. Not the most elegant process yet, but we will keep improving it!

**Comment by ZakJudges** [comment] 2023-02-16 09:37
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks

**Closed by ZakJudges** 2023-02-16 09:37 UTC
Labels: bug, Fixed but need confirmation., Max, Waiting for more information.
