### ISSUE TITLE
Particle effect is causing big trouble ( Report on Steam by Jessika 07  )

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#5087] opened 2023-11-29 18:34 UTC
To the devs. 
A particle effect is causing a big problem in the program. My level work fine, but only if i am from a great distance from a particle effect that seems to have its bloom level out of proportion, crashing the fps to almost an halt (from solid 60 fps to nearly 4 fps as you get closer to the effect.) i have tried to delete it but it seems it is stuck to the level. There is no way to remove it. i cannot even see an icon to remove or identify it.

https://drive.google.com/file/d/1UBAwUG6U-4FIivus9kLkO0jNUGR4IYfx/view?usp=sharing
https://drive.google.com/file/d/1QCElkrBL2FWX5Yis-G6oYybdfhrWSI_k/view?usp=sharing
https://drive.google.com/file/d/1Z1b6xFwFtOiZbdzBQaFp3qEd_zYyNz1J/view?usp=sharing
https://drive.google.com/file/d/1no2TA2YsmHP1m6PSBjheyUd_a0BXStka/view?usp=sharing

**Comment by davetgc** [comment] 2023-11-30 16:00
I can confirm I've seen this, but I've not be able to replicate it since for a report.

**Comment by LeeBamberTGC** [comment] 2023-12-01 19:12
@synchromesh62 Also cannot reproduce it, but you can remove any object from the level using the Detailed view, just find the item in the left expanded view, select the item, move the pointer into the level editor area and press the DELETE key:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/a3b2b4b0-0723-49df-bda8-1c4f608eaf1c)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/a7f147a9-8680-457b-b3e1-5c3543d1d6ff)

**Comment by synchromesh62** [comment] 2023-12-02 15:31
Hi Lee .. 
Ok thanks i will let the Steam user know .. Its a bit of a prob if they refuse to use Github as they cannot respond directly :(

**Comment by LeeBamberTGC** [comment] 2023-12-08 14:33
@Jessika07 Thanks for your words, much appreciated!  Have been blogging even before the internet had blogs and have a pretty thick skin these days, so feel free to throw vegetables if necessary :)  We have an amazing community here, and I am humbled and happy to continue working on game makers until I am no longer needed.  I will likely be the oldest 'game maker' maker out there before too long!

**Comment by LeeBamberTGC** [comment] 2023-12-10 14:00
As we have had some recent particle effects work and cleanup we may have accidentally fixed this one. I will mark as fixed until it surfaces again in the next EXP build.

**Comment by Jessika07** [comment] 2023-12-13 05:25
Thank you so much! 
By using the detailed object view,  i was able to delete all the particle effects causing trouble.  You should have a look at this particular one... called ; 'Fire_Tornado_3'  it was the culprit in my level.  When i look into the settings, i could not see anything special about it.
Thanks again!  ;)

**Comment by Jessika07** [comment] 2023-12-13 05:25
i will post on steam how to do that, it may help others as well.

**Comment by davetgc** [comment] 2023-12-13 06:36
I'll close this as fixed, but please feel free to reopen it if the problem resurfaces.

**Closed by davetgc** 2023-12-13 06:36 UTC
Labels: bug, Fixed but need confirmation., Max, Low, Particles
