### ISSUE TITLE
Test Multiplayer Map Issue #1

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#505] opened 2019-04-15 05:08 UTC
IF you accidentally press the test multiplayer button (which i do all the time by accident) and then you try to back out of multiplayer to your map. All of your map will appear empty.

**Comment by Teabone3** [comment] 2019-04-15 05:10
This issue is similar to #457 of which I reported in 2018. Almost forgot about that one.

**Comment by perelect** [comment] 2019-04-16 23:16
I do this all the time as well, 
Once you exit multiplayer mode the map you go back to Is empty. 
If you then run a normal TestGame the map returns back to normal.

**Comment by Teabone3** [comment] 2019-04-17 07:01
This just happened to me again. Lost over 1 hours worth of work. I am calling it a night.........

**Comment by plemsoft** [comment] 2019-05-12 07:13
@Teabone3 Thanks for reporting this.

Looks like Lee moved it a little bit away from "test" mode thats good.

And i can see that there is some problems if you forget to save your map first.

If i add a message box like this , would that solve your issue ?

![areyousure](https://user-images.githubusercontent.com/18662417/57579004-223f4900-7496-11e9-8255-b08b3f290644.jpg)

**Comment by plemsoft** [comment] 2019-05-12 07:15
Ahh sorry the dialog is in Danish , it would say "OK","CANCEL" on your setup :)

**Comment by Teabone3** [comment] 2019-05-12 17:37
The slight movement of the icons is actually a great way to avoid mistakenly hitting the button.

Though the addition of a prompt would be perfect.

**Comment by synchromesh62** [comment] 2019-05-13 00:11
Even making a Multiplayer Map and testing its pretty annoying when you exit MP and the map your working on has gone from the editor ?
Is that something that can be fixed or is that just the way it is ?

**Comment by synchromesh62** [comment] 2019-06-06 13:50
Smallg has found you can get the entities back by hitting the normal test game button and exiting back to the editor...

Confirmed as it works !!   Nice one smallg

**Comment by plemsoft** [comment] 2019-06-11 10:19
Restoring of old map, after multiplayer will be addressed in this issue:
https://github.com/TheGameCreators/GameGuruRepo/issues/513

**Closed** 2019-07-14 20:45 UTC
Labels: Version March 2019, bug, fixed
