### ISSUE TITLE
GGMAX Bug - Particles settings seem to reset when creating a standalone

### ISSUE THREAD

**Issue by mav3r1ck1981** [TheGameCreators/GameGuruRepo#5742] opened 2024-09-23 14:59 UTC
Image below is of particles in the editor, animation and opacity settings have been changed via the sliders, and work fine in test game:

![image](https://github.com/user-attachments/assets/cf34fa70-6fde-4acd-8df6-915ad7c7d3fe)

In standalone however, all settings appear to reset to default:

![image](https://github.com/user-attachments/assets/de9167aa-76ef-4502-9000-2df7f8a417cd)

**Comment by Kasseyus** [comment] 2024-10-04 01:42
https://youtu.be/3Adg6APuX9c

Additional Video from duplicate ticket:
https://github.com/TheGameCreators/GameGuruRepo/issues/5762

**Comment by Kitakazi** [comment] 2024-10-04 22:55
On the EXP.
Particles Opacity is reset to default 100 everytime you save a level, then close/reopen Max and then load the level.

Video: https://youtu.be/eFprGai3OIM

To Reproduce:

    Create a blank level and place a particle effect, something like the thick smoke to to easily see.
    Set the Opacity very low something like 5.
    Save the level and close Max.
    Reopen Max and load the level and the Particles Opacity will be as if it was set to 100.

**Comment by Kasseyus** [comment] 2024-10-07 15:35
@LeeBamberTGC 

Verified - The opacity resets to default, even though the slider is correct.  Touching the slider reverts to the correct opacity.

https://github.com/user-attachments/assets/5207824f-5bcd-421f-9a1e-0c95d3b447f9

**Comment by Kitakazi** [comment] 2024-10-09 07:14
I hate to be "that guy" but is there an ETA on when a fix for this will be made for the EXP version. I'm trying to complete my game for the Halloween contest that is coming up. And it is due really soon. As you can imagine for a Halloween competition, I have a ton of fog particles and having them all at default animation speed and opacity makes the levels basically unplayable because you cant see anything. 
If it won't be fixed within the next week then w/e I just need to know so I can start removing particles from my levels. If I need to update to the DEV version then I'll do that as well. I just need to build this game sooner than later, starting to stress out.

**Comment by LeeBamberTGC** [comment] 2024-10-13 13:44
@Kitakazi I heard on the grapevine that Preben stepped in to help, can you confirm or should I take a look this week?  Just uploading a new EXP build now, should be available in 10-20 minutes.

**Comment by Kitakazi** [comment] 2024-10-13 14:41
Yes Preben fixed the particle issue for me. If he sent the changes over to you then it should be good.

**Comment by LeeBamberTGC** [comment] 2024-10-14 09:21
@Kasseyus You should find a new EXP build with the latest commits in there :)

**Comment by plemsoft** [comment] 2024-10-14 09:56
@LeeBamberTGC This is not fixed , as I did not have your latest commits, the problem is here I think:
https://github.com/TheGameCreators/GameGuruMAX/commit/4f0597a6d0a02c58a8c5189b8d5c31e17460a297#diff-ece13a7ea9f99ad4b411ea489dab7f9f0167ffd55bd764d6418a2f40f55d4670R712
It looks like it always activates even if it already is .active ? :)

**Comment by mav3r1ck1981** [comment] 2024-10-14 11:00
Tried a standalone, all particles reset im afraid

**Comment by mav3r1ck1981** [comment] 2024-10-29 16:17
can confirm

**Comment by LeeBamberTGC** [comment] 2024-10-30 17:44
@plemsoft I think this was one of the issues you had a commit fix for. I am guessing it fixed it in the test level but not the standalone export for some reason.

**Comment by plemsoft** [comment] 2024-11-01 08:30
@LeeBamberTGC Just tested again , and it do work in standalone ? , even @mav3r1ck1981 confirmed it after you sent out the devtest ?

**Comment by LeeBamberTGC** [comment] 2024-11-03 18:05
@Kasseyus I have removed the officially reproduced as a new DEVTEST has just been uploaded. Can you test again and confirm this bug has been fixed as per originally reported, thanks!

**Comment by Kasseyus** [comment] 2024-12-09 16:59
@LeeBamberTGC The fix is solid for me.  In DevTest, the opacity remains where it should in both Test Game and Standalone.

**Closed by Kasseyus** 2024-12-09 16:59 UTC
Labels: bug, Fixed but need confirmation., Max, Medium, SaveStandAlone
