### ISSUE TITLE
Harddisk Error Prompt?

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#654] opened 2019-12-11 04:45 UTC
Experiencing an annoyance with one of my maps. It consistently displays this error and clicking either of the 3 options it provides makes it reappear 3 times before eventually loading my map. The map itself plays fine however when loading it the first time in editor it will always present this error.

![error](https://user-images.githubusercontent.com/35990109/70592164-d2993b00-1ba6-11ea-9ac4-f80d14c5ba6e.JPG)

**Comment by Teabone3** [comment] 2019-12-13 03:55
I found the offending entities. Was switches.

**Comment by Teabone3** [comment] 2019-12-14 04:39
It won't allow me to do standalone build either. Presenting same error in a constant loop.

**Comment by plemsoft** [comment] 2019-12-14 09:18
@Teabone3 I tried the fpm you posted last time , with no errors (just a blank water map) could you post the fpm the contain the error ?

**Comment by Teabone3** [comment] 2019-12-31 14:00
Found the issue for this bug , its directly related to  Model Pack 2 when using some of the Catacomb models.

**Comment by synchromesh62** [comment] 2020-02-28 18:49
@LeeBamberTGC 
@plemsoft 
Solution above related to Model Pack 2

**Comment by LeeBamberTGC** [comment] 2020-03-25 04:00
The original bug report looks like a system issue rather than a software one, related in some way to disk usage.  GameGuru works fine if given standard hard disk drives with plenty of capacity. I went ahead anyway and dropped in 'some of the Catacomb models', test game, standalone, run around, no disk drive related issues popped up:

![image](https://user-images.githubusercontent.com/35840583/77500492-20336e00-6e4d-11ea-93c0-a7c9dea79116.png)

Closing this bug as not reproducible, but if you can reproduce it with the update at the end of March we can reopen this and use a better report to reproduce the issue.

**Closed by LeeBamberTGC** 2020-03-25 04:00 UTC
Labels: bug
