### ISSUE TITLE
CRASH in test game mode, and other known issues

### ISSUE THREAD

**Issue by thecyrus** [TheGameCreators/GameGuruRepo#50] opened 2018-02-03 14:05 UTC
Hello folks (I'm Cylo on the forums), I just wanted to briefly share my experience with Public Preview.

- First of all, something that I read is well known. Lightmapping is a mess, and it creates crazy shadows on buildings and a sort of "fishnet" on terrain. Also, some pre-existing entities have black textures.
- Storyzone marker is not working.

- But the biggest one (that made me revert do the previous release) is Test Mode continuously freezing and going back to editor. It happens almost every time I simply try to edit setting tabs to modify some values; it freezes and... "Resuming from previous session". Back to editor. Even on a blank level with no entities, still happens.

**Comment by Teabone3** [comment] 2018-02-04 00:59
Lightmap issues have been reported #42

Story Zone issues have already been reported: #20  and if you review the changelog that are attempts to fix it. Including possible new support for other movie formats such as MP4.

**Comment by thecyrus** [comment] 2018-02-04 02:54
The first two I know where already known. I’m just talking about what I experienced.
The other one is strange, I never set different security settings on the application.
I’ll have to redownload PP to try this, but I never set it and this may be a workaround for sonething that has to be fixed.

**Comment by earthling45** [comment] 2018-02-04 04:25
It should be possible to whitelist GG i think.
I've had similar problems as you with an earlier build due to my antivirus.(avast)
After removing GG from the list in avast, everything run smooth again.

**Comment by Teabone3** [comment] 2018-02-04 05:26
Usually this occurs when the software cannot launch its assets properly. If not Windows Application Security Settings than next step would be checking your anti-virus as mentioned above. Only people to experience this issue its generally from the user end. Since the DX11 build seems to work for everyone else. Hopefully you'll able to isolate the cause otherwise it be hard for anyone to help figure out the problem since the contributors here are not experiencing it.

**Comment by thecyrus** [comment] 2018-02-04 11:14
I’m only using Windows Defender on W10.
Strange that few people are founding this issue.
I’ll probably make further tests but I’m not sure antivirus is involved.

**Comment by Teabone3** [comment] 2018-02-04 22:11
You probably answered this in the forums already what is your video card?

**Comment by thecyrus** [comment] 2018-02-05 10:09
Using a GTX 760 and re-validated a lot of times, it can’t be a point. It only happened with PP.

**Comment by thecyrus** [comment] 2018-02-05 10:19
Later, I’m going to reinstall PP again to do more tests.

**Comment by thecyrus** [comment] 2018-02-07 22:18
UPDATE:

I reinstalled Public Preview to do more tests about this.
I found out that it happens when pbroverride is set to 0.

At first, it didn't happen. Then I set pbroverride=0 to avoid black textures on my VA buildings, and the issue appeared again.

(with no antivirus enabled, just to be sure because it was mentioned)

**Comment by thecyrus** [comment] 2018-02-08 22:18
OK guys, I can confirm.
When pbroverride=0, Test Mode freezes if I try to edit settings on F9 menu.

But if I set it to 1, many of my assets are black-textured.

**Comment by plemsoft** [comment] 2018-02-09 17:31
Believe i fixed this , need someone to confirm , if you got this problem sent me a email plemsoft@plemsoft.com and i will sent you some new .exe files for testing. thanks for your help :)

**Comment by thecyrus** [comment] 2018-02-09 19:03
What do you mean "if you got this problem sent me a email"?

I got this problem, I told here.

**Comment by Teabone3** [comment] 2018-02-09 19:05
I think he's asking for others to confirm if they have this problem as well.

**Comment by plemsoft** [comment] 2018-02-09 23:55
thecyrus: Yes i know , what i asked was if you want to help confirm that it has been fixed , if you sent me a e-mail at plemsoft@plemsoft.com i will e-mail you back the .exe files that have been fixed, this way we can also check if it fixed your problem. And if anyone else have the same problem just give me a e-mail and i will sent you the fixed version for testing , Thanks for helping out.

**Comment by earthling45** [comment] 2018-02-10 03:39
My system, AMD FX-6300/GTX 960/16gb system memory/win764 
I've set pbroverride=1 to =0 and placed some items on an empty map, went in testmode and pressed F9.
I was able to sculpt the terrain, paint the terrain, place grass, select an entity and duplicate it and place it in another position.
To be sure, i've also loaded two large maps of which i'm certain that the village map has light maps.
But again no problems with sculpting terrain and duplicating/placing entities.
So i don't think i have the same problem as thecyrus. :)

**Comment by thecyrus** [comment] 2018-02-10 09:05
@earthling45 
It really freezes when editing settings.

Set pbroverride to 0 and then start GG, go in Test Mode, press TAB and try to change setting bars.

You ONLY scuplt terraing, but I don't see you tried to edit settings. Try that.

**Comment by thecyrus** [comment] 2018-02-10 09:43
@Teabone3 Please try it too yourself.
With pbroverride set to 0,  start GG, go in Test Mode, press TAB and try to change setting bars (shadows, bloom-related bars, etc.
I reinstalled Public Preview twice, it can't be casual.

**Comment by earthling45** [comment] 2018-02-10 15:08
Ok, i've pressed tab/tab in test mode and adjusted every slider. 
On two occasions it freezes temporary, when changing terrain and when changing grass type or very shortly when adjusting grass.

But this i consider normal, the longest freeze is when i change terrain from lush to another palette.
I tested this with the village map which is quite demanding and has lightmaps.

**Comment by thecyrus** [comment] 2018-02-10 15:20
@earthling45 No, that's normal.
I don't mean the slow-down when you change terrain or grass.
I mean that when I try to adjust ANY setting, it freezes and closes Test Mode.

So it didn't happen to you. Still need to know why does it happen in my case.

**Comment by earthling45** [comment] 2018-02-10 15:32
I'll try that. :)

What i did get just before i could place my previous comment was a bsod 1a, which points to a memory management problem or worse, a bad memory module in my system. :(
Gameguru was already closed so the latter seems more likely, i'm afraid.

**Comment by thecyrus** [comment] 2018-02-10 15:41
Oh, sorry about that.

I made a video on the fly to show what happens. Test Mode freezes and it goes back to editor without pressing ESC.

https://youtu.be/l8lje1Mzu9M

**Comment by earthling45** [comment] 2018-02-10 16:03
Yes, i've watched the video, which slider were you adjusting?

I've placed sandstone structure 16 and iron shed on the map and adjusted every slider without a problem, sorry.
Hopefully others will try the same to see if they get the same freeze as happening on your side.

In the video, that is an empty map with only those two structures?

**Comment by plemsoft** [comment] 2018-02-10 16:52
>So it didn't happen to you. But I'm trying to understand why it happens in my case. Not every time, but very often.
Instead of all this would it not be more easy to get the new fixed .exe files so you can confirm it has been fixed ? , i spent more then 20 hours ONLY on this bug to find it and fix it , and i know Lee spent time on it to, so if you could confirm it has been fixed we can move on and spent time on other bugs.

**Comment by thecyrus** [comment] 2018-02-10 17:21
@earthling45 

> I've placed sandstone structure 16 and iron shed on the map and adjusted every slider without a problem, sorry.

Ok, notice that it doesn't happen every time, but I've seen it often.

> i've watched the video, which slider were you adjusting?

This time, when I recorded, I didn't try to edit any bar, it froze just by pressing tab/tab.
But other times, it was on a random bar, it doesn't matter wich one.

plemsoft, send it to me so.
>  i spent more then 20 hours ONLY on this bug to find it and fix it , and i know Lee spent time on it 
It's a known issue, so.

**Comment by plemsoft** [comment] 2018-02-10 23:15
> plemsoft, send it to me so.

Great what is your e-mail ? , thanks for helping :)

**Comment by thecyrus** [comment] 2018-02-11 15:23
You're welcome. I really hope it's over.

Send to thecyrustemp@yopmail.com

**Comment by thecyrus** [comment] 2018-02-12 17:55
@plemsoft OK, it doesn't seem to happen anymore with this version.
There's only a little mess with higher water level.

**Comment by plemsoft** [comment] 2018-02-12 21:31
Hi , Thats **great** news :) , that one was pretty hard to find.

Dont worry about the water level , in the github version you need to edit setup.ini and set
defaultterrainheight=600

This has been changed , so its just your .exe that dont fit the setup.ini , you can just change that yourself and you should be good.

Thanks for your help testing this out :)

**Comment by plemsoft** [comment] 2018-02-12 21:34
Im going to get the fixed version into github and will then close this , as the other 2 bugs are duplicates.

**Comment by thecyrus** [comment] 2018-02-12 22:05
Nice, keep going, guys.

**Comment by plemsoft** [comment] 2018-02-13 10:35
Fixed in latest branch.

**Closed by plemsoft** 2018-02-13 10:35 UTC
Labels: bug
