### ISSUE TITLE
Object library preview crashing MAX

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#3896] opened 2022-11-16 08:34 UTC
Selecting the large object preview causing MAX to crash. Checked with several weapons previews, it might also affect other thumbnails, if anyone can confirm.

**Comment by ZakJudges** [comment] 2022-11-17 11:35
@davetgc I couldn't reproduce this crash in the latest experimental build, however, it is most likely caused by the DX12 changes.

**Comment by davetgc** [comment] 2022-11-17 11:45
@ZakJudges  - It could be, it wasn't just me, another user also reported it. I'll try again.

**Comment by ZakJudges** [comment] 2023-02-16 09:44
Closing this issue as likely caused by DX12. If the issue persists, feel free to reopen. Thanks

**Closed by ZakJudges** 2023-02-16 09:44 UTC
Labels: bug, Fixed but need confirmation., Max, High, CRASH!
