### ISSUE TITLE
Terrian texture doesn't change in the texture palette or paint.

### ISSUE THREAD

**Issue by Hamada880** [TheGameCreators/GameGuruRepo#2413] opened 2022-03-05 08:57 UTC
I have tried to change the terrain texture and used tiles texture in different format, but in the first two slots the texture doesn't appear on the texture palette or paint on the terrain and the rest of the palette texture can be seen on the slots but not paintable as well and still using the default textures.

**Comment by PaulSJ** [comment] 2022-04-19 14:41
Duplicate of #2737

**Closed by PaulSJ** 2022-04-19 14:41 UTC
Labels: bug, Max, Terrain, Post Early Access
