### ISSUE TITLE
Game guru crashes whilst editing a lua file

### ISSUE THREAD

**Issue by Grogadog** [TheGameCreators/GameGuruRepo#742] opened 2020-04-03 14:02 UTC
whilst editing a lua file game guru disappears, after changing the lua file for an entity, the third time you change it and do an edit in notepad++ game guru disappears, see attached video for better idea of whats going on.
[GameGuruCrash480.zip](https://github.com/TheGameCreators/GameGuruRepo/files/4427701/GameGuruCrash480.zip)

**Comment by plemsoft** [comment] 2020-04-06 09:49
@Grogadog Thanks for your issue,

I tried following your video , but i did not have any problems.

Did you try this in 2020.04.03 , i know there was some issues fixed in the IDE there, so this might also have fixed your issue ?

**Comment by Grogadog** [comment] 2020-04-06 10:39
Hi Preben,
I am not having as many crashes when dealing with lua in notepad, making
sure I dont leave more than one script open. But no problems today so far,
been working on it for several hours now and no crash so maybe its fixed.
Will reply again if it does it again. and i will dig deeper.
Thanks
Steve

mobile 07789 704104

**Comment by plemsoft** [comment] 2020-04-06 10:57
@Grogadog Yes things are happening fast at the moment , so many bug fixes ... i assume it is fixed as i was not able to reproduce it using the latest , this version have many additional fixes and will go out in a few days , so it would be better to report it again after the next update , so we have the same version :)

**Comment by Grogadog** [comment] 2020-04-06 16:35
Yep, not had problem since last email. Thanks
Keep Safe my friend. at 71 yrs, max self isolation
Steve

mobile 07789 704104

**Closed** 2020-04-07 00:32 UTC
Labels: bug, fixed
