### ISSUE TITLE
GGMAX - TGC Download version - Every time I update or verify files Installer Deletes Booster Pack and Aztec Game Kit.

### ISSUE THREAD

**Issue by thor49** [TheGameCreators/GameGuruRepo#3185] opened 2022-05-24 15:38 UTC
This is getting very frustrating.. Why is GGmax still silently deleting TGC packs and content and  Levels and projects..

What am I doing wrong..
It has to be something simple..
You would not  deliberately  delete these TGC products so it must be me..

The Booster Pack and Aztec do not give me access to change the install folder - 
so you must be putting them in the correct place but why would you then delete them.

Help

**Comment by LeeBamberTGC** [comment] 2022-05-26 13:41
@thor49 I think you have found a bug, this is not by design for sure!  Leave it with me, I will find a solution for this weeks release :)

**Comment by ZakJudges** [comment] 2022-05-27 15:54
Hi @thor49, thanks for reporting this issue :) The fix is now available for download. Note that since it is the installer itself being updated, the deletion of DLC bug will happen one final time

**Comment by thor49** [comment] 2022-05-30 12:33
Hi ZakJudges :-  Yes you are correct the new install did delete the Booster and Aztec again.. 
I then reinstalled them and did a Verify files and this time They did not get removed... 
I will let you know after the next update how it goes... 
Thanks for your quick work..

**Comment by LeeBamberTGC** [comment] 2022-06-01 11:59
I will test and close this soon, please let me know if it is still an issue, thanks!

**Comment by LeeBamberTGC** [comment] 2022-06-06 15:52
@thor49 Is this still an issue, or has it been fixed. Will close soon :)

**Closed** 2022-06-13 13:22 UTC
Labels: bug, Urgent, Fixed but need confirmation., Max
