### ISSUE TITLE
GameGuru MAX - Bug - Glitched Textures In-game and in editor

### ISSUE THREAD

**Issue by Sinergygames** [TheGameCreators/GameGuruRepo#3882] opened 2022-11-06 17:49 UTC
I don't know why this is happening. It's not just this level, even when I create a new level the same thing happens. Terrain textures are not loading properly, and objects are also missing textures. 
I tried loading into the level and GGMAX freezes with no error message, and I have to force quit from the Task Manager. 

https://youtu.be/SD5Zpu8AxG8

Same thing happening on a new empty level https://youtu.be/qO9Ppnnzx98

**Comment by realPrunelle** [comment] 2022-11-08 22:18
I confirm this.  But at my Installation of GGMax, this happens since month. I thought it is something at my PC .

**Comment by davetgc** [comment] 2022-11-09 18:46
It took awhile, but I can confirm this. It seems to be an issue with fog, but I'm not sure,

**Comment by plemsoft** [comment] 2023-04-07 13:07
@Sinergygames @realPrunelle @davetgc Im not able to reproduce it , we made a fix for some decals that was visible at startup even when not used, it could look like a decal mess thats scaled , this was fixed laste year, are any of you able to reproduce this in the latest build ? , and if so could you save the level while you see it and e-mail the level to me at plemsoft@gmail.com , but i do believe this was the old decal bug. Let me know Thanks :)

**Comment by LeeBamberTGC** [comment] 2023-04-13 20:18
@plemsoft Going to close this as I cannot reproduce it either, and it is a 2022 bug, probably long fixed :)

**Closed by LeeBamberTGC** 2023-04-13 20:18 UTC
Labels: bug, Max, Waiting for more information., High, Rendering
