### ISSUE TITLE
Game guru disables screensaver in Windows 10 pro PP build 2018.02.xx directx11 preview

### ISSUE THREAD

**Issue by a3dartist** [TheGameCreators/GameGuruRepo#90] opened 2018-02-25 15:00 UTC
Hi, everyone I have noticed that the screensaver in Windows 10 pro gets disabled when running game guru preview build! Also does it in current release as well! I have to reboot my computer after running game guru, is shut down because the screensaver doesn't work after shutting down game guru is there a way around it or is this a bug!

**Comment by LeeBamberTGC** [comment] 2018-04-10 11:40
Is anyone else experiencing this on Windows 10 Pro?

**Comment by LeeBamberTGC** [comment] 2019-06-26 14:09
Closing this issue as not able to reproduce.

**Closed by LeeBamberTGC** 2019-06-26 14:09 UTC
Labels: bug, help wanted
