### ISSUE TITLE
GGMAX Copy and Paste Issue

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#2096] opened 2022-02-12 22:38 UTC
When copying (Ctrl C) and paste with (Ctrl V) an object, the mode changes back to terrain mode when it shouldnt. It seems to happpen randomly but does happen after either 1 or more Ctrl V pastes. Not a game stopper but could be looked at for polishing editor useage.

**Comment by Necrym59** [comment] 2022-02-22 19:43
Yes Zac i still have the issue on this build

https://user-images.githubusercontent.com/95015657/155206676-7506717a-144d-4dc4-a727-a1531cfe0b9d.mp4

Happpens randomly but happen after either 1 or more Ctrl V pastes. I had no other tasks happening at the time just to be sure it wasnt a conflict of some sort.

**Comment by ZakJudges** [comment] 2022-02-23 11:02
Hi @Necrym59, thank you for the video. It seem the issue was caused by pressing the 'v' key on its own. A fix has been added and you should see it on Friday :)

**Comment by Necrym59** [comment] 2022-03-05 00:32
This is now confirmed fixed as of Build 2022.03.04 - thankyou guys

**Closed** 2022-03-05 08:50 UTC
Labels: bug, Fixed but need confirmation., Max, Level Editor
