### ISSUE TITLE
Alpha Clipped Objects Problem

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#1656] opened 2021-12-10 04:02 UTC
I imported and saved an object with alpha clipping before export it showed ok in the 3d view but in the add item thumnail it doesnt show alpha clipping. No alpha clipping setting seems saved and comes through without alpha clipping when an object is then loaded  in.
![alphaclipped_objects](https://user-images.githubusercontent.com/95015657/145515262-1ed932e9-f7b9-47ed-8af6-f5c9cf50eeb5.jpg)

**Comment by ZakJudges** [comment] 2022-02-25 12:55
Hi @Necrym59, so I can reproduce this. Would you be able to send me the model and the .fpe file that was generated for it? Thanks!

**Comment by Necrym59** [comment] 2022-02-25 20:35
Hi Zac
Here are the files having looked at the FPE transparency wasnt activated from the importer at the time even though it showd transaperency if its activated now in the FPE it works so it was just duing the import, it may have already been fixed by now.
The original images were png perhaps they had somthing to do with it. Im also in the process of redoing them anyway with dds images which seem to hold the transparency better anyway, (ive included the DDS for comparison purposes).
[samples.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8144702/samples.zip)

**Comment by ZakJudges** [comment] 2022-02-26 11:33
@Necrym59 Thank you for the attached files. I was able to reproduce the issue of alpha clipping values not being applied to the object after import. I believe the cause is related to issue #1636. Since the transparency works, I'll mark this issue as fixed. Once a fix has been added for the other issue, I will test your models again with only alpha clipping applied, and make sure it renders as expected before closing the issue :)

**Closed** 2022-04-03 09:40 UTC
Labels: bug, Fixed but need confirmation., Max, High, Importer
