### ISSUE TITLE
Importer not saving surface map settings. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#1303] opened 2021-08-10 09:29 UTC
If you import a model, and then change the surface map of the model and then adjust the roughness and metalness sliders and then save the model, the surface map / settings that were chosen on the import screen will be lost.

**Comment by Kitakazi** [comment] 2021-08-23 03:41
Also at the end of the import process when you got to select a thumbnail and background, it will show your textures that the model uses. The surface ones will all be reverted to what the model had when you first imported. 
The thumbnail creation page doesn't always open when importing objects either.

**Comment by ZakJudges** [comment] 2021-08-25 10:58
@Kitakazi Thank you for the info. Does the issue with the thumbnail creation page occur without changing the save path?

**Comment by ZakJudges** [comment] 2021-08-28 09:26
@Kitakazi If you look inside your custom write folder, all imported objects should be in the following folder structure: \Files\entitybank\user\

Could you confirm if this is the case? Thanks :)

**Comment by Kitakazi** [comment] 2021-08-29 06:44
Yes that is where the imported objects save too by default.

**Comment by ZakJudges** [comment] 2021-08-30 14:01
@Kitakazi Are the imported objects that don't appear in the thumbnail creation page still being saved to the write folder? By that I mean, are you still able to place them in your level, or not at all?

**Comment by Kitakazi** [comment] 2021-08-30 23:35
Yea everything saves as normal. Just sometimes the thumbnail creation page does not show up.

**Comment by ZakJudges** [comment] 2021-08-31 09:01
@Kitakazi The surface map issues should be fixed after the next update. I'm unable to reproduce the thumbnail creation screen not appearing. However, I'd really like to get it sorted, would you be able to send a video of the issue at some point? :)

**Comment by Kitakazi** [comment] 2021-09-01 06:14
Sure I just made this real quick just a video showing me importing a random .fbx file. No thumbnail creation screen opens. 
https://www.youtube.com/watch?v=nE9wPHSATzk

**Comment by ZakJudges** [comment] 2021-09-01 13:37
@Kitakazi Thank you for the video. If this is still an issue for you after the next update, just let me know :)

**Closed** 2021-09-04 12:06 UTC
Labels: bug, Max, High, Importer
