### ISSUE TITLE
GGMAX Bug - Smart Objects, doesn't keep objects linked

### ISSUE THREAD

**Issue by imothep85** [TheGameCreators/GameGuruRepo#5524] opened 2024-05-07 22:53 UTC
I created a smart object i attached fire decals, a particle and my torch object.
BUT if i don't select another copy of the smart object already in my scene AND i try to import the smart object from my library.....
the smart object doesn't work.
ALSO if you add those smarts objects in your level, and then later decide to delete some of them when we DELETE the smart object it randomly DELETE others smart objects in the level , sometimes it delete complete smart objects, sometimes it delete some parts inside the smart objects, decals, lights, particles...
If i just import the smart object from the library, it doesn't work, smart object is not complete decals, lights particles are missing....
as you can see in this video 

https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/3195b2cd-4205-4dad-9abe-0b45c8e02cac

**Comment by LeeBamberTGC** [comment] 2024-09-01 22:27
@imothep85 The random deleting of smart objects was related the group data corruption, and the latest DEVTEST attempts to correct any old corrupt data from the group system (that smart object uses) so should be fixed, but let me know with a fresh level step by step if you can still reproduce with DEVTEST.

As to the issue of having to select an existing smart object for a new smart object to work properly, can you send me the smart object you created along with any associated custom media you are using, and I will try to reproduce what I see in your video, thanks!

**Comment by Kasseyus** [comment] 2024-10-11 22:47
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.

**Closed** 2024-11-06 12:41 UTC
Labels: bug, Max, Waiting for more information., Medium, Level Editor
