### ISSUE TITLE
GG Max - grouped objects break when rotated

### ISSUE THREAD

**Issue by Ghost-l0l** [TheGameCreators/GameGuruRepo#2856] opened 2022-04-14 23:18 UTC
https://youtu.be/cySH-jqhejc  - recorded on lastest build [experimental]

**Comment by Tum1370** [comment] 2022-04-15 06:41
I have stopped using groups because they always mess up.
Not just the rotation, but end up getting other problems with previous groups you had already paced. 
Better to not even attempt to use them.

**Comment by LeeBamberTGC** [comment] 2022-04-28 20:23
@Ghost-l0l @Tum1370 Since this issue report, we have overhauled the rotation system to use Quaternions, and since then we have better rotation, and correct Widget rotation too. That said, I could reproduce it even after the quat work, so fixed a bug that would attempt to re-rotate the 'anchor' object of a group. Now I can create some Stairs as shown in the video and duplicate and rotate just fine:

![image](https://user-images.githubusercontent.com/35840583/165839333-9d0ce9bf-4f76-47f2-a893-2a68f1afbf38.png)

**Comment by Tum1370** [comment] 2022-04-29 13:51
@LeeBamberTGC 
Just had a test of groups quickly on the experimental build.
I placed a pallet down, then placed 8 sandbags on top of the pallet.
After grouping the pallet and 8 sandbags, i then placed 3 of the full groups to my right.
They rotated correctly whilst they were grouped up.
After ungrouping them, and testing the game, This is what i see.

Screenshot 1 is editor, The pallet directly in from of player markers arrow, is the original objects i placed and grouped.

Screenshot 2 is the Test game, and you can see the groups have messed up in test game. The pallets were actually moving about in Test Game, and the front one disappeared under the floor as i watched it, The screenshot caught it falling under the ground as you can see.

![image](https://user-images.githubusercontent.com/66874403/165957405-6c5e7c62-ea8d-4f5f-b06f-02ded9552b2a.png)

![image](https://user-images.githubusercontent.com/66874403/165957743-21cb4938-9b64-4987-8671-927b6baf8753.png)

**Comment by Tum1370** [comment] 2022-04-29 13:55
[Test Max Map.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8591276/Test.Max.Map.zip)

**Comment by plemsoft** [comment] 2022-05-02 09:32
@LeeBamberTGC Related: https://github.com/TheGameCreators/GameGuruRepo/issues/2965#issuecomment-1113869186 , could be the new quad ?

**Comment by plemsoft** [comment] 2022-05-03 05:10
@LeeBamberTGC same: https://github.com/TheGameCreators/GameGuruRepo/issues/3030
same: https://github.com/TheGameCreators/GameGuruRepo/issues/3036

**Comment by ZakJudges** [comment] 2022-05-11 12:49
@Tum1370 I tried the map that you sent but its blank, you will likely need to send the groups as well :)

**Comment by Tum1370** [comment] 2022-05-11 13:53
@ZakJudges 
This is just a pallet with 8 sandbags laid on top. Group them up, Place several of the group down, Then try test playing the games, rotating the groups, then test playing the game.
Some part of the group, LIke 1 sandbag, or maybe the pallet, Moves out of place.

Just tested this again now on the latest experimental build, and it was still doing this.

**Comment by LeeBamberTGC** [comment] 2022-05-16 15:25
@Tum1370 Cheers!!

**Comment by ZakJudges** [comment] 2023-03-10 14:56
Note: this is likely fixed as part of work on #3778

**Comment by Tum1370** [comment] 2023-03-16 11:12
@ZakJudges  Just retested this bug and after adding 10  sandbags to a pallet, grouped them up, and placed several copies of the group. The groups, and original group still messes up and messes up.

**Comment by Tum1370** [comment] 2023-03-16 11:23
@ZakJudges  I have just added 3 images, the 1st is the sandbags placed on the pallet and grouped up.
The 2nd is after placing 4 copies of the grouped object on the right hand side in the editor.
The 3rd is after testing the game, You can see the groups (including the original group in red circle) have all messed up in test game.

![1](https://user-images.githubusercontent.com/66874403/225602066-b5f19ea5-609e-4aeb-a613-a057757cebf5.png)

![2](https://user-images.githubusercontent.com/66874403/225602137-c71664a2-0d25-4a92-91f3-f71dc448f0d6.png)

![3](https://user-images.githubusercontent.com/66874403/225602170-dec22d78-3799-4c44-8b2b-a66494426ceb.png)

**Comment by plemsoft** [comment] 2023-03-30 13:43
@Tum1370 Just tried this in the latest EXP build , and was not able to reproduce it , could you try it again in the latest build and perhaps record a video when you do it, so im able to see exactly what you do , Thanks for your help :)

**Comment by LeeBamberTGC** [comment] 2023-03-30 13:49
@plemsoft Assign any group related issues to me for now. I am working on the BE import which are smart objects and the whole group object system needs an update, so rewriting parts of it now. When done, we should be able to hot swap pretty much any change to a group object/smart object including BE exports :)

**Comment by Tum1370** [comment] 2023-03-30 14:37
@plemsoft Sorry i dont do videos as never really cut / edited  / uploaded videos
But this is very easy to produce, Am not sure why you cant ?

This is the latest EXP build.

Screenshot 1, Place 1 (Pallet - 1200cm) on the ground. The stack 10 (Sandbag - A) on to the pallet like i have.
![1](https://user-images.githubusercontent.com/66874403/228870590-3de1625b-3654-4351-b221-1e7927153b7e.png)

Screenshot 2, Drag the box around the stack of sandbags and pallet, click create Group button.
![2](https://user-images.githubusercontent.com/66874403/228870808-824829dc-47fd-4169-9a6d-2a3967a49513.png)

Screensot 3, After locking the group, i then place the group 4 times to the right as in this screenshot.
![3](https://user-images.githubusercontent.com/66874403/228871022-5511d336-3d9b-4865-9929-76e9d2086e71.png)

Screenshot 4, Then hit the TEST GAME button, And watch all the pallets start going very funny and falling through the floot. Move around.
![4](https://user-images.githubusercontent.com/66874403/228871254-a6b876ec-92e8-4b6f-beb1-21ca1e6501cc.png)

**Comment by Tum1370** [comment] 2023-03-30 14:44
@plemsoft I do notice with what i just posted though. The more i move around, it is only the pallet at the bottom that moves / falls through the floor.
After a little time, all the pallets have fallen through the ground and disappeared. Including the original created group item.

![1](https://user-images.githubusercontent.com/66874403/228873612-c17bb0de-ee1e-4878-9d27-6e8ee3aae51d.png)

**Comment by plemsoft** [comment] 2023-03-31 08:53
@Tum1370 I i see the problem now , Pallet - 1200cm is set to physics on , so yes with the pallets above it would go under the terrain at some point , when placing the pallet just set the pallet to "static" and it will work.
This is not related to groups so will close this issue as the rotation is fixed, we will fix the Pallet - 1200cm issue for the next build :)

**Closed by plemsoft** 2023-03-31 08:53 UTC
Labels: bug, Fixed but need confirmation., Max, High, Groups

**Comment by Tum1370** [comment] 2023-03-31 09:33
@plemsoft Ok thanks for figuring this one out :)
