### ISSUE TITLE
Building Disappears

### ISSUE THREAD

**Issue by bbacle** [TheGameCreators/GameGuruRepo#3352] opened 2022-06-24 21:10 UTC
I put in a building & then put some barrels inside.
I also was putting lights in the building, but when I tried putting a light on the opposite wall to the 1st light, the entire building disappears.
I put it in play mode & the building is gone even in play mode.
Also when I was putting some assets into the game, the colors went all strange with everything in bright green & purple.

**Comment by davetgc** [comment] 2022-06-30 06:01
Can you find the building with the detailed assets list? Has it slipped under the terrain?

**Comment by ZakJudges** [comment] 2023-02-03 14:56
Closing due to lack of info and could not reproduce. If the problem persists, feel free to reopen.

It sounds like this is due to the building being moved below the terrain, likely caused by the following setting being switched off:
![Screenshot 2023-02-03 145515](https://user-images.githubusercontent.com/32545391/216634565-dd07265b-0fff-486f-a6e6-d48af6c570f3.png)

**Closed by ZakJudges** 2023-02-03 14:56 UTC
Labels: bug, Max, Waiting for more information., High
