### ISSUE TITLE
Made Smart wall

### ISSUE THREAD

**Issue by Snage62** [TheGameCreators/GameGuruRepo#1297] opened 2021-08-02 17:22 UTC
I have made a smart wall torch, but cant save it and keep in my items.

System Specs:
Operating System: Windows 10 Pro 64-bit (10.0, Build 19043) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: X570 UD
Processor: AMD Ryzen 7 2700 Eight-Core Processor           (16 CPUs), ~3.2GHz
Memory: 32768MB RAM
Windows Dir: C:\Windows
DirectX Version: DirectX 12
Card name: NVIDIA GeForce RTX 2060
Dedicated Memory: 5967 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)

**Comment by rvanner** [comment] 2021-08-10 13:53
@Snage62 Have you turned on Advanced settings? The save is not available until it's turned on;

![image](https://user-images.githubusercontent.com/1503593/128879354-e67547b9-6c43-4fe3-a161-1ce5103b8d32.png)

**Comment by rvanner** [comment] 2021-08-12 19:30
So this is not a bug. I will close this off now.

**Closed by rvanner** 2021-08-12 19:30 UTC
Labels: bug, Max
