### ISSUE TITLE
GG Max Bug Report - No Nav Mesh and the Characters pass through objects

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#2302] opened 2022-02-26 10:37 UTC
Max Update for February 27 in the evening.
No Nav Mesh and Character pass through objects :
![NoNavMesh](https://user-images.githubusercontent.com/96718175/155840057-e79400d1-52de-4e49-9ada-35a4347d5a33.jpg)
Flags Placement :
![FlagsPlacement](https://user-images.githubusercontent.com/96718175/155840359-173406b0-9095-46e0-b535-fc6f007bfeff.jpg)

**Comment by AlterMatz** [comment] 2022-02-27 08:49
Hi, I have the same problem. Character pass through closed door.

**Comment by synchromesh62** [comment] 2022-02-27 11:03
Reported this one a couple weeks back and Lee was looking into a system to deal with it.
The problem is simply that dynamic objects do not break the mesh unlike a static wall so its as if it is not there.
It was inevitable it would get picked up on again later but it is already being looked into hopefully.
https://github.com/TheGameCreators/GameGuruRepo/issues/2145

**Comment by UltraVox001** [comment] 2022-02-27 11:08
What mesh ? Take a good look at my first image ("Navigation Debug Visual" is enabled). There is no mesh.
And my walls are not dynamic objects. They are Static Box.
Enemies pass through all objects. Dynamic or not.

**Comment by synchromesh62** [comment] 2022-02-27 11:42
> What mesh ? Take a good look at my first image ("Navigation Debug Visual" is enabled). There is no mesh. And my walls are not dynamic objects. They are Static Box. Enemies pass through all objects. Dynamic or not.

What version are you using ?
Its working fine for me in the latest internal build. 
Note ... One panel i have left dynamic like a door ... He walks right through that which is what i thought you were referring to.

https://youtu.be/fiSuBz0GnBg

**Comment by UltraVox001** [comment] 2022-02-27 12:09
I use the same version as you.The Nav Mesh works on an empty map.
![NavMeshWithoutTerrain](https://user-images.githubusercontent.com/96718175/155881772-3e93d7bd-2f5f-4c4a-9dfc-3e9474266629.jpg)
Add a Terrain, and you will see like me. :)
[https://www.youtube.com/watch?v=bzYeYengMZo](https://www.youtube.com/watch?v=bzYeYengMZo)

**Comment by AlterMatz** [comment] 2022-02-27 12:40
I Have the Problem with door
![z_Body_specular](https://user-images.githubusercontent.com/100475522/155882677-fe8d2c02-a415-4b06-8c34-9004d8404776.png)

**Comment by synchromesh62** [comment] 2022-02-27 12:59
> I use the same version as you. The Nav Mesh works on an empty map. ![NavMeshWithoutTerrain](https://user-images.githubusercontent.com/96718175/155881772-3e93d7bd-2f5f-4c4a-9dfc-3e9474266629.jpg) Add a Terrain, and you will see like me. :) https://www.youtube.com/watch?v=bzYeYengMZo

Yep i can confirm on Terrain its not working.
As im working on Indoor stuff i went directly to my current level to test.

**Comment by UltraVox001** [comment] 2022-02-27 13:15
In reality, the nav mesh also "works" with terrain, but only on flat objects. A concrete slab placed on the ground, a hagar, but not on the ground. It is for this reason that for some users only dynamic objects do not work. This is because their game is located indoors. Outdoors, nothing works except large flat objects.
![NavMeshWithTerrain1](https://user-images.githubusercontent.com/96718175/155883909-1a440269-d52c-48d2-a469-58e6478da8c3.jpg)
![NavMeshWithTerrain2](https://user-images.githubusercontent.com/96718175/155883911-4449708c-f344-4bc7-b143-77afd20fb625.jpg)

**Comment by rvanner** [comment] 2022-04-03 09:37
Closing now.

**Closed by rvanner** 2022-04-03 09:37 UTC
Labels: bug, Fixed but need confirmation., Max, High, AI
