### ISSUE TITLE
Puddle reflection bug

### ISSUE THREAD

**Issue by dllllllllllb** [TheGameCreators/GameGuruRepo#2601] opened 2022-03-21 12:05 UTC
In Snowy Mountain Stroll, puddle reflection is cutting off under certain angles.
![image](https://user-images.githubusercontent.com/61796872/159256418-119a7194-c370-4ba4-904d-a515a598a4ff.png)

This only seems to be happening with this asset, water reflections are fine.

Steps to reproduce:
Put down a puddle
Scale it up
Place trees around it
Set sky box to sunrise

**Comment by rvanner** [comment] 2022-04-03 09:33
Closing this becuase it's a duplicate of [2495](https://github.com/TheGameCreators/GameGuruRepo/issues/2495)

**Closed by rvanner** 2022-04-03 09:33 UTC
Labels: bug, Max, High, Rendering
