### ISSUE TITLE
GG Classic Restoring

### ISSUE THREAD

**Issue by devitaldev** [TheGameCreators/GameGuruRepo#1771] opened 2022-01-17 03:50 UTC
Why is this happening?

_A game launched from the editor
Crash
Restoring the last project..._

The game runs from the editor. And this happens from time to time.

**Comment by UltraVox001** [comment] 2022-01-17 07:07
If there are active characters in your map, Max will crash.
Read this to understand :
https://github.com/TheGameCreators/GameGuruRepo/issues/1763
https://github.com/TheGameCreators/GameGuruRepo/issues/1766

**Comment by devitaldev** [comment] 2022-01-17 08:32
@UltraVox inform me:
_If there are active characters in your map, Max will crash.
Read this to understand :
#1763
#1766_
And yes, there are active characters on the map, from the character creator. Only this is not MAX, but GG Classic.
I hope this helps a little.

**Comment by devitaldev** [comment] 2022-01-17 15:07
It doesn't matter what was deleted. It is very likely that this is also a problem in the classic version of the program. That's why I mentioned it. Characters with custom head attachments, in particular, can also be a big problem.

**Comment by plemsoft** [comment] 2022-03-09 09:47
@devitaldev Thanks for reporting your issue , sounds like you found a bug ? , but the process is. If GameGuru crash for some reason it will restore your last project or level as it was before the crash. This is done to make sure even with the crash you will still be able to save your level/changes after it has been restored.

But about why it crash , i would need a little more information to find the problems, could you e-mail me a download link with the level that crash so I'm able to debug it and see what the problem is ? e-mail plemsoft@plemsoft.com

If you think the problem is your custom head attachments , could you also e-mail me that so im able to see what the problems is, thanks for your help :)

**Comment by devitaldev** [comment] 2022-03-09 10:58
@plemsoft Nothing is custom. Everything is from GameGuru except the respawn lua script, which I think is from the forum. I'm very sorry I can't help more. I currently do not use GameGuru.

**Comment by plemsoft** [comment] 2022-03-09 15:21
@devitaldev Thanks for getting back, even if you dont use GameGuru at the moment, perhaps you have a copy of the level that crashed, that would help me, and perhaps fix the issue for next time you give GameGuru a try, If you dont have it anymore we can just close this issue and you can open a new one next time you see it , thanks for your help :)

**Comment by devitaldev** [comment] 2022-03-09 20:49
@plemsoft I have a preserved map primarily for the reason that it was made with the help of a gguru loader with beautiful terrain. Unfortunately, the lua script, which I think is a problem, is lost. I think it's a script from the forum, and it's a script that revives a killed opponent after a while. Because the game level with the terrain is not an open source, I do not provide it. Sorry. As I don't use a GameGuru anyway, feel free to close the topic.

**Closed** 2022-03-09 22:04 UTC
Labels: bug, question, Waiting for more information., GGClassic
