### ISSUE TITLE
GGC - Issue - Character Creator Skin Tone Mismatch

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#4035] opened 2023-01-08 10:21 UTC
The character creator skin tone doesn't seem to always properly display when you place the character in to a map. The head will match the color picker but the rest of the body does not.

Older created characters seem to not have this issue.

![skin color](https://user-images.githubusercontent.com/35990109/211190854-e47747b5-e569-4fc6-86b7-1257395c3aa0.JPG)

**Comment by Teabone3** [comment] 2023-01-08 10:24
Another example and this is after relaunching GGC and opening the CC while on an empty map.

![skin2](https://user-images.githubusercontent.com/35990109/211190989-f9ecc065-4d77-45d1-bbe4-6b15b1cb188c.jpg)

**Comment by LeeBamberTGC** [comment] 2023-05-14 21:27
@Teabone3 Can you send me a newer character with this bad head issue, cannot reproduce in the March update.

**Comment by LeeBamberTGC** [comment] 2023-09-01 18:40
@Teabone3 Related to this one, now fixed in the next BETA: https://github.com/TheGameCreators/GameGuruRepo/issues/4805

**Closed** 2023-10-29 12:36 UTC
Labels: bug, Fixed but need confirmation., Medium, GGClassic, Character Creator
