### ISSUE TITLE
Crashed when I changed the colour of the water

### ISSUE THREAD

**Issue by Bollehopp** [TheGameCreators/GameGuruRepo#906] opened 2021-02-27 18:19 UTC
I had a rare crash today when I had changed the colour of water and it crashed on me twice in a row.
I mean by twice in a row that I task manager shut it down and then started gamegurumax again and then I changed the watercolour again and it crashed.. If its any help I changed it to a very bright red colour.
This happened twice in a row just today and was triggered only when I wanted to change the colour of the water in my level.

**Comment by rvanner** [comment] 2021-03-15 15:49
@Bollehopp  Are you able to reproduce this in the latest version release on Friday 12th March? If you can reproduce it, can you make a video of it happening?

**Comment by Bollehopp** [comment] 2021-03-17 00:30
Have not been able to reproduce this today but this test and the first time
I started to lower terrain in able to see water it crashed the engine.
Task manager shut down max and ran it a second time and the second time I
ran it no issues.


Den mån 15 mars 2021 15:49Richard Vanner ***@***.***> skrev:

**Comment by rvanner** [comment] 2021-03-17 08:08
We will be re-coding the terrain system so this will not be an issue later on. I will close this report now because you cannot easily reproduce and it will be superseded by the new terrain code.

**Closed** 2021-03-17 08:08 UTC
Labels: Future dev work will fix this, Max, help wanted
