### ISSUE TITLE
Import model - I can ONLY import models to the/user folder.

### ISSUE THREAD

**Issue by relishrompgames** [TheGameCreators/GameGuruRepo#2645] opened 2022-03-25 18:45 UTC
I created a folder in the entity folder called "JohnsBuildings"

When I Import a model - I can ONLY import models to the/user folder even though JohnsBuildings is the path. There is nothing imported into JohnsBuildings

**Comment by Ratall** [comment] 2022-03-25 21:13
I have successfully imported models into other folders but have found that in order to see them in max you have to restart it. Also when you do so it skips the final part where you set up the thumb nail and search keywords.
![proof subfolder import](https://user-images.githubusercontent.com/35710601/160201382-253bd450-ddee-4471-a1c1-7ab2bc3dbfc2.png)

**Comment by ArgentArts** [comment] 2022-03-26 00:35
I can confirm what Ratall has said. The folder is created and the model is saved/imported to the new folder, but you have to exit MAX and restart for it to show up in the Object Library. So, this is still a bug that needs to be addressed.

**Comment by ZakJudges** [comment] 2022-05-11 09:25
duplicate of #2830

**Closed by ZakJudges** 2022-05-11 09:25 UTC
Labels: bug, duplicate, Max, Medium, Importer
