### ISSUE TITLE
_CommonRedist folder is  empty ..

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#503] opened 2019-04-03 00:41 UTC
I noticed on the Beta that the _CommonRedist folder is empty ..
Im guessing this is also the case for the PP 
As we all install the original retail first before updating to the PP or beta it probably isn't a big deal but you may want to remember to put them in when releasing it retail …

No Directx or Visual studio installation might cause lots of DLL issues

**Comment by Pirate-Myke** [comment] 2019-04-03 03:08
I can confirm this on the Private Beta March fixer as well.
Folder names are there, but the folders are empty.

**Comment by perelect** [comment] 2019-05-23 13:52
[https://forum.game-guru.com/thread/220772#msg2615741](url)

I can confirm this a well.
The folder is actually missing altogether, in a new install of GG.
It looks like GG is now trying to use Steams _CommonRedist now.
But for me i get a"Runtime Error: 0: Cannot initialize DirectX 11" now.
Full info and screenshots linked, that goto the Beta Board at GG.

**Comment by perelect** [comment] 2019-05-24 07:08
My "Runtime Error: 0: Cannot initialize DirectX 11" was to do with my switchable graphics software.
I had to redirect the software to the 3 GG .exe and tell them to run at "High Performance".

So GG beta is working on my laptop without a _CommonRedist folder. 
ALL GOOD.

**Comment by Kasseyus** [comment] 2019-06-03 21:47
Issue appears to be resolved.  Closing...

**Closed by Kasseyus** 2019-06-03 21:47 UTC
