### ISSUE TITLE
GGM - BUG - The multi-select tool grabs other objects behind the object you're selecting

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#4524] opened 2023-04-22 11:38 UTC
And since there's currently no way to deselect an object you have multi-selected (requested here: #4281), the multi-select tool pretty much becomes unusable in situations such as these, where there are several objects around:

https://user-images.githubusercontent.com/103399301/233782130-67a61102-e97f-465a-9b3f-e5b3c57da3ea.mp4

**Comment by Kravenwolf** [comment] 2023-04-23 06:23
@davetgc , Enhancement? This literally makes the multi-select tool unusable when other objects are behind it. It's selecting objects through other objects!

**Comment by LeeBamberTGC** [comment] 2023-04-24 11:14
@Kravenwolf Fixed issue so now you have to click, and when you click, it only adds the one you clicked, not the one behind it, to the collection:
![image](https://user-images.githubusercontent.com/35840583/233980794-319c7007-1e15-43b0-b5a2-ca2dbc71a9c4.png)

**Comment by Kravenwolf** [comment] 2023-04-24 11:50
@LeeBamberTGC , thanks! This was giving me such a headache!

**Comment by Kravenwolf** [comment] 2023-04-28 09:30
@LeeBamberTGC , getting a new issue with multi-select in the V1 release that I wasn't getting a few days prior. Related? #4579 4579

**Comment by LeeBamberTGC** [comment] 2023-06-19 14:28
@Kravenwolf Took a whlle to reproduce. The cause is that if you drop in two object copies, then sel;ect one, hold down SHIFT and select the second, a third copy is created illegally which goes on to mess up multi-selection.  Fixed in NEXT EXP build :)

**Closed** 2024-09-13 16:19 UTC
Labels: bug, Fixed but need confirmation., Max, Medium, Level Editor
