### ISSUE TITLE
Waterlevel and enable trees are not saved

### ISSUE THREAD

**Issue by smmaas** [TheGameCreators/GameGuruRepo#1621] opened 2021-11-26 21:56 UTC
The waterlevel and the enable trees setting are not saved and the level is loaded with the default setting.

**Comment by ZakJudges** [comment] 2022-01-31 13:09
Hi @smmaas, I couldn't reproduce this issue. Are  you still experiencing it in the latest build? :)

**Comment by smmaas** [comment] 2022-01-31 20:23
Problem has disappeared some time ago.

**Comment by ZakJudges** [comment] 2022-02-01 09:05
Thank you for confirming. Closing this now

**Closed by ZakJudges** 2022-02-01 09:05 UTC
Labels: bug, Max, Waiting for more information., High
