### ISSUE TITLE
GG Max - The material index 10 (Tarmac sound) does not work

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#2103] opened 2022-02-13 17:48 UTC
The material index 10 (Tarmac) does not work.
The sound is however referenced in the materialdefault.txt file, and the sound files are present in: C:\Program Files\GameGuruMAX\Max\Files\audiobank\materials\tarmac
But no sound is produced.

I've tested and referenced all indexes that produce no sound, and 10 is one of them :
- 4
- 5
- 7
- 8
- 9
- **10 (Tarmac sound)**
- 12
- 14
- 15
- 16 

I hope it can help.

**Comment by LeeBamberTGC** [comment] 2022-02-14 13:37
@UltraVox001 Can you list your references of all materials that play no sound. It is likely related to the sounds being in stereo, and need to be in MONO if they are being used as 3D sounds.

**Comment by LeeBamberTGC** [comment] 2022-02-18 13:47
@dllllllllllb See if you can reproduce this one, and perhaps a stab at locating the code/sound event. I think my guess was wrong about the sound format, so it may well be the sound is never getting called..

**Comment by LeeBamberTGC** [comment] 2022-03-09 16:36
@dllllllllllb Turns out for material 10, the filename had a typo TARMAC vs TARMAK :)

**Comment by LeeBamberTGC** [comment] 2022-03-09 16:54
@UltraVox001 Will be in next internal build.

**Closed** 2022-03-09 16:55 UTC
Labels: bug, Fixed but need confirmation., Max, High, Sounds
