### ISSUE TITLE
Within Building Entity Selection Capability Continuing Problem

### ISSUE THREAD

**Issue by jasailor** [TheGameCreators/GameGuruRepo#366] opened 2018-09-05 14:40 UTC
GG has tremendous potential to be a great and popular engine. The editor, however, needs to be fixed so it can easily select and position objects more accurately. It is unbeleivablely poor when trying to work inside buildings and environments. The frustration of trying to select an object and then inadvertently select the wrong thing somewhere else in the level causing unintended changing is really turning me off to GG. I know about locking etc., but you need to be able to accurately and simply navigate the layers to even select right things to lock. Even then you can't select the right things to lock for the same reasons. 

I know this has been an issue for a long time and it needs to get fixed.

**Comment by LeeBamberTGC** [comment] 2018-09-06 11:11
Can you provide an FPM level using stock assets, and describe a step by step which shows the difficulty in selecting a specific object. That would be a good first step in understanding the problems you are having with the editor.

**Comment by synchromesh62** [comment] 2018-09-08 19:32
I must admit a video would help … Personally I don't have a problem but like everything you use a lot you get used to it so maybe there are easier ways when we can see what your struggling with.

**Comment by jasailor** [comment] 2018-09-08 20:29
Thanks for the interest in my issue.  I will post an example on Monday.

**Comment by jasailor** [comment] 2018-09-11 02:43
![dagored - sci fi corridors and halls](https://user-images.githubusercontent.com/41845014/45334912-8219d480-b542-11e8-98b4-c44824bb115d.PNG)

**Comment by jasailor** [comment] 2018-09-11 03:29
Lee, 
I'm not sure if this is sufficient to show you the situation.  The following files are:

1. The assets that I down loaded from the GG Store and used to create the building. (Dagored - Sci fi corridors and halls)
2. An over head shot of a building that I created to depict an alien space ship
3. First example of trying to select the door and it selects the room behind it.
4. Second example of trying to select the hall and selecting a room behind it that is below the surface plane.
5. Third example is on the second level and I try to select the hand switch and then the lift.


Another problem is that when I try to align entities by moving them a very small amount, they move at an exponential speed and distance.  Doesn't seem to matter what mode the editor is in at the time.  (grid, normal, snap).


![dagored - sci fi corridors and halls](https://user-images.githubusercontent.com/41845014/45335820-ad9ebe00-b546-11e8-9b82-b4c964bdd5fd.PNG)
![overall scene](https://user-images.githubusercontent.com/41845014/45336060-85638f00-b547-11e8-8135-c2c4b5ed624e.PNG)

[Game Guru - [mapbank_ST.fpm_] - [Entity Editing Mode] 9_10_2018 9_00_40 PM-2(2).zip](https://github.com/TheGameCreators/GameGuruRepo/files/2369212/Game.Guru.-.mapbank_ST.fpm_.-.Entity.Editing.Mode.9_10_2018.9_00_40.PM-2.2.zip)

[Game Guru - [mapbank_ST.fpm_] - [Entity Editing Mode] 9_10_2018 9_00_40 PM-2(3).zip](https://github.com/TheGameCreators/GameGuruRepo/files/2369215/Game.Guru.-.mapbank_ST.fpm_.-.Entity.Editing.Mode.9_10_2018.9_00_40.PM-2.3.zip)
[Game Guru - [mapbank_ST.fpm_] - [Entity Editing Mode] 9_10_2018 9_00_40 PM-2.zip](https://github.com/TheGameCreators/GameGuruRepo/files/2369217/Game.Guru.-.mapbank_ST.fpm_.-.Entity.Editing.Mode.9_10_2018.9_00_40.PM-2.zip)

**Comment by jasailor** [comment] 2018-09-13 04:14
I attempted to create the issue with the dungeon entities from the Mega Pack 02 with others and wasn't yet successful.  

Not sure how to send you the problem FPM file since it doesn't compress below 10M.  Should I send it through the Forum?  In any case the URL for the entity pack is  https://www.tgcstore.net/pack/10706 but I also use some standard entities in the scene.  Thoughts on next steps?

**Comment by jasailor** [comment] 2018-09-14 03:49
Lee,

Here is the link:

[https://drive.google.com/drive/folders/1p1nkHmAlt76YiU7bXG279B-M6rKvcpYD?usp=sharing](url)

Let me know if you need anything else.   I really appreciate you looking into this.

**Comment by synchromesh62** [comment] 2018-09-15 23:58
Hi there Jasailor 
I downloaded your map and tried it .. The first thing I noticed was the Clipping was literally way down below the models .. Can you confirm this isn't your problem before Lee spends time on it ..

Load the map ... Press " Tab" then hold the CTRL key down and scroll the mouse like hell backwards …
After 15 seconds or so you map will start to appear raising upwards with no roof  .. After that the same  method scrolling up and down will give you easy access to your models on various floors to select … Hovering your mouse above an asset will change it red or green so you know what your selecting .. Im not sure but this may be your problem ?

If I am miles off your problem I apologise but sometimes 2 heads are better than one :)

**Comment by jasailor** [comment] 2018-09-16 16:37
Synchromesh62,

Thanks for the suggestion.  I tried it and after it did raise the and lower the slice.  Thanks.  It didn't solve the problem though.   When I select an entity, it appears that the entity will flash the color for an instant then immediately revert back to the entity color.  What remains is it the movement tool but at that point it doesn't relate to the entity in view, but rather another entity which appears to be behind someplace.  Unfortunately, it isn't obvious until you move it a bit and the intended entity doesn't move but the unintended entity does thus causing the rather sloppy current condition of the scene.  :|

**Comment by synchromesh62** [comment] 2018-09-17 00:44
Ok it worked fine for me though although im missing models …
Could you try verifying your installation for corrupt files via steam ... Then reboot and try again … 
It may pay to backup any custom stuff you may have modified first though ..

But to confirm what I do see works fine for me ..

**Comment by tarkus1971** [comment] 2018-09-19 16:55
I sometimes have this problem too, and it is impossible to create a rubber band to grab the entity, as the others just get grabbed instead.

**Comment by jasailor** [comment] 2018-09-20 00:34
For me the rubber band doesn't work and if I click on an entity itself some entity our of sight gets selected.  

synchromesh62,  I did the repair you suggested and it seemed to help for a few selections, but soon deteriorated back into the same mode.  Although some of these assets are purchased I wouldn't think that would make a difference.  If it does then I would be really hesitant to keep building a scene in case at some arbitrary point I run into an issue and can finish the scene using the assets I need.   I see on the YouTube some elaborate indoor scenes so I keep wondering what can they be doing different than I am.  At this point, I'm not not sure what to do.   In case it is relevant, the following is my system config.
Windows 10 Home , Version 10.0.17134  
Processor  Intel Core i5-7600k CPU 3.8 GHz   3801 Mhz,  4 Cores, 4 logical Processors
Phy. Mem 8GB
Virt. Mem 9.2 GB

Are there any other techniques that I am not doing or something that I am doing that may cause this behavior?  Thanks for your help.

**Comment by synchromesh62** [comment] 2018-09-20 09:48
Could you perhaps do a video of this in action ..That would be a great help to actually see the issue your having in real time ?

**Comment by jasailor** [comment] 2018-09-22 12:10
Synchromesh62,

Here are the videos:

[Game Guru - [mapbank_ST.fpm_] - [Entity Editing Mode] 9_10_2018 9_00_40 PM-2(2).zip](https://github.com/TheGameCreators/GameGuruRepo/files/2407754/Game.Guru.-.mapbank_ST.fpm_.-.Entity.Editing.Mode.9_10_2018.9_00_40.PM-2.2.zip)
[Game Guru - [mapbank_ST.fpm_] - [Entity Editing Mode] 9_10_2018 9_00_40 PM-2(3).zip](https://github.com/TheGameCreators/GameGuruRepo/files/2407755/Game.Guru.-.mapbank_ST.fpm_.-.Entity.Editing.Mode.9_10_2018.9_00_40.PM-2.3.zip)
[Game Guru - [mapbank_ST.fpm_] - [Entity Editing Mode] 9_10_2018 9_00_40 PM-2.zip](https://github.com/TheGameCreators/GameGuruRepo/files/2407756/Game.Guru.-.mapbank_ST.fpm_.-.Entity.Editing.Mode.9_10_2018.9_00_40.PM-2.zip)

They show the depth issue quite well.  I had this issue with other assets both standard and purchased.

jasailor

**Comment by synchromesh62** [comment] 2018-09-22 14:15
Ok I have to be honest I was screaming at you watching the videos... No do it this way :)
Your going to have issues doing it like that … I kind of tried to replicate your situation and created a similar video ...I think ... 

This is the way i would handle things like that but you will notice at 2 minutes i lose the selection colours so i then zoom out ...click outside the models on the terrain and zoom back in and all become selectable again simply by highlighting with the mouse ... I didnt even realise i did it until i re-watched so its a good example of what your experiencing ... If the video helps then great but if not im really not sure what else to suggest unless Lee can improve the detection ...But for me its fine once you get your head round the quirks .. 

https://youtu.be/L0N4JyO5-6I

**Comment by jasailor** [comment] 2018-09-23 20:02
Synchromesh62, Lee,

Here are more video examples.   In these examples there are quite a few entity layers in the scene as opposed to the scene Synchromesh62 showed in the youtube.   Highlighting doesn't work and selection doesn't pick up the entity you are looking at even after doing the suggested work around steps.   

These kinds of things need to be corrected to make this tool productive even as a hobbyist.   The time needed to deal with the idiosyncrasies takes too much time away from developing the game elements and makes it frustrating rather than fun.   Sorry to be harsh, but GG is right on the edge of being really a great tool and it's frustrating to see these kinds of issues hold it back.    

[Game Guru - [mapbank_ST.fpm_] - [Entity Editing Mode] Moving Entity Behind Selection 1.zip](https://github.com/TheGameCreators/GameGuruRepo/files/2409073/Game.Guru.-.mapbank_ST.fpm_.-.Entity.Editing.Mode.Moving.Entity.Behind.Selection.1.zip)
[Game Guru - [mapbank_ST.fpm_] - [Entity Editing Mode] Moving Somthing Behind Selection 2.zip](https://github.com/TheGameCreators/GameGuruRepo/files/2409074/Game.Guru.-.mapbank_ST.fpm_.-.Entity.Editing.Mode.Moving.Somthing.Behind.Selection.2.zip)

**Comment by LeeBamberTGC** [comment] 2018-09-24 16:17
jasailor : Can you provide an FPM that uses only stock assets and a small step by step to reproduce the issue you show in your above videos. I tried reproducing it with SciFi corridors but they selected fine and I was able to create a small scene inside the tunnel no worries. My guess is that it has something to do with the entities you are using but won't know until I can reproduce the issue.

**Comment by LeeBamberTGC** [comment] 2018-10-15 12:34
@BodRH : Can you provide a step by step and small video showing this issue with any stock asset, I can then reproduce here and resolve it for the next build. Thanks.

**Comment by LeeBamberTGC** [comment] 2018-10-15 17:03
Can you post a link to the exact model thread, so I am not trying to reproduce an issue with the wrong model, thanks!

**Comment by LeeBamberTGC** [comment] 2018-10-15 17:04
I.E. Is there only one helicopter in the pack?

**Comment by BodRH** [comment] 2018-10-15 17:39
There are 2 helicopters in the pack, one animated and one not animated, there are also other animated models in it, all the animated ones have a red A on the icon bmp, I make the model then save it as a normal model before animating it and saving as an animated model. The link to the post with the model pack download is in the thread above or the direct link to the download is this https://forum.game-guru.com/attachment/18755

**Comment by LeeBamberTGC** [comment] 2018-10-15 22:11
The problem seems to be some extra animation matrix in the model (matCombined) which is throwing off the collision system. This can be solved by adding these lines to the FPE of affected models:

cpuanims         = 1
ignoredefanim    = 1

It is also worth disabling the playineditor flag as CPU animation has a small performance hit (though more so for boned models but okay if its a few limbs). The alternative is to find a way to export the X file without this additional matrix data, though I have no idea what setting it would relate to (perhaps something to do with first frame matrix or anim set, etc). I am not ignoring matCombined in models as a fix as some other legacy models use this data in concert with its other animation data to work. Goes back to the idea that there is no such thing as a single model format, even within the same file extension.

**Comment by BodRH** [comment] 2018-10-16 09:53
Thanks Lee, adding the 2 lines works fine but setting playineditor to 0 or commenting it out is not an option for the transport models, as they rely on the animations running for the scripts, I also use them for the lighthouses, search lights, windmills and waterwheels etc, if I get rid of playineditor they are just static models.

https://youtu.be/mOmXBafdaOM

https://youtu.be/ouS8O6Dgf2g

https://youtu.be/RYi0SM0NOXQ

**Comment by BodRH** [comment] 2018-10-16 10:19
Update, the 2 lines are no good for models whose animations aren't triggered by a script like the doors are, even with playineditor set to 1 they don't play the animations, when you place them the animation is played one full cycle then stops, like looping is turned off.

**Comment by BodRH** [comment] 2018-10-16 11:04
It doesn't play at all if you save as an FPM, it only plays as you place the model in the level, get the animated ghopperanim.fpe and use this for animation

;anim
animmax          = 1
anim0            = 1,16
playanimineditor = 1
cpuanims = 1
ignoredefanim = 1

Then place the gchopper in the level, as you place it the rotors spin one turn then stop.

**Comment by plemsoft** [comment] 2019-06-12 08:11
This issue has been fixed:
https://github.com/TheGameCreators/GameGuruRepo/commit/eafa0dce7acaf5aa0bd966350e1f5bb2786bcc82

**Comment by plemsoft** [comment] 2019-07-15 07:31
@BodRH Can you confirm that this has been fixed in the current release, actually i used your models to fix/test this so the selection problem should be fixed, let me know :)

**Comment by BodRH** [comment] 2019-07-15 19:15
I've just tried it and it is now fine, thanks.

**Closed** 2019-07-15 22:18 UTC
Labels: bug
