### ISSUE TITLE
Two Issues With GameGuru MAX

### ISSUE THREAD

**Issue by Enyawjt1** [TheGameCreators/GameGuruRepo#3993] opened 2022-12-20 21:14 UTC
Hi,
     I have two issues:
     1.) When I try to make a stand alone test I repeatedly get taken back to the launch page. What should I do? The GameGuru MAX forum recommended I contact you about this.
     2.) Also when I place a fort that I made with grouped parts in a game my allies don't follow me. Please advise.
       Thanks,
         Wayne

**Comment by davetgc** [comment] 2022-12-21 06:13
Hi,

What build are you using please?

**Comment by Enyawjt1** [comment] 2022-12-21 08:43
Hi,
I can't find where the game tells me what build it is but I can say that I purchased it off Steam and the game says "release date March 25, 2022."
     Thanks
        Wayne

**Comment by synchromesh62** [comment] 2022-12-21 13:06
@davetgc 
Tested and can confirm this issue ... Game will go to the **Game Won Screen** if you win
But if you **die** it restarts at the Start Position and does not go to the **Game Over Screen** 
This is a Standalone using the EXP Build

**Comment by Enyawjt1** [comment] 2022-12-21 16:46
My problem is when I try to TEST the standalone in preparation for making an actual standalone I go to the launch page and the test does not occur. Therefore I can not make a standalone that functions

**Comment by ZakJudges** [comment] 2023-02-03 12:44
Hi @Enyawjt1, I could not reproduce your first issue. However, there was a fix recently that could be related: #3974 

Your second issue was fixed last month. You can access the fix using the experimental build. For instructions on accessing the experimental build, see here: #3907

**Comment by ZakJudges** [comment] 2023-02-16 09:45
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks

**Closed by ZakJudges** 2023-02-16 09:45 UTC
Labels: bug, Fixed but need confirmation., Max, High, SaveStandAlone
