### ISSUE TITLE
Multiple Entities, In My Level Now Have Mis-Aligned Collision 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#3560] opened 2022-08-06 02:15 UTC
These Entities were previously fine, I haven't touched them. These entities were using Polygon and or Hull Decomposition. Here is screenshot of a desk that previously had no collision issues. 

![image](https://user-images.githubusercontent.com/51464873/183229569-6e1f30a2-5ae6-49a5-9467-b35d33510b5b.png)

Similar thing happens if I change the desk to "polygon." It makes it a little better but its still very misaligned. I have another entity in my level that is a Floor with a small step, for w/e reason it also now has misaligned physics, I was using Polygon on the floor model but changing to Hull Decom does not fix it either.

**Comment by Hamada880** [comment] 2022-08-08 03:23
I can confirm same issue happen to me and notice hugs frame drops when getting close to any of the static object compare to older updates.

**Comment by davetgc** [comment] 2022-08-12 09:17
HI, are you able to share the models so they can be tested?

**Comment by Kitakazi** [comment] 2022-08-12 15:31
I cannot share the models on here, I can send in email.

**Comment by davetgc** [comment] 2022-08-12 15:47
Hi, please send it to ***@***.***

Thanks,

**Comment by Kitakazi** [comment] 2022-08-12 15:58
aahhhh maybe some sort of security feature? I can't read your email address in the comment all I see is asterisks. 
![image](https://user-images.githubusercontent.com/51464873/184395658-0e4dad7c-bcdf-4c88-9d55-8649a50045e5.png)

**Comment by davetgc** [comment] 2022-08-12 16:04
Ok, I'll try this way around. Please send to Lee   (at) TheGameCreators.com

**Comment by ShadowMasterOfGames** [comment] 2022-08-13 03:59
@davetgc — They are couple of Max assets that collision is extremely mess up on, I will email @LeeBamberTGC tomorrow a list of the built-in assets that is screwed up.

**Comment by ShadowMasterOfGames** [comment] 2022-08-16 21:09
This has not been fix, so why close it

**Comment by LeeBamberTGC** [comment] 2022-08-17 11:14
@Kitakazi @ShadowMasterOfGames I dug around to find the model, and I think I have found an example (from another issue reported). Importing the original FBX models and scaling to centimeters, then setting the static model to polygon created the correct physics shape:

![image](https://user-images.githubusercontent.com/35840583/185105121-b033cd5f-0dc0-410b-b36c-3bea0950ea67.png)

**Comment by ShadowMasterOfGames** [comment] 2022-08-17 21:12
@LeeBamberTGC, I will get on tomorrow (Thursday) and let you know if it is fix. In my (#3614) I mention the military truck that comes with Max, and it was the not fix after today update. However, I will try your advice but the BRT GAZ truck is not custom, it comes with max. You can clearly see the polygon collision is way off on it. 

All my pictures are in #3614, if you want to see it for yourself. 

My has been hurting, so I not able to take more screenshots but I can email you the barn and the BRT GAZ truck, tomorrow as soon as I get on.

**Comment by Hamada880** [comment] 2022-08-18 06:03
> HI, are you able to share the models so they can be tested?

I have building structure I made on 3dsmax as fbx and it was fine first but after the update I noticed the shifting on physical shape, however I'm try to reimport again and test it.

**Comment by ShadowMasterOfGames** [comment] 2022-08-18 16:59
@LeeBamberTGC -- Nope, it not fixed yet, What files do you want me to send you?
![2022-08-18](https://user-images.githubusercontent.com/78239028/185452324-fb3ae9eb-170b-4fcd-ad8f-a45039608acf.png)

**Comment by davetgc** [comment] 2022-08-18 17:03
At least one that has this issue please.

**Comment by ShadowMasterOfGames** [comment] 2022-08-18 17:08
@davetgc I will send my map file

**Comment by davetgc** [comment] 2022-08-18 17:09
Well also need any models that are affected if not standard.

**Comment by ShadowMasterOfGames** [comment] 2022-08-18 17:26
@davetgc, I have a problem sending to Lee 
[_<[Lee@thegamecreators.com](mailto:Lee@thegamecreators.com)>: host aspmx.l.google.com[74.125.195.27] said:
    552-5.2.3 Your message exceeded Google's message size limits._]

That is the error that I am getting when I email to @LeeBamberTGC, any advice?

**Comment by ShadowMasterOfGames** [comment] 2022-08-18 17:39
@LeeBamberTGC, I split my email into two, to send to you, could you let me know if you got it?

**Comment by LeeBamberTGC** [comment] 2022-08-23 12:31
@ShadowMasterOfGames I am able to reproduce, and I agree it looks like a recent bug was introduced.  Thanks for reporting so far!

**Comment by LeeBamberTGC** [comment] 2022-09-14 16:04
@Kitakazi This has been fixed for the next EXP build (up soon).  You will need to delete any BULLET files you are using if you are using HULLs, and then rerun the level so the engine can generate new ones, but it will now handle all kinds of scaling, rotation, and offsets you may have used in the model importer phase.

**Comment by ShadowMasterOfGames** [comment] 2022-09-14 21:34
@LeeBamberTGC thank you for all your hard on this and on my issue #3614, the collision seems to be working great. 

Just a quick question, does Hull work just like the Polygon Collision? 

I am asking because I just bought GForce 2060 12vram from Amazon and the level I sent to you for the collision issue is only getting 1fsp to 8fsp. Is this being caused by the Polygon Collision or the new DX12_1 (Which 2060 can run) build?

**Comment by Kitakazi** [comment] 2022-09-15 01:09
@LeeBamberTGC 
Ah beautiful, thank you. I will wait till the final release and then close this issue.

**Comment by LeeBamberTGC** [comment] 2022-09-16 14:36
@ShadowMasterOfGames I am getting another report of slowness with the DX12 build which the EXP build uses.  Could be that.  For this issue, I think we can close as completed.

**Closed by LeeBamberTGC** 2022-09-16 14:36 UTC
Labels: bug, Fixed but need confirmation., Max, High, Physics
