### ISSUE TITLE
Soundloop script not working as intended

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#359] opened 2018-08-28 21:59 UTC
On the discord server we just discovered a bug that comes with one of the gg default scripts.

its about "Soundloop.lua"

It doesnt work as intended.
It loops the sound but there is no change in the volume when the player gets closer to the sound origin (entity)

I think this should be fixed

**Comment by AmenMoses** [comment] 2018-08-29 10:57
Try it with Mono 48Khz WAV files.   Positioning only seems to work with specific sound files.
(The engine noise I used for the Truck works btw)

**Comment by AmenMoses** [comment] 2018-08-29 13:47
No, sound attached to moving entities does not move with the entity.  The source location of the sound is set at the point where the PlaySound or LoopSound commands are issued, I have been toying with the idea of adding a MoveSound Lua command because the engine really has no idea what the game designers intent is with regards to sound source and simply 'fixing' it so sounds always move with the entity could very well be seen by some as a new 'bug'!

By putting sound positioning under direct Lua control then all sorts of things become possible.

**Comment by AmenMoses** [comment] 2018-08-29 13:48
@Lee, why does sound positioning not work for Ogg files?

**Comment by LeeBamberTGC** [comment] 2018-08-29 13:56
The OGG playback system is completely different to the WAV system which is much more flexible. If you want 3D sounds, best to convert them to WAV MONO (see the wav format of the stock audio files for info).

**Comment by AmenMoses** [comment] 2018-08-30 12:10
@LeeBamberTGC , Still don't quite get why some WAV files work and some don't, for example the metal door open sound in the Sci-Fi DLC doesn't work even though it is Mono WAV.
Also is the volume 'fall off' factor editable?  In testing I have sounds 10,000 units away from the player that are still audible, even if the factor could be set globally that may useful.

**Comment by LeeBamberTGC** [comment] 2019-06-27 22:54
Will be closing this task if the issue cannot be reproduced. All valid WAV files we have worked fine with the sound zone.

**Comment by plemsoft** [comment] 2021-05-20 12:01
duplicate.

**Closed by plemsoft** 2021-05-20 12:01 UTC
Labels: question
