### ISSUE TITLE
MAX - The player's flashlight won't work until they get near the water?

### ISSUE THREAD

**Issue by fearlesswee** [TheGameCreators/GameGuruRepo#1630] opened 2021-11-28 21:40 UTC
Often when starting a test level, the player's flashlight is entirely inoperable (emits no light) until the player steps close enough to the water at a distance where the flashlight would be casting a light on the water's surface, which makes it suddenly start working again. (You don't need to submerge the camera or even touch the water itself, simply getting close to the water will do it.) This is very annoying when trying to make a dark level for obvious reasons.

**Comment by Kitakazi** [comment] 2021-11-29 04:43
Yep I have same bug, on the default level at start, changed to night time and flashlight does not work.

**Comment by fearlesswee** [comment] 2021-12-06 02:44
Can't help but notice this hasn't even been assigned yet, and the Github issues board in general is seeming a bit neglected. Really hoping for a fix to this sooner rather than later; I'm trying to make a level that takes place in a dark area where the flashlight is needed but it's annoying to have to run to the water and back each time I load it up.

**Comment by rvanner** [comment] 2021-12-06 10:37
@fearlesswee We have a big internal list of tidy up issues that we are working on for now. The issues board will get much more attention in the New Year once we have finished our internal list.

**Comment by fearlesswee** [comment] 2021-12-08 07:51
Understandable, looking forward to having this addressed as it's VERY annoying while working on my level at the moment, lol!

**Comment by fearlesswee** [comment] 2022-01-29 14:32
Update: I think I have an idea on what could be causing this...?

I discovered sometimes when the player turns on their flashlight, you get a "ghostly" shadow of a recently viewed object that follows your flashlight. If you move far enough away and shine the flashlight on other things, the shadow can disappear. What I think is happening when the flashlight "doesn't work" is that it's actually getting this ghostly shadow of the **terrain itself**, which is naturally large enough to just outright block the flashlight.  

I hope this is accurate and provides some help, as this bug _still_ occurs in the latest build and is very annoying in my game project, which relies heavily on the use of the flashlight!

**Comment by LeeBamberTGC** [comment] 2022-02-08 12:57
@fearlesswee Any way I can quickly make a stock level to see this issue?

**Comment by LeeBamberTGC** [comment] 2022-02-08 16:06
@fearlesswee Okay, maybe have video recorder on standby and when you see it again, take about 30 seconds of footage, I might be able to see what the issue is from the video.

**Comment by Kitakazi** [comment] 2022-02-08 23:05
https://youtu.be/A5YMktnUe1E

@LeeBamberTGC @fearlesswee 
To recreate: go to the default map, add in an entity, and start test game. Turn on flashlight and shine it on entity to get a nice shadow. Then walk away from entity and its shadow will still be there. Turning off and on the flashlight usually does not make the "ghost" shadow disappear. Depending on the lighting of the scene, and what ghost-shadow sticks it can be pretty bad. If it is a big shadow it picks up it will just block the whole light. 

I just recorded the above video today, it is a little hard to see but in both clips I got the ghost-shadow of the soldier and then of the barrel. 

Like fearlesswee said it is quite common, but does not happen everytime. 

Additionally this bug can happen at any point while playing a level, not just after starting. But I have only noticed it happen with outdoor levels.

**Comment by LeeBamberTGC** [comment] 2022-02-17 22:18
@dllllllllllb Assigned this one as you are in the proximity of the flash light code now :)  Any questions relating to this, or reproducing this one, post here, thanks!

**Comment by dllllllllllb** [comment] 2022-02-21 16:29
@LeeBamberTGC Light remembers the shadow an entity casts and only updates that shadow when that specific entity is within the light zone. We need to either have a wicked function that resets shadow data from the light when it gets hidden or have the light be on at all times, but change the colour from white to black. I couldn't figure out how to reset that data but successfully implemented the 2nd option. Let me know if the 2nd solution is viable or guide me how to reset lights shadow data :]

**Comment by LeeBamberTGC** [comment] 2022-02-21 18:10
@dllllllllllb As this is only the flash light and not always used by the player, we can go with option 2 if that solves this issue. Please commit and post here, and I will test it out. If you can give me a short version of the step by step I should follow to see the issue, then apply the fix, then test again to confirm the fix, I can close this.

**Comment by dllllllllllb** [comment] 2022-02-22 09:39
@LeeBamberTGC Wanted to make sure my changes worked, however I noticed that the flashlight doesn't cast shadows at all now. I reverted my changes and I still get no shadows. Here are the steps to reproduce the original issue:

- Make an empty level (no trees, vegetation etc. I tested mine with morning skybox)
- Add a character
- Shine the flashlight on the character
- Turn off the flash
- Turn around where the character is not on screen
- Turn on the flashlight
- You should then have a cut-out of the shadow the character would cast

**Comment by dllllllllllb** [comment] 2022-02-22 09:52
@LeeBamberTGC I did a "dirty" fix for this issue, if it works well I can clean things up :]

**Comment by LeeBamberTGC** [comment] 2022-02-23 11:06
@dllllllllllb Yes followed the steps, the issue is no longer showing in the latest build.

**Closed** 2022-04-06 13:50 UTC
Labels: bug, Fixed but need confirmation., Max, High, Lighting
