### ISSUE TITLE
MAX - Dynamic Lua 'array' type crash

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#3323] opened 2022-06-19 15:33 UTC
Using the @Var type to select from a list or array of options and when above some number if items (10?) MAX just crashes to the desktop when test game triggered.

Would be better if in built limits like this generate a nice understandable error rather than simply dump the user to the desktop with no indication of why!

Btw, 10 items is not going to be enough, there are 25 different physics single hinge types that can be applied to an entity so allowing the user to select one from the behaviours tab was a no-brainer but that's not feasible now.  

RPG/Adventure genres are going to involve many tables of selectable parameters so if there needs to be a fixed limit then it should be a lot higher than it currently is.

**Comment by Teabone3** [comment] 2022-07-06 00:08
Currently my project doesn't work in Max because it uses tables (many) with various parameters inside each. I'm trying to find out what the maximum number i can get away with. No luck yet.

**Comment by ZakJudges** [comment] 2022-11-11 17:01
Hi @AmenMoses Sorry for the late response. This has been fixed and is in the latest Steam experimental build. The limit was caused by the crash. As a test after the fix, I added a dropdown with 30 items, which seemed to work fine. Any issues just let me know and I can take a look :)

**Comment by ZakJudges** [comment] 2023-02-16 09:32
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks

**Closed by ZakJudges** 2023-02-16 09:32 UTC
Labels: bug, Fixed but need confirmation., Max, LUA, CRASH!
