### ISSUE TITLE
Max Spotlight Radius Resets to 45

### ISSUE THREAD

**Issue by wizardofid29** [TheGameCreators/GameGuruRepo#1829] opened 2022-01-25 05:52 UTC
Add a spot light 
Change radius
Save level
Close max
Start max, and the spotlight has reset to 45 degrees

This is a major game breaking issue

![spotlight radius](https://user-images.githubusercontent.com/82841733/150918918-b97b9962-08ec-4b93-8d2c-ae8ad553d6d7.jpg)

**Comment by UltraVox001** [comment] 2022-01-25 06:17
You are right. I previously reported this issue here :
[https://github.com/TheGameCreators/GameGuruRepo/issues/1701](https://github.com/TheGameCreators/GameGuruRepo/issues/1701).

**Comment by wizardofid29** [comment] 2022-01-25 06:30
Yeah perhaps a reminder is a good thing, it is game breaking, and with demo games being due soon. This is a pretty serious issue.

**Comment by UltraVox001** [comment] 2022-01-25 06:51
Yes, a reminder is a good thing. And I appreciate that you did.
I gave up on the directional lighting because it didn't work. Same for some lighting behavior.

**Comment by ZakJudges** [comment] 2023-01-04 14:16
Apologies for the late reply. It looks like it was fixed as part of work relating to #1701. Additionally, I could not reproduce the issue in the latest build, so I will close this now.

**Closed by ZakJudges** 2023-01-04 14:16 UTC
Labels: bug, Max, High, Lighting, Level Editor
