### ISSUE TITLE
EBE Structure Herring Bone pattern , seams on seamless textures in distance

### ISSUE THREAD

**Issue by Ratall** [TheGameCreators/GameGuruRepo#440] opened 2018-11-03 01:05 UTC
Herring bone patterns and distant seams appear and disappear as you move.

![snapshot000001](https://user-images.githubusercontent.com/35710601/47946347-bae09380-df5e-11e8-8053-9e5f03b9f833.png)
If you look at the back wall you can see Herringbone pattern on right side

![snapshot000002](https://user-images.githubusercontent.com/35710601/47946380-1b6fd080-df5f-11e8-95e9-a9f5247e8474.png)
If you look at floor you can see texture seamless closeup but develops seams further away.

![snapshot000003](https://user-images.githubusercontent.com/35710601/47946416-7dc8d100-df5f-11e8-95a6-25c4d4d4bd0d.png)
Another example showing both Herringbone pattern and seams starting 3 panels away.

![snapshot000004](https://user-images.githubusercontent.com/35710601/47946468-3b53c400-df60-11e8-8d92-976596566d98.png)
Also noticed odd looking shadow effect in corners wondering if this could be related to seam effect something that happens on edges/joins of panels viewed at an angle?

**Comment by Ratall** [comment] 2018-11-03 01:51
Video to show effect when moving.
[https://youtu.be/rTVttS0EAEs](url)
Also include textures for floor as not standard
[texturesource.zip](https://github.com/TheGameCreators/GameGuruRepo/files/2544546/texturesource.zip)

**Comment by earthling45** [comment] 2018-11-03 15:10
The shadow effect in the corner is due to SAO.
The lines are due to mipmaps, it was and might now also be visible on entities with stacked uv's if Prebens fix for this is somehow lost.
He had fixed this problem several months ago.

**Comment by synchromesh62** [comment] 2020-02-10 23:32
@LeeBamberTGC 
@plemsoft 
Unable to reproduce this issue.

**Comment by LeeBamberTGC** [comment] 2020-03-24 22:38
I cannot see the herringbone issue as this may be fixed in the latest version (could be related to shadows, etc), but the seams issue shown on the latest repro videos are confirmed,

**Comment by LeeBamberTGC** [comment] 2020-03-25 01:50
Solved issue by using a new sampler for the shader, limiting the mipmap access to 6 levels down only, and increased the margin applied to UV coordinates for the texture slot lookup (32 pixels instead of 1) which ensures no texture slot leakage at distance.

**Closed by LeeBamberTGC** 2020-03-25 01:50 UTC
Labels: bug
