### ISSUE TITLE
Structure editor: Crashing/Hanging

### ISSUE THREAD

**Issue by Ghazzly** [TheGameCreators/GameGuruRepo#1171] opened 2021-05-29 07:13 UTC
Keeps crashing and hanging when using the structure editor after the latest update.

System Specs:
Operating System: Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: English (Regional Setting: English)
System Model: System Product Name
Processor: AMD Ryzen 7 2700X Eight-Core Processor          (16 CPUs), ~3.7GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce RTX 2070 SUPER
Dedicated Memory: 8011 MB
Current Mode: 1920 x 1080 (32 bit) (144Hz)
Card name: NVIDIA GeForce RTX 2070 SUPER
Dedicated Memory: 8011 MB
Current Mode: 1920 x 1080 (32 bit) (60Hz)

**Comment by rvanner** [comment] 2021-06-04 06:49
Work on the structure editor will be dealt with later. Don't worry about it's current state.

**Comment by rvanner** [comment] 2022-02-04 11:49
Structure Editor still crashes, needs to be fixed.

**Comment by LeeBamberTGC** [comment] 2022-02-17 18:06
Latest build no longer crashes structure editor, and corrected other small issues so can be used again, and final object edited once initially created.

**Comment by ZakJudges** [comment] 2022-05-11 12:33
duplicate of #1028

**Closed by ZakJudges** 2022-05-11 12:33 UTC
Labels: bug, Fixed but need confirmation., Max, Level Editor, CRASH!
