### ISSUE TITLE
Water Height 

### ISSUE THREAD

**Issue by niijel** [TheGameCreators/GameGuruRepo#1781] opened 2022-01-17 10:26 UTC
On default terrain no water visible at start. setting water height to 122 metres - no water, set to 123 metres - most of terrain underwater.
build is 14/01/22

**Comment by OldFlak** [comment] 2022-01-27 03:46
Yes water goes up in meters which is kind won't make flooding possible via LUA if and when we get access to it
Can we have water height adjustable in much smaller increments please? 

:)

**Comment by plemsoft** [comment] 2022-02-24 10:53
Duplicate of https://github.com/TheGameCreators/GameGuruRepo/issues/1551

**Closed by plemsoft** 2022-02-24 10:53 UTC
Labels: duplicate, Max, High, Level Editor
