### ISSUE TITLE
Character-creator made characters glow in the dark (Possible relation to AMD hardware?)

### ISSUE THREAD

**Issue by fearlesswee** [TheGameCreators/GameGuruRepo#676] opened 2020-01-28 06:45 UTC
From my limited testing, I've found every AMD machine I've tried has this bug where the character creator puts out characters with fluorescent bodies. Interestingly, their heads seem to be unaffected by this bug.

Side-note; setting entity shader to "lowest" seems to "fix" this. (But makes your whole game look incredibly ugly.) 

(To replicate this bug, simply use the character creator to create a new character, then insert this character in a low-lighting or shaded area.)

Cards tested:

AMD Ryzen 5 2400g: Character glows in the dark.
AMD Ryzen 5 3550H: Character glows in the dark.
AMD RX 580: Character glows in the dark.
NVidia GeForce GTX 1050: Character is affected by lighting as expected; bug is not present. (This card is on the same machine as the Ryzen 5 3550H, so it can be ruled out as a glitched/broken installation.)

(Attached are two images, one depicting the characters "glowing" due to this bug, and one depicting characters on the "lowest" entity shader and not glowing.)

![Normal](https://user-images.githubusercontent.com/56294129/73241077-eb69aa00-416e-11ea-9cff-917407775f66.PNG)
![LowestShader](https://user-images.githubusercontent.com/56294129/73241088-f6bcd580-416e-11ea-8fb0-de418c1e14d4.PNG)

**Comment by sfkylcnky** [comment] 2020-01-29 08:04
#398 
same issue with different configurations

**Comment by synchromesh62** [comment] 2020-02-08 13:18
@LeeBamberTGC 
@plemsoft 
Confirmed that it only seems to effect AMD Graphics cards or GPU's

**Comment by plemsoft** [comment] 2020-03-19 09:02
@fearlesswee Thanks for reporting this,

I seen something similar before , this looks like the constant buffers is overwriting other data, as you can see the shadows do not work , as shadow data is just after the constant buffer this could be the problem. I have aligned our constant buffers to 256 so data should not go outside the allocated shader memory.

AMD might be more strict about constant buffer alignment and this is the only reason i can see could produce this result, but i do not have a AMD card so this fix need to be confirmed.

**Comment by LeeBamberTGC** [comment] 2020-03-19 17:09
@fearlesswee if we attached a binary here, could you test the fix on your AMD system?

**Comment by LeeBamberTGC** [comment] 2020-03-25 10:18
Started a forum thread, and have one user who has AMD who would like to help test out an EXE: https://forum.game-guru.com/thread/221671?page=1#msg2628381

**Comment by redagent101** [comment] 2020-03-25 20:45
am also willing to test.  AMD card is HD7570

**Comment by KRivva** [comment] 2020-03-26 11:27
I have the Radeon RX 480 (8 GB), also willing to test.
My Creator characters always glow (as long as the entity shader isn't set to low), no matter if they are placed in dark or bright areas.

**Comment by LeeBamberTGC** [comment] 2020-03-28 21:56
Watch out for the PublicPreview build announcement soon, and reopen this issue if the AMD bug has not been fixed, thanks!

**Comment by KRivva** [comment] 2020-04-01 13:34
My characters still glow.

**Comment by LeeBamberTGC** [comment] 2020-04-01 16:50
@KRivva We have mad reports that aligning the constant buffers resolved the glowing issue for some AMD graphics card users. Just wanted to make sure you are using the current live release, and that your files are up to date (i.e. the shaders in effectbank\reloaded\* show dates for the end of March). Can you perhaps create an executable of a level with one glowing character and zip it up and attach here, I can then confirm you are using the latest files (and fixes). Thanks!

**Comment by KRivva** [comment] 2020-04-02 14:48
[Test.zip](https://github.com/TheGameCreators/GameGuruRepo/files/4421717/Test.zip)
 Of course, here you go.

**Comment by LeeBamberTGC** [comment] 2020-04-02 19:51
@KRivva I would need the whole standalone folder zipped up so I can see the other files and which version they are. The glowing would relate to the shaders more than the executable binary, and I also want to try running it as you see it, thanks!

**Comment by KRivva** [comment] 2020-04-02 21:14
My bad. Because of the file size limit, I assumed you just meant the exe.
Here's the whole standalone:
https://www.mediafire.com/file/jl7uhyr3c599vjg/Test.zip/file

**Comment by sfkylcnky** [comment] 2020-04-07 15:19
Tested the provided .exe and can confirm i am having the same issue with GTX850m

**Comment by LeeBamberTGC** [comment] 2020-04-07 15:23
@sfkylcnky Can you post your standalone that includes a stock character here and we can test it out. 

@KRivva Thanks for the whole standalone attachment, I can confirm the characters do not glow on my system so its likely a system thing!  If you can provide the FPM of the level (using stock assets only, not custom characters) that also shows the glow, I can drill into the assets a little closer, thanks!

**Comment by KRivva** [comment] 2020-04-09 14:11
@LeeBamberTGC 
It's only the custom characters which glow.
No glowing with assets or stock characters.

**Comment by LeeBamberTGC** [comment] 2020-04-09 15:40
@KRivva Can you provide the FPM of a level and the custom character that is placed in the level, and then a screenshot of what the level renders like you on your PC, so I can see the glow, I can drill into the assets a little closer from my end, thanks!

**Comment by KRivva** [comment] 2020-04-09 17:40
[Glowing Characters.zip](https://github.com/TheGameCreators/GameGuruRepo/files/4457645/Glowing.Characters.zip)

Here you go.

**Comment by KRivva** [comment] 2020-04-09 18:40
The DBO files for the characters, if needed:
http://www.mediafire.com/file/72485lth0cboy7z/DBO_Files.zip/file

**Comment by sfkylcnky** [comment] 2020-04-10 10:08
@LeeBamberTGC i uploaded a sample here as you requested:

http://www.chaos-design.net/shine_bug.zip

**Comment by LeeBamberTGC** [comment] 2020-04-16 16:24
Upgraded character basic and static shaders to use PBR shader system, which should align to the latest techniques and solve the AMD/Glow issue.  Will be in the next PP build this evening.

**Comment by KRivva** [comment] 2020-04-17 09:59
@LeeBamberTGC 
It seems to work now, the glowing is gone.
Thanks for the quick fix! :-)

**Comment by LeeBamberTGC** [comment] 2020-04-17 10:36
No worries!

**Closed by LeeBamberTGC** 2020-04-17 10:36 UTC
Labels: bug, fixed
