### ISSUE TITLE
Massive frame drop due to physics processing when player capsule interacting with entities.

### ISSUE THREAD

**Issue by AmenMoses** [TheGameCreators/GameGuruRepo#1140] opened 2021-05-09 12:06 UTC
This problem was a killer in Classic and is due I believe to ray casting against polygon collision mode entities.

The issue is still present in MAX.

The first screenshot is taken from my memory usage testing of the latest version of MAX (2021.05.07) {Issue 1074}.
The second is after simply moving the player forward until standing on the oil cans.

![max-memory-latest](https://user-images.githubusercontent.com/35708338/117571427-6a65c600-b0c6-11eb-9dc2-ca94a2ffec98.png)

![max-memory-latest-2](https://user-images.githubusercontent.com/35708338/117571430-705ba700-b0c6-11eb-9166-1b91f506d6fd.png)

Note how the fps has dropped to 6.2 and the Max Physics figure is 151.75 ms!

This is with a stationary player capsule standing on a bunch of static entities (which probably have collisionmode = 1 for some daft reason even when they are virtually box shaped anyhow) which if Bullet was being used correctly would cause hardly any processing at all.

I think this needs tracking down and quashing in MAX before release and also retro-fitting into Classic as it has been around a long time and really gives the engine a bad rep.

**Comment by plemsoft** [comment] 2021-05-20 11:31
@AmenMoses Thanks for reporting this issue, This has been fixed and will be in the next update :)

The problem here is when objects penetrate each other, in this case the player capsule, bullet will try to resolve the penetration.
It will do this by moving the objects in the "normal" direction of the penetration point, you can imagen what will happen as the player capsule is round it will move from one oilcan directly into another oilcan and them try to resolve that ... this bring down the fps.

Bullet work by calling the simulation as many times as it takes to keep it running at the current fps, as the current fps is now lower bullet will then start to call the simulation more times then before to keep up, this then again bring down the fps even more, a never ending "fps drop loop" that never stop before the penetration is resolved.

This is also why it only happens in cases where the normal points directly into another object, like in a corner , or on small objects below you, if it was one object it would never happen, or the objects had box collision that are way faster to process.
Also this only happens in the Kinematic controller (the player capsule) as its kinematic bullet must resolve the problem.

The fix, well.. it dont fix the penetration problem but, change bullet to move the world in larger chunks at the same time.
Currently GG and Max run the simulation on 1/120 steps per call to the simulation, using many calls per frame to give a very precise simulation. so what the fix simple do when it see a penetration problem is to change the simulation steps into 1/60 steps that will move the world twice as fast as 1/120 and then we do not need to call/update the simulation as often. This lower the precision but makes the simulation way faster.

It will only happen when it see a kinematic penetration problem.

I tried you oilcan sample and it improved the fps when stuck from 8fps to 40fps using the new way. the precision could be lowered more (fit 60fps+) but lets try this first :)

This fix is for both Classic and Max.

**Comment by AmenMoses** [comment] 2021-05-21 11:41
There are a few places in the code where damping is applied to physics objects, if you fix the simulation steps the values used in those places will now be wrong! (or at least will give strange results)

The most obvious of those is the rather dodgy code that attempts to mimic behaviour for objects when in water.

There is another one in the main object loop intended to stop explosions throwing objects off the map (the explosion 'push' force is way too high for small objects).

**Comment by LeeBamberTGC** [comment] 2022-02-08 12:27
@AmenMoses If you spot any remaining objects that exhibit the physics perf hit, let me know as a new issue, and I will make sure the correct hulls are generated for them, thanks!

**Closed by LeeBamberTGC** 2022-02-08 12:27 UTC
Labels: bug, fixed, Max, Medium, GGClassic

**Comment by fearlesswee** [comment] 2024-10-04 05:12
Can confirm this is still a big issue in MAX as of 10-4-2024. Walking into the intersection of two railings on the "Warehouse" asset seems to be the easiest way to replicate this bug, although I have noticed it happening seemingly randomly in levels/games made in MAX. 

[https://vimeo.com/1015980962?share=copy](https://vimeo.com/1015980962?share=copy)

**Comment by LeeBamberTGC** [comment] 2024-10-07 11:14
@Kasseyus Can you confirm this also, thanks!  See if you can create a step-by-step that does not rely on random chance and uses only stock media.

**Comment by Kasseyus** [comment] 2024-10-07 15:53
@LeeBamberTGC

I can reproduce this slowdown on the warehouse model, but that is using polygon collision with a lot of small detail on the railings.  Switching to Hull Decomp removed the problem.

I am unable to reproduce this issue with stock assets using more efficient collision through multiple scenarios.  It feels more like an optimisation issue at this time.
