### ISSUE TITLE
DX11 Update scaling issue

### ISSUE THREAD

**Issue by Emperor2000** [TheGameCreators/GameGuruRepo#196] opened 2018-04-19 16:33 UTC
When I open a dx9 map entities can lose their scale. As an example I noticed objects becoming way bigger then they were in the previous version. I noticed this applies at least for pole with wire and pole. This also goes for the lightray decal in which the particle effect changes in size. Also the particle effect seems to play faster, but I'm not 100% sure about this.

**Comment by LeeBamberTGC** [comment] 2018-04-20 01:17
Does it happen for any other assets outside the Cityscape folder?

**Comment by Emperor2000** [comment] 2018-04-20 12:06
Right now I am guessing it does not.

2018-04-20 3:17 GMT+02:00 Lee Bamber <notifications@github.com>:

**Comment by plemsoft** [comment] 2018-06-20 09:59
I also had this problem in GameGuru Loader , the problem is that the new objects (.dbo) have a different scale, so there is really nothing to do about it other then scale the objects to fit the new PBR .dbo objects.
Sure this will not be a problem in new maps , only on old maps where you already scaled the objects.

Unless Lee wants to scale the mesh inside the dbo to fit the old DX9 models scale, we cant do anything , what do you think should we just close this issue as its not really a bug.

**Comment by Emperor2000** [comment] 2018-06-20 12:36
Ye sure, as there doesn't seem to be a simple fix that is probably the best
thing to do right now anyway. I'm sure there's a lot of other issues that
need a look as well.

2018-06-20 11:59 GMT+02:00 Preben Eriksen <notifications@github.com>:

**Comment by plemsoft** [comment] 2018-06-20 14:08
Yes also if we did scale the mesh inside the new PBR .DBOs , well then new created level that use those will display the objects way to small, when they load it into the next version , so yes its properly better to just close it, and scale to fit :)

**Closed by plemsoft** 2018-06-20 14:08 UTC
Labels: bug, help wanted
