### ISSUE TITLE
Strange EBE wall bug

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#207] opened 2018-04-22 10:04 UTC
looks like a messed up normal map, but I even deleted the corresponding file now! I dont understand it..
Maybe some of you know what's causing this?

![guru-mapeditor 2018-04-22 11-39-18-81](https://user-images.githubusercontent.com/35990507/39093787-55a549de-4625-11e8-8bb1-ed4feeb57544.jpg)
![guru-mapeditor 2018-04-22 11-39-52-65](https://user-images.githubusercontent.com/35990507/39093792-63f5de90-4625-11e8-8348-baf732c7e848.jpg)

**Comment by LeeBamberTGC** [comment] 2018-04-23 15:12
Can you attached an FPM using stock media that shows this issue so it can be reproduced, thanks!

**Comment by lordjulian1** [comment] 2018-04-24 10:58
I had something similar when I used a cobbled floor. I thought it was the cobble texture reflecting off the wall.

**Comment by korodai** [comment] 2018-04-25 16:40
I had this problem a lot. I thought it was caused by using normal maps that don't end with _D.dds.

**Comment by LeeBamberTGC** [comment] 2018-05-21 15:56
This can happen if you are using custom media that is not specifying a normal texture but the shader will need to use one. I am closing this one as not reproducible, but feel free to open it again with stock or custom media that shows the issue (even when a normal map is included)

**Closed by LeeBamberTGC** 2018-05-21 15:56 UTC
Labels: help wanted
