### ISSUE TITLE
system crashes saving level

### ISSUE THREAD

**Issue by smmaas** [TheGameCreators/GameGuruRepo#1554] opened 2021-11-14 18:29 UTC
System crashes Runtime Error: error 8204 () when saving a level. Start new project, edit level by clicking pencil on Level 1 window, create level, go back with error in left corner, give name for new level, system crashes.

**Comment by smmaas** [comment] 2021-11-14 19:52
I can save again after I run update (same version) but  the problem returns. When I haven't figured out yet.

**Comment by plemsoft** [comment] 2021-11-21 10:33
@smmaas Thanks for reporting this issue, i was not able to reproduce this, but 8204 has to do with memblocks so i secured all the cases where this error can happen. So should not happen again, will be ready from the next update, please give it a good test and let me know if it fix your issue, thanks for your help :)

**Comment by rvanner** [comment] 2022-02-10 08:32
@smmaas Can you try this again with the latest build? We would like to close this issue down if it's now fixed. Thanks!

**Comment by smmaas** [comment] 2022-02-11 09:44
can be closed

**Closed** 2022-02-17 08:47 UTC
Labels: Fixed but need confirmation., Max, High, CRASH!
