### ISSUE TITLE
save and load issue for GG Max

### ISSUE THREAD

**Issue by ghost** [TheGameCreators/GameGuruRepo#3991] opened 2022-12-20 05:43 UTC
if i create a new project, ggmax "save project" doesnt save and the project doesnt appear in the list of projects. also creating a new level and saving it doesnt have it show up on the list of levels. nothing is saving or loading properly. i dont understand why. its making me start over constantly. if i try and edit a previous level and save it, it either deletes the level or none of the changes ever get applied. i only just started having this issue tonight. ive never had this issue before.

**Comment by davetgc** [comment] 2022-12-21 06:12
I've not seen this issue, can anyone else confirm please?

**Comment by zirathashe** [comment] 2022-12-22 17:47
> 

i can live stream this on twitch and show you if youd like.

**Comment by zirathashe** [comment] 2022-12-22 17:58
nevermind. the second i start streaming the issue, it mysteriously starts working fine. weird. i restarted ggmax before which didnt help and i even restarted my pc which did nothing so i dont understand why it magiclly started working fine now.

**Comment by zirathashe** [comment] 2022-12-22 18:04
nevermind, i was wrong. its still happening and this time i have it on stream. my twitch is zd_zma. ill save it as a highlight so you can see it past 7 days. let me know when youve watched it.

**Comment by ZakJudges** [comment] 2023-02-03 13:04
Hi @ghost, I have not been able to reproduce this issue. Are you continuing to experience it? 

If so, could you please check your documents->GameGuruApps->GameGuruMAX->Files->projectbank folder and see if they are there? Since Max creates a folder for your project, its possible that certain names could be interfering with the folder creation.

**Comment by ZakJudges** [comment] 2023-02-16 09:45
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks

**Closed by ZakJudges** 2023-02-16 09:45 UTC
Labels: bug, Fixed but need confirmation., Max, Waiting for more information., High, Storyboard Editor
