### ISSUE TITLE
GGMAX - Texture Problem

### ISSUE THREAD

**Issue by Necrym59** [TheGameCreators/GameGuruRepo#2411] opened 2022-03-05 02:02 UTC
Terrain Material 7 has a problem
Image here of it applied to a couple of objects and also sprayed on the ground, as you can see it doesnt spray well on the terrain???
![mat7](https://user-images.githubusercontent.com/95015657/156863371-eb722466-5b00-41ee-96ee-4f6ec99cd28d.jpg)

**Comment by PaulSJ** [comment] 2022-03-11 15:18
Duplicate of #2473

**Closed by PaulSJ** 2022-03-11 15:18 UTC
Labels: bug, Max, Terrain, Post Early Access
