### ISSUE TITLE
MAX EXP - Particles Behaving Badly

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#4939] opened 2023-09-19 11:54 UTC
Particles do not play correctly in either the editor or at runtime.
Couple Vids to demonstrate:

https://youtu.be/8B5fa2OPdRw

https://youtu.be/nowptMkAxfs

And also can we remove the restriction of removing the first 9 (stock) particles - I promise I will not use them :)

**Comment by davetgc** [comment] 2023-09-23 08:35
Is this with the experimental build? Could you also please post your graphic card specs.

**Comment by OldFlak** [comment] 2023-09-23 21:31
Hi @davetgc - Yes tis MAX EXP
Windows 11
i7-4790 @ 3.2GHz. 8GB Ram. NVidia GeForce GTX 1060 6GB.

**Comment by LeeBamberTGC** [comment] 2023-10-28 18:20
@OldFlak Fixed issue for next EXP build, turns out it was using a single global in a multi-threaded sorting of the particle distances :)  Will show as fixed in the switch escape demo level:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/be7975da-6cd7-4edb-9391-0ce3ce3abb75)

**Comment by OldFlak** [comment] 2023-10-29 02:10
@LeeBamberTGC - thanks :)
- Will test as soon as the build goes out :)

**Comment by OldFlak** [comment] 2023-11-02 11:44
Still the same here Lee no different to the videos on op 
- just built new system and everything installed from scratch
- so, if the build with the fix hasn't gone out yet I will test again later
- :)

**Comment by LeeBamberTGC** [comment] 2023-11-02 11:54
@OldFlak It is in the EXP build.  When you have updated to that and confirm you still see a flicker, can you zip up and email me your "Max\shaders" folder as the updated particle shaders are stored there.

**Comment by OldFlak** [comment] 2023-11-02 22:30
Thanks Lee. Yes, I am using the exp build already. 
Have not opened MAX today (real life stuff day today) but will test again tonight.

**Comment by OldFlak** [comment] 2023-11-03 11:48
Hi Lee, Apart from the **flickering** still being present, **rotations** are now messed up somewhat as well :)

https://youtu.be/OZSPN_-WNpE

**Comment by OldFlak** [comment] 2023-11-04 03:50
The rotation is sorted now thanks Lee :)

The glitching is still as before, here is one I just recorded:
https://youtu.be/n_JinunjjkY

**Comment by LeeBamberTGC** [comment] 2023-11-04 13:29
@OldFlak can you send me that level. No need for custom media. The particles are what I am after

**Comment by OldFlak** [comment] 2023-11-06 00:02
Hi Lee finally got onto it - email sent :)

**Comment by LeeBamberTGC** [comment] 2023-11-07 14:40
@OldFlak Thanks for the files, I had some missing media and had to reattach and set the opacities (thanks for the chart), and also had to set MSAA to zero, but after that I could glide through the particles and ground fog but no flickering at my end. I may have recreated things differently, or it is the MSAA which my old AMD card does not support.  

I have created and will email you a standalone from my test level and set the start marker to the particles area. Can you confirm if this standalone shows the same particle flickering when you move through the ground fogs, thanks!  You can use the ARROW KEYS to get a smoother player movement to try and provoke the flickering.

**Comment by OldFlak** [comment] 2023-11-08 04:53
Will test thanks Lee 
- fyi this is both a test-game and standalone issue :)

**Comment by OldFlak** [comment] 2023-11-10 01:07
Hi Lee tried the standalone - but it gave an error so wouldn't run
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/12246318/3e84e827-86ab-4e93-81b4-6edba0f271a5)

**Comment by LeeBamberTGC** [comment] 2023-11-13 11:43
@OldFlak I have emailed you another one, release build this time :)

**Comment by OldFlak** [comment] 2023-11-18 22:17
@LeeBamberTGC sorry for late reply - been away for the last week.

The standalone works fine - none of the particles are behaving badly 👍

When it makes it to the exp will test again and if all good this bug is done and dusted 😁

Thanks for looking into it.

**Comment by OldFlak** [comment] 2023-11-26 04:03
@LeeBamberTGC Hi Lee :)
Current report on issue fyi:
Just tested latest exp and particles are still the same as in OP - so the fix not working it seems :)

**Comment by LeeBamberTGC** [comment] 2023-11-26 11:25
@OldFlak In correcting your level you sent me, I may have fixed it in the level rather than the engine for the standalone I sent to you that worked. Do you want to create a new level using only stock media that shows the issue (if poss) that I can load and test 'as is'?  It may be a combination of certain objects and particles indispersed in the draw order.

**Comment by OldFlak** [comment] 2023-11-27 01:48
@LeeBamberTGC Hi Lee :) thanks for reply.

I'm not sure it is worth pursuing really. 
Maps that worked fine previously now are broken in one way or another, but new maps don't exhibit the issues.

That same map with particles issue, has buildings on it that now have the roof sections on the ground, whereas before the latest update they were fine. Previously the same map only had the particles issue - kind of like russian roulette atm.

Other maps with the same buildings setup on them are all fine (atm) - It seems to me like MAX is corrupting the FPM somehow.

Onward and upward as they say :)

**Comment by OldFlak** [comment] 2023-11-27 22:14
Thats fine thanks Lee :)
Personally, I am kind of losing confidence in MAX, not sure what bug could exist that suddenly makes models fall to the ground.
Every time you open a map it is hit and miss if it will work like it did the last time it was loaded - like I said russian roulette.

Thanks for looking into it 👍

**Comment by LeeBamberTGC** [comment] 2023-12-11 14:43
@OldFlak Referring back to the original issue title, I will mark this as needing more info (a stock level that shows flickering particles). I suspect it relates to a specific combination of particles set at distances away from the player, intersected with other transparent objects that then fight for draw order, but provoke some error in the sort system.  Once we can reproduce it in an FPM using stock media, the fix should come very quickly.

**Closed** 2024-04-17 08:00 UTC
Labels: bug, Max, Waiting for more information., Low, Particles
