### ISSUE TITLE
Lights Dont Move on Old Maps

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#375] opened 2018-09-10 03:02 UTC
Moving lights via LUA seems to only work on new maps. But fails to move in legacy maps from past GG versions.

**Comment by HierToo** [comment] 2018-09-10 17:16
I tested the The Heirs Revenge Map and used my script here [](https://forum.game-guru.com/thread/219888#msg2603332) and it worked. Maybe your script has some faults

**Comment by Teabone3** [comment] 2018-09-11 00:55
Its very strange my script on any script made with any past version of Game Guru. But will work on a brand new map.

```
function movelight_init(e)
end
function movelight_main(e)
GetEntityLightNumber(e)
if g_KeyPressE == 1  then 
SetLightPosition(e,g_PlayerPosX,g_PlayerPosY+10,g_PlayerPosZ+5)
 end
end
```

**Comment by Teabone3** [comment] 2018-09-11 01:02
What is really odd is it DOES work on The Heirs Revenge Map. So strange... so there must be something that is conflicting.

**Comment by synchromesh62** [comment] 2020-02-11 15:36
@LeeBamberTGC 
@plemsoft 
Unable to reproduce..

**Comment by LeeBamberTGC** [comment] 2020-03-24 21:32
The original bug cannot be reproduced here, but it sounds like an issue with an old entity/light data bug in the old FPM levels. Newer levels would have correct entity/light data. This is normally fixed by deleting the offending entity/light/zone, saving and reloading the FPM then adding them in again. This would have been fixed long ago.

As to the new issue of moving lights using entity commands, create a new bug report and provide the script used and the FPM example using stock media, allowing us to reproduce, thanks.

**Closed by LeeBamberTGC** 2020-03-24 21:32 UTC
Labels: bug
