### ISSUE TITLE
AI does not follow a path when told to do so

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#1902] opened 2022-01-30 14:19 UTC
I made a game level with 3 enemies. 2 should follow flags but the third should stand his ground. The all follow the paths!

![image](https://user-images.githubusercontent.com/1503593/151703547-e7a37c19-aad5-40af-8aac-1472075bfc56.png)

**Comment by LeeBamberTGC** [comment] 2022-02-11 18:20
Fixed for next weeks build.

**Comment by rvanner** [comment] 2022-02-14 15:11
@LeeBamberTGC I made another small level with 3 character enemies. Two were told to follow their way points and one was to not. Only one followed his way point flags, the other wandered around where he liked!
![image](https://user-images.githubusercontent.com/1503593/153890472-c02b6589-7724-4e66-baae-acad8992ef7a.png)

**Comment by LeeBamberTGC** [comment] 2022-02-15 14:04
@rvanner In these cases, it is best to send me the FPM as I can reproduce what you see exactly. Otherwise I waste time attempting to create a level that looks like yours and there is no guarantee I can reproduce if I do something slightly different.

**Comment by LeeBamberTGC** [comment] 2022-02-16 10:24
@rvanner The issue was that this map was right on the edge of the editable area, so half the nav mesh was not there. Paul is sorting this one now. The other issues was neutral characters just ran off, now fixed. And some character rotations were off due to an obj management bug, will be fixed once AI tasks are complete.

**Comment by rvanner** [comment] 2022-02-16 12:15
I just tried the updated level you sent me. The neutrals still ran off, is that not in the current build yet?

**Comment by LeeBamberTGC** [comment] 2022-02-16 13:25
@rvanner When you see a post or tag change, check the date stamp. Only when you get the internal build email AFTER that date stamp will the version be available to test.

**Closed** 2022-02-16 14:45 UTC
Labels: bug, Fixed but need confirmation., Max, Medium, AI
