### ISSUE TITLE
Zombie animation and behavior doesn't work

### ISSUE THREAD

**Issue by vinurd** [TheGameCreators/GameGuruRepo#3642] opened 2022-08-22 14:23 UTC
https://youtu.be/Fmw7uphyl30?t=44

**Comment by davetgc** [comment] 2022-08-25 08:58
I've tested this and they work. Were the zombies spawned?

**Comment by vinurd** [comment] 2022-08-25 17:53
> I've tested this and they work. Were the zombies spawned?
No, I just put in the zombies on the map.

**Comment by davetgc** [comment] 2022-09-11 13:04
Ok, I've managed to replicate this with Zombie 02. Just place the zombie in any level and it will keep repeating it's steps.

**Comment by davetgc** [comment] 2022-09-11 13:06
https://user-images.githubusercontent.com/99803873/189529183-b76c1684-c425-4cd1-9d49-2e9cf9ad52a4.mp4

**Comment by davetgc** [comment] 2022-09-11 13:08
Slightly glitchy video, but it shows the point.

**Comment by RajMaha1** [comment] 2022-09-11 14:39
I've got similar problem in my game

**Comment by LeeBamberTGC** [comment] 2022-12-12 11:19
@vinurd Latest EXP build solved a nav mesh issue which could have been the cause, works fine here with Zombie 02:
![image](https://user-images.githubusercontent.com/35840583/207032702-568a8113-b2b8-40fa-8412-6b96b6f26645.png)

**Comment by ZakJudges** [comment] 2023-02-16 09:38
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks

**Closed by ZakJudges** 2023-02-16 09:38 UTC
Labels: bug, Fixed but need confirmation., Max, High, Behaviors
