### ISSUE TITLE
Build 07/01/2023 breaks hud editing in storyboard

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#4031] opened 2023-01-08 06:24 UTC
Clicking edit in game hud, no longer allows repositioning of HUD, it just goes to an import image screen.  Also, the window tool tip now says edit splash screen, which may be the issue.

**Comment by LeeBamberTGC** [comment] 2023-01-08 07:29
@ZakJudges When you are back on MAX, make this one your top fix. You made some changes before but for legacy projects the HUD screen can get confused. I have also committed newer code around the storyboard and HUD screens so worth checking that out to see if I messed up, or confused a few things.

My own experiences is that if I delete the "GameGuruApps\GameGuruMAX" folder, and then select the ISLAND SHOWDOWN, everything is fine and the SPLASH HUD and the IN-GAME HUD can both be edited.

If I edit one of my own projects, when clicking the IN-GAME HUD it takes me to the SPLASH HUD to edit, which is wrong.

As I think this relates to projects edited mid-dev for this feature, the solution is a new BUTTON bellow EDIT GAME SETTINGS called "RESET HUD SCREENS" that will delete any old ones and reset them factory defaults, so they can be edited with clean data:

![image](https://user-images.githubusercontent.com/35840583/211185338-b548ff74-2bdf-43dd-b7d6-57dff420255f.png)

**Comment by LeeBamberTGC** [comment] 2023-01-08 07:32
Attached is my writeables project folder, load the OFF project as that shows the SPLASH editing when click the IN-GAME HUD screen:

[projectbank.zip](https://github.com/TheGameCreators/GameGuruRepo/files/10367903/projectbank.zip)

**Comment by ZakJudges** [comment] 2023-01-12 11:27
@LeeBamberTGC Fixed and committed: https://github.com/TheGameCreators/GameGuruMAX/commit/7f0544abd163371560b1dda23a8df79d85f77221

This was caused by the splash screen and HUD screen ending up with duplicate IDs within ImNodes, and so the HUD screen ended up 'merged' with the splash screen. I could not find the root cause of the duplicate IDs, but they do not need to be saved/loaded, so with each storyboard load they are now reset to default values, which allows the HUD screen to be selected again. I have also added the "Reset HUD Screens" button (advanced settings), which will reset the HUD node position, as well as reset the screen editor data back to defaults.

**Closed** 2023-02-16 09:45 UTC
Labels: bug, Urgent, Fixed but need confirmation., Max, High, Storyboard Editor
