### ISSUE TITLE
GG Max- Bug: Sliding Doors & Fire Doors have No Behaviour?

### ISSUE THREAD

**Issue by mauriegit** [TheGameCreators/GameGuruRepo#3453] opened 2022-07-17 08:50 UTC
Good Day

1. When attempting to add a sliding door or a fire door to a warehouse or building, the doors have no behaviour and the text "No behaviour for static objects" displays under the behaviour selection? The behaviour works fine on other doors?

2. Also, when attempting to add a visual logic connection from a switch to a sliding door, the node does not connect? 

Please assist
Regards

**Comment by MonkeyFrogStudio** [comment] 2022-07-17 12:48
@mauriegit - This is not a bug. The clue is given to you when it says, "No behavior for static objects". It means that the object you've chosen for your door is set to Static. In this case, just select the object in the editor, go to the General tab on the right-side of the UI, and change the Static Mode to something like Physics On. Once the object is no longer a static model, a Behavior can be applied to it. And once the object is no longer a static object, then the visual logic connectors will work.

One other thing - when you switch the mode to one of the Physics settings, you my need to twirl down the Developer tab and tick the IsImmobile tick box. This will make sure that your door, now a physics object, will not let physics take over, causing the door to fall over, etc.

**Comment by mauriegit** [comment] 2022-07-17 15:27
Thank you for your email. Sorted.

Regards


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MonkeyFrogStudio** [comment] 2022-07-17 15:29
If this has been resolved, then please CLOSE this. Thanks. ;)

**Comment by mauriegit** [comment] 2022-07-17 15:33
Will do.

Regards

**Closed** 2022-07-17 15:34 UTC
