### ISSUE TITLE
drawcalloptimizer

### ISSUE THREAD

**Issue by m2design** [TheGameCreators/GameGuruRepo#635] opened 2019-10-24 17:20 UTC
There appears to be real problem with the drawcalloptimizer feature in the setup.ini file.
step 1. I load up a map that contains several entities that meet the criteria for optimization (fps=101)
Step 2. press F11 (fps=101)
Step 3. press "9" display the batched entities  (fps=101)
step 4. press"9" display all entities (batched and unbatched)  (fps=77) dramatic reduction.  The batched entities now display a dramatic flicker.
The flicker indicates duplicate entities sharing the same coordinates.
step 5. press F9 and "E" and move one of the flickering batched entities just a minimal amount, exit the move function (press F9)

Flicker is gone and the fps goes up to 125, a large increase from the original 101 in step 1.
I will try to include screen shots and a short video
Also note that F11+"9" will no longer display the batched entities/any entities like before the added optimization option.

[color=red]EDIT: I have spent most of the day trying to figure out if the problem is caused by my custom models and or the texture files. I do not find evidence of that being the case. The flickering only happens with the entities that have been batched. All un-batched entities are fine.[/color]

[color=orange]Edit: oct 19 2019
Latest finding on flashing batched entities. When the flashing starts (after the final "9" is pressed) if I press the F9 key twice the flashing STOPS and the higher fps (125) reading is displayed and everything is normal.
PROBLEM: This process must be done every time I go to into the test mode even if I have saved the file between sessions.. [/color]
https://forum.game-guru.com/thread/221169?page=2#msg2622322

**Comment by plemsoft** [comment] 2019-10-27 09:54
@m2design Thanks for reporting this,

The problem is actually the F11-9 procedure, this has been fixed and should be in the next update :)

**Comment by Kasseyus** [comment] 2019-12-02 11:08
Will close this issue now...

**Closed by Kasseyus** 2019-12-02 11:08 UTC
Labels: bug, fixed
