### ISSUE TITLE
GameGuru Max - Bug - Building Editor - Bug 4/6 - Crash When Clicking Away When Creating Rooms

### ISSUE THREAD

**Issue by Lemuripest93** [TheGameCreators/GameGuruRepo#3845] opened 2022-10-19 17:52 UTC
Individual posts by request from #3772

There is no video footage of this bug, and i've not been able to recreate it since it happened - but when occurring, creating a room and clicking away (when the white pillar and wall preview has turned red.) will erase floor portions, when used on the roof of a building it crashes the editor.

**Comment by ZakJudges** [comment] 2022-10-21 13:23
@Lemuripest93 I think I have found the cause of this one and have added a fix. Though I will keep this issue open for a while, just in case it crops up again :)

**Comment by ZakJudges** [comment] 2022-12-05 10:41
Closing this issue as has not been reported since. If the problem occurs again, feel free to reopen. Thanks :)

**Closed by ZakJudges** 2022-12-05 10:41 UTC
Labels: bug, Fixed but need confirmation., Max, CRASH!, Building Editor
