### ISSUE TITLE
entity error

### ISSUE THREAD

**Issue by digitechone** [TheGameCreators/GameGuruRepo#731] opened 2020-03-31 20:34 UTC
I opened the classic map and all the entities look like this
![Sin título](https://user-images.githubusercontent.com/62585580/78072622-aaebff80-735c-11ea-88f0-ba2fb5dec811.png)

**Comment by LeeBamberTGC** [comment] 2020-04-02 23:56
@digitechone Looks like you have brightness and bloom set quite high.  There is a new PP build going out Friday. If you can try backing up all your files, then uninstalling GameGuru, then deleting your local files, then installing a fresh, then loading and running the above level and post another shot, that would be great. Remember to wait until Friday PM and that you have set the build from the product BETA tab, so you are sure to be using the new PP build, thanks!

**Comment by LeeBamberTGC** [comment] 2020-04-03 00:11
Just to confirm, I uninstalled and reinstalled the Classic Expansion DLC to get fresh entities and the level, and took this shot from the latest PP build, all looks fine:

![image](https://user-images.githubusercontent.com/35840583/78311204-0a5a3300-7548-11ea-8c1e-75653f886c06.png)

Can anyone else reproduce the issue reported here, thanks!

**Comment by earthling45** [comment] 2020-04-03 01:08
This is also something i tried yesterday, but it all looked fine.

**Comment by LeeBamberTGC** [comment] 2020-04-03 02:03
New PP build uploaded :)

**Comment by digitechone** [comment] 2020-04-03 06:06
![prueba](https://user-images.githubusercontent.com/62585580/78329445-f6f69a00-753e-11ea-8a59-cc7ac802e34b.png)
it still appears to me, I have to lower almost all the brightness so that they look good and that halo appears to me
I do not know if it is an error similar to the character models since I use an amd card and processor

**Comment by digitechone** [comment] 2020-04-03 06:35
![demo2](https://user-images.githubusercontent.com/62585580/78331289-f5c76c00-7542-11ea-89ac-5f32d6102f2d.png)
![demo3](https://user-images.githubusercontent.com/62585580/78331301-fc55e380-7542-11ea-9b22-b04abf45342a.png)

**Comment by digitechone** [comment] 2020-04-03 06:38
uninstall the dlc and game guru and reinstall and do not change the results apparently it is an error with my amd system

**Comment by plemsoft** [comment] 2020-04-03 07:12
@digitechone In the last shot your using "PRE-BAKE" without any lightmaps ? , try to change that to "REALTIME" , and post a screenshot.

**Comment by digitechone** [comment] 2020-04-03 07:24
![demo4](https://user-images.githubusercontent.com/62585580/78334748-8ef98100-7549-11ea-8756-907c02ede3fd.png)


that brightness still appears in the entities that is not normal also appears a halo and a flash

**Comment by plemsoft** [comment] 2020-04-03 07:55
@digitechone The halo is from the "Lens flare intensity" slider , just turn that down :)

But yes it is way to bright , i think the problem is that these old objects do not have a effect inside the dbo , and they dont have a "effect = " inside the fpe , so not even sure what shader its using , could you try to use this fpe for the building "\Game Guru\Files\entitybank\Classics\Ancient Rome\romanbuilding1.fpe"

Just replace the file with the attached :)

[romanbuilding1.zip](https://github.com/TheGameCreators/GameGuruRepo/files/4425706/romanbuilding1.zip)

Please post screenshot with the changes.

**Comment by Pirate-Myke** [comment] 2020-04-03 13:23
Tried this one with the media from the specified folder. I could not see an issue either.
I am still on the Beta version, to which my understanding is the same as the PP.

**Comment by LeeBamberTGC** [comment] 2020-04-03 13:27
@Pirate-Myke Beta and PP build are the same. I suspect this is related to some AMD cards, and the way the pre-built shaders are aligned.

@digitechone Just in case the AMD driver has a role in how DX compiles its shaders, can you go to the "Game Guru\Files\effectbank\reloaded" folder and delete all the ".blob" files from there, then run the software again. It will take longer to launch, but the shaders will be recompiled live and let me know if you see the same thing.

**Comment by Pirate-Myke** [comment] 2020-04-03 13:28
Thank you.

**Comment by digitechone** [comment] 2020-04-03 17:00
indeed I did not have an effect assigned this is the result thank you very much everyone
![DEMO5](https://user-images.githubusercontent.com/62585580/78386172-4d44f680-759a-11ea-8002-12bcd334d0d7.png)

**Comment by LeeBamberTGC** [comment] 2020-04-05 21:56
@digitechone : Do you want me to close this bug report?

**Comment by digitechone** [comment] 2020-04-06 15:51
thanks lee

**Closed** 2020-04-06 15:51 UTC
Labels: Need explanation, bug
