### ISSUE TITLE
Rotation Widget Borderline Unusable

### ISSUE THREAD

**Issue by fearlesswee** [TheGameCreators/GameGuruRepo#1439] opened 2021-10-11 03:00 UTC
The rotation widget behaves incredibly awkward more often than not, with the model jittering around uncontrollably. This can make simple adjustment of an object's rotation incredibly tedious, since you are forced to use the unintuitive sliders rather than the visual widget. 

https://user-images.githubusercontent.com/56294129/136727211-ee88b80c-9076-4ff5-b8fb-3b32e24633e2.mp4

**Comment by plemsoft** [comment] 2022-02-24 08:48
@fearlesswee Thanks for reporting this issue , i was not able to reproduce this, could you try it in the latest version and let me know if this is still a issue, thanks for your help :)

**Comment by fearlesswee** [comment] 2022-02-24 16:15
@plemsoft Can confirm it still occurs on the latest build.
- Open any level/map.
- Place down any asset.
- Try rotating them using the widget rather than the sliders.
- Model will jitter and randomly rotate uncontrollably. 

I even used the same sofa model here!

https://user-images.githubusercontent.com/56294129/155563065-6f79879e-f16a-4198-be43-55183d18ff42.mp4

Here it is also occurring on a stock GGM asset, just to clear up it's not any issue with the specific model and simply the widget itself.

https://user-images.githubusercontent.com/56294129/155563302-798d26ca-4b18-4fbe-9b43-880d224a072e.mp4

**Comment by plemsoft** [comment] 2022-02-28 10:35
@LeeBamberTGC This is giving me some problems , perhaps a TW: to discuss, think its related to "Quaternion - Eular - conversion problem." , thanks :)

**Comment by LeeBamberTGC** [comment] 2022-02-28 12:16
@PaulSJ You mentioned you have some code from AGK which could convert between EULER -> QUAT -> EULER and avoids the weird inversion of the Euler to the +180,+90,+180 when moving between quats and eulers.  Post it here and I will take a closer look.

**Comment by LeeBamberTGC** [comment] 2022-02-28 13:19
@PaulSJ Thanks for the code and advice :) Now get yer hide back to nav mesh land - we are going to need it :)

**Comment by fearlesswee** [comment] 2022-03-26 21:54
Just bumping this issue as it still frequently occurs and I think should be addressed WAY sooner rather than later; widgets are how users piece together levels, without it the software's functionality and ease-of-use is severely limited.

**Comment by synchromesh62** [comment] 2022-03-27 00:33
I think its already fixed for the next update :)

**Comment by ZakJudges** [comment] 2022-05-11 12:31
Fixed in latest build

**Closed by ZakJudges** 2022-05-11 12:31 UTC
Labels: bug, Fixed but need confirmation., Max, Medium, Object Placement
