### ISSUE TITLE
GG Max - Patrol Rifle Damage ?

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2548] opened 2022-03-17 13:12 UTC
Am not sure why, but you can aim perfectly using the scope on the patrol rifle, but when you fire, even though the aim is perfect, you dont seem to hit or do any damage.

**Comment by LeeBamberTGC** [comment] 2022-03-17 17:21
@Tum1370 Even the patrol rifle has bullet drift and inaccuracy. There is no such thing as an infinitely straight bullet trajectory, but I see your general point. Would be nice if you can paint a red dot and hit it robin style :)  Maybe a future weapon or more options after EA.

**Comment by LeeBamberTGC** [comment] 2022-03-17 17:57
@Tum1370 I know it might be a vote of ONE right now, but do you feel we should wipe out inaccuracy for the patrol rifle?  Maybe open this up to the commuity. It might be cool to have an uber weapon in the ranks.

**Comment by Tum1370** [comment] 2022-03-17 17:59
@LeeBamberTGC Yes, I think as long as they are hold their breath and take the shot, it should kill.

**Comment by Tum1370** [comment] 2022-03-17 18:03
@LeeBamberTGC 
Maybe have it like as long as you are totally holding your breath, whilst taking the shot, the inaccuracy goes to 0. That way it’s like a proper rifle.

**Comment by LeeBamberTGC** [comment] 2022-03-17 18:09
@Tum1370 Nice idea. Maybe get some other community members to chime in here, and I will make happen for EA :)

**Comment by ArgentArts** [comment] 2022-03-17 19:37
As the old meme goes - why not both? Could there be a checkbox for the patrol rifle that makes it very accurate at all times or "real world" accurate or some such so the developer can decide how they want the patrol rifle to function?

Personally, it's fun to finally get something like a sniper rifle and be able to pick off the enemy from a loooong distance. ;)

**Comment by Tum1370** [comment] 2022-03-17 20:26
> As the old meme goes - why not both? Could there be a checkbox for the patrol rifle that makes it very accurate at all times or "real world" accurate or some such so the developer can decide how they want the patrol rifle to function?
> 
> Personally, it's fun to finally get something like a sniper rifle and be able to pick off the enemy from a loooong distance. ;)

Thing is though, You cant pick them off at long distance as most shots miss, I just use the assault rifle now as its much better at range shots, whereas it should not be.

**Comment by stuartds86** [comment] 2022-03-17 20:43
I totally support this as an issue. I wasted over a day trying to get long range shooting with the Patrol rifle to work. Editing the gun spec itself to get it somewhat accurate. If it has a zoom sight it should be accurate, more so when holding breathe otherwise its not worth using. I'd be interested in creating a game similar to the Sniper Ghost Warrior series and this rifle is the only option at the moment and it doesn't work. If there was calculated bullet drop etc then having inaccuracy make sense but if it is just random drift to add challenge it is just getting in the way.

**Comment by fearlesswee** [comment] 2022-03-17 23:59
It's hard to tell what's the gun being inaccurate, and what's just the hit registration being rubbish. In Lee's recent stream he was unloading the rifle at point-blank at a zombie, which did not react nor seem to take damage (it was an exploding zombie of which Lee killed several and they seem to only be able to take a single point of damage, so if any of his shots landed it should have clearly died.) Lack of any visual indicators for where your bullets are flying and landing most certainly does not help xD

**Comment by stuartds86** [comment] 2022-03-18 07:31
I set up physics based oil cans as a shooting range and tried to shoot them but they weren't being hit either at range. Instead I needed to be close up to have any effect.

**Comment by Tum1370** [comment] 2022-03-18 10:44
Ye its not a good gun, When in fact at range it should be the best gun, and accurate.

**Comment by PaulFox12** [comment] 2022-03-18 15:57
> @Tum1370 Nice idea. Maybe get some other community members to chime in here, and I will make happen for EA :)

An AR style rifle with a high magnification scope should definitely be more accurate than what the current patrol rifle. At the very least it should probably be adjusted for the EA release and beyond that it would be nice to open up some gunspec.txt variables to the editor so these can be adjusted by a games developer

**Comment by LeeBamberTGC** [comment] 2022-03-19 20:52
@Tum1370 I have reduced the patrol rifle damage to (38*2) and currently working on the inaccuracy problem for the next build. I can confirm the issue of 'missing' when you should not when zoomed in and steady, so just a matter of time now :)

**Comment by Tum1370** [comment] 2022-03-25 12:10
@LeeBamberTGC 
The Patrol Rifle is back to how it was before you tried to fixed it.
Not worth using now in the Early release version.
You miss far to many shots, Even at close range as well.

**Comment by fearlesswee** [comment] 2022-03-25 18:34
When setting the weapon's "accuracy" (bullet spread) field in the gunspec.txt file to zero, the weapon is a lot more reliable and functions like you imagine a "sniper" should. In my opinion it should have slight spread when firing from the hip, very little spread when aimed, and when in the alternate "long range scope" mode, it should have zero spread when aiming.

**Comment by LeeBamberTGC** [comment] 2022-03-27 18:15
@dllllllllllb Work with fearlesswee to create a new gunspec file that reflects the need for the patrol rifle to have near perfect accuracy when zoomed up, and deadly accuracy when using the secondary scope mode and holding player breath.

**Comment by dllllllllllb** [comment] 2022-03-28 14:01
I tuned the Patrol Rifle to be more accurate. Here are the changes to keep a changelog:
![image](https://user-images.githubusercontent.com/61796872/160413716-73835fc2-4b26-4040-9456-a32d22f067f7.png)

For anyone who would like to test the changes, extract this into "Max" folder and see if you agree with my changes, feedback will be appreciated :]
File:
[Files - Patrol Rifle Update.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8363414/Files.-.Patrol.Rifle.Update.zip)

**Comment by Tum1370** [comment] 2022-03-28 14:44
@LeeBamberTGC @dllllllllllb 
Can i just asked what these developer settings do in the object tool ?
Because i have tried changing these several times and they do not seem to affect the weapon ?
Is the weapon setting only changable by the gunspec ? Or are these developer setting meant to change it as well ?

![Untitled](https://user-images.githubusercontent.com/66874403/160423792-d43fc1eb-c3e4-43fd-836a-a80a97a9a4bf.png)

**Comment by stuartds86** [comment] 2022-03-28 17:53
> @LeeBamberTGC I made a "shooting range" with a bunch of enemies and set their health to 1 so they die after they get shot once. I then tested different settings in the gunspec.txt file and found that the variables under the Accuracy section seem to only affect the sway of the camera while aiming. I set all relevant variables to 0 || 1 and I still miss shots that shouldn't miss. Here's a video: https://www.youtube.com/watch?v=By2GlvnhH94
> 
> I thought that maybe there is something wrong with the hitboxes, so I turned enemies to face towards me and managed to get better accuracy. Then I saw that when I aim lower, I usually get more hits, so I figured that there might be something wrong with the crosshair.
> 
> My monitor has a feature to display a crosshair, and it doesn't line up with the crosshair from the patrol rifle. Using my monitors crosshair (the green dot) I can successfully hit all shots. ![crosshairtest](https://user-images.githubusercontent.com/61796872/160409033-ea673d12-902d-4af9-8121-f674219f3a56.jpg)
> 
> I also looked at the hold breath mechanic and I can't get it to work on my end. Changed the key bind from shift to "H" because shift would take you out of aiming, but I still couldn't get it to trigger my breakpoint in the code.
> 
> Any tips how I should approach the crosshair issue? Is there a sprite I should centre properly or is this issue in the code?

Thanks for the new gunspec file. Did you figure out what to do about the crosshair? Also what is the app you used to add your own?

**Comment by dllllllllllb** [comment] 2022-03-29 09:06
@stuartds86 I'm waiting for Lees response on the crosshair fix. The custom crosshair is a built in feature in my monitor, hence I had to take a picture of it rather than a screenshot, because it's only showing up on the monitor :]

**Comment by dllllllllllb** [comment] 2022-03-30 15:21
@LeeBamberTGC I changed one of the crosshairs colour, and changed the code only display it when zoomed in. It's centred properly, however the crosshair is fixed on the screen and doesn't respond to the animations / movement of the weapon.
Video: https://www.youtube.com/watch?v=ohEPKqhwPTg

I tried to edit the gun_color.dds file to centre the crosshair properly but the pixel density or maybe the compression doesn't allow a pixel to be perfectly in the middle.

**Comment by LeeBamberTGC** [comment] 2022-03-31 08:27
@dllllllllllb I think that will be fine as it will be accurate now when the gun is steady, we can always add back in the sway offset to the crosshair as an enhancement in the future. Check all the other weapons that have cross hairs to make sure we have not messed anything else up and then we can put this one in a build.

**Closed** 2022-05-11 13:08 UTC
Labels: bug, Fixed but need confirmation., Max, High, Weapons
