### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Misha365Days** [TheGameCreators/GameGuruRepo#3849] opened 2022-10-19 23:53 UTC
I have an issue it launches gets on loading and then crashes everything was good before yesterday

**Comment by ZakJudges** [comment] 2022-10-20 08:45
Hi @Misha365Days, could you post your system specs below? It is most likely caused by the change to DX12 in the latest public Steam build. For now, you could revert to the previous public build by right-clicking on GameGuru MAX in your Steam library, select Properties...->BETAS and then choose "previousdefault" from the drop-down list

**Comment by Misha365Days** [comment] 2022-10-20 10:15
Device name DESKTOP-LPA3A72
Processor AMD Ryzen 5 5500U with Radeon Graphics 2.10 GHz
RAM 8.00 GB (Available: 5.85 GB)
Device code 68949401-C226-48D6-B0E1-09353F72537F
Product code 00325-82194-93964-AAOEM
System type 64-bit operating system, x64 processor
Pen and touch input Pen and touch input are not available for this monitor

**Comment by Misha365Days** [comment] 2022-10-20 21:58
> Hi @Misha365Days, could you post your system specs below? It is most likely caused by the change to DX12 in the latest public Steam build. For now, you could revert to the previous public build by right-clicking on GameGuru MAX in your Steam library, select Properties...->BETAS and then choose "previousdefault" from the drop-down list

TY this helped

**Comment by ZakJudges** [comment] 2023-01-03 16:33
Hi @Misha365Days This should now be fixed on all builds. I will close this issue but if you experience it again, feel free to reopen. Thanks :)

**Closed by ZakJudges** 2023-01-03 16:33 UTC
Labels: bug, Max, CRASH!
