### ISSUE TITLE
gameguru max

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#3428] opened 2022-07-11 07:04 UTC
bug extracting aztec textures when you extract the game the textures do not work

**Comment by davetgc** [comment] 2022-07-12 11:27
Please name your threads here with the nature of the bug.

Thanks.

**Comment by ZakJudges** [comment] 2023-02-10 16:03
Duplicate of #3440

**Closed by ZakJudges** 2023-02-10 16:03 UTC
Labels: bug, Max, Medium, SaveStandAlone
