### ISSUE TITLE
Saving and loading games in standalone causing bugs and issues

### ISSUE THREAD

**Issue by mike123yy** [TheGameCreators/GameGuruRepo#3220] opened 2022-05-31 14:54 UTC
I've made a game and put it out there for people to play on the in progress forums and ive had Multiple reports of having  problems with saving the game and loading it. saving the game or loading from the save causes winning the level to not go to the next level properly and also causes collected items to not work. I also have reports of it making doors glitch out among other things. Here's the link to the forum. I've gotten some pretty detailed reports on the issues so visiting the post might be the best way to iron the problems out. The games also available to download there to see what's happening.

[https://forum.game-guru.com/thread/223599](url)

**Comment by LeeBamberTGC** [comment] 2023-09-22 12:49
@mike123yy Many fixes and tweaks and additions to ingame save and load since this report. Feel free to check it out when you have time, and I will schedule to close this soon.

**Comment by mike123yy** [comment] 2024-07-12 21:51
Figured I would update this post since I've been going back and fixing my game. Saving and loading with the stand-alone is still very broken and causes the same issues. Although the stand-alone exporter itself seems to not be working properly as well. As far as the issues I'm getting it's the same as the post above and the ones in the forum

**Comment by LeeBamberTGC** [comment] 2024-07-17 18:45
@mike123yy There has been some very recent work on this issue in the DEVTEST build. You can try it out and export a new standalone and see if some of your save game reloads restore the level state. The password for this build is "lettesterin42".

**Comment by mike123yy** [comment] 2024-07-17 23:13
I went ahead and made a new stand-alone and saved at all the spots that I figured would cause a problem. I would say it's about half fixed. A few of the spots I had tried to say that before no longer had any problems and work like they should while others made triggers or entities not appear or not activate like they were supposed to. I also had one level after saving when I completed it took me back to the second level instead of moving on to the fourth level like it's supposed to. I had my fifth level I saved at about halfway through and when you get to the end of the Woodlands corridor you're supposed to collect an item to open the door to the exit. Now on the first save before I collected the item everything worked fine but when I saved after collecting the item and reloaded it the item was missing but when I went to the door it acted as if it wasn't collected so the level can be completed. I also noticed lightning I made on my house level wouldn't activate until after the save which I hadn't seen before. And the last one off the top of my head was one of my levels had several readable notes and after saving some of them disappeared and the ones that worked were way over sized when the image came on the screen. Still seems like it needs more time in the oven before it's fixed :-)

**Comment by LeeBamberTGC** [comment] 2024-07-25 11:56
@mike123yy The lighting should be fixed in the DEVTEST branch. Your other feedback has parallels to other issues I am working on so watch Srteamn for another DEVTEST and hopefully a few more issues will be resolved.

**Comment by LeeBamberTGC** [comment] 2024-07-25 13:15
@mike123yy New DEVTEST uploaded with improved restoration of game saves.

**Comment by mike123yy** [comment] 2024-07-26 00:18
I gave it another spin and exported my standalone with the latest dev test. I'm still getting the same issues but in different spots and with different objects and scripts. I did a save test on my third level where after you enter a room and step on the trigger it opens a gate. I decided to save after and when I reloaded my save the gateway shut and refused open. I also had doors go missing and a couple other objects. Also on the third level I got a hard crash when entering the win zone which hasn't happened before. Now when I got to the level where you're supposed to escape the house there's also another trigger zone upstairs that opens the attic door and it no longer activates with the stand-alone so I couldn't get any far in my game past that. I sent my game into you for some help and Chris Bamber (no relation I'm sure :-) ) is currently taking a look at it for these bugs and for a list of other stuff so if you would like to use it for testing feel free.


> the lighting should be fixed in the DEVTEST branch

I never had a problem with the lighting, it seems to be working good. I was talking about lightning that strikes outside my windows when the player walks into a zone. It works on one level but not on another in the stand-alone. It seems to be doing what some of the other objects are doing and deciding to show up sometimes but not in others. Everything works just fine with the test game minus the final boss dropping loot and a couple sound zones.

**Comment by LeeBamberTGC** [comment] 2024-08-13 17:41
@mike123yy New DEVTEST build uploaded with improvements to lots of areas of the game save reloader, and I have even created a small marathon of tests to make sure all the little niggles are sorted so a typical level state is restored. Pretty much everything in the shot below and the inventory/container system works fine for me in this build:
![image](https://github.com/user-attachments/assets/076b71fb-1c8b-452c-8a33-4b72b4958908)

**Comment by mike123yy** [comment] 2024-08-13 20:42
I gave the stand-alone another try and made a bunch of saves in the same areas. It was actually working very well when loading back the saves. Almost everything was functioning like it should minus a couple things that wouldn't trigger after the save, but there were very few. But, I had to take a break and I loaded the game back up later and tried to start one of the saves again. That's when the problem started happening. Like last time the keys wouldn't show up so you can finish levels, the wrong levels loaded after finishing, triggers weren't working, etc. and it was doing it on almost every single save I made where they were fine before I shut the game down. So something's happening when you quit the game that makes things go haywire when you come back to playing. If you could get that to stop happening from when I tested so far it seems like it would mostly be fixed.

**Comment by LeeBamberTGC** [comment] 2024-08-13 21:52
@mike123yy Any way you can prepare a small level as a standalone and send it to me, and then show me the steps to get to reproduce just one of the things you reported above. Bunching them all together there is no way to know where to start, best if we have your most serious issue reproduced, get that fixed, then move through the list.

**Comment by mike123yy** [comment] 2024-08-14 00:12
Alright, I'm sending to your email the nightmare level from my game that's pretty quick to beat and has one of the big bugs. Since it's only one level though I can't reproduce  it jumping to the wrong level after a save. I also made a save that should trigger the bug so you can't go through the final door. You probably want to play it through once to see what happens so all you have to do  is run past the TVs to the left and around the corner to the end where there is a chair with a doll and it.. If you pick it up it will let you go through the final door  and complete the level. If my save doesn't work just make a save right after you pick up the doll and it should cause the bug and it will also cause the cult member guys to not appear afterwards.You have to close the games down and come back for the bug to happen though. One more thing, I noticed when I was  playing through this single level on the export that a lot of the entities that were broken weren't broken anymore. The TV screens were where they are supposed to be and the creature guy that crawls across the path is working as intended.So if the level works on its own with no broken entities but there broken when connected to other levels that might be the key to some kind of bug there.Anyway, I'm sending you the level now.

**Comment by LeeBamberTGC** [comment] 2024-08-14 09:32
@mike123yy Thanks for the demo, I can reproduce your issue, great stuff. Just sit back and wait for the fix :)

**Comment by LeeBamberTGC** [comment] 2024-08-14 11:33
@mike123yy I have fixed the issue with the door not opening when you reload from after collecting the doll, but having an issue reproducing the missing cult ghosts on the journey from the doll to the door. Can you email me the unencrypted version of your USER folder, thanks!

**Comment by mike123yy** [comment] 2024-08-14 14:34
Do you need the entire user entity folder from my documents or the FPM for the level? Or the entire Max folder from my documents? It's grown to about 18 GB so that would be a lot to send. Just making sure

**Comment by LeeBamberTGC** [comment] 2024-08-14 14:40
@mike123yy You had 127 files in the "" folder of the standalone you sent, these are the ones I need to recreate the cult disappearances issue, assuming one of those entities is indeed that model. I have the FPM which I can use to them load the level with the missing files and see what behaviour is attached to these things and why they do not show up after a reload.

**Comment by LeeBamberTGC** [comment] 2024-08-14 15:08
@mike123yy New DEVTEST build uploaded with improved refresh of game saves, this might help. Still working on the standalone issue of the cult ghosts moving around after the doll is colllected.

**Comment by LeeBamberTGC** [comment] 2024-08-26 14:46
@mike123yy I used the dream FPM from the standalone to load it into the level editor to find the cult member object but it does not seem to be there. Can you show me the detailed object view of your level in objects starting with C:
![image](https://github.com/user-attachments/assets/777ce8a8-55ff-4e77-af58-327ac1d2337a)

As you can see, even though I have the cult object in the user folder, it does not show up in the level or the missing objects log.

**Comment by mike123yy** [comment] 2024-08-26 16:14
![1](https://github.com/user-attachments/assets/f323a98a-a088-43be-b3be-78dc33564f36)
here it is on mine. It should be right under computer3 but yeah, it's not showing on yours. That strange.

**Comment by LeeBamberTGC** [comment] 2024-08-26 16:23
@mike123yy Can you email me that exact FPM from your local project mapbank area, just to be sure.  Then I will step through and determine why it is not included in the level loaded

**Comment by mike123yy** [comment] 2024-08-26 17:09
I sent the files on over to you. It's titled dream level with the issue number for the bug.

**Comment by mike123yy** [comment] 2024-08-27 15:57
He appears just fine before the save but he's still not appearing after saving right after collecting the doll. There's actually two guys and neither one of them will appear after the save. I did have to do a standalone of the individual level while testing. I tried to do the whole game but there seems to be a bug with collision. Every item that is hidden until triggered still has collision and so if there is a hidden wall you can't get past it. This didn't happen on the individual level standalone though which is odd. I don't know what the difference would be. These levels are about two years old, maybe they have some kind of corruption causing the problems, just an uneducated guess :-)

**Comment by LeeBamberTGC** [comment] 2024-08-27 16:20
@mike123yy Send me another new standalone demo from what you have and I will check. I noticed the restore script was an older one which caused some of the issue, so the latest thing you are using will allow me to track what old part you might have, thanks!

**Comment by mike123yy** [comment] 2024-08-27 18:21
On its way now

**Comment by LeeBamberTGC** [comment] 2024-08-27 19:41
@mike123yy Could you also send me these four too, managed to find out the cult chap is triggered by something else and I suspect the "triggerbox.fpe":

entitybank\Purchased\BSP\Furniture\Bed 02.fpe=replaceentitybank\Purchased\BSP\Furniture\Bed 02.fpe
entitybank\Purchased\that model guy\Misc\tv.fpe=replaceentitybank\Purchased\that model guy\Misc\tv.fpe
entitybank\Office & Industrial props\Fence.fpe=replaceentitybank\Office & Industrial props\Fence.fpe
entitybank\tools\triggerbox.fpe=replaceentitybank\tools\triggerbox.fpe

**Comment by mike123yy** [comment] 2024-08-27 20:06
Maybe that trigger box is the problem. I had to use that back when because the trigger zone's didn't allow you to trigger them at the time so that was a workaround I used. Anyway, I sent the files to your inbox

**Comment by LeeBamberTGC** [comment] 2024-08-27 21:38
@mike123yy New DEVTEST build uploaded with HOPEFULLY the fix you need. Turned out the REAL reason was the inability for the playerzone script to resurrect itself once it had been triggered.  You will need to make a new standalone and new save game position files for the fix to show.

**Comment by mike123yy** [comment] 2024-08-27 22:47
I gave it another spin and everything does trigger how it's supposed to, even after a save. I can't really test the rest of the levels with the collision issue when exporting the entire game I'm having but I suppose that's a different issue for a different thread. As for this one though it looks like it's fixed :-) thanks Lee

**Comment by LeeBamberTGC** [comment] 2024-08-27 22:54
@mike123yy Cool, please drop a link to this new issue and perhaps send a new standalone and I can work on it while I am familiar with your standalone :)

**Closed by LeeBamberTGC** 2024-08-27 22:55 UTC
Labels: bug, Fixed but need confirmation., Max, Medium, SaveStandAlone

**Comment by mike123yy** [comment] 2024-08-27 23:09
Here's a link to the other thread where me and a couple other people reported the collision issues as well as a couple others that were happening. Some of it might be fixed now due to what you're working on here. I could start a new thread but this one already mentions the problems so I figured I would keep from making the get hub list too messy
https://github.com/TheGameCreators/GameGuruRepo/issues/5620
I'm building the full standalone for the game right now. I will email you the link when it's done
