### ISSUE TITLE
Zombie and Classic Characters warping in standalone

### ISSUE THREAD

**Issue by honkeyboy** [TheGameCreators/GameGuruRepo#54] opened 2018-02-05 18:46 UTC
Tested on two machines with the same result the dogman, the chainsaw brute and various zombies warp so badly that the black out the whole map.
Pic on forums showing the chainsaw brute
https://forum.game-guru.com/attachment/17843
Both Graphics cards were radeons doesnt seem to happen in the editor

**Comment by Teabone3** [comment] 2018-02-05 19:53
Does setting skipfvfconvert = 1 in the FPE correct this bug?

**Comment by honkeyboy** [comment] 2018-02-05 20:06
No m8 its already assigned in the FPE

**Comment by GraPhiX-Guru** [comment] 2018-02-05 20:12
@honkeyboy  can you send me one of the FPE's of the character that's doing this from the editor version and then the same one from the standalone version please

**Comment by honkeyboy** [comment] 2018-02-05 20:49
Sure Graphix but you do remember the stanadlone one is encrypted? They are just the standard FPE's in the classics folder, and the zombies folder. I have just run the level again and noticed in the standalone (not the Editor) I am getting some serious fps dips e.g in the editor I'm getting 40-50 fps in the standalone 30-40 fps which occationally dips right down to say 6 just for a split second. Could this be the cause of the issue?

**Comment by honkeyboy** [comment] 2018-02-06 12:49
Actually thats a good idea m8 will test it here also


________________________________

**Comment by LeeBamberTGC** [comment] 2018-03-13 17:32
I used the latest PP build and dropped in Female Hag Zombie from the stock media, added a player start marker, saved the FPM then saved a standalone executable. Ran this standalone game and the zombie was rendering fine. I can only suspect there was something unique to your project that caused this corruption, and until we can reproduce it this bug report will be closed at some point. If you have a way to allow someone to reproduce this issue with a fresh install of GameGuru PP build and stock media only, we can get it resolved.

**Comment by plemsoft** [comment] 2018-03-14 10:57
Looks like the skin weight problem , this has been addressed in my latest branch.

**Comment by honkeyboy** [comment] 2018-03-16 11:26
@ Preben thanks for the fixes m8 that would maybe explian why it was happening with the fuse characters in the previous project e.g the warping which i was unsure whether was an fps/memory issue as the editor would glitch for a split second = fps 0 and then resume. will rebuild the standalone later and retest thanks :)

**Closed** 2018-03-21 13:26 UTC
Labels: bug, fixed, question
