### ISSUE TITLE
GG Max Bug Report (with last internal build) - Terrain Bug

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#2270] opened 2022-02-24 21:13 UTC
Latest Max internal update (2022-02-24).
Max is giving me two huge Terrain bugs. It is not possible to delete them. The Restore Terrain does not work on these bugs, nor any other Terrain modification tools. The tools work everywhere else, but not on the bugs.
![Original Map](https://user-images.githubusercontent.com/96718175/155608401-6a1aefa0-48b8-4c6b-9ee9-2144caffc6da.jpg)
I had made a backup copy, just before the update, but the bug appears there too :
![Copy Map](https://user-images.githubusercontent.com/96718175/155608491-bfc6e400-2984-44b8-af8b-605c9b4fb3c3.jpg)
I don't know how to get rid of it. I managed to open the map only once without this bug. Admit that it spoils the view.
![BadView](https://user-images.githubusercontent.com/96718175/155608650-712aa035-3990-486d-8650-c4f1de0e294e.jpg)
Suggestions ?
After several attempts to load :
![NoBug](https://user-images.githubusercontent.com/96718175/155610160-736ca2b6-7b29-4f39-9f33-8b110e062461.jpg)
Random bug ?
This bug also occurs with new maps created with this internal build.
![BugNewMap](https://user-images.githubusercontent.com/96718175/155675044-87600168-5208-4013-aaf8-affad267aca6.jpg)

**Comment by ArgentArts** [comment] 2022-02-24 21:47
Wow. It looks like the terrain auto-flattening thing gone mad ... trying to flatten the terrain under those two items only, failing miserably, and pushing the terrain upward ... way upward.

As a possible workaround, have you tried grabbing and moving those two models somewhere else? Then saving (under a different name to be safe), closing, and reopening to see if anything changes at all?

**Comment by UltraVox001** [comment] 2022-02-24 21:55
It's unrelated, in my opinion.
The FPE of both elements does not contain the line : "autoflatten = 1" :)
It's a terrain bug like I've discovered others over the past few weeks. :)

**Comment by ArgentArts** [comment] 2022-02-24 23:03
Or it's happening (a bug) despite you having autoflatten set to 1. Just a thought.

**Comment by UltraVox001** [comment] 2022-02-24 23:10
To my knowledge, the only elements of Max with the auto flatten are the buildings located in "Building Collection". It is not possible (for the moment) to impose an auto flatten on an element which does not have the line "autoflatten = 1" in its FPE.

However, I made a request to generalize the situation.
That is, allow any object to be auto flattened, if the user requests it.
Read : [https://github.com/TheGameCreators/GameGuruRepo/issues/2263](https://github.com/TheGameCreators/GameGuruRepo/issues/2263).

**Comment by Necrym59** [comment] 2022-02-25 00:45
Lol thats one nice looking map there Ultra

**Comment by UltraVox001** [comment] 2022-02-25 07:47
@Necrym59 Thank you.
For the moment, this map contains 1462 3D objects.
Great for testing things out. :)

**Comment by Necrym59** [comment] 2022-02-25 08:21
A good test map i would say...is that a climber i see tucked away there ;)

**Comment by UltraVox001** [comment] 2022-02-25 08:23
All your scripts are on it. They are all useful.
And they all have to work together :)

**Comment by ZakJudges** [comment] 2022-02-25 10:39
@LeeBamberTGC this happens to me as well. 
Steps to reproduce:
- place some buildings down that have autoflatten = 1
- place some objects that do not have autoflatten
- save and quit the software,
- reload the map there will either be large raised areas of terrain like seen above, or regions that have sunk lower that the object above them

**Comment by UltraVox001** [comment] 2022-02-25 10:43
@ZakJudges @LeeBamberTGC 
This bug also occurs on a completely blank map created with the latest build.
There is no building. No 3D objects. Do you want the blank map ?
![EmptyMap](https://user-images.githubusercontent.com/96718175/155701730-e146c003-13ea-448c-ad6e-2b6c2ee369f3.jpg)

**Comment by ZakJudges** [comment] 2022-02-25 10:45
@UltraVox001 Yes please attach it here :)

**Comment by UltraVox001** [comment] 2022-02-25 11:05
Map too heavy for Github, here is a download link : [https://we.tl/t-L9lBxrajI9](https://we.tl/t-L9lBxrajI9)
- For the bug to occur on this blank map, I must first load a map in which there are objects.
- Once this big map is loaded and after noticing the bug, I load the blank map and there is the bug.
- The appearance of the bug is exactly the same in both maps.
- I placed a StartPlayer in front of the bug (it appears in the water).
- No bug will appear on a blank map if you have not seen the bug on a previous map containing objects.

**Closed** 2022-02-28 11:23 UTC
Labels: bug, Fixed but need confirmation., Max, High
