### ISSUE TITLE
Hanging black screen on save

### ISSUE THREAD

**Issue by honkeyboy** [TheGameCreators/GameGuruRepo#72] opened 2018-02-15 16:34 UTC
Mostly after adding a few items on the map when save is clicked the screen goes black and hangs until you ctl alt del ou,t although the changes are saved you do have to reboot GG

**Comment by LeeBamberTGC** [comment] 2018-03-13 21:34
This has been fixed in the PP build caused by an infinite loop relating to the text prompts to report progress of the save process.

**Closed by LeeBamberTGC** 2018-03-13 21:34 UTC
Labels: bug
