### ISSUE TITLE
GGMAX Bug - Weapons Continually Added To Level

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#5488] opened 2024-04-28 22:51 UTC
My game does not use any weapons - but MAX continually adds weapons randomly to a level
- sometimes its just an Aztec dagger
- sometimes it is several firearms 

Thanks for checking :)

**Comment by Necrym59** [comment] 2024-04-29 02:18
Delete the TSV files from your project folder and see if it resolves it

**Comment by OldFlak** [comment] 2024-04-29 22:29
@Necrym59 Tried that - just puts them back - nine weapons now :)

**Comment by Necrym59** [comment] 2024-04-30 05:23
I dont think they are added to the level - if they say (Auto-gen) after their name in the list, they are just the cache for weapons.

**Comment by Kitakazi** [comment] 2024-04-30 19:28
The weapons from stock GG and the DLC's always auto-gen. There is no way to stop it.

**Comment by ShadowMasterOfGames** [comment] 2024-05-02 22:08
@LeeBamberTGC as you found out with my melee behavior bug #5486 map that I first sent you, there were guns list that are not in the level which I did not add, so this needs to be fixed as well when you have time.thank you

**Comment by OldFlak** [comment] 2024-08-06 10:00
By the way, deleting or even editing the collection files just results in MAX replacing them

**Comment by LeeBamberTGC** [comment] 2024-08-10 14:00
@OldFlak The only way auto gen weapons can be added to the TSV is if they exist in some form within the level you are working on. Can you email me the FPM level that causes the TSV file to update during a save, thanks!

**Comment by ShadowMasterOfGames** [comment] 2024-08-10 16:38
@LeeBamberTGC i have been having that same issue as oldflak has been having with weapons (guns) that are showing up and I have no guns in any of my levels and after deleting them from the tsv, the collection list, they keep coming back over and over

**Comment by LeeBamberTGC** [comment] 2024-08-10 17:26
@ShadowMasterOfGames Drop me an FPM of your level that has no weapons and I will scan to see if any are hiding.

**Comment by OldFlak** [comment] 2024-09-02 06:42
Here is a pic
![image](https://github.com/user-attachments/assets/57ce259f-72b9-46d1-90cd-0b688f2f222d)
Note the two weapons at the top, if I go through the list every weapon is there, even if I select and remove them MAX will put them back. Note I have never added any weapons to this (or any other) level :)

**Comment by LeeBamberTGC** [comment] 2024-09-20 12:18
@OldFlak From looking at your recently sent standalone that includes the level you are showing, and looking at the collection file, I noticed there are a few weapons that need auto generating into the level. Can you confirm your game needs all the weapons shown in your collection file:

title	profile	image	description	cost	value	container	ingredients	style
Frag Grenade	Max Collection\Weapons\Frag Grenade.fpe	gamecore\guns\enhanced\M67\item.png	 	10	5	none	none	weapon=enhanced\M67
Assault Rifle	Max Collection\Weapons\Assault Rifle.fpe	gamecore\guns\enhanced\AK\item.png	 	10	5	none	none	weapon=enhanced\AK
Aztec Dagger	Aztec Game Kit\Weapons\Aztec Dagger.fpe	gamecore\guns\aztec\AztecDagger\item.png	 	10	5	none	none	weapon=aztec\AztecDagger
Colt Pistol	Max Collection\Weapons\Colt Pistol.fpe	gamecore\guns\max\colt\item.png	 	10	5	none	none	weapon=max\colt
Patrol Rifle	Max Collection\Weapons\Patrol Rifle.fpe	gamecore\guns\enhanced\AR\item.png	 	10	5	none	none	weapon=enhanced\AR
Sledgehammer	Max Collection\Weapons\Sledgehammer.fpe	gamecore\guns\enhanced\SledgeHammer\item.png	 	10	5	none	none	weapon=enhanced\SledgeHammer
Pocket Knife	Max Collection\Weapons\Pocket Knife.fpe	gamecore\guns\enhanced\B810\item.png	 	10	5	none	none	weapon=enhanced\B810
Tactical Pump Shotgun	Max Collection\Weapons\Tactical Pump Shotgun.fpe	gamecore\guns\enhanced\R870\item.png	 	10	5	none	none	weapon=enhanced\R870
Compact Assault Rifle	Max Collection\Weapons\Compact Assault Rifle.fpe	gamecore\guns\enhanced\MK18\item.png	 	10	5	none	none	weapon=enhanced\MK18
Snubnose Revolver	Max Collection\Weapons\Snubnose Revolver.fpe	gamecore\guns\enhanced\M29S\item.png	 	10	5	none	none	weapon=enhanced\M29S
Shovel	Max Collection\Tools\Shovel.fpe	gamecore\guns\tools\Shovel\item.png	 	10	5	none	none	weapon=tools\Shovel
Magnum Pistol	Max Collection\Weapons\Magnum Pistol.fpe	gamecore\guns\enhanced\MK19T\item.png	 	10	5	none	none	weapon=enhanced\MK19T

**Comment by OldFlak** [comment] 2024-09-20 22:41
Hi @LeeBamberTGC 
I can confirm I **don't** need them at all. I have not added any weapons to any level in the game

**Comment by ShadowMasterOfGames** [comment] 2024-09-21 00:56
@LeeBamberTGC is there a way to turn off auto generated weapons, and other items? Or just get rid of the auto generated system?

**Comment by ShadowMasterOfGames** [comment] 2024-09-21 01:02
> @ShadowMasterOfGames Drop me an FPM of your level that has no weapons and I will scan to see if any are hiding.

@LeeBamberTGC i have not been on my laptop (just sold my house in August and also been busy getting things done to move) basically everything you see in @OldFlak level is also in mine as well. I can try to get on and send you my fpm (if I have time between cleaning and packing as well as buying my new house)

**Comment by ShadowMasterOfGames** [comment] 2024-09-21 01:11
@LeeBamberTGC I found the fpm that I sent you in this form #5486, which is below and as you will see, I am not using any guns in that level only a dagger 

[Stonehearts_Office.zip](https://github.com/user-attachments/files/17082341/Stonehearts_Office.zip)

**Comment by LeeBamberTGC** [comment] 2024-09-21 18:28
@ShadowMasterOfGames Looks like your level does contain weapons:
MISSING MEDIA:
entitybank\Purchased\Sula\The Ultimate Wild West Pack GG Classic  GG Max\Ultimate Wild West Pack\Misc\watertower.fpe=replaceentitybank\Purchased\Sula\The Ultimate Wild West Pack GG Classic  GG Max\Ultimate Wild West Pack\Misc\watertower.fpe
entitybank\Purchased\BSP\Animated FPS Weapons Mega Pack\Weapons\Modern\Combat Shotgun.fpe=replaceentitybank\Purchased\BSP\Animated FPS Weapons Mega Pack\Weapons\Modern\Combat Shotgun.fpe
entitybank\Purchased\BSP\Animated FPS Weapons Part 2\Weapons\Modern\M9 Pistol.fpe=replaceentitybank\Purchased\BSP\Animated FPS Weapons Part 2\Weapons\Modern\M9 Pistol.fpe
entitybank\Purchased\BSP\Futuristic Weapons Pack MaxClassic\Weapons\Futuristic\Voidbolter.fpe=replaceentitybank\Purchased\BSP\Futuristic Weapons Pack MaxClassic\Weapons\Futuristic\Voidbolter.fpe
entitybank\Purchased\BSP\GG MAX FPS Weapons Set\Weapons\Modern\Uzi.fpe=replaceentitybank\Purchased\BSP\GG MAX FPS Weapons Set\Weapons\Modern\Uzi.fpe
entitybank\Purchased\BSP\Animated FPS Weapons Mega Pack\Weapons\Modern\Submachine Gun.fpe=replaceentitybank\Purchased\BSP\Animated FPS Weapons Mega Pack\Weapons\Modern\Submachine Gun.fpe
entitybank\Purchased\BSP\Animated FPS Weapons Mega Pack\Weapons\Modern\Sniper Rifle.fpe=replaceentitybank\Purchased\BSP\Animated FPS Weapons Mega Pack\Weapons\Modern\Sniper Rifle.fpe
entitybank\Purchased\BSP\Animated FPS Weapons Part 1\Weapons\Modern\Shoulder-Launched Missile.fpe=replaceentitybank\Purchased\BSP\Animated FPS Weapons Part 1\Weapons\Modern\Shoulder-Launched Missile.fpe
entitybank\Purchased\BSP\Animated FPS Weapons Mega Pack\Weapons\Modern\Semi-Automatic Pistol.fpe=replaceentitybank\Purchased\BSP\Animated FPS Weapons Mega Pack\Weapons\Modern\Semi-Automatic Pistol.fpe
entitybank\Purchased\BSP\GG MAX FPS Weapons Set\Weapons\Modern\Pump Action Shotgun.fpe=replaceentitybank\Purchased\BSP\GG MAX FPS Weapons Set\Weapons\Modern\Pump Action Shotgun.fpe
entitybank\Purchased\BSP\Animated FPS Weapons Part 1\Weapons\Modern\General-Purpose Machine Gun.fpe=replaceentitybank\Purchased\BSP\Animated FPS Weapons Part 1\Weapons\Modern\General-Purpose Machine Gun.fpe
entitybank\Classics\Coffin 1.fpe=replaceentitybank\Classics\Coffin 1.fpe
entitybank\Mega Pack 02\ChurchPack\Wooden Cross of Christ.fpe=replaceentitybank\Mega Pack 02\ChurchPack\Wooden Cross of Christ.fpe
entitybank\Classics\Sci-Fi\Props\sign4.fpe=replaceentitybank\Classics\Sci-Fi\Props\sign4.fpe
etc..

Can you now send me the "collection - items.tsv" from your project folder so I can check to see if they have entries there.

@OldFlak In this case you can manually delete the unwanted weapons from your level(s), then exit MAX, delete the TSV file, then reload your project and the weapons will not reappear.

**Comment by ShadowMasterOfGames** [comment] 2024-09-21 21:37
> @ShadowMasterOfGames Looks like your level does contain weapons: MISSING MEDIA: entitybank\Purchased\Sula\The Ultimate Wild West Pack GG Classic GG Max\Ultimate Wild West Pack\Misc\watertower.fpe=replaceentitybank\Purchased\Sula\The Ultimate Wild West Pack GG Classic GG Max\Ultimate Wild West Pack\Misc\watertower.fpe entitybank\Purchased\BSP\Animated FPS Weapons Mega Pack\Weapons\Modern\Combat Shotgun.fpe=replaceentitybank\Purchased\BSP\Animated FPS Weapons Mega Pack\Weapons\Modern\Combat Shotgun.fpe entitybank\Purchased\BSP\Animated FPS Weapons Part 2\Weapons\Modern\M9 Pistol.fpe=replaceentitybank\Purchased\BSP\Animated FPS Weapons Part 2\Weapons\Modern\M9 Pistol.fpe entitybank\Purchased\BSP\Futuristic Weapons Pack MaxClassic\Weapons\Futuristic\Voidbolter.fpe=replaceentitybank\Purchased\BSP\Futuristic Weapons Pack MaxClassic\Weapons\Futuristic\Voidbolter.fpe entitybank\Purchased\BSP\GG MAX FPS Weapons Set\Weapons\Modern\Uzi.fpe=replaceentitybank\Purchased\BSP\GG MAX FPS Weapons Set\Weapons\Modern\Uzi.fpe entitybank\Purchased\BSP\Animated FPS Weapons Mega Pack\Weapons\Modern\Submachine Gun.fpe=replaceentitybank\Purchased\BSP\Animated FPS Weapons Mega Pack\Weapons\Modern\Submachine Gun.fpe entitybank\Purchased\BSP\Animated FPS Weapons Mega Pack\Weapons\Modern\Sniper Rifle.fpe=replaceentitybank\Purchased\BSP\Animated FPS Weapons Mega Pack\Weapons\Modern\Sniper Rifle.fpe entitybank\Purchased\BSP\Animated FPS Weapons Part 1\Weapons\Modern\Shoulder-Launched Missile.fpe=replaceentitybank\Purchased\BSP\Animated FPS Weapons Part 1\Weapons\Modern\Shoulder-Launched Missile.fpe entitybank\Purchased\BSP\Animated FPS Weapons Mega Pack\Weapons\Modern\Semi-Automatic Pistol.fpe=replaceentitybank\Purchased\BSP\Animated FPS Weapons Mega Pack\Weapons\Modern\Semi-Automatic Pistol.fpe entitybank\Purchased\BSP\GG MAX FPS Weapons Set\Weapons\Modern\Pump Action Shotgun.fpe=replaceentitybank\Purchased\BSP\GG MAX FPS Weapons Set\Weapons\Modern\Pump Action Shotgun.fpe entitybank\Purchased\BSP\Animated FPS Weapons Part 1\Weapons\Modern\General-Purpose Machine Gun.fpe=replaceentitybank\Purchased\BSP\Animated FPS Weapons Part 1\Weapons\Modern\General-Purpose Machine Gun.fpe entitybank\Classics\Coffin 1.fpe=replaceentitybank\Classics\Coffin 1.fpe entitybank\Mega Pack 02\ChurchPack\Wooden Cross of Christ.fpe=replaceentitybank\Mega Pack 02\ChurchPack\Wooden Cross of Christ.fpe entitybank\Classics\Sci-Fi\Props\sign4.fpe=replaceentitybank\Classics\Sci-Fi\Props\sign4.fpe etc..
> 
> Can you now send me the "collection - items.tsv" from your project folder so I can check to see if they have entries there.
> 
> @OldFlak In this case you can manually delete the unwanted weapons from your level(s), then exit MAX, delete the TSV file, then reload your project and the weapons will not reappear.

@LeeBamberTGC I do not use any of those weapons, I have deleted them until I am blue in the face. It so frustrating to open Max and find those back in the list of assets in my level and when you click on them to delete them, it shows you the ground. I will try to find time tomorrow to get on my laptop to send you those files but as I mentioned earlier, I between cleaning and packing since I close on October 10 on my old house and close on October 11 on my new house

**Comment by ShadowMasterOfGames** [comment] 2024-09-21 22:03
@LeeBamberTGC Sending you a link to the zip file with everything in.

https://www.dropbox.com/scl/fi/xyv9ipdoubiosu4mgrn7b/Stoneheart-Secret-Bunker-level.zip?rlkey=kzst78n0b5lbawb68ihicqzrk&st=kct7mjw2&dl=0

**Comment by OldFlak** [comment] 2024-09-22 03:30
Hi @LeeBamberTGC 
after todays update, I went through the project file system and remove any weapon related media aside from the folders
I also removed the three collection files.

When loading the project again all the weapons are still showing up in the Level Objects panel 
This is what is in collection - items.tsv
![image](https://github.com/user-attachments/assets/1c211a79-cb68-44d9-90f2-5b4a00ddc3db)

**Comment by LeeBamberTGC** [comment] 2024-09-22 13:35
@OldFlak Email me the level that shows the weapons and I will scan to see which weapons match those in the TSV. If you can also include the TSV file as well, I can use both to produce a clean set of each, OR will find the bug that prevents this.

**Comment by LeeBamberTGC** [comment] 2024-09-22 16:10
@ShadowMasterOfGames Thanks for sending the ZIP with your project TSV files and level.  It allowed me to reproduce the issue you are seeing and a fix has been added to the next DEVTEST build, after the fix this is what I did to remove the Aztec Dagger and Axe (as examples of two removals which you can do with the rest):

![image](https://github.com/user-attachments/assets/ddd66aa9-4dc5-4679-883b-9f146ec57cbc)
Switch to the DETAILED OBJECT LIST so you can see your objects to confirm they are there, grr.

![image](https://github.com/user-attachments/assets/58579a4e-f379-417e-9221-12032efd65ab)
Exit MAX, and then open the "collection - items.tsv" file in your projects area

![image](https://github.com/user-attachments/assets/cc415214-5ca7-4d92-9508-7e93391a3f64)
Highlight the weapons you wish to remove forever and delete those lines, then save the file

![image](https://github.com/user-attachments/assets/91c7b32e-8e3d-4724-bcd6-98de7e2a07f9)
Now launch MAX and open your project and load the level we saw in step one

![image](https://github.com/user-attachments/assets/4284b0b2-78b2-4529-8623-f92ff9b000db)
Return to detailed oblist, highlight the weapon, move mouse pointer to level editor area and press DELETE key

![image](https://github.com/user-attachments/assets/1b10ea8b-ad70-4d62-a394-f4bbac994b67)
Repeat with other weapon

![image](https://github.com/user-attachments/assets/6491dee8-05e8-49a7-b5c4-019f9d33051e)
Now click into the level editor floor to mark a change, then save the level

When you leave and return to MAX and load the project and then level, you will notice these two weapons are gone.

**Comment by ShadowMasterOfGames** [comment] 2024-09-22 16:17
@LeeBamberTGC, thank you so much for fixing this, since I do not have Devtest maybe @OldFlak can see if this fixes his issues too. I am using exp build, so hopefully this fixes both my and oldflak's issues. Thanks again for your patience and hard work on this matter.

**Comment by LeeBamberTGC** [comment] 2024-09-22 16:27
@ShadowMasterOfGames Will be updating EXP along with DEVTEST later today :)

**Comment by ShadowMasterOfGames** [comment] 2024-09-22 16:30
@LeeBamberTGC Great, I will get on my laptop today or at the latest tomorrow and let you know, thanks again for all your hard work

**Comment by ShadowMasterOfGames** [comment] 2024-11-03 20:46
@LeeBamberTGC it still does auto-load weapons into levels but I using your advice to remove them. Max should not do any auto-generation of anything.

**Comment by OldFlak** [comment] 2024-11-03 22:28
Hi @LeeBamberTGC 
Yes it appears to be fixed in DevTest branch - awesome - thanks for your hard work.
Happy for you to close this unless you would like @ShadowMasterOfGames to confirm when the fix gets to EXP

👍

**Comment by LeeBamberTGC** [comment] 2024-11-03 22:43
@OldFlak I can close for now and reopen if @ShadowMasterOfGames finds anything amiss in the next build of EXP :)

**Closed by LeeBamberTGC** 2024-11-03 22:43 UTC
Labels: bug, Fixed but need confirmation., Max, Medium, Containers & Inventory
