### ISSUE TITLE
MAX - 2022.02.04 - Terrain Shadows

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1982] opened 2022-02-06 22:58 UTC
Perhaps we need control over distant shadows on terrain - they just don't look like shadows

![image](https://user-images.githubusercontent.com/12246318/152705098-f5332e16-aa68-4283-b9cf-e57b125197bf.png)

**Comment by PaulSJ** [comment] 2022-02-07 12:20
I've not seen anything like that happen here, can you give some more details on how to reproduce it?

**Comment by OldFlak** [comment] 2022-02-07 13:11
Hmm I have seen it ever since terrain was introduced. I can send a link to a demo level if it will help.

**Comment by PaulSJ** [comment] 2022-02-07 14:08
Yes please

**Comment by OldFlak** [comment] 2022-02-07 21:01
Hi Paul - where to send link :)

**Comment by PaulSJ** [comment] 2022-02-08 01:04
@OldFlak paul@thegamecreators.com

**Comment by OldFlak** [comment] 2022-02-08 06:53
Hi Paul
Here be the link to the level as requested
https://www.dropbox.com/s/3ecjabrlygsz6dt/Terrain%20Shadow%20Issue.zip?dl=0

Player marker is in position – when level starts you can just do a 360 turn to see the issue in multiple places

Thanks for looking into it 😊

Regards
Michael

**Comment by PaulSJ** [comment] 2022-02-11 13:54
@plemsoft Can you take a quick look at this. The shadows are fine in the editor but then become changed after pressing test game. Returning to the editor keeps the shadows in their broken state so I'm wondering if the test game process is modifying some shadow settings?

The bug itself is caused by the shadow terrain being lower detail than the visual terrain, so I could fix it by increasing the shadow terrain detail, but for performance I'd like to keep it as is if possible. The fact that it works initially in the editor suggests that it could work

**Comment by plemsoft** [comment] 2022-02-11 15:04
@PaulSJ Could you forward the test map , thanks :)

**Comment by PaulSJ** [comment] 2022-02-11 15:10
Sent

**Comment by plemsoft** [comment] 2022-02-13 10:08
@PaulSJ Fixed , the problem is when the camera distance is set low like in the test map. FYI: Auto adjust min max z for orthographic shadow matrix, auto dont really work when CameraFAR_f < fShadowFarPlane, i set them by hand when CameraFAR_f is lower then our default setup , but next time we look at shadows we should properly get the auto adjust working :).

@OldFlak This has been fixed and will be in the next update , FYI: you are loosing some shadows when you set the camera distance so low (but it will now work) i suggest that you set the camera distance around 30 for this level, so you dont loose some of the shadows from nearby terrain :)

**Comment by plemsoft** [comment] 2022-02-14 16:25
@OldFlak We are currently optimizing the different settings , could you let me know your fps on this level in graphics quality "Test Level High","Test Level Medium" and "Test Level Low" , Thanks that would really help me getting it setup :)

**Comment by OldFlak** [comment] 2022-02-14 22:16
@plemsoft Hi Preben did some tests using the same map for the shadow issue.
Here are the settings for the foliage
**Trees**
Palette: two types selected - Pine and Scots Pine 2
Density: 25
Height: 39-70

**Grass**
Palette: three types selected - first three
Density: 50
Draw Distance: 1500

To test I walked up and down the valley - you will find a roughly painted sandy path :)

Results are varied and change often.

**Low**
Occasionally as low as 35
- Average 45- 60
- Often solid 60

**Medium**
Sometimes as low as 33
- Average 35-45
- Sometimes solid 60

**High**
Sometimes as low as 30
- Average 32-45
- Occasionally solid 60 (higher ground)

Hope that helps :)

**Comment by OldFlak** [comment] 2022-02-17 12:24
@plemsoft Just to let you know the shadow issue is fixed - thanks :)

**Comment by plemsoft** [comment] 2022-02-17 12:28
@OldFlak Thanks , and also for the high/medium/low testing :)

**Closed by plemsoft** 2022-02-17 12:28 UTC
Labels: bug, Fixed but need confirmation., Max
