### ISSUE TITLE
GGMax crashes randomly when viewing assets on the library.

### ISSUE THREAD

**Issue by waterdrinkingfox** [TheGameCreators/GameGuruRepo#4185] opened 2023-02-23 03:43 UTC
I think this happens because I've imported GGClassic assets to Max, because I don't recall seeing that before.

**Comment by ZakJudges** [comment] 2023-02-24 09:17
Hi @waterdrinkingfox, which assets from Classic did you import into Max?

**Comment by waterdrinkingfox** [comment] 2023-02-26 17:25
Hello! I've imported all of the assets that comes with Classic, + all the assets from the DLCs that are (were?) on the Humble Bundle.

(Every DLC EXCEPT the Industrial Sewer Pack, Enhanced Weapon Pack (obviously), Furniture Pack, Trees, Plants & Rocks Pack, Camping Pack, Melee Weapons Pack, Walled Garden Pack, and Ancient Treasure Pack)

**Comment by ZakJudges** [comment] 2023-03-03 10:45
Hi @waterdrinkingfox, I haven't been able to reproduce this issue. Does it crash consistently enough for you to be able to record a video of it? That should hopefully allow me to follow your actions and reproduce. Thanks :)

**Comment by waterdrinkingfox** [comment] 2023-03-03 14:04
Seems like it actually isn't random, so my bad on that. I assume it's crashing while trying to load an asset named "AC_System", "AC_withVENTSHAFT" or "Acacia Tree" (these are the assets that you barely see at the end of the video). Also, keep in mind that it doesn't only happen with like one or two assets.
https://user-images.githubusercontent.com/112423658/222736489-d3557eb3-30c1-498e-8c24-5af79ff1046e.mp4

**Comment by Indiemandeceased** [comment] 2023-03-06 22:08
Hi, I can reproduce this in the same way as described for the same reasons (import of GG classic and store items) it appears that the engine crashes during the rasterising(?) Of the PNG image in the asset browser. Unfortunately, the crash seems to wipe any and all changes made up to that point, even if save and save as is used.

**Comment by ZakJudges** [comment] 2023-03-10 10:28
Hi all, thank you for the extra info, I can now reproduce the issue. It is caused by the fact that the files copied across are .X format, not DBO.  

GameGuru Max only supports .dbo files being in the Object Library. We have a tool that converts any old X files to DBO, here is its location:
![Screenshot 2023-03-10 102635](https://user-images.githubusercontent.com/32545391/224292456-e35097f5-9f54-4aef-bfc7-8589771bca2c.png)

After Guru-Converter.exe has been run, you will receive a notification about successfully converting models (it may take a couple of minutes). After this, the crash should not occur.

**Comment by ZakJudges** [comment] 2023-03-10 10:50
Hi @Indiemandeceased, I have not been able to reproduce that issue after using the converter. Are there any specific files that always cause the crash? If so, could you let me know the asset names or email some to zak@thegamecreators.com? Thanks!

After checking, the converter only seems to work on the Max core install, not the writable folder. So if you are bringing Classic assets into Max (and not using the importer), then you should first copy the Classic assets to the Max install location, run the converter, and then move the files to your writable folder.

Re the crash removing all work - could you please send me the fpm in your mapbank folder before and after the crash has occurred? Thank you

**Comment by ZakJudges** [comment] 2023-03-17 11:28
Hi @Indiemandeceased, I have not received the FPM file, it's possible that it was detected as malicious and not sent/automatically deleted. Would you be able to upload a zip of the fpm to Google Drive, or something similar, and then share a link? If possible, it would also be helpful if you could include an object that you suspect triggers the crash. My email is zak@thegamecreators.com. Thank you

**Comment by Indiemandeceased** [comment] 2023-03-17 12:36
Hi Zak,

As soon as I find the same error I’ll resend to you – for now though I have completely removed all assets and I am slowly reimporting using the add assets tool to see if I can spit which ones are causing the issue.

Kind Regards,

Chris.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by plemsoft** [comment] 2023-04-06 08:31
@waterdrinkingfox I believe this has been fixed in the lastest EXP build , just tried copy over all my classic objects 12000+ and no crash , also tried the AC search and no problem it displayed the AC_System object and other. Could you please try this in the lastest EXP build and let me know if its also fixed for you , Thanks for your help :)

**Comment by waterdrinkingfox** [comment] 2023-04-07 10:44
Hello! The issue has been fixed for me by running Guru-Converter, but didn't close this as @Indiemandeceased seems to have a different problem than me, as running the same app as I did didn't work for him.

**Comment by LeeBamberTGC** [comment] 2023-04-07 11:26
@Indiemandeceased Are you still getting this issue?  Preben and I have made fixes in this area for the latest EXP build.

**Closed** 2023-04-13 15:08 UTC
Labels: bug, Fixed but need confirmation., Max, High, CRASH!
