### ISSUE TITLE
Create character hostage with no weapon Problem

### ISSUE THREAD

**Issue by Tam51** [TheGameCreators/GameGuruRepo#3737] opened 2022-09-30 12:16 UTC
Hi There

When I create a character using the Character Creator Plus in GGMax which I assigned no weapon and I want it to be a hostage, the only problem is that it shows a weapon in game every time. I can't find anyway to have the character without a weapon. Character Attack just doesn't show a no weapon option in the Weapon drop down menu as you can see from the two images below. I was wondering if anyone else was having the same problem. 
![Character Attack problem](https://user-images.githubusercontent.com/93008801/193266890-22cc7776-0eef-4f12-a88b-3f8618296b59.jpg)
![Character Attack Problem 2](https://user-images.githubusercontent.com/93008801/193266922-bf025f11-875c-4639-8855-97a693814231.jpg)

**Comment by Tam51** [comment] 2022-09-30 14:17
Hi There With a lot of faffing around with the character FPE file I got it to work. I had to change the character FPE to the following: 
aimain           = people\hostage_runs_away.lua
voice            = Microsoft Hazel Desktop - English (Great Britain)
speakrate        = 0
soundset         = audiobank\characters\human\female\sfx_female_hurt_1.wav
soundset1        = audiobank\characters\human\female\sfx_female_hurt_4.wav
soundset2        = audiobank\characters\human\female\sfx_female_punched_2.wav
soundset3        = audiobank\characters\human\female\sfx_female_punched_4.wav
hasweapon        =

 I shouldn't have to do this after I have created a character without a weapon using the Character Creator in GGmax. This was the only way I could get to work.

**Comment by ShadowMasterOfGames** [comment] 2022-10-05 20:23
That goes with my bug report #3697  like I said in my post, hostage behavior is not working and I cannot make a video but thank God that Tam51 is also having this issue as well.  

@LeeBamberTGC if you want me to send all my custom stuff to so you can test my level (which you already from the collision issue) let me know. I cannot do anything on that level because of the crappy Frame rate per second maybe one of your teammates can look into the fps issues or can at least reproduce the hostage behavior issues

**Comment by LeeBamberTGC** [comment] 2022-10-29 15:58
@ZakJudges May be character creator related

**Comment by ZakJudges** [comment] 2022-12-08 11:35
Hi all, this should be fixed in the next experimental update. 

The hostage did not animate correctly because they still had their weapon "attached" to them, causing the wrong animation set to be loaded for the character - as was pointed out in the above post, you cannot select "No Weapon". 

I have added a dropdown to the Character Creator to allow you to specify the character's behavior, as well as being able to specify No Weapon - however, be advised that your choice cannot always be carried out. E.g. you cannot have a "Character Attack" behavior attached with No Weapon, and so your Character Creator choice would be overridden here.

Additionally, I have added a new script description field called < Unarmed >. If this is detected in the description of a Lua script, then it will remove any weapons that the character may have. For now, it is in the hostage script only, but it may be the case that it is required in other scripts as well. If you continue to experience the problem in other scripts, please let me know and I will take a look. Thanks :)
![Screenshot 2022-12-08 112709](https://user-images.githubusercontent.com/32545391/206436342-a9ab3dfb-c991-4a82-9695-afa7bd12b6d4.png)

**Closed** 2023-02-16 09:40 UTC
Labels: bug, Fixed but need confirmation., Max, Medium, Character Creator
