### ISSUE TITLE
MAX bug ( blood does not turn off )

### ISSUE THREAD

**Issue by bluemeenie195** [TheGameCreators/GameGuruRepo#2783] opened 2022-04-08 12:36 UTC
https://youtu.be/6vdticAb33w

**Comment by dllllllllllb** [comment] 2022-04-12 14:09
@LeeBamberTGC The "Blood Effects" setting in characters developer settings doesn't do anything from what I can tell. However there is a Blood Effects setting in the Player Start Position marker that works as intended.
 
I think the character setting gets overridden by the Player Start Position setting. It also makes no sense to tick off every single character in the level to get rid of blood effects, using one setting in the Player Start Position marker is a lot more convenient.

Should I comment out the "Blood Effects" setting on characters as it doesn't do anything for the character nor the player?

**Comment by plemsoft** [comment] 2022-05-02 09:33
@bluemeenie195 Thanks for reporting this issue, this has been fixed and will be in the next update :)

**Closed** 2022-05-11 14:27 UTC
Labels: bug, Fixed but need confirmation., Max, Medium, Characters
