### ISSUE TITLE
GGMAX - BUG - Player Characters Hands and Gun Stretching Issue

### ISSUE THREAD

**Issue by ZD-ZMA** [TheGameCreators/GameGuruRepo#5485] opened 2024-04-28 15:05 UTC
hands and gun stretching towards the middle of the level, into the ground. at first i thought it was just the weapon, but after further tests, i found it to be any weapon... it happens the first few load attempts of the current session.

i recorded a video on it but found i was unable to post it to github. i will instead upload it to youtube as a private/link only video and ill share the link as soon as i can.

**Comment by ZD-ZMA** [comment] 2024-04-28 15:08
https://youtu.be/olnK-DEthQE

this is the video. i explain my thoughts on it, although i did more testing afterwards which i mentioned in my original comment.

**Comment by DBird-1994** [comment] 2024-04-28 16:12
Just want to confirm that it's happening to me too.  Sometimes it will randomly go away and fix itself, but usually not.

https://github.com/TheGameCreators/GameGuruRepo/assets/136038988/0d9e57b8-0d9b-42e3-b8bc-a2d0bafd4c51

**Comment by ZD-ZMA** [comment] 2024-04-29 01:28
> I just tried this with the exact setting you did and had no problems, just out of interest what graphics card do you have and do you have any particular settings in the graphics optimizations on.

default settings. changing settings still causes this. 

cpu   amd ryzen 5 5600 6-core

gpu   amd radeon rx 6500 xt

this has only been a problem recently. since the last update or the one before it. 

(february and most of march i had no internet so if there was an update during that time, i wouldnt have known)

**Comment by ZD-ZMA** [comment] 2024-04-29 01:32
> Just want to confirm that it's happening to me too. Sometimes it will randomly go away and fix itself, but usually not.
> 
>  gunglitch.mp4

glad to know im not the only one with  this bug. alot of the times i have bugs, i get called a liar because im the only one with some of these bugs and because of that, alot of the bugs i report never get addressed. its why i dont report bugs that much. i get alot of crap from people and its frustrating as hell. 

are you using amd as well?

asking because someone mentioned it might be the graphics card.

**Comment by DBird-1994** [comment] 2024-04-29 01:50
I noticed this started happening after the last few updates where the new performance options were added.  No, I'm not using AMD here, I have an Nvidia RTX 2060.

I notice the gun glitching out on NEW levels, but it doesn't seem to happen on some of my old saved levels.  But it happens on a NEW level every single time using the default settings.  Changing the graphics options seems to help a little, but doesn't make the problem go away completely.

**Comment by Necrym59** [comment] 2024-04-29 02:16
I have a nvidia 3080 and tried it on new and old maps without a problem so its very odd, all i can suggest is check the video drivers and do a steam verify on max and see if that helps. If not it will be somthing Lee will have to look into.

**Comment by DBird-1994** [comment] 2024-04-29 02:39
Ok, so I found a solution to the gun glitching out on new levels.    This is bizarre, but simply adding any character to the level fixes it.   You can then delete that character if you want, the gun glitching will be gone.  

This solution works for me.  @ZD-ZMA I'd be interested to know if this works for you as well.

**Comment by ZD-ZMA** [comment] 2024-04-29 05:42
> I have a nvidia 3080 and tried it on new and old maps without a problem so its very odd, all i can suggest is check the video drivers and do a steam verify on max and see if that helps. If not it will be somthing Lee will have to look into.

i did that already. didnt change anything

**Comment by ZD-ZMA** [comment] 2024-04-29 05:44
> Ok, so I found a solution to the gun glitching out on new levels. This is bizarre, but simply adding any character to the level fixes it. You can then delete that character if you want, the gun glitching will be gone.
> 
> This solution works for me. @ZD-ZMA I'd be interested to know if this works for you as well.
![Screenshot (152)](https://github.com/TheGameCreators/GameGuruRepo/assets/124307560/e0fc3903-b1f3-4e69-926d-f50e857e3503)
nope, still happening

**Comment by ZD-ZMA** [comment] 2024-04-29 05:50
i just want to point out, this only happens during testing. it doesnt happen when you save as a standalone and play the standalone version.

**Comment by Kraven3D** [comment] 2024-04-29 09:57
@Necrym59, was just about to report this myself. And it's not just weapons, certain character animations are doing it, too:

https://github.com/TheGameCreators/GameGuruRepo/assets/160327315/47f6ab47-5bfe-4ff5-9d04-9dd57c088eef

RTX 3060 btw. Never had any issues like this before with it, or my previous 1060. Started happening after the 04/11 update.

**Comment by PetrNaj** [comment] 2024-04-29 23:06
RTX 2060. It's happening to me too. Only in the editor. Standalone is without problems.

**Comment by ZD-ZMA** [comment] 2024-05-04 13:00
> RTX 2060. It's happening to me too. Only in the editor. Standalone is without problems.

same for me. only in editor, not through standalone

**Comment by LeeBamberTGC** [comment] 2024-05-06 13:57
@ZD-ZMA I have created a new issue that will perform the work to update and move the Building Editor source into the main MAX repo so that these and other changes can be applied: https://github.com/TheGameCreators/GameGuruRepo/issues/5518

**Comment by LeeBamberTGC** [comment] 2024-05-06 14:00
@ZD-ZMA Can you try with AMD driver version 23.3.1. I have a test AMD card In right now and they introduced some rather nasty code after this version into their driver that actually crashes my card completely.

**Comment by fearlesswee** [comment] 2024-05-22 12:16
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/56294129/ba9c380e-ec32-4852-8de4-136785c80ac9)

Also getting this too, RTX 3050. No issues of any sort with other games, or earlier MAX versions, so it's not a card/driver issue.

Original post (closed as a duplicate):

"Sometimes, regardless of weapon or hand choice, the player's hand will stretch infinitely long for a single frame, before returning to normal. This doesn't seem to happen with "legacy" weapons where the hands are a part of the weapon itself (i.e. the sci-fi weapons from the TGC Store do not have this issue.) so I presume it may have something to do with the new player hands system miscalculating a bone position or so."

**Comment by synchromesh62** [comment] 2024-05-27 01:49
I did not get this either initially
However since i installed the new **medieval weapons pack** i get the glitching 
I uninstalled it ... restarted Mx and now its gone. 
Can we confirm we all have the new melee pack installed as i think it might be the cause ?

**Comment by ZD-ZMA** [comment] 2024-05-27 06:46
> @ZD-ZMA Can you try with AMD driver version 23.3.1. I have a test AMD card In right now and they introduced some rather nasty code after this version into their driver that actually crashes my card completely.

sorry for the late response. been dealing with some irl issues. ill take a look at it and try

**Comment by ZD-ZMA** [comment] 2024-05-27 06:48
> @ZD-ZMA Can you try with AMD driver version 23.3.1. I have a test AMD card In right now and they introduced some rather nasty code after this version into their driver that actually crashes my card completely.

ill downgrade for now, but will this issue be fixed in the future for updated drivers?

**Comment by ZD-ZMA** [comment] 2024-05-27 06:49
> @LeeBamberTGC I did not get this either initially However since i installed the new **medieval weapons pack** i get the glitching I uninstalled it ... restarted Max and now its gone. Can we confirm we all have the new melee pack installed as i think it might be the cause ?

i dont have any one the weapon dlc. i wish i did. lol

**Comment by ZD-ZMA** [comment] 2024-05-27 06:55
> @ZD-ZMA Can you try with AMD driver version 23.3.1. I have a test AMD card In right now and they introduced some rather nasty code after this version into their driver that actually crashes my card completely.

i can confirm that this issue still happens even after i downgrade my driver. (also i restarted my pc just in case and still a no go)

**Comment by synchromesh62** [comment] 2024-05-27 09:14
> > @LeeBamberTGC I did not get this either initially However since i installed the new **medieval weapons pack** i get the glitching I uninstalled it ... restarted Max and now its gone. Can we confirm we all have the new melee pack installed as i think it might be the cause ?
> 
> i dont have any of the weapon dlc. i wish i did. lol

Ok thanks .. That's that idea out the window then :)
Must be something else but i re-installed again to double check and for me the Glitching returns. 
Im on a Nvidia GTX1080 so perhaps my glitching with this pack is caused by something entirely different.

**Comment by DBird-1994** [comment] 2024-05-27 15:11
@synchromesh62 @LeeBamberTGC I have the medieval pack also, but it makes no difference to me if I uninstall it.   What I did find is that if I roll back to the 2024.03.01 build the glitching is completely gone.  So it seems something has changed between March 2024 and now that is causing the gun glitching.

**Comment by synchromesh62** [comment] 2024-05-28 00:08
Its so strange .. There does not seem to be a common factor that stands out ?
I use stock and its fine ... Then i add the dlc. Once i select the Long sword it all kicks off and then the majority of my weapons do it until i uninstall the pack and restart.

![1](https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/4bc0dd31-ac3d-4ce5-b9b7-c0242e22bf49)

![2](https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/61938b0b-03aa-41f5-8a17-5bfd4db84d10)

**Comment by ZD-ZMA** [comment] 2024-06-02 05:34
> Its so strange .. There does not seem to be a common factor that stands out ? I use stock and its fine ... Then i add the dlc. Once i select the Long sword it all kicks off and then the majority of my weapons do it until i uninstall the pack and restart.
> 
> ![1](https://private-user-images.githubusercontent.com/35708217/334229858-4bc0dd31-ac3d-4ce5-b9b7-c0242e22bf49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMDY2NjUsIm5iZiI6MTcxNzMwNjM2NSwicGF0aCI6Ii8zNTcwODIxNy8zMzQyMjk4NTgtNGJjMGRkMzEtYWMzZC00Y2U1LWI5YjctYzAyNDJlMjJiZjQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDA1MzI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyOGYwMzQ2YjBiNWYzMmI1OGYxODM1OTZmOTM3NTI4ZGE0MmU1ZDJkMmUwZTliNWFjZDU2YTA2NjhhZDU1ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.frQd7GLOV9cqe7dqsZ_DqE4wxOQCcTaphvxOLR0Kg1k)
> 
> ![2](https://private-user-images.githubusercontent.com/35708217/334229882-61938b0b-03aa-41f5-8a17-5bfd4db84d10.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMDY2NjUsIm5iZiI6MTcxNzMwNjM2NSwicGF0aCI6Ii8zNTcwODIxNy8zMzQyMjk4ODItNjE5MzhiMGItMDNhYS00MWY1LThhMTctNWJmZDRkYjg0ZDEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDA1MzI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwNzcxOGRjMGU1NjFmZTg5Y2I5NjExNTdkZWViNDYwMDIzYmUxZDc5MDRiNmIwZTI2N2Y2YTNhMjUwNDIzODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eJ1zzK1FnJEmm9LlIG9By8vvro-VpvQ7yiGVuW0lQs0)

i dont have any DLC weapons. this happens with stock weapons for me.

**Comment by synchromesh62** [comment] 2024-06-05 00:05
Well it was only a theory at the time if we all happened to have the DLC as a common factor.
LOL .. Whilst your trying to get rid of the issue with stock assets I'm trying my hardest to get it :)

**Comment by ZD-ZMA** [comment] 2024-07-07 08:34
> Well it was only a theory at the time if we all happened to have the DLC as a common factor. LOL .. Whilst your trying to get rid of the issue with stock assets I'm trying my hardest to get it :)

a month has gone by. have you been able to recreate this?

**Comment by LeeBamberTGC** [comment] 2024-07-08 10:05
@ZD-ZMA I have been unable to reproduce so the issue is marked as more info needed at this time. There is a new update out soon (for EXP) so you are welcome to try that when it comes out as we may have nudged something to correct this issue, which I assume was introduced in the June public update.

**Comment by ZD-ZMA** [comment] 2024-07-17 20:43
> @ZD-ZMA I have been unable to reproduce so the issue is marked as more info needed at this time. There is a new update out soon (for EXP) so you are welcome to try that when it comes out as we may have nudged something to correct this issue, which I assume was introduced in the June public update.

sorry for the trouble

**Closed** 2024-10-10 23:26 UTC
Labels: bug, Max, Waiting for more information., Medium, Visual Quality

**Comment by ZD-ZMA** [comment] 2025-01-28 00:29
i wanted to mention that i havent had issues with this bug for awhile. it seems to be fixed
