### ISSUE TITLE
Cyberpunk dlc Broken in both retail and EXP

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#5246] opened 2024-02-10 17:02 UTC
As stated 
The Cyberpunk dlc Broken in both retail and EXP.
The retail has no emissions from the wall lit posters but does run.
On the EXP it crashes on start and the wall lit posters have no emissions, or animations.

Not worried about the EXP so much but doesn't look good for the retail purchasers although it will probably be a one fix does all.

**Comment by DBird-1994** [comment] 2024-02-10 17:12
Yes I can confirm it happens to me as well. Video clip of the problem on EXP build - no emissive or animations on the billboards:

https://github.com/TheGameCreators/GameGuruRepo/assets/136038988/92d47c42-dcc4-44a0-a9f3-76a70c3116a2

**Comment by davetgc** [comment] 2024-02-11 12:11
@LeeBamberTGC - This one looks urgent.

**Comment by Necrym59** [comment] 2024-02-12 06:46
The test map needs the bahavior reaplied to the map.

**Comment by davetgc** [comment] 2024-02-12 08:32
@Necrym59 - Thanks, but I'm not sure that explains the crash.

**Comment by LeeBamberTGC** [comment] 2024-02-12 12:14
@synchromesh62 It was due to a script change. New one attached here (and will be in next EXP build):
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/df0a9ea6-273a-4b8f-b366-6a9253741bd7)

I could not reproduce a crash when loading the Cyberpunk Streets level, but did encounter a script error related to nil values in the emissive fields in the level.

[change_texture.zip](https://github.com/TheGameCreators/GameGuruRepo/files/14238214/change_texture.zip)

**Comment by Necrym59** [comment] 2024-02-12 20:41
Lee you beat me to it, yep its fixed

**Closed** 2024-02-13 10:41 UTC
Labels: bug, Fixed but need confirmation., Max, High
