### ISSUE TITLE
A problem with the normal maps?

### ISSUE THREAD

**Issue by earthling45** [TheGameCreators/GameGuruRepo#719] opened 2020-03-24 15:13 UTC
![aGCJzgH 1](https://user-images.githubusercontent.com/35744254/77440980-39a2ce80-6de9-11ea-9bda-147885bb2481.jpg)
https://i.imgur.com/aGCJzgH.jpg

It looks very flat in the latest build compared to the earlier version.
Also, as Kitakazi already mentioned in the other issue topic, there is indeed also a problem with texture tiling on terrain.

![lines2](https://user-images.githubusercontent.com/35744254/77441870-3c51f380-6dea-11ea-85df-632cd5558f8e.jpg)

**Comment by synchromesh62** [comment] 2020-03-25 02:36
@LeeBamberTGC 
@plemsoft 
Detailed explanation and pics above

**Comment by LeeBamberTGC** [comment] 2020-03-25 02:45
@synchromesh62 I want to get the old bugs fixed before classifying new ones, otherwise it's like filling up a bath with a hole in it :)  Once all the classic bugs have been sorted, we can go through the reports from March and set the bug label. I do of course welcome help in getting them ready for easy reproducible status as that saves me OODLES of time, thanks!

**Comment by earthling45** [comment] 2020-03-25 05:50
Hi Lee,

I was kind of hesitating to be posting this issue because there is obviously already work being done in this area.
But i posted it because maybe it is viable info for the bug fixing this month. :)

**Comment by LeeBamberTGC** [comment] 2020-03-25 09:40
It's fine, and will be fixed. I just wanted to have a dividing line so I can say we fixed all bugs reported up to the start of the bug fixing work. A nice little feel-good news piece for GameGuru users.

**Comment by earthling45** [comment] 2020-03-25 11:51
Understood, thanks Lee. :)

**Comment by synchromesh62** [comment] 2020-03-25 11:53
@LeeBamberTGC 
Understood , I did wonder about that myself :)
I will ensure no new ones get marked as bugs for the time being :)

**Comment by LeeBamberTGC** [comment] 2020-04-03 00:21
@earthling45 The issue you are comparing from 2018 and the Christmas update will be related to the addition of the Sun Factor slider which allowed control over the strength of the normal mapping against the sun light direction. See my shots on how this is controlled, and is the intended functionality of the engine:

![image](https://user-images.githubusercontent.com/35840583/78311553-1692c000-7549-11ea-90ca-3fbd51587876.png)

I have also attached a shot of the default terrain floor just in case you can see seams that I cannot (attached). 
![MyStockFloor](https://user-images.githubusercontent.com/35840583/78311647-522d8a00-7549-11ea-92e9-4598ef039e66.jpg)

If you can provide a stock FPM, and a start marker so I know where to point the camera to see the seam issue you describe, I can look at this again.  I am using the latest PP build out Friday,

**Comment by earthling45** [comment] 2020-04-03 00:52
Hi Lee, thanks for looking into this. :)
I've made an FPM and put some firewood where you can see these seams, see this picture.
![example](https://user-images.githubusercontent.com/35744254/78312966-a2124e00-7555-11ea-9541-fac05cd8a2a5.jpg)
What i did is paint a texture from slot 1 and marked the spots with firewood as seen in the texture.

[fpm map.zip](https://github.com/TheGameCreators/GameGuruRepo/files/4424468/fpm.map.zip)

**Comment by earthling45** [comment] 2020-04-03 00:55
I also feel a bit dumb now because i had not thought of the sun factor slider.. sorry for that Lee.

**Comment by LeeBamberTGC** [comment] 2020-04-03 02:02
No worries, new PP build uploaded :)

**Closed by LeeBamberTGC** 2020-04-03 02:02 UTC
Labels: Need explanation, bug
