### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by Denis87z** [TheGameCreators/GameGuruRepo#4300] opened 2023-03-24 14:20 UTC
![image](https://user-images.githubusercontent.com/89519185/227549448-3ef5185e-84ba-4497-b40e-eef2c5d4e1de.png)

**Comment by ZakJudges** [comment] 2023-03-24 15:51
Hi @Denis87z, I could not reproduce this issue. Did add the Flame Light behavior to a light, or a regular object? Thanks :)

**Comment by plemsoft** [comment] 2023-04-05 09:46
@Denis87z Yes i think somehow your level got corrupted , as you say "models huddled together", If you could e-mail me the level .fpm that have this issue ,i would be able to check what went wrong with the level. e-mail: plemsoft@gmail.com
Also i was not able to reproduce this. and do not think its a Lua error but something else , i will close this issue, but please do e-mail me the corrupted level so im able to see the original problem, Thanks for your help :)

**Closed by plemsoft** 2023-04-05 09:46 UTC
Labels: bug, Fixed but need confirmation., Max, High, LUA
