### ISSUE TITLE
collision issues

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#3127] opened 2022-05-14 21:24 UTC
hello!

I've angled this model (highlighted) and its completely  messed up  the collisions.

![image](https://user-images.githubusercontent.com/68471279/168448589-4876e1d7-74f7-4e83-8c9d-14c146ef09b0.png)

**Comment by casigus** [comment] 2022-05-14 21:25
![image](https://user-images.githubusercontent.com/68471279/168448600-6a61c873-5e24-40ab-bc60-0eb92706ba43.png)

**Comment by Ghost-l0l** [comment] 2022-05-15 08:06
I can confirm this one, It happens also with simpler objects like rocks (it was happening to me when I was building grand canyon level - when I was turning rocks upside-down collision wasn't adjusted to model's rotation), and with different collision types, like convex hull or hull decomp

**Comment by casigus** [comment] 2022-05-16 14:46
yes ill grab the  model now!

**Comment by Ghost-l0l** [comment] 2022-05-19 07:55
![rock](https://user-images.githubusercontent.com/101792609/169241496-22c314ca-96c6-473a-bb40-78252cf0eb4d.jpg)

@LeeBamberTGC Its this rock - I got it from sketchfab, and imported with Max's impoter. When placed normally - it works; but when placed upside-down - collision is a bit off and the more you change the scale the more broken collision is. Its like that for both convex hull and hull decomp.

**Comment by AmenMoses** [comment] 2022-05-19 16:28
#2279

**Comment by LeeBamberTGC** [comment] 2022-06-21 11:11
@Ghost-l0l Am able to reproduce with your instructions, thanks:

![image](https://user-images.githubusercontent.com/35840583/174786085-9eea81b3-536f-460e-a380-94544a956b94.png)

I will see into it now :)

**Comment by ZakJudges** [comment] 2022-12-05 10:32
Hi all, closing this issue as it seems to be fixed. If the problem persists, feel free to reopen. Thanks

**Closed by ZakJudges** 2022-12-05 10:32 UTC
Labels: bug, Fixed but need confirmation., Max, High, Physics
