### ISSUE TITLE
inventory doesn't work

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#4420] opened 2023-04-07 13:55 UTC
inventory no longer works when you take things no longer put them there

**Comment by SampeyFS** [comment] 2023-04-07 15:01
Básicamente son las llaves que no están en el inventario. Sucede algo extraño. Pongo la puerta para que se abra con la llave. Intenta abrirla. Cierra. Es el guión de la llave.

**Comment by SampeyFS** [comment] 2023-04-07 15:16
![20230407171149_1](https://user-images.githubusercontent.com/108415264/230633110-5c63b6ad-aa96-4b4f-9740-5218e6d70b6c.jpg)

as you see the Door was opened and closed by taking the key and the key is not put in the inventory

**Comment by Necrym59** [comment] 2023-04-08 10:30
Inventory works.... the 'Key" script hasnt ben updated to put the key into the inventory yet.

**Comment by davetgc** [comment] 2023-04-09 17:02
Closed as not a bug, but an incomplete feature.

**Closed by davetgc** 2023-04-09 17:02 UTC
Labels: Answered
