### ISSUE TITLE
When "force = x" is added to a gunspec file the amount of force is also applied to the player when the weapon is fired.

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#670] opened 2020-01-08 19:44 UTC
The amount of force applied is still correctly applied to the entity the bullet hits but it also applies the force to player. 

 It is very annoying especially with weapons that one would want a high force with such as a shotgun. Automatic weapons are just as bad even with a low force as it is constantly applied, pushing the player, usually at a kinda weird angle backwards. 

This bug affects all the weapons in the Enhanced Weapon Pack and probably all other weapons too once "force = " is added to gunspec line.

It's possible that enableplrspeedmods = 1 must also be set.

**Comment by synchromesh62** [comment] 2020-02-08 14:16
@LeeBamberTGC 
@plemsoft 
I was unable to reproduce this error

**Comment by Kitakazi** [comment] 2020-02-08 17:03
@LeeBamberTGC
@plemsoft 
@synchromesh62 
 https://www.youtube.com/watch?v=NSQ6W5c6hl8&feature=youtu.be

**Comment by Kitakazi** [comment] 2020-02-08 18:07
For the video I set force = 250 in the gunspec.

**Comment by synchromesh62** [comment] 2020-02-08 21:14
Excellent thanks … 
and that is why videos help so much … It sounded like the player was thrown back violently and I tested for that whilst in normal gameplay. That's all Lee and Preben need to see ..Thanks Kitakazi

**Comment by plemsoft** [comment] 2020-03-20 06:37
@Kitakazi Thanks for reporting this, This has been fixed and will be in the next update :)

**Comment by LeeBamberTGC** [comment] 2020-03-23 18:07
Confirmed as fixed

**Closed by LeeBamberTGC** 2020-03-23 18:07 UTC
Labels: bug, fixed
