### ISSUE TITLE
( GameGuru MAX - Bug ) problems makes the custom texture feature not working or useless :(

### ISSUE THREAD

**Issue by Nader-B10** [TheGameCreators/GameGuruRepo#3972] opened 2022-12-16 04:15 UTC
when I paint an area with the custom texture and save the changes at the level, then close GameGuruMAX, and when I run it again, I see that the custom texture has been replaced in the area which it was painted with the default texture of the GameGuruMAX

**Comment by ZakJudges** [comment] 2022-12-16 09:32
Hi @Nader-B10, I wasn't able to reproduce this issue. Have you updated GameGuru Max on Steam? This was an old bug that should be fixed now. 
If you continue to experience the issue, would you be able to show a video? That might allow me to follow your steps to reproduce and find a fix. Thanks!

**Comment by ZakJudges** [comment] 2022-12-16 10:28
@Nader-B10 It's also worth checking the properties of GameGuru MAX in your Steam library, and making sure that you are not using a previous build. In the betas section, the most up-to-date builds are "None", "experimental" and "publicpreview"
![Screenshot 2022-12-16 102714](https://user-images.githubusercontent.com/32545391/208078492-d1819fdd-8537-46c8-948d-c52a41b4386f.png)

**Comment by Nader-B10** [comment] 2022-12-16 17:57
Since I started using the feature of changing the texture folder to use a custom texture, and until today I am facing the same problem... and yes, I am using the latest experimental version and I am sure of that... I check daily for any update and update it...

I can't show you any video right now but as soon as I get home from my job I will

**Comment by OldFlak** [comment] 2022-12-17 07:08
Not tested completely but I think because max is mixing up the order of the tiles in the editor he may just be painting the wrong texture - see #3979

**Comment by ZakJudges** [comment] 2023-02-03 13:12
Hi @Nader-B10, are you continuing to experience this issue? If so, could you please send a video of the texture folder being changed, followed by the issue. Can you also please send the custom textures you are using to zak@thegamecreators.com? That should allow me to reproduce the issue and find a fix. Thanks :)

**Closed** 2024-09-13 16:18 UTC
Labels: bug, Fixed but need confirmation., Max, Waiting for more information., High, Terrain
