### ISSUE TITLE
GGMAX Bug - Navmesh for a modular level is generating in the space above the meshes, not inside where its supposed to be

### ISSUE THREAD

**Issue by mav3r1ck1981** [TheGameCreators/GameGuruRepo#5748] opened 2024-09-24 13:08 UTC
A picture paints a thousand words...................................

![image](https://github.com/user-attachments/assets/4524ffb0-d573-40a9-8b89-218c1850b060)

As you can see, the navmesh has generated, but not inside the assets, rather directly above them where the AI cant access them. Not only that, it appears to have doubled the generation to include the roof/ceiling as well as the floors.

![image](https://github.com/user-attachments/assets/be7fefb4-7223-4a5b-971f-dcc2fd289119)

Obviously, I cant use this level with any form of NPC. This is different but may be associated with my previous post concerning navmesh not being generated on complicated levels, but the interior of these sections is significantly simplified:

![image](https://github.com/user-attachments/assets/f8e97f54-5f82-4b7e-a85c-0488b90c50fd)

any help gratefully recieved

**Comment by Kitakazi** [comment] 2024-10-01 20:41
I've also noticed alot of issues with the Navmesh recently. Area's characters should be able to move across, the navmesh just isnt generating for those areas. It's actually really bad at the moment.

**Comment by Kasseyus** [comment] 2024-10-04 08:56
@mav3r1ck1981 I've been trying to re-create this issue, but so far, the Navmesh system is behaving itself..

In order to narrow this down, can you please let me know what version you are currently running (DevTest, Experimental, Standard).

Also does this happen every time, or is it only showing up sporadically?

@Kitakazi Same Question :)

**Comment by mav3r1ck1981** [comment] 2024-10-04 09:51
![image](https://github.com/user-attachments/assets/9cc12c19-3d5b-4fce-9dd9-2fb9a9e94731)

![image](https://github.com/user-attachments/assets/b880f5b0-8997-4411-b87c-e76a4f4c7ee5)


I dont think i have a single level where theres not some issue with the navmesh. most if not all of my levels are made form modular sections ie, prefab rooms and corridors, i need to do some testing and see if it occurs when a room is generated from individual walls etc,

Im on EXP as standard, with occasional bouncing to DEVTEST, spec as follows:

13th Gen Intel(R) Core(TM) i9-13900K   3.00 GHz
128Gb DDR4 Corsair Vengeance
GeForce RTX 4090

**Comment by Kasseyus** [comment] 2024-10-04 11:01
@mav3r1ck1981 The screenshots are quite dark, it's a little hard to see what's going on.

Are those BE buildings, or individual entities like the ones from the Offworld Station?  Also, are they stock  or custom  imports?

**Comment by mav3r1ck1981** [comment] 2024-10-04 11:22
those are prefab rooms, ie, individual walls/floors/ceiling etc put together in blender and exported as  a single entity before importing into max as a single room. Everything is custom, i dont use stock other than some props. Same level below, albeit it lightened up 

![image](https://github.com/user-attachments/assets/d356f0f8-fd99-4b69-b982-c336f96e5744)

![image](https://github.com/user-attachments/assets/54940dfb-81d2-4aed-867d-e31e10b29a0f)

![image](https://github.com/user-attachments/assets/06a53886-3e21-41ba-b56b-da2409cf5e8c)

![image](https://github.com/user-attachments/assets/95dc0b22-75f6-46b5-a2a7-337b7788fc9a)

![image](https://github.com/user-attachments/assets/834700be-a9e3-4f31-acef-f4b26e008cd2)

![image](https://github.com/user-attachments/assets/28586429-d41c-40ec-b09e-17d5eebc9757)

**Comment by Kasseyus** [comment] 2024-10-04 11:48
@mav3r1ck1981 Can you  please send me a couple of those entities at chris@thegamecreators.com so I can take a closer look.

**Comment by Kitakazi** [comment] 2024-10-04 15:53
I'm on the EXP version currently. 
Issue happens for me most notably when working on interior levels. It doesn't matter if the level is like a completely closed in interior, like a corridor or hallway. Or something like a cave where the "walls" and ceiling might be made of individual wall entities and the floor itself is made from the Terrain editor.  Because at first I thought it was something with the floor models. But no, recently when this has happened I removed the floor entities and raised the terrain to be the floor, just for testing. And it never generated the nav-mesh correctly.  I noticed if I raised the height of the ceiling, at some point the navmesh would generate better. It wasnt even close to perfect, but it would generate .. more correctly..
That doesn't happen everytime with the ceiling, sometimes in massive rooms the navmesh just didnt generate. And sometimes if I have a floor that is made from 2 different floor entities, the navmesh just wont generate on one side. 

When Maverick said "I dont think i have a single level where theres not some issue with the navmesh." This is honestly the truth and I feel like it's been getting worse and worse.

**Comment by Kasseyus** [comment] 2024-10-07 15:27
@mav3r1ck1981 Would you be able to create a short video, showcasing the issue and the steps leading up to it; it may assist my efforts to reproduce it.  

So far, I've not managed to re-create the issue.

**Comment by mav3r1ck1981** [comment] 2024-10-07 16:31
https://www.youtube.com/watch?v=Zfb7IEDy2FA

@Kasseyus so originally i made this section of tunnel as one piece,  the split it into 2 sections do reduce the polygon load (though it doubles the draw calls) Each section is approx. 36k tris. 

New project>new blank map> dropped to sections of the same tunnel, similar architecture, and load. section 1 works as you would expect, section 2, the navmesh generates directly below the physical mesh. This is with simply geometry, the complex and higher poly sections generate even worse problems.

Because of the difficulty in getting custom characters into max using the Max Rig, the vast majority of us are limited to using Necryms brilliant NPC controller. With the significant navmesh issues, the script throws up an error 6 out 10 times at last test, which leads to not only the affected NPC stopping working, but any and all clones of that NPC (due to the heavy setup of the npc script, cloning them is faster that setting all up individually) CC created characters or stock, dont throw up an error, but they are unable to move around the level, so you can pick them off very easily  and makes for boring gameplay.

This coupled with multiple crashes when moving round the editor and/or saving (17 in 2 hours), particles not working, HUD screen videos not looping when the loop button it ticked, storyboard screens maxing out at 50, all import menus in the editor having shifted to the right so that no controls are on display (you can see this in the attached video) random issues with global lighting suddenly appearing during saves.........................im pretty fed up. What's worse is that some of these only appear to be affecting me no matter how many verifies and clean installs i do. Yes, i should report these properly on github, and i will when the frustration dies down. Prior to release, Max was probably the most stable id experienced and i was making strides in my project. Now? Its basically a hot mesh, for me at least.

I dont think its my PC spec, but somethings affecting my copy:

13th Gen Intel(R) Core(TM) i9-13900K 3.00 GHz
128Gb DDR4 Corsair Vengeance
GeForce RTX 4090


Sorry for the rant, but you touched a nerve ;)

**Comment by Kasseyus** [comment] 2024-10-10 14:14
@mav3r1ck1981 Thanks for sending those assets.  I can see the issue in action now and we should be able to find a solution for this.  The particle issue has already been replicated, so we should be able to get that one sorted soon.

The reproduction of bugs is s one of the hardest parts of this process, so once we get that bit sorted, the fix usually comes quite quickly - which is what I'm here to help with :)

It appears the root cause of the problem is in the models, and how they are used by MAX.  I had a look at the .blend files and the scale and rotation were not normalised...this can cause issues during the import process.    (a clean FBX export should have zeros on the rotation and scale factors.)

I'm not sure what tools/methods you have used to export the file from Blender and import into MAX and there are many ways this could have been done.,   It is different though, as our results were not identical.  For example, your models appear to have 2-sided polygons, and mine were  only 1-sided.  They were also different sizes; I had to scale mine down to match yours - which is the opposite as I would have expected with a  blender scale factor of 0.010.

I grabbed a short video of a comparison of the two meshes.

Video of Difference:
https://github.com/user-attachments/assets/7902f861-5aee-4324-89dd-d693b2f1d190

Can you talk me through your process for exporting and importing and we may be able to see where the issue is creeping in.  On the one I did, I loaded the blend file up into Blender 4.2, reset all of the transforms and then exported as FBX - this was then imported into MAX the usual way.  The resultant model was able to generate a Navmesh correctly.

**Comment by mav3r1ck1981** [comment] 2024-10-13 20:57
![image](https://github.com/user-attachments/assets/b103f3f2-7ab2-44fe-a3c8-ef9a91d70739)
I can confirm that re-importing after setting scale/rotation and location and applying them allows for the navmesh to be regenerated correctly. Appreciate you looking into this.

Ive been using an exporter addon/plugin for blender as part of my recent workflow, rather than stock and whilst i thought these were taken care of automatically, it appears thats not the case

**Comment by Kasseyus** [comment] 2024-10-16 23:11
@mav3r1ck1981 Happy to help :)

**Closed by Kasseyus** 2024-10-16 23:11 UTC
Labels: bug, Max, Waiting for more information., Medium, Collisions and Navmesh
