### ISSUE TITLE
[Max][Crash] The memory could not be read. Crash when attempting to open a level. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#3784] opened 2022-10-16 06:52 UTC
I was working on a level and when messing around with the shadows Max crashed my whole PC. Once I rebooted and attempted to open the level I get this error and cannot open up the level. 
![crash](https://user-images.githubusercontent.com/51464873/196022351-ef8074e5-0f2b-4230-b1bc-98760ef38ce0.png)

This error message does not always pop-up sometimes it just crashes straight to desktop. 

GPU: NVIDIA GeForce RTX 2080
CPU: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Memory: 16 GB RAM (15.97 GB RAM usable)

**Comment by Kitakazi** [comment] 2022-10-16 22:39
Also forgot to add, when I attempt to open this level now, GGMax will completely crash Windows.

**Comment by ZakJudges** [comment] 2022-11-09 11:25
Hi @Kitakazi, would you be able to send me the level, and any custom media it may use? That will allow me to hopefully reproduce the crash. My email address is zak@thegamecreators.com

**Comment by Kitakazi** [comment] 2022-11-09 16:47
Yes sir I will send to you this evening when I get home from work.

**Comment by ZakJudges** [comment] 2022-11-10 13:13
Hi @Kitakazi, thanks for sending that over. I have been able to reproduce the crash.

It seems to be caused by the switch to DX12. This will be fixed as part of Lee's work on the new Wicked integration. I will be sure to mention it to him when he is back :)

If you need to work on the level in the mean time, you can switch to a previous DX11 build (the 2022-08-19 build on Steam was able to load the level on my end)

**Comment by Kitakazi** [comment] 2022-11-30 19:47
Wops I didnt mean to close this one :( 
@ZakJudges

**Comment by LeeBamberTGC** [comment] 2022-12-01 17:52
@Kitakazi From my extended dev into the latest Wicked, I suspect something fundamental with our current DX12 that is being a little silly.  The latest Wicked Engine seems to have resolved this. For now our pre-Christmas attack is on non DX bugs and then we can try again after Christmas to get the latest Wicked DX12 edition on our side.  Should be resolved when that build is ready :)

**Comment by LeeBamberTGC** [comment] 2023-09-04 14:09
@Kitakazi Since we reverted to DX11, I have closed this one, and after a new attempt to move to DX12 I suspect this error will be historical.  Thanks for the report, we nearly got there :)

**Closed by LeeBamberTGC** 2023-09-04 14:09 UTC
Labels: bug, Max, High, Level Editor
