### ISSUE TITLE
[Bug has returned] When "force = x" is added to a gunspec file the amount of force is also applied to the player when the weapon is fired. 

### ISSUE THREAD

**Issue by Kitakazi** [TheGameCreators/GameGuruRepo#823] opened 2020-08-31 04:23 UTC
Same issue that was previously fixed here https://github.com/TheGameCreators/GameGuruRepo/issues/670

It seems worse now than before.
 Testing with the enhanced weapon pack MK18, zooming in and firing in full auto makes the push back really bad.

**Comment by Ratall** [comment] 2020-09-20 21:25
For every action there is an equal and opposite reaction.
The amount of force excerpted on player should take into account not just the force exerted on the projectile but also the  mass differential between projectile and player
in this case Id say the force mass calculations are incorrectly implemented.

**Comment by fearlesswee** [comment] 2020-10-10 18:17
Just today I noticed this may actually be caused by the casing ejecting.

In the enhanced pack, try out the shotgun. You don't get pushed back until the casing is ejected, instead of instantly after firing.

**Comment by plemsoft** [comment] 2020-11-11 15:04
@Kitakazi Thanks for reporting this issue , this has been fixed and will be in the next update :)

**Closed** 2021-01-20 13:34 UTC
Labels: bug, fixed
