### ISSUE TITLE
Trees - White outline with high fog opacity and low light

### ISSUE THREAD

**Issue by dllllllllllb** [TheGameCreators/GameGuruRepo#2193] opened 2022-02-18 12:02 UTC
How to reproduce: Set time of day to Dusk/Night -> change fog opacity

https://www.youtube.com/watch?v=0siau6lHc0M

**Comment by PaulSJ** [comment] 2022-03-08 14:29
Trees are using an alpha mask clip, but the clouds are rendered afterwards and may be sampling a less detailed depth buffer or something. Needs a closer look in RenderDoc

**Comment by LeeBamberTGC** [comment] 2022-03-08 17:48
@PaulSJ I have pushed this to post EA, we can take a more detailed look after March as I think there are other issues that skirt this one.

**Comment by PaulSJ** [comment] 2022-04-21 16:20
Should be fixed in a future version

**Comment by PaulSJ** [comment] 2022-05-23 13:32
It's the same issue, caused by the downsampling of the depth buffer. It's also an issue in the current WickedEngine so this may be as good as we can make it for now.

**Closed** 2022-06-06 12:10 UTC
Labels: bug, Fixed but need confirmation., Max
