### ISSUE TITLE
Shortcut problem on Japanese Windows

### ISSUE THREAD

**Issue by ECL-JP** [TheGameCreators/GameGuruRepo#757] opened 2020-04-11 08:23 UTC
This was also posted in the Steam discussion in the past.

In Japanese version of Windows, once IME is turned on, keyboard shortcuts do not work on GameGuru even after IME is turned off.

This is because GameGuru's current key scan process only determines the first byte key code, and when returned in multi-byte format, truncates the second byte that should be determined.

For example, if press the key "F", GameGuru can usually get 0x46 in the first byte, but if use IME even once in Japanese Windows, the first byte is 0xF3 (or 0xF4) and the second byte is 0x46 It becomes.
Keyboard shortcut does not work because GameGuru only determines this 0xF3.

This problem only occurs with GameGuru, and other applications and games do not have this problem.
Of course, AppGameKit does not have this problem.

**Comment by plemsoft** [comment] 2020-04-24 07:09
@ECL-JP Thanks for reporting this,

Could you let me know what shortscuts that dont work , is it only editor shortcuts ?

Do wasd work in editor ?
Do wasd work in tesgame ?

We run a combination of direct input and normal windows messages , so need to know where the problem is , thanks for the help :)

**Comment by ECL-JP** [comment] 2020-04-24 16:40
Hi,
I use Google Translate. I'm sorry if my explanation is insufficient!

- Editor
WASD can be used correctly.
Other keys (eg. F, G, T,-, +, F1) do not respond.

- Test game
All keys can be used correctly.

**Comment by plemsoft** [comment] 2020-04-27 11:07
@ECL-JP Thanks.

I tried installing a Japanese keyboard using IME , and it looks like the shortcuts is working fine here ?
See video:
https://drive.google.com/file/d/1t7pqvMlxCDbh1dutfGs-VhmmNle18s4Y/view?usp=sharing

Is there anything special with your setup ? , could you provide a step by step how im able to reproduce this , that would really help , thanks :)

**Comment by ECL-JP** [comment] 2020-04-27 11:48
Thanks for the video.

I'm using Game Guru Classic Steam Edition.
The OS is Japanese version Windows 10 Pro (1903) and it is a general setting.
I am not using any other application that uses hotkeys.

Immediately after starting the OS, GG can be keyed in normally.
However, this problem occurs when I use GG after inputting Japanese (eg NotePad) using JP MS IME.
Of course, IME is off when using GG.

1. Start Windows.
2. Starting GG, GG can be keyed in normally.
3. GG close.
4. Inputting Japanese(MS-IME ON) on any texteditor.
5. IME OFF and close texteditor.
6. Starting GG, GG can not be keyed in normally.

I use a lot of creative software (Game Engine, Graphics, Audio, Video Editing, and many more!), But this problem only occurs in GameGuru's EDIT mode.

In older versions of GameGuru could use debug mode (display the keycode on the screen) with a command line parameter, could that option be re-enabled?
With that capability, should be able to find out what key code GameGuru is receiving.

**Comment by plemsoft** [comment] 2020-04-28 09:50
@ECL-JP Thanks for the step by step.

I was not able to reproduce it , but i made a new gameguru.exe that disable IME in the app , so IME should not interfere with anything.

Please try this version and let know if it fix your issue.

Backup your gameguru.exe file and replace it with the following:
https://drive.google.com/file/d/1U5DNlcwCJU8tMIGmqz6Re5PzpDVkL-On/view?usp=sharing

Just in case it will also display the keycode , see video:
https://drive.google.com/file/d/1Kf4MgbIxvjsGzIRt4EYMadChyq42IdhM/view?usp=sharing

Hope it helps :)

**Comment by ECL-JP** [comment] 2020-04-28 11:48
Thank you.
But unfortunately the problem has not been resolved.

With the new version, the GG always displayed the key code 243 immediately after booting. The GG always displayed 243 while editing, and keys other than WASD do not respond. If keep pressing the F or G key, it may occasionally react after a few seconds.
When the window of GG is deactivated, the key code shows 0.

I tried an experiment.
1. Turn off IME and start GG (GG shows key code 243)
2. Start a text editor while GG is running (GG displays key code 243)
3. Turn on IME in text editor (GG shows key code "244")
4. Turn off IME in text editor (GG shows key code 243)
* WASD keys is working properly under all conditions.

I suspect that the cause of this problem is the Windows system (or IME).  Please suspend this issue and resolve other issues.

If possible, please tell me how to get F/G key (API). I can program it, so I'll investigate what's happening on my PC.

**Comment by plemsoft** [comment] 2020-04-28 15:09
@ECL-JP Thanks , OK i think i understand what is going on then,

Could you try this version and let me know if that fix your issue:
https://drive.google.com/file/d/1id7ZK1BpeyPWWzQX1x1LDIULlC6qGG_D/view?usp=sharing

It is a bit hard when i cant test it, but i think we are getting there :)

Let me know if it fix your problem.

**Comment by ECL-JP** [comment] 2020-04-28 17:43
Wow! With this version, all keystrokes are working correctly on my PC as well!

I am very grateful for your efforts to fix this issue. 
Thank you very much!

**Comment by plemsoft** [comment] 2020-04-29 11:32
@ECL-JP Thanks for confirming the fix, it will be in the next update :)

**Closed** 2020-04-30 15:42 UTC
Labels: bug, fixed
