### ISSUE TITLE
Shadow judders back again with latest update

### ISSUE THREAD

**Issue by BodRH** [TheGameCreators/GameGuruRepo#724] opened 2020-03-29 20:19 UTC
This problem has reared it's ugly head once again with the latest update.

https://youtu.be/uVLXaVp_jk4

After changing speedshadows to 0 in the setup.ini the shadow problem has gone but the vehicles drop through entities to the terrain after they have been driven, another previous problem. 
![tmc](https://user-images.githubusercontent.com/36109432/77860232-f63fca00-7205-11ea-9058-55047897090a.jpg)

**Comment by plemsoft** [comment] 2020-03-30 06:52
@BodRH Thanks for reporting your issue.

Yes you still need =0 for fast moving shadows :)

I remember the fix we made for vehicles dropping down to the terrain, i just checked and that fix is in the last PP , so please make sure your running the PP version. If you are , then we need to check if the problem is the same as last , so edit your setup.ini and set "drawcalloptimizer=0".

Then make another test , and let me know if this fix your issue , thanks :)

**Comment by BodRH** [comment] 2020-03-30 08:19
I had already set it to zero and the shadow problem had gone but they still don't make contact with my road/pavement entities, they can no longer get up a slight kerb, last time they were sunken to the terrain on load up like in this video https://youtu.be/E05v-Ny3d4E but now they sit on the road fine until they are driven and I can no longer drive up my modular car park https://youtu.be/xgAvRv6JuxE
![fte](https://user-images.githubusercontent.com/36109432/77890451-62064f00-7267-11ea-9ae0-98729c60f406.jpg)

**Comment by plemsoft** [comment] 2020-03-30 11:24
@BodRH Please make sure your have "drawcalloptimizer=0" in the setup.ini , and give it another go!

This is not about the shadows but "drawcalloptimizer=0" :)

**Comment by BodRH** [comment] 2020-03-30 14:35
I tried that but all driveable vehicles are sunk through the roads into the terrain from the outset when the level loads, before it only occurred when driving them, now they are sunken all the time like in the video I linked above from the September 2019 update.

**Comment by plemsoft** [comment] 2020-03-30 14:57
@BodRH Tried my old test map when we looked at this the last time, and it is still working.

![driveable](https://user-images.githubusercontent.com/18662417/77927318-65212f80-72a7-11ea-98c8-ed092313dd78.jpg)

Perhaps you updated the script ? , anyway could you make me a fpm with all needed media that display the problem , and i will try to get it fixed :)

**Comment by BodRH** [comment] 2020-03-30 16:02
I haven't changed any of the scripts, I could make a small level with a car and some roads and pavements in it but I can't PM you on the forum or Discord for 2 years and I'm not posting any of my media on here.

**Comment by plemsoft** [comment] 2020-03-30 17:20
@BodRH Just email it to me like before , plemsoft@plemsoft.com :)

**Comment by BodRH** [comment] 2020-03-30 18:09
This is all very odd, I deleted most of the large level and left just one car in it to make the test level, if I have drawcalloptimizer=0 the car is sunken into the road but now if I have it as drawlcalloptimizer=1 it works fine, even where it is highlighted in the picture where it was getting bogged down before. It has to be something in this build because 10 minutes before I installed the update I made the police car lights video and it worked fine. https://youtu.be/13db2Zq-dDo, I will isolate and structure the required files for you and upload to my site then send you the link.
![sinking](https://user-images.githubusercontent.com/36109432/77946098-b63a1f00-72b9-11ea-80df-18e631473421.jpg)

**Comment by plemsoft** [comment] 2020-03-31 15:31
@BodRH Thanks for the test level , got it working using drawcalloptimizer=0 , but it looks like it would always have been like that , perrhaps you always used drawcalloptimizer=1 ? , anyway it do have some changes where Lee will have to validate the fix, but fixed for now :)

**Comment by BodRH** [comment] 2020-04-01 18:13
I noticed in the big level the vehicles only get bogged down on the pavement risers where I have sculpted the terrain away underneath when drawcalloptimiser=1 , the vehicles don't seem to recognise them as solid but physics is set to on so I tried setting them as always active as well and now the vehicles go up them instead of through them.

**Comment by LeeBamberTGC** [comment] 2020-04-01 18:32
If your scripts use the IntersectAll command, then I have a quick update planned which may resolve this for you.  Watch the forums for the announcement of a new PP build for you.

**Comment by BodRH** [comment] 2020-04-01 18:38
I'm banned from the forums.

**Comment by LeeBamberTGC** [comment] 2020-04-01 19:23
Fair enough. As this issue has been reopened we can use this issue report to keep the conversation going, no worries.

**Comment by LeeBamberTGC** [comment] 2020-04-02 23:50
Fix applied for next PP build - check out the Steam PP build from the BETA tab on Friday.

**Comment by LeeBamberTGC** [comment] 2020-04-03 02:03
No worries, new PP build uploaded :)  Also, if judder persists, you can set shadowspeed in SETUP to zero to remove any shadow optimization that would cause this.

**Closed by LeeBamberTGC** 2020-04-03 02:03 UTC
Labels: Fixed but need confirmation., bug
