### ISSUE TITLE
Script weirdness in Max

### ISSUE THREAD

**Issue by bluemeenie195** [TheGameCreators/GameGuruRepo#2742] opened 2022-04-02 14:00 UTC
I know guys are super busy, but when you have a second could you take a look at this script.

Don't know if it's due to a different command or something else, but in the video when you move the torch to an entity it pushes the flame away and also when running at different directions too.

Works perfectly in Classic.

 https://youtu.be/hINecd64FSY

[torchgo.txt](https://github.com/TheGameCreators/GameGuruRepo/files/8402661/torchgo.txt)

**Comment by Granada1** [comment] 2022-04-02 15:14
It’s best to post this on the Max Discord in the scripts channel 👍

**Comment by bluemeenie195** [comment] 2022-04-02 15:24
I was working with AmenMoses through Discord Message. We came to the conclusion to post it here and see if they could figure it out.

**Comment by Granada1** [comment] 2022-04-02 15:29
Cool,  if amen can’t sort it your probably right 👍

**Comment by AmenMoses** [comment] 2022-04-02 17:28
Well if a script works perfectly in Classic and then doesn't work in MAX it's not much use asking the scripter what the problem is!

Obviously a Lua function doesn't work in MAX the same way it does in Classic.

In this case the flame is using the Classic particles system so something about that in MAX no longer works the way it should.

**Comment by Kasseyus** [comment] 2024-10-10 14:36
Sometimes multiple tickets for the same bug exist, or fixing one bug will also fix another, or other examples that result in old tickets remaining in the system.

For the sake of clarity, II will close this ticket for now, but If you are still having an problem with this issue, please reply here and I will re-open the ticket and investigate further.

**Closed by Kasseyus** 2024-10-10 14:36 UTC
Labels: Question, Max, LUA
