### ISSUE TITLE
Collision issues preventing player movement

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#1269] opened 2021-07-21 10:45 UTC
Collision Issue preventing player moving freely
- Load jungle map
- Walk around level 
- Get up on the rock slabs, and try walking around 
- becomes very slow for player to move, sometimes almost gets stuck

**Comment by michaeloldman** [comment] 2021-08-14 02:39
This issue is not restricted to Jungle Assets, it also occurs on other objects, usually anything that is not flat.

For example, you will eventually notice movement issues when walking on rooves of buildings that come with MAX.

Try adding any one of the buildings with a sloped roof, and put the plyer on the roof.

**Comment by rvanner** [comment] 2021-08-14 07:09
@michaeloldman I've recorded a video. Is this the type of behaviour you are referring to?
https://youtu.be/wI0p3vikw4I

**Comment by michaeloldman** [comment] 2021-08-14 14:06
Yes, that is spot on.
Also, if you try the jungle map that comes with MAX, and get up on the flat rocks, it is sometimes near impossible to move after a while.

**Comment by ZakJudges** [comment] 2022-02-01 13:28
@OldFlak Just checking you no longer experience this issue?

**Comment by OldFlak** [comment] 2022-02-03 01:32
@ZakJudges - it was fixed for jungle rocks for a while, but recent builds it is no longer restricted to rocks etc - but pretty much prevalent everywhere on any level with terrain. 

Player constantly goes faster/slower when walking/running - like being held back.

All to do with terrain physics rather than models no doubt.

**Comment by ZakJudges** [comment] 2022-02-04 13:17
@LeeBamberTGC See OldFlak's recent comment re the movement speed :)

**Comment by LeeBamberTGC** [comment] 2022-03-17 12:02
@ZakJudges This was related to physics system loosing track of material detection briefly, causing the player velocity accumilator to slow down / speed up. Now material remembered long enough to overcome occasional 'non touch' events between player and physics world.  Building roofs no longer 'slow down' but DO make it harder to climb UP than to climb DOWN.

Be aware the natural sharp edges of some rock formations will still cause the player to slide to the side as physics takes over,

Will be in next internal build.

**Comment by OldFlak** [comment] 2022-03-18 03:09
Player Movement issues in todays build are actually worse now - no longer just in certain areas, but now everywhere.

I created this level from scratch - simply used default Terrain Generator settings.

Apart from some obvious graphical issues - everywhere the player goes he is struggling to walk or run - always feels like being held back.

https://youtu.be/NcK6vtg5Oqs

**Comment by LeeBamberTGC** [comment] 2022-03-18 08:55
@OldFlak Thanks for providing a video. Not sure what the video is showing. Maybe you can walk in a straight line (not run) and allow time for the video to show the 'stutter' you report.

**Comment by LeeBamberTGC** [comment] 2022-03-18 08:56
@ZakJudges Can you also confirm the player movement is now broken everywhere, thanks.

**Comment by OldFlak** [comment] 2022-03-18 09:32
@LeeBamberTGC Sorry to be a thorn :)

The video shows the player movement is not smooth - once the player is moving I am holding down the W key, some times I have engaged shift for running. The whole time the player is walking or running there is constant speed increase/decrease as if player is being held back. 

Here is another one that shows it better:
In this video once player is moving he is running the whole time.
https://youtu.be/l9TfCqz4BM0

I am pretty sure the real issue with movement is caused by the trees more than anything else - previous builds mainly pine trees would show the issue on every map I tried - but it was usually in valleys.

In the current build any trees cause it and it is everywhere on the map - but pines are definitely the worse :)

I can produce these issues on every map, including new maps with nothing but vegetation and player marker.
Has been same with every build since bug bash began, and of course prior to that.

**Comment by ZakJudges** [comment] 2022-03-18 09:54
@LeeBamberTGC I was able to reproduce the issue that OldFlak is seeing. I think its due to the difference in speed between going uphill vs downhill. When there is a slight change in the steepness of the terrain, there is a significant change in the players speed. I.e. Going uphill is so much faster than going downhill, that when you go from uphill to downhill or anywhere in between, it feels like you are stepping in treacle. 

Here is a video:

https://user-images.githubusercontent.com/32545391/158979688-6f900b05-a596-4093-ab9a-729ded1ba59c.mp4

**Comment by OldFlak** [comment] 2022-03-19 10:30
Not seeing any difference in Friday Public Release
- Same issue with outside levels - if you use any pines it is much worse
- Now inside feels like walking on treacle as well.

**Comment by LeeBamberTGC** [comment] 2022-03-19 16:55
@ZakJudges Fixed for next build

**Comment by 3coms** [comment] 2022-03-21 13:24
Here is quite noticeable, I even lost on my own map. lol
Here Player tries to run, but almost can't move away.

https://youtu.be/j4_C-11o5go

**Comment by 3coms** [comment] 2022-03-22 00:43
@LeeBamberTGC 
After updating to the latest build, I've tried my swamp level (video above) and no player movement issues here,
The level load and works like a charm :)
Good work guys!

**Closed** 2022-03-22 12:44 UTC
Labels: bug, Fixed but need confirmation., Max, High, AI

**Comment by OldFlak** [comment] 2022-03-24 03:00
Much better than previously mostly - but this issue is not completely sorted.

Try valleys and use pine trees - easily reproduced.

**Comment by LeeBamberTGC** [comment] 2022-03-24 08:48
@OldFlak Can you attach/email me a stock FPM and place the start marker in the direction I should walk, that way I can see the player stopping due to invisible collisions. Thanks!

**Comment by OldFlak** [comment] 2022-03-25 11:49
@LeeBamberTGC Thanks for getting back Lee :)

There are no invisible barriers now - it is just that player feels like being held back, and sometimes can hardly walk in places or becomes very slow.
- you will especially see it in valleys and when you use the big pines trees
- you may need to go for a wander around for a while before it becomes obvious

will make fpm to you soon :)
