### ISSUE TITLE
GameGuruRepo Build Issue 2020 (Shadows)

### ISSUE THREAD

**Issue by nomad5oul** [TheGameCreators/GameGuruRepo#827] opened 2020-09-06 17:37 UTC
Hi 
I have successfully cloned and built the latest GameGuru source code on Github.
I can build the application binaries and the engine works but there is a rendering issue with dynamic shadows on entities.
I've attached some pics to show the lines appearing on the top and sides of models in the editor and test game.
Please can this be fixed as it does not happen with the latest autumn steam build. 

![shadows1](https://user-images.githubusercontent.com/37256116/92331614-f921cf00-f06f-11ea-837b-3434b1c5c383.png)
![shadows2](https://user-images.githubusercontent.com/37256116/92331616-fc1cbf80-f06f-11ea-8a86-861949f1e291.png)

**Comment by plemsoft** [comment] 2020-11-12 10:07
@nomad5oul Thanks for reporting this issue.

The problem is fixed in our private REPO , unfortunately we are currently not able to update these bug fixes in the public repo.

The source code in the public repo is an early 2020 version and do not include the latest source code fixes.

Sorry , but at some point there might be a new "updated" public version. but don't think anything has been decided yet.

**Closed** 2021-01-20 13:34 UTC
Labels: Answered, bug
