### ISSUE TITLE
Big mouse pointer 

### ISSUE THREAD

**Issue by olfbcn** [TheGameCreators/GameGuruRepo#4521] opened 2023-04-21 22:50 UTC
I finished a small project with 4 levels. Testing all ok. Trying to export to standalone game and...open it..menu ok, but the first level appears a big mouse pointer and the game not works. Block game, task manager from Windows to close it. The project inside gameguru now has the same problem, testing all levels always appears on screen a big mouse pointer and not works. I hope someone can help me about this. Thanks in advance.  Sorry for typos.

**Comment by davetgc** [comment] 2023-04-22 15:14
I've not seen this, and can't replicate it. Has this happened to anyone else?

**Comment by Kitakazi** [comment] 2023-04-22 18:48
Yea this has happened to me. It was a while ago around the time RPG HUDS first came out on exp build. Not sure exactly how the bug started but I know I was messing around with RPG HUDS. At some point I reset all HUDS and then tried to add a User Defined Global Statusbar on the main In-Game HUD.

![image](https://user-images.githubusercontent.com/51464873/233801318-c9b52c27-d7b1-406b-9c03-1f24f9dd717c.png)

Once I added that a pressed test game I experienced what @olfbcn is experiencing.  Launching Test Game would start me out with a locked screen and only a mouse pointer. Even after I returned to project and reset all HUDS it would still happen. I had to delete my project file to fix it.

**Comment by plemsoft** [comment] 2023-04-24 14:31
@olfbcn @Kitakazi Thanks for reporting this issue, could you zip up the project folder that has this problem and e-mail me a download link to e-mail: plemsoft@gmail.com , this will allow me to see what the problem is , thanks for your help :)

**Comment by plemsoft** [comment] 2023-04-26 08:40
@olfbcn I know what the problem is now, your using an older version and not the current EXP build, this system has been changed and are now fixed in the current EXP build, could you try to update to the latest EXP build and let me know if its also fixed for you, Thanks for your help :)

**Comment by Jobisgame** [comment] 2023-04-26 09:29
@plemsoft Hi, it's not an old version. i have the last. The solution indicated by the colleague @Kitakazi resetting the hud has been the solution to this problem. Thanks all for your help!!

**Comment by plemsoft** [comment] 2023-04-26 09:59
@Jobisgame Thanks for getting back , ok if you see this again please zip up your project folder before resetting the hud and upload it here or e-mail it to me plemsoft@gmail.com , then im able to see what the problem is.  Thanks :)

**Closed by plemsoft** 2023-04-26 09:59 UTC
Labels: bug, Fixed but need confirmation., Max, High, Storyboard Editor
