### ISSUE TITLE
Lua Error on standalone

### ISSUE THREAD

**Issue by RajMaha1** [TheGameCreators/GameGuruRepo#4109] opened 2023-01-22 13:27 UTC
![image](https://user-images.githubusercontent.com/107326667/213918267-e14bdc63-9cd8-41f7-9453-d36fb1b8bd91.png)

**Comment by Tum1370** [comment] 2023-01-22 17:51
I Guess this is on the experimental build of Max ?
I reported this last week, yet its still not marked as a bug.

**Comment by davetgc** [comment] 2023-01-23 13:51
Closed as duplicate of #4066

**Closed by davetgc** 2023-01-23 13:51 UTC
