### ISSUE TITLE
Editor Issue: Locking Entities

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#738] opened 2020-04-02 02:13 UTC
- Place an entity on the map
- Click on the Widget and Lock the Entity

The entity will not go invisible nor transparent. Only until you test the game then exit the test.

More on the topic with others confirming how to reproduce:

https://forum.game-guru.com/thread/221698?page=1#msg2628733

EDIT 4/11/2020 - I'm reporting he issue of the entities NOT going invisible. Which i felt the x-ray mode was actually an excellent feature. Looks like my bug post has actually canned the feature rather than fix it where as it only worked after exiting Test Mode.

**Comment by synchromesh62** [comment] 2020-04-02 10:16
This has always happened for me if you do not unlock it before testing ?
If you forget and come out of the game you can drag the mouse over , press spacebar to unlock and when you highlight it the model returns to normal.

Not saying its not a bug or couldn't be improved but for me its always been that way ..

**Comment by LeeBamberTGC** [comment] 2020-04-02 17:55
@Teabone3 I checked out the forum thread but its goes off in a few directions and I could not see any stock media or FPMs to try out. Can you post an FPM here and a step by step so I can reproduce this issue. I tried with a building and a dragon and both before and after test game the LOCKED object did not change visually at all, and the SPACEBAR released the lock as it should.

**Comment by Teabone3** [comment] 2020-04-03 02:36
I don't think an FPM will help with this.

How to reproduce:

**1. Place Barrel on Map
2. Lock Barrel**

- The barrel still remains entirely visible in Editor. 
- The expected transparent effect only occurs after you return from Test Mode.

The locking to see through the entity worked 2 weeks ago. It was an important functional part of the development of my game as I need to see through complex geometry in my levels. It worked great prior latest build. 

Here is a video of the bug and how to reproduce:
https://www.youtube.com/watch?v=r8JANzUS1Hc

**Comment by Pirate-Myke** [comment] 2020-04-03 13:07
I can reproduce this issue also. Not loosing the smoothing groups as Teabone3 is.
Video from my machine.
https://www.youtube.com/watch?v=YCxPNfTMY4U

[ObjectLockIssuePirateMyke.zip](https://github.com/TheGameCreators/GameGuruRepo/files/4427359/ObjectLockIssuePirateMyke.zip)

**Comment by plemsoft** [comment] 2020-04-06 09:28
This has been fixed and will be in the next update :)

**Comment by LeeBamberTGC** [comment] 2020-04-07 00:40
New PP build uploaded to confirm this fix.

**Comment by LeeBamberTGC** [comment] 2020-04-07 15:32
@Teabone3 A better way to edit inside entities (such as buildings) is to use the TAB key to do the alpha slice and use CTRL+Mousehweel to select the slice height.  This way you can keep solid floors but remove the upper floors or roof when editing inside things.

**Comment by Teabone3** [comment] 2020-04-10 09:41
Testing in the PP

The entities no longer fade at all. Which was actually a great benefit for me. As TAB doesn't work for the smaller entities layered.

However, perhaps this feature was underutilized by most. I will find a workaround.

**Comment by Teabone3** [comment] 2020-04-10 09:44
I now have no way of seeing through entities that are layered. As TAB seems to only work with larger objects? Perhaps I'm using it incorrectly?

**Comment by LeeBamberTGC** [comment] 2020-04-10 22:13
As you can see from the shot, here is an EBE room, a small cardboard box and an even smaller teacup on the box, all viewed using the TAB and CTRL+Mousewheel to intersect them. All see-through:

![image](https://user-images.githubusercontent.com/35840583/79026478-e10d5880-7b80-11ea-8189-5760403de15f.png)

**Comment by Teabone3** [comment] 2020-04-11 17:13
I am having a really difficult describing the issue here. I am no longer able to edit my dungeon crawler level because I utilized being able to lock the structure components (not EBE) to see through AND select behind complex layers of entities. The ability to choose which entities are see-through and which are not and be able to select what's behind, beneath or above them has been tremendously helpful. 

I am full aware of the tab and control mouse controls. However this is purely top level. This does not help me for any other direction but from above. Even for above i prefer the previous as I'd like to select things that are on the exact same level that are inside each other and not have them both become transparent. For instance, i have sliding doors, traps and other things that hide within other entities at the exact same positions as them.

Id have to revert to the older version of GG to show a video example of what I mean in comparison to the difficulties without this feature which seems to be now viewed as a bug.

There is now a new issue for me with locking entities to select what is inside them or just behind them. When you lock something there is no way to know which entity was locked whereas before the transparent x-raymode was also helpful with knocking that, visually. The widget isn't dynamic to go from "lock" to "unlock" either so now its a guessing game with what pixel you click as to what entity in the layers shows up as not locked to know what was locked.

For the record, I don't use the EBE. I use entity structure components to build my multi-level complex indoor interior sets with layers of entities.

**Comment by LeeBamberTGC** [comment] 2020-04-16 22:35
Re-introduced semi-transparency for locked entities in the latest PP build.

**Closed by LeeBamberTGC** 2020-04-16 22:35 UTC
Labels: bug, fixed
