### ISSUE TITLE
Copy Asset Bug

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#1043] opened 2021-03-30 00:05 UTC
build 26-3-21
If you copy an asset and press the DEL key ( if you change your mind for example ) both models are deleted.
https://youtu.be/iAgTQhEogt0

**Comment by rvanner** [comment] 2021-04-01 15:54
@synchromesh62 Can you reproduce this with the standard barrel object? I just tried it in this week's build and it works fine for me.
If it still happens for you, please list every step you take to make it happen. Thanks.

**Comment by synchromesh62** [comment] 2021-04-01 16:09
@rvanner 
Hi Rick Yes its the same today with Barrels
Place a barrel **but do not let it go** 
Press (shift+click ) to copy **but again do not let go of the copy** .. Then as if you have changed your mind press **DEL** 
Hope that makes sense.

**Comment by rvanner** [comment] 2021-04-05 07:51
That's very odd. I cannot reproduce that here. Does anyone else in the internal test team see this issue do you know?

**Comment by plemsoft** [comment] 2021-04-05 07:55
@rvanner Im able to reproduce it , just assign it to me :)

**Comment by synchromesh62** [comment] 2021-04-08 23:06
I think this is fixed in this build.
@plemsoft Did you do anything as you were able to reproduce it or is it just a fluke :)

**Comment by plemsoft** [comment] 2021-04-09 06:38
@synchromesh62 Yes should be fixed, and should be in the Friday build :)

**Closed** 2021-08-14 09:01 UTC
Labels: bug, fixed, Max, High
