### ISSUE TITLE
Change texture folder, not importing new terrain textures.

### ISSUE THREAD

**Issue by 42Pix3ls** [TheGameCreators/GameGuruRepo#3871] opened 2022-10-29 06:26 UTC
I have been trying to import custom ground textures in to a scene and I have set up the file structure the same as the texture bank with mat folders numbered and the 3 textures inside. When I change to this folder, I just get a single blank texture.

![image](https://user-images.githubusercontent.com/95527550/198817133-e5fdee41-adc4-4183-b77f-b696a8c1eb0e.png)
![image](https://user-images.githubusercontent.com/95527550/198817265-6ee2aab1-c39d-4c4c-984e-ec7846b5959b.png)
![image](https://user-images.githubusercontent.com/95527550/198817271-727b67d7-8536-4f41-908c-36b604dbf903.png)

**Comment by ZakJudges** [comment] 2022-11-17 11:52
Hi @42Pix3ls, would you be able to email me the folder than contains the materials showing the issue? That should allow me to reproduce and fix, thanks. My email address is zak@thegamecreators.com

**Comment by Nader-B10** [comment] 2022-12-05 03:04
I'm facing the same problem : (

**Comment by Nader-B10** [comment] 2022-12-05 03:08
The same guy ( [42Pix3ls](https://github.com/42Pix3ls) ) who posted about the problem here has posted a video explaining adding a custom texture and the video shows the problem and the solution  

https://www.youtube.com/watch?v=-7I_Jl7RXhQ&ab_channel=42PixelsStudios

**Comment by 42Pix3ls** [comment] 2022-12-05 20:41
Apologies for the delayed response, I missed the notification and am now just sifting through a backlog of emails.
@Nader-B10 is correct. Although there is a bug where the images do not seem to import, they are in fact there they just have to be re selected once imported. For the most part, the issue is resolved.

**Comment by LeeBamberTGC** [comment] 2022-12-12 11:23
@ZakJudges One for you to look at this week :)

**Comment by ZakJudges** [comment] 2022-12-13 11:48
Hi all, thank you for reporting this issue. A fix has been added which you should see in the next experimental build :)

**Comment by 42Pix3ls** [comment] 2022-12-15 17:59
Sad to say, custom terrain textures still not working. I just tried importing a new folder and this is all that I get. the PNG files have been moved in to the folder but they have not been converted to DDS

![image](https://user-images.githubusercontent.com/95527550/207933450-11cc96a9-e56f-4c20-8cb1-a472605f45d2.png)

**Comment by Nader-B10** [comment] 2022-12-16 04:09
( @ZakJudges )...After my experience of the latest beta update, the problem has been resolved, but there are other problems that have not been resolved yet ... and one of these problems makes the custom texture feature not working or useless...And it is that when I paint an area with the custom texture and save the changes at the level, then close GameGuruMAX, and when I run it again, I see that the custom texture has been replaced in the area which it was painted with the default texture of the GameGuruMAX

**Comment by 42Pix3ls** [comment] 2022-12-16 06:30
I removed all of my custom textures and re-imported them fresh. It moved the PNG files to the correct folder, but no DDS was generated from the PNG files, so I have no custom textures. I can record a video to show if that helps??

**Comment by Nader-B10** [comment] 2022-12-16 06:49
Try verifying files on Steam

![image](https://user-images.githubusercontent.com/113104542/208039432-a206b7a6-7a2d-4e79-933e-1d3a0e5653f8.png)

**Comment by 42Pix3ls** [comment] 2022-12-16 07:12
> Try verifying files on Steam
> 
> ![image](https://user-images.githubusercontent.com/113104542/208039432-a206b7a6-7a2d-4e79-933e-1d3a0e5653f8.png)

Verified, old PNG files cleared, re-imported, same issue.

**Comment by Nader-B10** [comment] 2022-12-16 07:17
> > Try verifying files on Steam
> > ![image](https://user-images.githubusercontent.com/113104542/208039432-a206b7a6-7a2d-4e79-933e-1d3a0e5653f8.png)
> 
> Verified, old PNG files cleared, re-imported, same issue.

try re-name image  : color  , normal , surface

**Comment by 42Pix3ls** [comment] 2022-12-16 07:20
Last time I imported the textures, and they worked, all I had to do was import a PNG image. I have even done a YouTube video showing how it was done, and it was working. 

Here is the video showing that it brings in the png images but does not generate the DDS like it has in the past.

https://user-images.githubusercontent.com/95527550/208044587-a59bd02b-5a9c-42c9-9d92-d82e32d1814c.mp4

**Comment by Nader-B10** [comment] 2022-12-16 07:33
Try this method for the last time...I faced the same problem as your current one before the last update to fix the problem and I solved it this way


try re-name image : color , normal , surface ....and re-name folder

...............................................................

**Comment by 42Pix3ls** [comment] 2022-12-16 07:56
> 

Happy to report your instructions are correct. Thank you @Nader-B10 and @ZakJudges for getting
 this sorted.

**Comment by Nader-B10** [comment] 2022-12-16 08:05
> > 
> 
> Happy to report your instructions are correct. Thank you @Nader-B10 and @ZakJudges for getting this sorted.

I'm glad I was able to help :) 


I want to ask you something before you go....Are you facing this problem :

( I paint an area with the custom texture and save the changes at the level, then close GameGuruMAX, and when I run it again, I see that the custom texture has been replaced in the area which it was painted with the default texture of the GameGuruMAX )

**Comment by 42Pix3ls** [comment] 2022-12-16 08:13
That has happened to me in the past, but I have not tested it yet with this build, so I will check it out and let you know.

**Comment by ZakJudges** [comment] 2022-12-16 10:44
Hi @42Pix3ls, glad to hear you got it working. The current implementation isn't ideal, since it relies on textures having certain names. Here are the current expectations:

- At the moment, the custom textures that you use should be in PNG format
- The texture type should be included in the filename. For example: **worn_ground.png** should be **worn_ground_color.png**
- One material should consist of a **color**.png, **normal**.png, **roughness**.png, **ao**.png and **metalness**.png

The reason for requiring the files in PNG format, and having the surface texture separated into individual components is that the terrain system needs DDS textures in various different compression formats. If the textures are not in the correct format, they cannot be used. We already have functionality to convert PNG to the required DDS format, so that is what gets used at the moment. We do also have functionality to convert DDS to the correct compression format, but it is extremely slow, and also doesn't yet work in DX12. 

I think down the road, there will probably need to be some sort of material importer, where you can choose what system the textures will be used for (e.g. terrain, building editor, entities etc)

**Comment by 42Pix3ls** [comment] 2022-12-16 12:09
I agree there is room to improve the system but once you get it they look great! 

![image](https://user-images.githubusercontent.com/95527550/208095026-5135b5fe-69dd-441a-812f-c9a4fb222a5b.png)

**Comment by ZakJudges** [comment] 2023-02-16 09:43
Closing this issue. Custom terrain textures will need to be included in the User Guide at some point: #4142

**Closed by ZakJudges** 2023-02-16 09:43 UTC
Labels: bug, Fixed but need confirmation., Max, High, Terrain
