### ISSUE TITLE
Autoflatten doesn't update with scaling

### ISSUE THREAD

**Issue by ZakJudges** [TheGameCreators/GameGuruRepo#2383] opened 2022-03-04 10:19 UTC
- Place down a building with autoflatten
- Scale the building
- The flattened area will not update to reflect the scale until you select the building

**Comment by rvanner** [comment] 2022-04-07 15:11
@ThomasJowett Because this is related to the auto flatten work you are on now, we're assigning this one to you.

**Comment by LeeBamberTGC** [comment] 2022-04-19 15:52
Confirmed fixed in latest build.

**Closed by LeeBamberTGC** 2022-04-19 15:52 UTC
Labels: bug, Fixed but need confirmation., Max, High, Terrain
