### ISSUE TITLE
GG Max - Another Smart placement bug

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2477] opened 2022-03-11 10:54 UTC
I placed these warehouses using smart placement, and they placed fine.
But when testing the game, or even going back to the warehouse in the editor the warehouse appears slightly below the surface in some area as you can see in the screenshot, grass is visible inside the warehouse.

EDIT UPDATE: I Have just replaced my warehouses, and they placed fine, I then saved the map, and after reloading the map they were not placed correctly again.
This does not always work as i tried the same on a different warehouse and it would not place fine.

![image](https://user-images.githubusercontent.com/66874403/157853783-dac0613e-6891-46c6-958e-15b513a0b902.png)

**Comment by LeeBamberTGC** [comment] 2022-03-14 14:36
@dllllllllllb Please reproduce it, thanks.

**Comment by dllllllllllb** [comment] 2022-03-14 15:43
Without pre-flattening terrain / using auto flatten option, I can't even place a warehouse using smart placement so it's placed perfectly; there is always some ground sticking through, unless the middle of the warehouse is on a hill.

I used the smart placement and then adjusted it to fit properly. I have 5 warehouses in total and all of them don't change their position after testing the level, saving it and restarting GGM :/ 

@Tum1370 Does this happen after you ONLY place the warehouses and save the map? Or do you also edit something else in the level? Since I cannot reproduce it in a vacuum, I think that some other action is causing this to happen.

Also if you could send me a screenshot of the settings you're using while placing them, that will be useful :] Thanks!

**Comment by Tum1370** [comment] 2022-03-14 16:04
It was only happening after testing or saving the map. Initially they place perfectly.

**Comment by Tum1370** [comment] 2022-03-14 16:10
After trying to quickly reproduce this bug, i have encountered a different smart placement. 
This time, the warehouse placed perfectly on the ground, and i even after testing the level, the warehouse was still placed perfectly.
I then tried to move the warehouse, and look at how the smart placement has replaced the warehouse.
It has flattened the ground below the warehouse, but it has left the warehouse floating in mid air.
You can see the settings on the screenshot.

![image](https://user-images.githubusercontent.com/66874403/158213602-280ed7fb-d3fe-40c2-a1ff-12402fa90cd3.png)

**Comment by dllllllllllb** [comment] 2022-03-14 16:54
@Tum1370 I just tested this again to be absolutely sure and my warehouses stay in the correct places. Maybe there have been some changes that fixed this in the dev build. If this issue still happens in the next internal build @ me :]

**Comment by Tum1370** [comment] 2022-03-17 03:53
@dllllllllllb 
I see a similar issue about saving after the auto flatten was mentioned before now. 
issue #2445

**Comment by dllllllllllb** [comment] 2022-03-18 12:09
@Tum1370 I believe I have fixed this, to keep things organised I'll close this one and use #2445 as the main thread. If there are any follow up issues with this one, let me know in this thread #2445 :]

**Closed by dllllllllllb** 2022-03-18 12:09 UTC
Labels: bug, Max, High, Object Placement
