### ISSUE TITLE
GG Max - Bug - Plrinzone behaviour - trigger zone - Does not remove the trigger zone after it has activated once.

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#2814] opened 2022-04-10 13:10 UTC
As the title says, This behaviour does not remove the trigger zone after it has activated once.

**Comment by Tum1370** [comment] 2022-04-10 14:28
Same issue as my last one, The Plrinzone behavoiur was not working when using inside a shanty building where i had slightly lowered the base below the ground. I Have closed this for now as i t seem to fix my issue.

**Comment by dllllllllllb** [comment] 2022-04-12 14:33
@Tum1370 It works as intended for me. https://gyazo.com/0ffa5a7bb7c8215085dab250c099fc7b

Does this happen in standalone or maybe have you modified the trigger zone in some way? If you can reproduce it, please send me your .fpm 
My email: maciej@thegamecreators.com

**Comment by Tum1370** [comment] 2022-04-12 15:23
@dllllllllllb 
I have created a simple test of this for you.
There is a shanty building in front of the character spawn, Inside the 2nd room, there is a Ally character not showing at start.
There is a trigger zone in the 2nd room.
The trigger zone activates the ally character to spawn, but never gets removed like it should do after triggering once.
If you run out and in the room, or sometimes even just move around inside the room, it will constantly trigger.
No this is not a modified lua

[Plrinzone Test.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8474305/Plrinzone.Test.zip)

**Comment by dllllllllllb** [comment] 2022-04-13 09:58
@LeeBamberTGC I tried to fix this myself but I'm not sure what the appropriate solution would be. 

The issue comes from linking AI characters to the trigger box which makes them share the t.entityelement[t.e].active var. 

When you walk into the trigger zone, the zone gets deleted and has .active set to 0 but then it gets reset in the entity_lua_spawn_core() to "Restore entity and it's AI". Getting rid of the code that sets it to active fixes the issue, but deactivates the AI.

**Comment by Tum1370** [comment] 2022-04-28 19:44
@LeeBamberTGC 
I think this bug was when the zone was placed inside a building.
I sent the level to Maciek to try and he found the same issue.
Even though in the script it had the Destroy(e)

**Comment by ZakJudges** [comment] 2022-05-11 12:43
@LeeBamberTGC I was able to reproduce the issue in the latest build. Seems to only happen when the character is an ally

**Comment by LeeBamberTGC** [comment] 2022-05-11 13:13
@ZakJudges Okay :) Nice little fix for you :)

**Comment by ZakJudges** [comment] 2022-05-30 09:51
Hi @Tum1370, is this issue now fixed for you?

**Comment by Tum1370** [comment] 2022-05-30 10:00
@ZakJudges Not tested this in a while. But if you look at the earlier posts on this thread, there is a zip with this bug happening. Maybe download that and try to see if it’s still there? 
I am currently at work so cannot test this yet.

**Comment by ZakJudges** [comment] 2022-05-30 10:07
@Tum1370 Fixed for me. Closing this issue :)

**Closed by ZakJudges** 2022-05-30 10:07 UTC
Labels: bug, Fixed but need confirmation., Max, Waiting for more information., High, Trigger Zone
