### ISSUE TITLE
GGMax Experimental New Build Crashing

### ISSUE THREAD

**Issue by Technodweeb** [TheGameCreators/GameGuruRepo#3556] opened 2022-08-05 19:45 UTC
I updated to the newest Steam Beta build today and It is crashing non stop. No matter what I am doing, creating a level, editing a level, trying to play a level.. it crashes. I validated the files and they are all good.

My PC Specs: 
Windows 10 64 bit, 64GB Dual Channel HyperX(TM) FURY DDR4 XMP at 3200MHz, 
AMD Ryzen(TM) 9 5900X (12-Core, 70MB Total Cache, Max Boost Clock of 4.8GHz) 
Nvidia GeForce RTX 3080 10Gb GDDR6X

**Comment by MonkeyFrogStudio** [comment] 2022-08-05 20:32
MAX is crashing for me, also, when working on outdoor levels. Usually the crash happens about 2 minutes in while doing something like painting grass or adjusting water. However, while working on an interior level using an "empty" level for terrain, I can work without crashes. If I open an outdoor level and leave it be (i.e. I'm not trying to paint grasses, not trying to adjust the water, MAX doesn't crash). 

EDIT - Was finally able to run and work on an outdoor level with no crashes while editing grasses, water, terrain. Strange.

**Comment by synchromesh62** [comment] 2022-08-05 20:59
Have you tried verifying and reboot ?
sometimes the updates do not sit well initially or a reboot may be required anyway.
I usually reboot after every update of any product as a rule.

**Comment by ruckupvr** [comment] 2022-08-05 21:23
I have rebooted and still crashing

**Comment by synchromesh62** [comment] 2022-08-05 22:24
Ok labeling as a bug, crash etc

**Comment by casigus** [comment] 2022-08-05 22:35
yeah had a fair few crashes to day too!

**Comment by MrWitherstormYT** [comment] 2022-08-05 22:46
it may be specific to amd cpus if you haven't experienced it

**Comment by Sinergygames** [comment] 2022-08-05 23:39
having the same problem, I can't do anything, Max keeps crashing over and over since the update.

**Comment by Kitakazi** [comment] 2022-08-06 01:40
Also having random crashes, even with empty terrain and mostly indoor levels.

**Comment by casigus** [comment] 2022-08-06 03:03
If you roll the build back to the previous update, fixes the random crashes! Still not perfect but better than nothing!


On 6 August 2022, at 02:40, David Brandt ***@***.***> wrote:


Also having random crashes, even with empty terrain and mostly indoor levels.

**Comment by Tam51** [comment] 2022-08-06 10:32
It was doing the same thing on my PC but it seams to working now and not crashing anymore. Very strange

**Comment by Tam51** [comment] 2022-08-06 10:46
I also get random crashes with the new update. I got a crash when I tried to import a object, traps and changing the animation of a character. Is anyone else experiencing these issues

**Comment by casigus** [comment] 2022-08-06 11:07
Yeah! Turns out everyone is. Amazingly the same crash happened on the live stream and they still released the update? Mind boggling. Every two e we get a update with no fix for how incredibly unstable max now is. I've been singing its praises from day one, but the resources max uses, the countless bugs, the updates not improving performance and in this case actually making it worse. Beginning to lose faith. Mods will shout "it's early access" well I'm sorry but I've never ever had this many issues with any early access things before. Beginning to not just lose patience but my support is slowly eroding away. I can't justify defending ggmax anymore.


On 6 August 2022, at 11:46, Tam51 ***@***.***> wrote:


I also get random crashes with the new update. I got a crash when I tried to import a object, traps and changing the animation of a character. Is anyone else experiencing these issues

**Comment by synchromesh62** [comment] 2022-08-06 11:45
**Amazingly the same crash happened on the live stream and they still released the update? Mind boggling.**
Oh come on.
I went 2 hours yesterday without so much as a hitch before it crashed on me .. Chances are it never happened to Lee after that.
Even this morning it has not happened to me. There is a difference between Lee knowing there is a bug and being Psychic. :)

**Comment by MonkeyFrogStudio** [comment] 2022-08-06 11:48
Lee is normally also working with code that is not ready to be delivered to us. There have been a few times that he's warned us, during a live broadcast, that things could go south as he'd just gotten the code in, etc.

**Comment by DaveTGC2** [comment] 2022-08-06 12:34
Hi all., we've really sorry that you're experiencing these crashes. To help Lee, if it's happening to you, could you please post your system spec in this thread. I know some of you will already have posted them else where, but it speeds thing up if we can find them quickly.

Many thanks,

**Comment by casigus** [comment] 2022-08-06 13:59
rolled max back to the previous build. works fine. (WELL AS it should in early acccess) :)

**Comment by casigus** [comment] 2022-08-06 14:03
![image](https://user-images.githubusercontent.com/68471279/183252202-324e26a2-c7ee-4b95-baff-b7a7dc27dc13.png)

anddddddddddd

![image](https://user-images.githubusercontent.com/68471279/183252216-e31474a9-694b-46a8-a68e-669c7f7def68.png)

**Comment by earthling45** [comment] 2022-08-06 14:46
> Hi all., we've really sorry that you're experiencing these crashes. To help Lee, if it's happening to you, could you please post your system spec in this thread. I know some of you will already have posted them else where, but it speeds thing up if we can find them quickly.
> 
> Many thanks,


I doubt that system specs are going to be of any help, these crashes seem to be quite randomly happening.
Yesterday i did some quite heavy stuff without problems but then suddenly, even without doing anything fow a few moments it crashes to desktop.

**Comment by synchromesh62** [comment] 2022-08-06 20:39
Have not had had a crash all day so far .. Definitely a weird one ?

**Comment by MonkeyFrogStudio** [comment] 2022-08-06 21:20
> Have not had had a crash all day so far .. Definitely a weird one ?

Meanwhile, all was going well with me and MAX and then ... blam! Out of the blue it just disappeared ... Sigh.

**Comment by Jisafu** [comment] 2022-08-07 08:24
After 5 to 10 minutes i also get random crashes with the new update.

Apparaatnaam	LAPTOP-HA50VRA7
Processor	Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.59 GHz
Geïnstalleerd RAM-geheugen	16,0 GB (15,9 GB beschikbaar)
Apparaat-id	4CEAAEC3-D035-43BF-8B1D-F1528D32E4A9
Product-id	00325-81133-26435-AAOEM
Type systeem	64-bits besturingssysteem, x64-processor
Pen en aanraken	Pen- of aanraakinvoer is niet beschikbaar voor dit beeldscherm
Editie	Windows 10 Home
Versie	21H2
Installatiedatum	‎14/‎03/‎2021
Build van besturingssysteem	19044.1766
Ervaring	Windows Feature Experience Pack 120.2212.4180.0

**Comment by Jisafu** [comment] 2022-08-07 10:23
I put it back to the previous version, and now it works fine

**Comment by AmenMoses** [comment] 2022-08-07 11:48
Started up Max after the latest update finished, played synchromesh demo, crashed out when shooting first zombie.

Off back to O3DE until next update.

**Comment by LeeBamberTGC** [comment] 2022-08-08 10:16
Thanks everyone for reporting quickly! Looks like one of those that cannot be reproduced with a simple step-by-step. I will go through every change in code since the last good update (was this the 2022.08.02 or the 2022.07.22)?  Had 18 messages on Steam over the weekend, I feel an emergency fix coming on :)

**Comment by Tam51** [comment] 2022-08-08 10:29
Hi Lee I found the 2022.08.02 didn't crash on me but as soon as it went to 2022.08.05 it did random crashes and closing down GGmax. 

THK
Tam51

**Comment by LeeBamberTGC** [comment] 2022-08-08 10:50
@Tam51 That's great to know! Narrows down my hunt considerably.

**Comment by synchromesh62** [comment] 2022-08-08 11:01
@LeeBamberTGC 
If you want to see the crash in action it happened in your stream this week a few seconds after 6:15
You were sent straight back to desktop with no warning May give you a clue to what you were working on at the time ?

**Comment by LeeBamberTGC** [comment] 2022-08-08 11:55
@synchromesh62 Yes I did go back and check that useful piece of footage, though completely random as everyone has reported. The good news is that once I knew it was introduced between 08.02 and 08.05 I could do some focusing. I have discovered I am pushing more than I am popping with ImGui which historically does produce random nasties when you do that, related to the new compact object placement system (which fits the timeline). Going through code now. P.S Also fixed two other bugs while I was hunting for this one which is a bonus. New update planned for later today.

**Comment by LeeBamberTGC** [comment] 2022-08-08 13:08
ALL: New EXP and PP builds up which should fix the issue of the random crashing.  I will test for an hour, then make it public to all MAX users.  Thanks again for the quick action!

**Comment by LeeBamberTGC** [comment] 2022-08-08 14:07
New Steam update live with the fix of the crash issue. An hour's testing of all the demo games and a custom level performed but a confirmation of the fix will be much appreciated. For my test, I made an Artic battle scene, ten futuristic characters fighting it out with laser pistols and hammers :)

**Comment by casigus** [comment] 2022-08-08 14:22
if I had a hammmerrrrrrrrrrrrrrrrrr i'd hammer in the morningggggggg. yeah ill have a check now.

**Comment by earthling45** [comment] 2022-08-08 14:33
I think it is fixed indeed, had no problems while working and playing some. :)

**Comment by Tam51** [comment] 2022-08-08 15:09
It's not crashed on me now so I think it's fixed. Had no problem importing objects and playing with lighting.

**Comment by LeeBamberTGC** [comment] 2022-08-08 15:33
Thanks for confirming :)

**Closed by LeeBamberTGC** 2022-08-08 15:33 UTC
Labels: Urgent, Fixed but need confirmation., Max, CRASH!

**Comment by Jisafu** [comment] 2022-08-08 16:07
It works fine for me now, thanks Lee
