### ISSUE TITLE
MAX - SSAO does not affect terrain/generated trees/etc.

### ISSUE THREAD

**Issue by fearlesswee** [TheGameCreators/GameGuruRepo#3208] opened 2022-05-28 12:14 UTC
Currently SSAO only affects user-placed objects, and doesn't apply to the terrain or generated trees. This greatly reduces the effect of SSAO outdoors, which a shame because SSAO adds an extreme level of visual depth to a scene, and if it worked outdoors it would really boost MAX's visuals.

**Comment by MonkeyFrogStudio** [comment] 2022-05-28 13:45
Reported here:

https://github.com/TheGameCreators/GameGuruRepo/issues/2937

**Comment by ZakJudges** [comment] 2022-05-30 09:16
Hi @fearlesswee, thank you for reporting this issue. I will close this as it is a duplicate of #2937. Feel free to check that thread for more info in the future :)

**Closed by ZakJudges** 2022-05-30 09:16 UTC
