### ISSUE TITLE
Importer thumbnail not recognising emmisive textures.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#5230] opened 2024-02-06 16:55 UTC
This model is of an neon sign, in the importer it looks like this:

![Importer](https://github.com/TheGameCreators/GameGuruRepo/assets/99803873/d9b92760-272f-4556-af82-1c77ef7a6f47)

However, the importer generates a thumbnail like this:

![Thumbnail_generator](https://github.com/TheGameCreators/GameGuruRepo/assets/99803873/6b301630-4a9d-4c3a-8347-f0658efed71f)

**Comment by Melburnian70** [comment] 2024-02-07 23:52
Thanks Dave. 

Just to add more context: this object that I created has multiple materials which I think is the cause of the thumbnail generator not using the emissive parameters. 

Thumbnails of single-material objects with emissive textures work correctly.

Cheers,
Roberto

**Comment by LeeBamberTGC** [comment] 2024-02-12 13:51
@Melburnian70 If you can email me (lee@thegamecreators.com) the model/textureset you are attempting to import, I can confirm and fix the emissive issue, thanks!

**Comment by LeeBamberTGC** [comment] 2024-02-12 14:51
@Melburnian70 Fixed for next EXP build:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/d4aca31c-be51-48ed-b709-89405a46d8dd)

**Comment by Melburnian70** [comment] 2024-02-12 21:27
Thanks @LeeBamberTGC I can confirm that's fixed now!

Cheers,
Roberto

**Closed** 2024-02-13 10:41 UTC
Labels: bug, Fixed but need confirmation., Max, High, Importer
