### ISSUE TITLE
GameGuru MAX - Bug - Changing Texture Not Saved

### ISSUE THREAD

**Issue by MonkeyFrogStudio** [TheGameCreators/GameGuruRepo#3536] opened 2022-08-02 07:22 UTC
If I select an object, go to the Materials tab, and select a new Albedo texture for it, after saving the level and restarting MAX, the original texture is still applied and the new one forgotten. As a result, I cannot change a texture on an individual object if I want to.

**Comment by Kitakazi** [comment] 2022-08-29 20:00
I've been having something similar happening since the last update. 

I select an object, go to Materials tab and select a new Albedo Texture, or I change the color of the Albedo texture, once I select a different entity it will change back to its previous state before I made any changes. Sometimes simply selecting this entity again will switch it back to the changes I had just made. 

Seems this bug has plagued GGMax since its creation.

**Comment by ZakJudges** [comment] 2023-01-04 12:23
Hi @MonkeyFrogStudio, I wasn't able to reproduce this issue. Do you still experience it in the latest build?

**Comment by ZakJudges** [comment] 2023-02-16 09:37
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks

**Closed by ZakJudges** 2023-02-16 09:37 UTC
Labels: bug, Fixed but need confirmation., Max, Waiting for more information., Medium, Level Editor
