### ISSUE TITLE
GGMAX Bug - Assets move on their own when loading level

### ISSUE THREAD

**Issue by ZD-ZMA** [TheGameCreators/GameGuruRepo#5614] opened 2024-07-07 08:20 UTC
![Screenshot (294)](https://github.com/TheGameCreators/GameGuruRepo/assets/124307560/d1acd4fe-e26e-47bf-b9b4-1242289f7d6b)
items keep moving on its own everytime i close and reopen the level. 
![Screenshot (295)](https://github.com/TheGameCreators/GameGuruRepo/assets/124307560/f1aea4a5-b6ca-4906-9695-e93d67a75505)
this is how its supposed to look. everytime i close and reload it, it reverts back to the first image. (also im saving after i fix it. i even added stuff to see if the save is working and it is, its just these 4 items that keep glitching)

**Comment by ZD-ZMA** [comment] 2024-07-07 08:21
i also want to add the fact that these exact 4 items are on the opposite side of the area and those 4 assets dont glitch... only theses specific 4 keep glitching.

**Comment by Kasseyus** [comment] 2024-10-12 07:45
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.

**Comment by ZD-ZMA** [comment] 2024-10-20 05:57
i havent had much issue with this bug however i havent gone back to that level to really check. i finished what i needed to do on the level and moved on to another level. (im working on level 8 which i ran into a new bug... which i opened up a report on it)

**Comment by Kasseyus** [comment] 2024-10-20 22:57
@ZD-ZMA Are these grouped smart objects?

**Comment by ZD-ZMA** [comment] 2024-10-20 23:18
yes. ones i did myself

**Comment by Kasseyus** [comment] 2024-10-21 07:48
@ZD-ZMA So far, I have not been able to re-create this issue.  It's possible that this issue was fixed in an intervening patch.

If you return to that level and the issue is still present, or if it crops up on one of your current projects, please reply top this issue and I will re-open and investigate.

**Closed by Kasseyus** 2024-10-21 07:48 UTC
Labels: bug, Max, Waiting for more information., Medium, Level Editor
