### ISSUE TITLE
Map Change

### ISSUE THREAD

**Issue by bbacle** [TheGameCreators/GameGuruRepo#3343] opened 2022-06-23 15:58 UTC
I have made a few games with previous builds, but when I update the build, my game either is not recognized anymore or the map gets changed to the default map.
Can you explain to me why this is happening?
And can you make it so that we can change maps on our games without losing all of our work & assets that we have put in?
Thanks.

**Comment by ZakJudges** [comment] 2022-11-10 16:33
Hi @bbacle, are you still experiencing this in the latest Steam build?

**Comment by bbacle** [comment] 2022-11-10 17:37
WOW...just now getting a response on this nearly 4 months later.
Honestly I kind of gave up on GameGuruMAX for now since it wouldn't let me create my own map & it kept losing stuff I had in there from previous builds.
The previous builds are now recognized, but stuff is still missing in them.
I have deleted some of them & have not done anything else with it.

**Comment by ZakJudges** [comment] 2022-11-11 09:34
@bbacle Apologies for the late response! Were you using the TGC updater before the switch to Steam-only? If so, your lost files will likely be backed up with your writable folder (usually located in Documents -> GameGuru Apps -> GameGuruMAX). The backup folder would be named GameGuruMAX, followed by numbers, for example "GameGuruMAX0908372021-12-07"

**Comment by ZakJudges** [comment] 2023-02-03 15:03
Hi @bbacle, are you happy for this issue to be closed? It sounds like a problem caused by the updater before the switch to Steam (see comment above)
If you continue to experience the issue, please load up a map with the missing assets and attach the .log file that gets generated in the mapbank folder. Thanks!

**Comment by ZakJudges** [comment] 2023-02-16 09:32
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks

**Closed by ZakJudges** 2023-02-16 09:32 UTC
Labels: bug, Fixed but need confirmation., Max, High
