### ISSUE TITLE
GGMAX Bug - Graphics Settings of Medium or Low effect Grass Placement

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5550] opened 2024-05-19 08:52 UTC
Look at the video I found the problem of the grass on the road are the settings high, low, medium (graphics)

https://youtu.be/5KuHPtV1lK4

**Comment by LeeBamberTGC** [comment] 2024-08-04 22:50
@SampeyFS Can you create a fresh blank FPM level with just a path and some grass and recreate this issue when I set the graphics setting to LOW or MEDIUM. Doing it this way I can reproduce the issue very quickly and find the bug.

**Comment by Kasseyus** [comment] 2024-10-11 22:57
I’m currently in the process of going through all the outstanding issues.  As this ticket is over a month old, I'm just checking to see if you are still having a problem with this, or if the matter has since been resolved, either through an update to the engine, or if the issue was resolved when another, similar issue was fixed.

Please let me know by replying to this issue and I will investigate further.

**Comment by SampeyFS** [comment] 2024-10-12 06:55
The problem is still present

**Comment by Kasseyus** [comment] 2024-10-16 19:52
@SampeyFS So far, I am unable to rre-create this isssue...

https://github.com/user-attachments/assets/2701b0e2-b9f1-46e7-b591-6cd9c960b69a

Can you create a short video of the process you took to lead up to see this bug?

**Comment by SampeyFS** [comment] 2024-10-16 19:56
the empty map with the terrain did it for me with the one without anything

**Comment by SampeyFS** [comment] 2024-10-23 21:22
it's the desert template that does it like this others don't do it here is the FPE

https://bestfile.io/FPcFIrLCh2I3Hgv/file

**Comment by Kasseyus** [comment] 2024-12-10 00:04
In this instance, I believe the problem may be in how the grass is placed in the world.

If an area of the map is assigned grass, then the density of the grass can be controlled in the editor, but adjusting the graphics setting in the standalone game can increase the quantity of grass, and the position of the grass.  It looks like the area of your map that had had roads assigned to it, also allows grass to appear there, and when the settings are adjusted to a higher quality, more grass appears in more random locations - in this case in the middle of the road.

The solution to this is to draw out the areas of your roads to make sure the engine doesn't put any grass there at all.  (with the grass painting tool, it will not affect the textures you have already painted)

On some terrain biomes where grass is spawned by default, drawing new terrain will also get rid of the grass, but in instances where this is not the case and grass has been painted on, it will remain there irrespective of the texture painted over the top of it.

If you find this problem persists, please let me know by replying to this ticket with a custom FPM file, containing only stock media that I can use to diagnose the issue, and I will be able to investigate further.

**Closed by Kasseyus** 2024-12-10 00:04 UTC
Labels: bug, Max, Medium, Visual Quality
