### ISSUE TITLE
Meshes sharing material - importer [GGMax]

### ISSUE THREAD

**Issue by 3coms** [TheGameCreators/GameGuruRepo#3064] opened 2022-05-07 13:16 UTC
@ TGC
Hi

**The issue**
I have a mesh ( a house), and I've modeled and exported it as OBJ from 3ds max, when try to import it, GGMax talks about the mesh being up to 100 materials; that's the issue. 

**What's going on**
My mesh (a house plus exteriors) is a composed mesh, compound by just 8 pieces, all of them sharing material, so, really is 8 materials nor 100+ as GGMax says.

**What you should do**
Please, take into account the meshes sharing the same material, so, if I have 80 chairs sharing the same wood material, they are not 80 materials, but just 80 meshes sharing the same material.

In my case, I have a fence surrounding the house, of course, it is several walls that compound that fence, but they share the same material, so, here really are 1 material and 1 mesh named fence. (all the walls are merged into 1 mesh using 1 material)
 Now in my material list, I have several:

1-brick sidewall
2-brick sidewall
3-brick sidewall
and so on, till almost 40, when it is a was merged as just 1 mesh named "fence" using/sharing the same material; it should be really listing the 8 materials I'm using for, since I can't interact with those meshes individually, just with 1 mesh(the fence), so, why I want 40 side walls?

The material list should be material-based nor mesh-based, at least I'm able to work with each piece that compounds let's say a stair.

**Comment by MonkeyFrogStudio** [comment] 2022-05-07 17:13
Question - Why are you using OBJ as a file format for something like this? OBJ is an old and obsolete file format. The issue you are encountering may not be the fault of the MAX importer per se, but may be the fault of the OBJ .mtl file. I'm just guessing since I don't have the .mtl file at hand to look at. But you can open it as it's a simple text file and see what's inside. In any case, OBJ is great for single models with simple materials these days, but it's an old and outdated file format that should be mostly avoided for the most part. I mean, it was originally created in the 1980s! Is text based, slow, and inefficient.

Have you tried using FBX? Or, for a case like your house with shared materials/textures, GLB/GLTF? GLB/GLTF was created specifically for exporting/importing entire scenes.

**Comment by 3coms** [comment] 2022-05-07 19:18
@MonkeyFrogStudio 
Thanks for your input but I'm hoping for an answer from TGC whom the question was for. :)

**Comment by 3coms** [comment] 2022-05-07 23:05
@ TGC
I've finally managed to import the home mesh, of course, just with 99 materials; therefore, objects such as the water pool are metallic, rather than blue watercolor (red arrow in the pic below)
so, the lack of materials was replaced with metallic ones by GGMax. :)

![myhome1_UP100_mat_GGMax_EA_pic01](https://user-images.githubusercontent.com/47690174/167274730-fac6b814-48e4-408c-81ba-45d42cbfdc1b.png)

**Comment by OldFlak** [comment] 2022-05-08 13:55
Matters not the format - MAX should do them properly :)
- Maybe MAX is having a fit due to so many textures? 

Don't have any issues here with OBJ or even X - old formats perhaps, but they still work just fine.

FBX never comes in correctly for me - always have to rotate them 90 degrees - whereas OBJ and X come in correctly every time.
- FBX does come in with all textures applied already, so that is great.
- I wonder about the precision for modular stuff tho if you have to rotate them all - which is why I use OBJ for modular

**Comment by ZakJudges** [comment] 2022-05-09 14:49
Hi @3coms, our current plan to handle this is to combine any meshes that share the same material ( see #2805). At present the importer assumes that any meshes that share the same material will have already been combined into a single mesh before importing. More on this in the future :)

**Comment by 3coms** [comment] 2022-05-09 15:42
@ZakJudges 
Right now GGMax is duplicating textures in my mesh folder, so, now I originally had let's say mymesh_color and mymesh_normal, now I've:
mymesh_color.png
mymesh_colo1r.png -- duplicate by GGMax after the first attempt to fix the texture path
mymesh_color2.png -- idem second attempt

![Duplicating_material_GGMax_EA_pic02](https://user-images.githubusercontent.com/47690174/167446368-6ecb6258-09c7-46bb-a12a-767cf1f1893b.png)

![Duplicating_material_GGMax_EA_pic01](https://user-images.githubusercontent.com/47690174/167446704-1be82f4f-a9fd-4668-860a-fe22e97750b7.png)


Although I know this is temporary so, don't worry about it, just as info :)

**Comment by 3coms** [comment] 2022-05-09 16:09
@ZakJudges 
Notice here on the pic below, that the mesh ( a rock) has several minerals attached to it, however, all that's minerals are just 1 mesh
and 1 texture nor 100 textures.
And for any reason GGMax this time do the right way; gets the mineral mesh as just 1 mesh, therefore just 1 material, please refer to the pic below. This is the way I'm requesting here, rather than allow a ton of materials, just get those meshes sharing the same material into one, as GGMax did in the pic below. :)

![Ground_Import_OBJ_GGMax_EA_pic02](https://user-images.githubusercontent.com/47690174/167451354-648e8b52-e381-4903-b170-7182219bfbe5.png)

You can notice the minerals clearly because of the emissive turning all-white color when you try to set some glow, but this is another different thread. :)

**Comment by ZakJudges** [comment] 2022-05-10 08:13
@3coms Could you send me the models and textures and I will take a look :)

**Comment by 3coms** [comment] 2022-05-10 10:15
@ZakJudges 
Done :)

**Comment by ZakJudges** [comment] 2022-05-31 15:48
duplicate of #2805

**Closed by ZakJudges** 2022-05-31 15:48 UTC
Labels: bug, duplicate, Max, Importer
