### ISSUE TITLE
GG Max - bulletholes appear (or not) randomly

### ISSUE THREAD

**Issue by Ghost-l0l** [TheGameCreators/GameGuruRepo#3102] opened 2022-05-11 21:55 UTC
https://youtu.be/8-YcbBNVFhE - video is stuttering a little, but that's fault of Obs recording, not Max :)

**Comment by LeeBamberTGC** [comment] 2023-09-15 20:20
@Ghost-l0l Fixed in latest EXP Build was caused by ripple decal effect hiding decals that could not be reused for muzzle flashes and bulletholes.

**Closed** 2024-09-13 16:17 UTC
Labels: bug, Fixed but need confirmation., Max, Weapons, Visual Quality
