### ISSUE TITLE
[GGC] Lightmapping issue: AO map compression matters

### ISSUE THREAD

**Issue by AvengingEagle** [TheGameCreators/GameGuruRepo#1130] opened 2021-05-05 22:23 UTC
I'm getting a weird intermittent issue when I lightmap this metal cage entity I got from Sketchfab. I have optimised the model by saving the original jpg textures as dds. Since the AO, metalness, and gloss maps are grayscale, I should be able to save those using BC4 compression, a format specifically designed for grayscale. However, when I save the AO map as BC4, the cage lightmaps red. If I save the AO map as BC1 dds, this doesn't happen. 

First image shows two cages in a level prior to lightmapping (it has already been lightmapped once without them, then I added them). The cage on the left has an AO map saved as BC4 dds, the one on the right has a BC1 dds. 

![snapshot124](https://user-images.githubusercontent.com/60984223/117216078-20938c00-adf7-11eb-9432-d7aaf9adfd09.jpg)
 
This is what they look like after lightmapping, note the red colour on the one on the left.

![snapshot125](https://user-images.githubusercontent.com/60984223/117216143-3608b600-adf7-11eb-950d-4e2cbdb09cd1.jpg)

This appears to be an intermittent issue as I have other assets that have BC4 dds AO maps that do not turn red when lightmapped. But it broadly falls into the category of "entities not looking right once lightmapped", of which I have documented many different symptoms (see the other issues I've raised!)

Why does this matter?
BC4 compression is the preferred compression method for grayscale texture maps because it contains only one channel of information; luminance. This means it can accurately replicate the full 256 shades of grey present in 8-bit colour. BC1 compression on the other hand, whilst using the same amount of bits, has to store three channels of colour so just compresses the colours more, resulting in artifacting. In the case of an AO map, this might result in sub-optimal rendering of ambient occlusion.

**Comment by plemsoft** [comment] 2021-05-18 12:36
@AvengingEagle Thanks for reporting this issue, i was not able to reproduce it.

I tried all the different format BC4 unorm and snorm and other formats, but all worked fine with and without lightmapper. so it must be something else, could you e-mail the object so im able to test it here ? : plemsoft@plemsoft.com

Thanks for your help :)

![ao-problem](https://user-images.githubusercontent.com/18662417/118651979-63d1ff80-b7e6-11eb-9bd3-9a06c8e04ea2.jpg)

**Comment by plemsoft** [comment] 2021-05-19 09:04
@AvengingEagle Tried the model you e-mailed me with the bc4 texture and it worked fine here ?, Im not sure about that red color it could look like its the "selection" color , what happens if you save the map and reload it , is it still red ?

![ao-problem2](https://user-images.githubusercontent.com/18662417/118786268-ed8ad700-b891-11eb-9d12-3642e2a23dc0.jpg)

**Comment by plemsoft** [comment] 2021-05-19 09:07
BTW: What graphics card are you using ?

**Comment by AvengingEagle** [comment] 2021-05-19 22:22
How strange, I now can't replicate the issue. I was having it on two separate maps, and I had tried reloading, and re-lightmapping numerous times. I haven't changed anything about the model, the AO map is still in BC4, I haven't updated Game Guru, and I haven't installed any new graphics drivers. I'm running a 1050ti btw.

**Comment by plemsoft** [comment] 2021-05-20 07:38
@AvengingEagle Yes this is a strange one ? , anyway i will close this , if you see it again just open a new issue, but somehow it looks like if you press F9 press E and point at a object, it would look just like that (could that have been triggered somehow? ) strange one :)

**Closed** 2021-05-20 07:38 UTC
Labels: Answered, GGClassic
