### ISSUE TITLE
MAX - Editor Issues - Numeric Inputs 

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#1851] opened 2022-01-27 04:10 UTC
The editor has a ton of issues with how it retrieves settings for numeric inputs and when trying to adjust the values.
You see this in multiple areas from a models scale settings to water.

It seems to affect every numeric input value if you try editing it enough times.

Here be a collection of some of the more recent ones I have recorded.
Camera
https://www.youtube.com/watch?v=Y7823-JM-F0
Lights
https://www.youtube.com/watch?v=-kwMNJHmRRw
Water
https://www.youtube.com/watch?v=TQWXQ-X8w-I

**Comment by ZakJudges** [comment] 2022-02-21 16:20
@OldFlak Many thanks for reporting these issues :)

I've added some fixes which see the camera and light issues fixed. As for the water problem, I could not reproduce in the latest build, do you now see the same?

**Comment by OldFlak** [comment] 2022-02-22 11:31
@ZakJudges Hi Zak thanks for looking into it.

The issues is still there for the last in put in water settings
https://youtu.be/x2mgMOEnJQU

There are quite a few errors still with the editor
- The Color Chooser is still broken 
- Max puts random settings in the last audio slot
- Can't delete a reference to an unwanted emissive texture in the importer
- Scale X, Y, and Z for selected models do not show correct value. No doubt because the input won't allow a whole number like 10 and just drops it back 1 digit to 9

To name a few.

**Comment by OldFlak** [comment] 2022-02-24 11:27
@ZakJudges Thanks will check with Friday release. 

You may want to go through and check every numeric input - just noticed fog opacity does the same. Example: type 15, editor will drop it back to 14 - there really seems to be an ongoing issue with the controls used for the UI :)

Have added issues for other points :)

**Comment by OldFlak** [comment] 2022-02-24 21:24
@ZakJudges Hi Zak - the issue persists in today's build.

**Comment by OldFlak** [comment] 2022-02-28 12:20
@ZakJudges Hi Zak - FYI - Not fixed in Monday's build - type 15 and value drops back to 14

**Comment by ZakJudges** [comment] 2022-02-28 12:24
@OldFlak Looks like my changes have only just been merged. Will be in the next internal build. I imagine Lee will email soon :)

**Comment by ZakJudges** [comment] 2022-02-28 12:32
@OldFlak Scratch that, it should be in tomorrow's build. Apologies :)

**Closed** 2022-04-03 09:39 UTC
Labels: bug, Fixed but need confirmation., Max, High, Level Editor

**Comment by OldFlak** [comment] 2022-04-04 11:20
No not fixed - almost but not completely :)

You need to test every available numeric input
Affected Controls:
- Water Patch Size - try setting to 30
- Camera (first vid in op - still same issue

**Comment by rvanner** [comment] 2022-04-04 12:16
@ZakJudges Please fix the items mentioned above.
