### ISSUE TITLE
GG max (copy item bug)

### ISSUE THREAD

**Issue by Keepo1** [TheGameCreators/GameGuruRepo#4744] opened 2023-06-26 19:35 UTC
you can no longer duplicate item by holding shift

**Comment by MonkeyFrogStudio** [comment] 2023-06-27 04:39
Same here. Really want to see this back.

**Comment by davetgc** [comment] 2023-06-27 08:06
Not sure if this was removed, but I'm listing it as a bug.

**Comment by LeeBamberTGC** [comment] 2023-06-27 18:39
@Keepo1 @MonkeyFrogStudio @davetgc There was an obscure bug that meant if you clicked object A, then held SHIFT, then clicked object B, it would duplicate object B and require the user to click again to free the object from being associated with the cursor, which in turn caused the multi-object highlighter to go haywire. The above sequence was prevented as it was a bug.

The intended way for the SHIFT to work for duplication is to select an object from the left panel, hold down SHIFT, and then place all your duplicates, and on your last object to place, release the SHIFT and place it down.  The basic upshot is that you need the object attached to your cursor FIRST before you can hold SHIFT and make duplicates.

**Comment by MonkeyFrogStudio** [comment] 2023-06-27 19:14
@LeeBamberTGC When you say, "The intended way for the SHIFT to work for duplication is to select an object from the left panel ..." are you referring to the Current Object panel? If that's the case, then it's not needed because dragging (without SHIFT depressed) already produces a duplicate of the currently selected object. But that's not quite as nice as being able to SHIFT+CLICK and drag out a duplicate directly in the viewport. What I've found works best is doing this with the widget/gizmo turned OFF. So, it's SHIFT+Click on the object and the object is then attached to the cursor until you click again to place. With the gizmo/widget active, it did, indeed, create a duplicate in place requiring an additional click to grab one of them for positioning.

If possible, it would be great to retain this functionality in the viewport. But I would recommend that SHIFT+Click be DISABLED when the gizmo/widget is active and ENABLED when the gizmo/widget is DISABLED. Thus, a simple click of F1 would either 1) enable SHIFT+Click to duplicate in the viewport while also DISABLING the widget or 2) enable the widget but DISABLE SHIFT+Click in the viewport for duplicate.

Just a thought.

**Comment by LeeBamberTGC** [comment] 2023-06-28 16:14
@MonkeyFrogStudio Nice idea, and it works too. Is in the next EXP build :)

**Comment by MonkeyFrogStudio** [comment] 2023-06-30 11:41
Working on my end! Thanks for the quick fix!

**Closed** 2023-06-30 20:36 UTC
Labels: bug, Fixed but need confirmation., Max, Medium, Level Editor
