### ISSUE TITLE
Runtime Error 7018 ()

### ISSUE THREAD

**Issue by Ohneiros** [TheGameCreators/GameGuruRepo#3600] opened 2022-08-13 07:06 UTC
Cheers! Since last update I get 5 of these - consecutive - when I first run one of my levels. Any ideas? 
![Error](https://user-images.githubusercontent.com/10661202/184473779-ba2fbea3-df6d-4fac-ab42-a90b26bbd7f8.png)

**Comment by davetgc** [comment] 2022-08-14 12:16
This error is caused when MAX has failed to load a 3D object. Have you added anything new since the last update?

**Comment by synchromesh62** [comment] 2022-08-14 12:45
Verifying often fixes this one .. 
Sometimes updates do not initially sit well and a reboot after is also a good idea.
Hope that helps.

**Comment by Ohneiros** [comment] 2022-08-14 14:36
Tried verifying files, but that didin't do the trick. I think it might have to do with an EBE I placed before the update: after updating the EBE was texture-less, which was easily fixed by its edit mode. The error started springing immediately after that.

**Comment by davetgc** [comment] 2022-08-14 16:28
Can you try removing that object and testing again please?

**Comment by Ohneiros** [comment] 2022-08-14 18:04
Yes, I already tried that, but to no avail. I also tried deleting all the other EBE structures, plus some items that were left over a previously used part of the level. Sadly the error is still there.

**Comment by davetgc** [comment] 2022-08-14 18:18
Ok, does it happen on a fresh level.

**Comment by Ohneiros** [comment] 2022-08-14 18:25
Nopes, it doesn't happen in any other level, old or new. Just this one.

**Comment by Ohneiros** [comment] 2022-08-14 18:34
Interestingly, when I tried to save the object as an entity, it made the engine crash. I deleted it - although it did not save in the library *sigh* -, however, the problem still persists. Another curious thing: if I try to save an object with the name I gave to the EBE structure, it says the object already exists, although it doesn't apper in the library.

**Comment by davetgc** [comment] 2022-08-15 08:09
To be honest, the EBE isn't supported as it's a legacy feature. My advice would be to try to track down the offending model, as it's not happening on other levels, it's an issue with a single model.

**Comment by Ohneiros** [comment] 2022-08-15 17:14
.I believe I found the problem; somehow the last update made a .x model to "teleport" outside of the editable area. I'm guessing that's the one that can't be loaded, since it is in the list of objects, but outside of the area that is executed when running the game. I would need instructions to move (ideally) or delete such model, since I cannot click on it to get any kind of interface. Maybe we would need a way to delete/move entities from the drop list as a feature.
![Entity](https://user-images.githubusercontent.com/10661202/184682962-3c94d840-6017-4449-a9a5-191e87e2bb81.png)

**Comment by Ohneiros** [comment] 2022-08-15 17:18
New update: I managed to grab the entity by one tiny corner and drag it again inside the editable area. Sadly, the error still remains.

**Comment by Ohneiros** [comment] 2022-08-15 20:55
Ok, last update of the day: I found several items that had been clone several times by unknown reasons. After deleting all of them I check all the level files, and everything seems to be in its place; however, the error keeps appearing, now in successions of 7 instead of 5. If I had to guess, I'd say there is a list of items somewhere that is looking for items that have been deleted. Any ideas? Thanks!

**Comment by Ohneiros** [comment] 2022-08-26 15:21
I entered the .lst file and deleted some items that were listed but linked to no entities in the level. This brought the error warnings from 8 down to 5, but they're still there. I'm at a loss of what else to do. Any thoughts? Thanks!

**Comment by ZakJudges** [comment] 2023-02-03 14:39
Hi @Ohneiros, apologies for the late response. Are you now happy for this issue to be closed? 
As a side note: when using GameGuru Classic entities, I would recommend bringing them into Max via the model importer, to ensure they are set up correctly. It is possible that is the cause in this case.

**Comment by ZakJudges** [comment] 2023-02-16 09:37
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks

**Closed by ZakJudges** 2023-02-16 09:37 UTC
Labels: bug, Fixed but need confirmation., Max, High

**Comment by Ohneiros** [comment] 2023-02-16 18:26
Never saw the previous email, a thousand apologies! The issue is fixed and
advices noted, thanks!
