### ISSUE TITLE
GG Max - Bug - Building Editor

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#4144] opened 2023-02-03 19:18 UTC
Look the the screenshots.
This is a very simple log cabin created using building editor.
You can see that the Windows are all messed up, and one of the doors is messed up.

You have used a very BUGGED system with the SMART OBJECT system to create the new building editor. 
If you want to use the SMART OBJECT system for this, Then fix the SMART OBJECTS first.
You cannot even create simple buildings due to bugs like these.

![1](https://user-images.githubusercontent.com/66874403/216688758-83de54cd-bf3e-424b-b6ce-4f22a4bb248f.png)

![2](https://user-images.githubusercontent.com/66874403/216688780-0f309625-e2be-4872-83e0-2da9632b4987.png)

https://github.com/TheGameCreators/GameGuruRepo/issues/3402
https://github.com/TheGameCreators/GameGuruRepo/issues/3219

I have linked to 2 other Group Objects bugs, i guess these are all related to a BUGGED Smart Object system, that has not been fixed.

**Comment by ZakJudges** [comment] 2023-02-17 11:56
Closing as duplicate of #3961

**Closed by ZakJudges** 2023-02-17 11:56 UTC
Labels: bug, Urgent, Max, Building Editor
