### ISSUE TITLE
Crash when creating a smart object from 3 characters

### ISSUE THREAD

**Issue by LeeBamberTGC** [TheGameCreators/GameGuruRepo#2078] opened 2022-02-11 18:49 UTC
Crash when creating a smart object out of 3 characters. Like last week, I couldn't reliably reproduce this one. But here are the steps I took before the crash:

Place a character in a level - I used Tony Armed Response
Copy and paste the character a couple of times
Group the characters and create a smart object out of them
Press "Add to Object Library" at the thumbnail creation and sometimes the crash will occur.

**Comment by ZakJudges** [comment] 2023-02-17 13:04
Closing this issue: was caused by trying to render images that were deleted.  Has since been fixed

**Closed by ZakJudges** 2023-02-17 13:04 UTC
Labels: bug, Max, CRASH!, Object Placement
