### ISSUE TITLE
Duel Screen Monitor Issue with ActivateMouse

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#833] opened 2020-09-21 14:50 UTC
When in using Duel Screen Monitors and using ActivateMouse Lua command, in Test Mode if you happen to click outside of the screen, it will sometimes interact with the duel screen monitor and start clicking icons on your desktop if you are clicking the mouse within your test map.

This issue also sometimes makes it so the mouse is interacting with the taskbar which ends up closes GG engine or leaving the focus and starts displaying the taskbar over the test mode.

Windows 10

**Comment by Teabone3** [comment] 2020-09-21 16:22
Just want to add, this doesn't occur when the mouse is off the screen, but actually when the mouse cursor is anywhere less than 50% of the width of the screen. My duel screen being to the left. I would assume if I assign to the right this issue would then occur when the cursor is more than 50% on the screen in width position. 

I've not tested if this occurs in standalone (if not, its not a huge issue then)

**Comment by plemsoft** [comment] 2020-11-13 13:34
@Teabone3 Thanks for reporting this issue,

Sorry cant test this, but are you running GG on your main monitor or the additional monitor ?

**Comment by Teabone3** [comment] 2020-11-17 16:19
Just did an additional test with just one monitor and the issue doesn't seem to occur. Only with duel screen.

I'm going to test if this happens with other engines or games in full screen while using Duel screen. As it may be a Windows 10 issue and not GG Classic. Will report back on this.

Game Guru was running on my main menu

**Comment by Teabone3** [comment] 2020-11-18 00:45
Sorry cant test this, but are you running GG on your main monitor or the additional monitor ?

Yep

**Comment by michaeloldman** [comment] 2020-11-18 00:50
I have a three monitor setup and notice this issue as well using AmenMoses flight script, which uses the cursor to show cross hair, and the flight is controlled by the mouse.
The problem is that the mouse cursor can leave the Primary Screen and the cursor can click on stuff on any of the other two screens - and it kinda destroys the game play.

What we need is for the mouse coordinates to be contained with in the Primary Screen space. Other games I have do this, and the only way to get the cursor to go on the other screens is to use the Win key to interrupt the game.

OldFlak....

**Comment by plemsoft** [comment] 2020-11-23 07:53
Thanks both for helping solving this issue , this has been fixed and will be in the next update :)

**Closed** 2021-01-20 13:34 UTC
Labels: bug, fixed
