### ISSUE TITLE
Zombie Collision issue.

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#2420] opened 2022-03-06 11:42 UTC
Zombies can be shot and pushed back through walls

**Video**

https://youtu.be/caplLHKzUa0

**Comment by Tum1370** [comment] 2022-03-06 13:48
Zombies still walk through doors when they are shut, This has been reported and was suppose to of been fixed a while ago.

**Comment by synchromesh62** [comment] 2022-03-06 13:58
> Enemies can still walk through doors when they are shut, Guess collision is still a ongoing bug.

Its never been fixed but is being worked on
Characters have always been able to walk through Dynamic objects like doors.
Some kind of blocker is needed for when a door is shut. 
But that is not related to this as the walls are static.

**Comment by Retrogamebloke** [comment] 2022-03-06 19:00
As an additional to this I have noticed sometimes you seem to shoot straight through the zombies completely even at point blank range.

**Comment by thecyrus** [comment] 2022-03-06 19:21
I've also seen a zombie following me and getting stuck into wall.

**Comment by ArgentArts** [comment] 2022-03-08 18:26
Yep, zombies and soldiers can both walk through my doors in my level, too.

**Comment by ArgentArts** [comment] 2022-03-11 22:04
Is the fix for enemies walking through doors going to come soon? I just tried to test my level with an enemy and they ran right through the door. Everything else was great. ;)

**Comment by LeeBamberTGC** [comment] 2022-03-14 15:53
@ArgentArts I have the code in the engine now which will allow doors to invalidate the nav mesh, watch the internal bullds :)

**Comment by ArgentArts** [comment] 2022-03-14 20:22
Very awesome! Let me know when it's up and if I am at my computer, I'll definitely give it a run!

**Comment by LeeBamberTGC** [comment] 2022-03-15 09:42
@ArgentArts The internal build will be uploaded on the server in about 20 minutes. System for single doors works nicely. Might need more thinking for double doors and other odd-doors.

**Comment by ArgentArts** [comment] 2022-03-15 15:44
@LeeBamberTGC - I need to test this some more. The nav mesh looks like it being created properly in my test level, but the test enemy seems to be pushing through a good bit of my custom collision meshes, which I don't recall happening before (passing through walls).

Just ran a few more tests. The enemy is able to walk through the walls and escape my level to get outside of it. They also seem more reluctant to chase me around for some reason. In the previous build, I felt hunted by the enemy in my test level (they actually freaked me out a few times). Now, they seem to hesitate so much that I can just easily get them. The only time they feel sneaky now? It turns it is because they've gone "between the walls" like ghosts ... which isn't supposed to happen.

![ghost](https://user-images.githubusercontent.com/36735507/158416188-3b512ce5-6916-4589-b884-fbfaa9e1df8e.png)

**Comment by ArgentArts** [comment] 2022-03-15 15:48
@LeeBamberTGC Meant to say this above - The enemy does not seem to walk through closed doors. I wanted to test opening the door, letting the enemy through, closing the door again to see if they would respect that, but if they can walk through walls, what's the point? :P

**Comment by LeeBamberTGC** [comment] 2022-03-15 22:58
@synchromesh62 Latest internal build prevents characters moving against their prescribed navmesh path. Let me know if this is solved, or needs improvement, thanks!!

**Comment by Granada1** [comment] 2022-03-16 00:41
Hoping it works🤞

**Comment by LeeBamberTGC** [comment] 2022-03-16 00:59
@Granada1 I assumed you where part of our internal team. Let me know if you do not have access :)  Would be nice to know this is solved in this evening's build.  Maybe we can hear what @ArgentArts says as he has access.

**Comment by ArgentArts** [comment] 2022-03-16 01:31
I was away from my PC. I'll get the build now and give it a test after it finishes downloading.

**Comment by ArgentArts** [comment] 2022-03-16 01:54
@LeeBamberTGC One issue is solved - the soldiers no longer are moving through my walls or attempting to shoot through walls or through other pieces of level geometry. So, there's that. Yay! :)

But there's another issue. For whatever reason, the soldiers don't want to cross the door threshold and chase me down. Now, in my level, the area at the base of the doorway is raised, not level with the rest of the floor. It's a ramp. But the nav mesh seems to compensate for this, so it looks like it should be fine. Even so, they won't cross the boundary:

![door1](https://user-images.githubusercontent.com/36735507/158501091-688fbdab-e9ea-4481-a904-2790d1e0798a.png)

![door2](https://user-images.githubusercontent.com/36735507/158501109-f5f67004-5086-42fe-bd95-1facf01bb8a0.png)

**Comment by ArgentArts** [comment] 2022-03-16 01:56
Also, a more minor issue - while the nav mesh accurately moves up the slope on the sides and the soldiers frequently go there (making great hiding places for them to shoot at you from, btw!), their feet sometimes sink into the mesh a bit, especially if one foot is on the level floor and the other is on the slope.

**Comment by ArgentArts** [comment] 2022-03-16 06:34
Let me know if a video of their actions would help and I'll record one. I've got three enemies in my current test level.

**Comment by Granada1** [comment] 2022-03-16 08:09
@LeeBamberTGC I am on the internal testing team , I will try my level tonight and see how they perform

**Comment by ArgentArts** [comment] 2022-03-16 20:10
@LeeBamberTGC Will there be a fix for this in this Friday's build? Should I look to test this then?

**Comment by ArgentArts** [comment] 2022-03-16 20:20
Here's a video of what's happening at the threshold of my doorways:

https://user-images.githubusercontent.com/36735507/158683547-7cd0e6a6-20f9-412b-b8a4-4832bcc28526.mp4

**Comment by ArgentArts** [comment] 2022-03-16 20:42
BTW - I took the above video after doing a download of MAX that included the Foggy Forrest demo in it. I don't know if any code had been updated. Even so, I thought I would inform you.

**Comment by ArgentArts** [comment] 2022-03-17 06:53
https://user-images.githubusercontent.com/36735507/158753321-a5254ac9-6578-4859-8ec8-83de1ecdca83.mp4

**Comment by LeeBamberTGC** [comment] 2022-03-17 17:18
@ArgentArts New internal build with tweaks. Let me know how your AI work out :)

**Comment by ArgentArts** [comment] 2022-03-17 17:40
@LeeBamberTGC Nope. One guy went through the walls, but this has only happened once so far. None of them will cross the thresholds of the doorways. I'm guessing it's because they are raised? Though they are coming up to the very top edge this time, instead of standing at the bottom of the slope.:

![edge](https://user-images.githubusercontent.com/36735507/158862401-2bc89e96-73d5-4c0e-ab8b-b86bfe27699f.png)

**Comment by ArgentArts** [comment] 2022-03-17 17:41
They are attacking/chasing me more aggressively, though, in this level, which is nice. Just need them to cross over that hump! ;)

**Comment by ArgentArts** [comment] 2022-03-17 17:50
@LeeBamberTGC Sure:
![nav](https://user-images.githubusercontent.com/36735507/158864377-b55245b7-5ec5-442f-bb9e-5a20a6429391.png)

I can do a video walkthrough with the navmesh on, too, if you need.

**Comment by ArgentArts** [comment] 2022-03-17 17:54
@LeeBamberTGC Do you just want the doorway and the door meshes? Where would I send them because I don't want to post them here for everyone to be able to grab. ;) And you've not been able to get my emails for some reason.

**Comment by ArgentArts** [comment] 2022-03-17 18:23
@LeeBamberTGC I'm finishing the level now (getting ready to package it up). But I've pretty much discovered it's the door that's causing the issue, not the doorframe. I've created a long hall that has the doorframe without the door and one with the door. The soldier rushes through the doorframe without the door, but once he encounters the one with the door that's been raised, he won't cross the threshold.

I'll get the level to you in just a few minutes.

**Comment by ArgentArts** [comment] 2022-03-17 18:42
@LeeBamberTGC Email was just sent!

**Comment by ArgentArts** [comment] 2022-03-17 18:43
@LeeBamberTGC BTW - another thing happens in the level - my player moves slowly up the ramp. It's not that steep. It feels strange to slow down that much for such a small area.

**Comment by ArgentArts** [comment] 2022-03-17 20:02
@LeeBamberTGC - Did you get the email with the link to the ZIP with the test level?

**Comment by ArgentArts** [comment] 2022-03-18 15:32
@LeeBamberTGC Were you able to get my email and download the ZIP with the test level?

**Comment by ArgentArts** [comment] 2022-03-18 15:33
As of today's build, the soldiers still won't cross my thresholds if they have doors that have been opened.

**Comment by ArgentArts** [comment] 2022-03-18 20:08
On the level I'd sent you, I've been able to get the soldier to run through my threshold after the door's been opened, but I can't get it to work in my original level, even if I delete and replace the doorframe and door models. I'm going to do a test and rebuild the level from scratch with the latest build and see what happens. I'll report back here what happens.

**Comment by ArgentArts** [comment] 2022-03-18 22:59
@LeeBamberTGC I've been able to get the soldiers to cross the threshold fairly consistently. What I did was widen my collision mesh (shown in green in the screen shot) to be a bit wider at the base than the actual visible mesh:

![threshold_6](https://user-images.githubusercontent.com/36735507/159094765-37a4cfb8-7b64-449b-b8b9-0886e4204fa5.png)

This made for a wider (and nicer) nav mesh as it crossed over that threshold:

![threshold_7](https://user-images.githubusercontent.com/36735507/159094805-1cde787e-d668-4bcf-84dd-33e1ddf355c7.png)

The end result:

https://user-images.githubusercontent.com/36735507/159094824-a4a25493-6982-4fbb-921c-e3cdfbe25c19.mp4

So, it seemed the main issue was the narrowness of the base of the threshold. Make it a bit wider "unclogged" things. Previous to this, using the same build, it was spotty if they would get through. About 80%+ of the time, they would get stuck. Now, they come right through about 95% of the time.

**Comment by ArgentArts** [comment] 2022-03-18 23:06
Now, there's another issue (an old one has resurfaced):

https://user-images.githubusercontent.com/36735507/159095407-ee56f4aa-8089-4c80-8923-5009788098e5.mp4

**Comment by ArgentArts** [comment] 2022-03-18 23:34
Ugh. Still running into issues with them coming through the doorway. I am going to experiment further. :(

**Comment by ArgentArts** [comment] 2022-03-19 00:17
Flattening out the raised area totally removes the issue with the soldiers getting stuck at the door:

https://user-images.githubusercontent.com/36735507/159098892-079b06ac-7280-4d46-a4fe-24dfb1911c17.mp4

I am getting fluid and consistent results as long as I don't have a raised area at the threshold. As noted before, the raised area doesn't seem to pose an issue IF there was no closed door there. But it does if there was a closed door there.

**Comment by ArgentArts** [comment] 2022-03-21 20:16
@LeeBamberTGC Enemies still able to move through closed doors as of the internal build downloaded today.

**Comment by LeeBamberTGC** [comment] 2022-03-21 21:04
@ArgentArts do you mean like this when the soldier is on the other side of the closed door, but poking through:

![image](https://user-images.githubusercontent.com/35840583/159363559-0fa14374-1f86-419c-8aeb-d05c64f85ec1.png)

**Comment by ArgentArts** [comment] 2022-03-21 21:41
@LeeBamberTGC No, they come completely through the door as if there's no door there. Here's a video in today's internal release:

https://user-images.githubusercontent.com/36735507/159368387-1de68340-828c-4b6a-bd84-fd69ea6bd3d1.mp4

**Comment by LeeBamberTGC** [comment] 2022-03-21 21:45
@ArgentArts Ah, it is probably related to custom content :)  If you can, try editing the radius value from 20 to say 200 in this line of code at the end of the door_sliding.lua script:

RDBlockNavMesh(g_Entity[e]['x'],g_Entity[e]['y'],g_Entity[e]['z'],20,blockmode)

**Comment by ArgentArts** [comment] 2022-03-21 21:53
@LeeBamberTGC That didn't make a difference. The soldiers still charge through the door as if it's not there.

**Comment by LeeBamberTGC** [comment] 2022-03-21 21:59
@ArgentArts Is this scene in the "threshold.zip" you sent me?  If so, I can reproduce this Tuesday and also look into the original threshold issue to see if the problem has larger implications.

**Comment by ArgentArts** [comment] 2022-03-21 22:01
It is basically the same scene, though I had flattened the raised areas since then to allow the enemies through (though I liked the area better with the raised area at the base). But, yes, it's basically the same.

**Comment by ArgentArts** [comment] 2022-03-21 22:05
@LeeBamberTGC It's basically the same scene, but if you need me to set up a new one for you, I can, though I can't get to it for a few more hours. Just let me know what you need me to do and I will do it.

**Comment by LeeBamberTGC** [comment] 2022-03-21 22:25
@ArgentArts If you can send me a new one that will exactly show me the characters going right through the door when it is closed, that will mean I can reproduce quickly and provide a fix on Tuesday for you to test :)  Thanks!!

**Comment by ArgentArts** [comment] 2022-03-21 22:26
I'll send you the exact level as it is with everything in it. Give me a few to put it in a ZIP and upload it.

**Comment by ArgentArts** [comment] 2022-03-21 22:37
@LeeBamberTGC The email with link to download the new threshold ZIP has been sent. Please let me know you've received the email and when you've downloaded the ZIP file so I can delete it from my server. Thanks. :)

**Comment by LeeBamberTGC** [comment] 2022-03-24 11:48
@ArgentArts You can remove the file from your server. Tested with latest build and soldiers could get through the door when the nav mesh let them, I had to change them so they always used the Get Close mode :)

**Closed by LeeBamberTGC** 2022-03-24 11:48 UTC
Labels: bug, Fixed but need confirmation., Max, High, AI

**Comment by ArgentArts** [comment] 2022-03-25 17:16
@LeeBamberTGC Did a fresh install today with the Early Release version and the soldiers still just run through the door on my test level. Did this fix not make it into the the Early Release version?

**Comment by LeeBamberTGC** [comment] 2022-03-25 17:22
@ArgentArts Zip up the FPM you are using, and let me know what I should do to see this. The last level I received, the two soldiers stayed behind the door until I was close enough for it to open, and they pushed through as expected.

**Comment by ArgentArts** [comment] 2022-03-25 17:32
@LeeBamberTGC :

https://user-images.githubusercontent.com/36735507/160172085-00894914-b5bd-43fe-92e9-966dca083275.mp4

**Comment by ArgentArts** [comment] 2022-03-25 17:34
@LeeBamberTGC What I do is click the invisible Trigger Volume that is in front of the door and set its behaviour to Manual instead of Automatic so that I can control opening and closing the door. That way, I can open the door, get the soldier's attention by firing a shot to make him charge me, and then immediately close the door. When I place the soldier, I set him as an enemy and set him to Alert.
