### ISSUE TITLE
Aztec Colour Issue

### ISSUE THREAD

**Issue by Curiosityuk** [TheGameCreators/GameGuruRepo#3256] opened 2022-06-04 12:17 UTC
I have just updated to the latest version of GGM and bought and installed the Aztec DLC.
However, when I'm trying to add charaters they come out inverted in colour with no skin. 
Has anyone else experiencing this????

I've added a video for you to view [https://youtu.be/btrGUWVTd4o](url)

**Comment by MonkeyFrogStudio** [comment] 2022-06-04 16:22
Correct link here:

https://www.youtube.com/watch?v=btrGUWVTd4o

**Comment by ZakJudges** [comment] 2023-01-27 15:18
Hi @Curiosityuk, apologies for the late response! I could not reproduce this issue. Do you still experience it?

**Comment by ZakJudges** [comment] 2023-02-16 09:29
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks

**Closed by ZakJudges** 2023-02-16 09:29 UTC
Labels: bug, Fixed but need confirmation., Max, Medium, Characters
