### ISSUE TITLE
Max no longer wants to start via Steam

### ISSUE THREAD

**Issue by Jisafu** [TheGameCreators/GameGuruRepo#5483] opened 2024-04-26 17:54 UTC
This morning everything went well. Now when I try to start up, GGM starts to load but after a few seconds it shuts down. (During the white screen)

**Comment by synchromesh62** [comment] 2024-04-26 19:23
> This morning everything went well. Now when I try to start up, GGM starts to load but after a few seconds it shuts down. (During the white screen)

Yep looks like an issue in the last EXP Update.
For now you can just roll back to retail if your stuck.

**Comment by Jisafu** [comment] 2024-04-26 20:26
OK, thanks



Verzonden vanaf mijn Galaxy



-------- Oorspronkelijk bericht --------
Van: synchromesh62 ***@***.***>
Datum: 26/04/2024 21:23 (GMT+01:00)
Aan: TheGameCreators/GameGuruRepo ***@***.***>
Cc: Jisafu ***@***.***>, Author ***@***.***>
Onderwerp: Re: [TheGameCreators/GameGuruRepo] Max no longer wants to start via Steam (Issue #5483)


This morning everything went well. Now when I try to start up, GGM starts to load but after a few seconds it shuts down. (During the white screen)

Yep looks like an issue in the last EXP Update.
For now you can just roll back to retail if your stuck.

**Comment by davetgc** [comment] 2024-04-27 05:59
Confirmed and we are working to fix it. This crash only affects the Exp build, so please revert to the public build for a few days. We're sorry about the crash, and will get it back up and running asap.

**Comment by SampeyFS** [comment] 2024-04-27 07:43
Exactly it doesn't work for me too

**Comment by LeeBamberTGC** [comment] 2024-04-27 13:45
Now Fixed :)

**Closed by LeeBamberTGC** 2024-04-27 13:45 UTC
Labels: Fixed but need confirmation., Max, High, CRASH!

**Comment by SampeyFS** [comment] 2024-04-27 13:49
Now it works, let's wait for the fix of the lua scripts, they don't load the save when the game is unpacked with (standalone)

**Comment by Jisafu** [comment] 2024-04-27 14:26
Thanks
