### ISSUE TITLE
Editor - Loading Two Maps Same Time

### ISSUE THREAD

**Issue by Teabone3** [TheGameCreators/GameGuruRepo#496] opened 2019-02-21 16:01 UTC
Game Guru editor will sometimes load two maps at a time. Causing the screen to flicker between the two, with a blue screen in-between the frames. When I attempt to video record this issue the editor screen remains blue for some reason once the record button is pressed.

Others have experienced this issue as well ive been told so would be helpful to have other people share their experiences here. Its been an odd bug thats lasted a couple years. Simple fix is closing GG and starting it again.

When I get sometime i may record the issue via my cellphone and upload to youtube and send a video example of whats going on here.

**Comment by synchromesh62** [comment] 2020-02-10 20:55
@Teabone3 
Unable to reproduce are you still getting this issue since the recent updates?
If so could possibly supply a video of this issue ..

**Comment by synchromesh62** [comment] 2020-02-28 18:53
@LeeBamberTGC 
@plemsoft 
Unable to reproduce .

**Comment by LeeBamberTGC** [comment] 2020-03-25 03:24
It is pretty impossible for the GameGuru editor to hold two maps at the same time, the code simply does not work like that. Without more evidence, the closest could be that the video graphics card is holding an image of an old back-buffer and then rendering the new one from the current map. This would only happen if there are graphics driver issues in conflict with the DX calls GameGuru makes which could have happened back when we had some incompatibilities with some drivers released by NVIDIA and AMD.  There have been no other reports of anything like this aside from the above graphics driver issues we once had. Closing this until we see a video or more reports of this strange one.

**Closed by LeeBamberTGC** 2020-03-25 03:24 UTC
Labels: bug
