### ISSUE TITLE
Reported on Steam ... Classic zombie animation + custom model animations

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#4996] opened 2023-10-08 09:13 UTC
### Steam Report 
i recently discovered a bug, that once some custom made enemies from the gameguru store (ehm the rabbits) have a bug in their animation, sometimes once they are killed they just stand still and that until you leave the map first i thought its something wrong with the rabbit animations....but it used to happen with the stock enemies too so im guessing its something with the engine........i made a video to show it: any chance this gets fixed? i got some feedback advicing this from players of my just released first (short) gamegurur game: https://xx696.itch.io/rhs01/ https://ko-fi.com/s/2e86974f15 if you click the link you'll propably understand why i mentioned the bunnies :D yes i know im crazy ;)

https://youtu.be/EfQuVhnJGd8?si=L0gMP7j5RCfekF9v

**Comment by XScornGames** [comment] 2023-10-08 09:29
hey in case youve got any questions i have now subscribed to this topic :)

**Comment by LeeBamberTGC** [comment] 2024-03-07 17:40
I checked the only two rabbits in the stock media for Classic, only one that animates and not a character, so work as intended:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/b29a4bca-b951-4c01-af96-8b8acb7228ff)

If you can provide details on the third party asset that was used, I can contact the author to see if there is a fix for their asset, in the meantime I will close this thread as not a direct Classic out of the box bug.

**Closed by LeeBamberTGC** 2024-03-07 17:40 UTC
Labels: bug, Waiting for more information., GGClassic
