### ISSUE TITLE
Standalone bug

### ISSUE THREAD

**Issue by slender1200** [TheGameCreators/GameGuruRepo#233] opened 2018-05-17 00:21 UTC
Hello everyone! Before I start, I just want to say, I have been loving this new update. But something has been really annoying me. I recently finished a game I have been working on called Shadow War, I have been working on it for a long time, and I really want to release it to the public. I had lots of fun making it, but it seems I can't share that joy right now. Every time I try saving it as a standalone, I get a specific error, every single time. I really hope this can be resolved soon. Thank you for reading. Bye!

**Comment by LeeBamberTGC** [comment] 2018-05-17 11:04
Can you provide more information on the specific error you are seeing in as much detail as possible. You are also welcome to zip up and send me the standalone directly so I can check it out for you at lee@thegamecreators.com

**Comment by Teabone3** [comment] 2018-05-17 19:55
90% of the time this is caused by just missing media not carrying over. That's why its generally helpful to post bugs on the forums as well so others can help you there as well. You may need to manually move over images/sounds to their respected folders in the standalone.

**Comment by slender1200** [comment] 2018-05-18 01:39
Hello. I might not have been as clear as I should have been. The standalone never saves, it is always when I press "Save Standalone". This is what pops up when I press it 

    On Thursday, May 17, 2018 7:04 AM, Lee Bamber <notifications@github.com> wrote:
 

 Can you provide more information on the specific error you are seeing in as much detail as possible. You are also welcome to zip up and send me the standalone directly so I can check it out for you at lee@thegamecreators.com—

**Comment by LeeBamberTGC** [comment] 2018-05-18 12:05
Can you provide more information on the specific error you are seeing when you try to save the standalone, in as much detail as possible? Thanks!

**Comment by slender1200** [comment] 2018-05-18 19:09
It pretty much only says "Microsoft Visual C++ Runtime Library" and "Runtime Error! This application has requested the Runtime to terminate it in an unusual way"

**Comment by LeeBamberTGC** [comment] 2018-05-21 10:35
Sounds like you are missing some vital redistributables. They are normally installed by Steam client when installing GameGuru from a fresh install, but if you look for the "vc_redist.x64.exe" and "vc_redist.x86.exe" files for VS 2005 this might resolve the issue for you. Also make sure your Windows Service Packs are up to date as this is a requirement of the software too.

**Comment by plemsoft** [comment] 2019-06-14 07:25
@slender1200 Could you confirm that this has been fixed in the latest versions ?

**Closed** 2019-12-02 16:21 UTC
Labels: bug, fixed, old version, question
