### ISSUE TITLE
Scene requires one light to be placed for shader to work

### ISSUE THREAD

**Issue by TheGameCreators** [TheGameCreators/GameGuruRepo#4] opened 2018-01-16 15:42 UTC
May be obvious but it left me scratching my head at first

**Comment by plemsoft** [comment] 2018-01-23 10:56
scratching ? what shader ? is this missing a pic ?

**Comment by plemsoft** [comment] 2018-02-13 11:14
Please explain this bug Lee ?

**Comment by LeeBamberTGC** [comment] 2018-03-06 20:48
Agreed, I cannot reproduce this bug (was reported by email) but without knowing the specifics of the shader and the scenario, unable to act. Closing this one.

**Closed by LeeBamberTGC** 2018-03-06 20:48 UTC
Labels: bug
