### ISSUE TITLE
GG Max Bug Report - Crosshair mode causes the Skybox to shake

### ISSUE THREAD

**Issue by UltraVox001** [TheGameCreators/GameGuruRepo#1910] opened 2022-01-31 06:15 UTC
Crosshair mode causes the Skybox to shake (only on non-simulated SkyBoxes).
See this [Video](https://www.youtube.com/watch?v=dSIfeVJ7cao).

The reflections in the viewfinder are unpleasant.
This should be fixed or optional.

**Comment by PaulSJ** [comment] 2022-02-04 16:53
Duplicate of #1437

**Closed by PaulSJ** 2022-02-04 16:53 UTC
Labels: bug, Max, High, Weapons

**Comment by plemsoft** [comment] 2022-02-22 12:19
@UltraVox001 Thanks for reporting this issue, this has been fixed and will be in the next update :)
