### ISSUE TITLE
GG Max - Bug - Terrain / Assets moved on many levels including DEMOs

### ISSUE THREAD

**Issue by Tum1370** [TheGameCreators/GameGuruRepo#3249] opened 2022-06-03 16:05 UTC
I just tested the demo level DISRUPTION, and noticed that the wall in the warehouse has moved away from where it was originally placed, as you can see in the screenshot below.

On one of my own level i had a similar issue with a wall moving like this, and this happened after the 6th May update on my level.
I have also just found that a different level i had (which i have not checked since the 6th May update), all my canyon walls have moved out of place, and all need resetting in the correct place.

EDIT : Also i have just tested playing Snowy Mountain Stroll again, and it would seem that the terrain has messed up on this demo as well. I can imagine all these bugs are to do with the same issue.

I Have added some more screenshots from some DEMO games and you can see all the screenshots have problems with assets moved.

Not sure what happened on the 6th May update, but something must of moved these.

Disruption Demo - Wall Moved ?

![Untitled](https://user-images.githubusercontent.com/66874403/171903103-8a538bda-e461-42f9-9d98-c1f1b8d87688.png)
e then.

Jungle Fever Demo - Cliff face moved over starting area

![Untitled](https://user-images.githubusercontent.com/66874403/172042753-564e203c-cd77-4a0a-b0d1-23bcf8d2d201.png)

Canyon Offensive Demo - Crates / Boxes now in Cliff Wall

![Untitled](https://user-images.githubusercontent.com/66874403/172042858-71b08184-0074-4b28-881f-38931630941c.png)

**Comment by LeeBamberTGC** [comment] 2023-09-07 22:44
@Tum1370 Early issues as we fixed assets but not levels, all HUB DEMOs should now be as intended :)

**Comment by Tum1370** [comment] 2023-09-08 07:36
@LeeBamberTGC Hi, I dont understand why you have closed this issue. I have just tested Canyon Offensive Demo and Jungle Fever demos and they are exactly the same. The objects have moved and not as they should be.

Do you not want the demo maps to be working correctly ?

**Comment by LeeBamberTGC** [comment] 2023-09-08 11:44
I am happy with the changed demo levels now, new layouts are fine. No complaints so far.

**Comment by Tum1370** [comment] 2023-09-08 12:23
@LeeBamberTGC  I do NOT see any changes to the broken DEMO levels.

I have just made sure i redownloaded the latest versions of all demos, and here are 2 of the ones i mentioned above about moved assets.
Look at items merged in with the walls of the canyons.
This is just one of many bugs on them..

I certainly do not see how you could be happy with these. This is the first thing new users will actually test and see, and they are bugged.

![1](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/9e5a8c82-edd4-45e1-aae1-f4cc8f1dedc2)

![2](https://github.com/TheGameCreators/GameGuruRepo/assets/66874403/652e74d9-478b-4c5f-a66c-14fd79ca4ee7)

**Comment by LeeBamberTGC** [comment] 2023-09-10 16:53
@Tum1370 Changed level evidence as requested:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/cd9cbe25-2e91-4fc0-a67b-477d257324bd)

I have contacted the original authors of the levels to see if they wish to improve on them since the asset fixes, and I am also happy to extend the opportunity to anyone reading to make their own corrections and submit a better version of these levels for inclusion into the main product.

Re-opening this issue.

**Comment by LeeBamberTGC** [comment] 2023-09-22 13:30
Update: Ghost LOL has kindly updated his level and improved some AI too, should be no more issues with buried assets:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/7033b1a3-a2e6-4165-9a05-f9b4ffc49ff5)

Just waiting on the JUNGLE level now and then we can close this :)

**Comment by LeeBamberTGC** [comment] 2023-09-22 15:49
@Tum1370 Many thanks :)

**Comment by LeeBamberTGC** [comment] 2023-10-13 00:39
@Tum1370 Island Showdown now updated by GhostLOL for next EXP build. That should be all of them now :)

**Closed** 2024-09-13 16:17 UTC
Labels: bug, Fixed but need confirmation., Max, Low, Assets
