### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5197] opened 2024-01-24 08:41 UTC
![Screenshot 2024-01-23 175330](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/4b3519d4-2bb5-479d-b9be-0e7371dabd0e)
how do i turn the axe in the right direction i have tried every way i could not

**Comment by thecyrus** [comment] 2024-01-24 09:27
This is most likely not a bug, should be posted on forum or Discord.

**Comment by MonkeyFrogStudio** [comment] 2024-01-25 02:19
You may need to rotate the model in your modeling program.

**Comment by davetgc** [comment] 2024-01-25 09:42
I'm closing this as it's not a bug but an import issue. Please post these questions on the discord.

https://discord.com/channels/950796460683829329/951154251613216798

**Closed by davetgc** 2024-01-25 09:42 UTC
