### ISSUE TITLE
Exact same model changed sizes on import between versions

### ISSUE THREAD

**Issue by 42Pix3ls** [TheGameCreators/GameGuruRepo#3390] opened 2022-07-02 23:42 UTC
I have had trouble importing models consistently between versions. Creating a modular city  import sizes have been very inconsistent despite the exact same export and import settings being used.

![image](https://user-images.githubusercontent.com/95527550/177019160-325a6f10-dc77-4b2b-8f19-8cf1ae8cde8d.png)

**Comment by MonkeyFrogStudio** [comment] 2022-07-03 01:03
Just tested on my end with selections of my previously imported models. Cleared out the user folder so that none of the old models were there and reimported several models. In all cases, my models came in the correct size each time. So, not experiencing this here. Just an FYI.

**Comment by 42Pix3ls** [comment] 2022-07-04 08:49
The problem lies in exporting additional models over time. I have started to create this pack and added to it slowly over several weeks. Anything I import in the same session is the same size but it does not match previous imports from a few weeks back even with the same settings being used. Thus I need to re-import all the original files to make them match the sizing of the new ones. 

Realistically I will have to import batches once they are finished otherwise I will be re-importing all models every time the sizing does not match when adding new ones defeating the purpose of building and importing the pack over time.

**Comment by 42Pix3ls** [comment] 2022-07-04 23:47
Well I am unsure what the difference is between yours and mine, however I have followed your own tutorial to complete the task. The export parameters are exactly the same from the same blender file and the import is exactly the same. as you can see by the image, there is a distinct size difference.

**Comment by MonkeyFrogStudio** [comment] 2022-07-05 01:44
Here's a screen shot from within the latest update of MAX showing two of my floor tiles:

![size](https://user-images.githubusercontent.com/36735507/177233037-a9c1995e-bc19-43c3-a9f0-717db92bce90.png)

On the left side are two tiles, one selected. The selected one was imported today. The unselected one (connected to it at the top) was imported at an earlier time. The are both the same size and fit perfectly to one another.

The floor tile to the right was made some time ago (almost two months ago). I made it using a new scale (division of 8 instead of 10). In previous editions of MAX, it imported with exactly 16 grid squares to a side. I just imported this one as new today (new name, etc.) and, once again, it imports exactly 16 grid squares to a side, just as the ones did from well over a month or so ago. This means that the new import is importing to exactly the same size as the ones did over a month or so ago. 

I don't know what's going on on your end, but all of my previous models and matching up with newly imported ones perfectly.

**Comment by 42Pix3ls** [comment] 2022-07-05 02:19
I completely understand what you are saying but mine are not. Something somewhere is not right and I triple checked all import settings and export settings allowed all of the correct scales and still have issues. It's great yours are working fine. Mine however are not. Hence the post on here.

**Comment by MonkeyFrogStudio** [comment] 2022-07-05 05:40
Right. Not trying to be a pain. What I am indicating is that since it's not happening to me ... and we both have the same version of MAX ... then it may not be an issue with MAX. Even if it is, then at least TGC can see that this is not happening to everyone. That, too, may be helpful to them finding the issue (provided there is one). So, it's not to argue with you. It's to provide information.

**Comment by 42Pix3ls** [comment] 2022-07-05 07:23
Haha it's ok, I didn't think you were arguing, I am simply trying to understand where you are coming from. I was trying to do that by confirming my process and make sure all the facts were clear. 

That being said I can see why you might have thought that and I apologise if it came across as argumentative. I truly appreciate the help! :)

**Comment by MonkeyFrogStudio** [comment] 2022-07-05 07:25
Didn't really think you were, to be honest (being argumentative), but wanted to make sure anyway. ;) Text without voice inflection and all that. ;) If you catch me on Discord, I'll try to help (if you like).

**Comment by 42Pix3ls** [comment] 2022-07-05 07:30
Absolutely agree, you can never fully get someone's intentions or mood through text. I'm stuck at work at the moment but would love to pick your brain about it ina day or two, thank you.

**Comment by ZakJudges** [comment] 2023-02-03 14:47
Hi @42Pix3ls, are you still experiencing this in the latest experimental build? If so, could you email me copies of a model that import with different sizes? That should allow me to reproduce. My email is zak@thegamecreators.com. Thanks!

**Comment by 42Pix3ls** [comment] 2023-02-03 20:53
No luck I am afraid 
![polygon_updated](https://user-images.githubusercontent.com/95527550/216708569-0faa5f6e-8855-4f50-83ad-9d71176d2724.png)
I will email one of the models now

**Comment by ZakJudges** [comment] 2023-02-16 11:59
Hi @42Pix3ls, do you have any models you could send me that show this issue? Thanks!

**Comment by 42Pix3ls** [comment] 2023-02-16 18:14
I have emailed you one of the models when I replied 2 weeks ago

**Comment by ZakJudges** [comment] 2023-02-17 08:22
Hi @42Pix3ls, I don't seem to have the email. It is possible it was automatically filtered out due to the presence of the attached files. Could you try emailing it to zakjudgestgc@gmail.com instead? We might have more luck that way. Thanks :)

**Comment by 42Pix3ls** [comment] 2023-02-17 09:25
No problem @ZakJudges I have sent the new email, it contains 2 GTLF and the converted FBX and DBO files

**Comment by ZakJudges** [comment] 2023-02-17 09:39
@42Pix3ls I have received the email and files. Thanks!

**Comment by 42Pix3ls** [comment] 2023-02-17 09:41
Hoepfully we can get to the bottom of this haha

**Comment by ZakJudges** [comment] 2023-02-17 11:30
@42Pix3ls I have managed to reproduce the physics issue from #4141, however I have not been able to reproduce models importing with inconsistent sizes. Do you still experience that issue? :)

The other issue looks like the physics are only correct for the the first mesh making up an object. That gives me a clue where to start. In the mean time, whilst a fix is worked on, you should be able to change the export settings in Blender so that you do not have to rotate the object in Max, which should bypass the issue.

**Comment by 42Pix3ls** [comment] 2023-02-17 11:33
Thanks Zak, I belive with some help from monkeyfrog my current settings all import correctly with max and have not experienced the odd sizing for a while now so, safe to say that once can be laied to rest :)

**Comment by ZakJudges** [comment] 2023-02-17 11:34
@42Pix3ls Thank you for confirming, closing this issue. I will continue the post any updates about the physics issue in #4141 :)

**Closed by ZakJudges** 2023-02-17 11:34 UTC
Labels: bug, Max, Waiting for more information., High, Importer
