### ISSUE TITLE
Map Editor Stutter

### ISSUE THREAD

**Issue by tarkus1971** [TheGameCreators/GameGuruRepo#195] opened 2018-04-19 14:31 UTC
Getting a lot of editor stutter when using the map editor. disbalesurfacesnap = 1 so is off so it is not that.

Anyone else got this too?

**Comment by LeeBamberTGC** [comment] 2018-04-20 01:16
Any way you can create a video to show the stutter, not seeing any here so might be related what is in the level when the editor is navigating around (I am assuming you mean stutter when in free flight mode).

**Comment by tarkus1971** [comment] 2018-04-20 06:52
Yes in free flight mode, and on some levels which are quite busy, i will try and do a short video and dropbox it later tonight. At work at the moment.

**Comment by tarkus1971** [comment] 2018-04-22 07:01
Here is a dropbox link to the video.

The stutter is gone it seems, there was a small GG update last night, 8.8mb in size, might of cured it.

But there is a problem with long shadows on the terrain in the editor, which you can see in the video.

https://www.dropbox.com/s/fr9mqid5cf8i7v0/mapeditor.mp4?dl=0

**Comment by tarkus1971** [comment] 2018-04-22 07:37
Ok the stutter seems to occur when or after using the right mouse button sometimes in the editor to rotate. 

First few seconds with right mouse held then i let go and it slowly returns to normal speed. 

https://www.dropbox.com/s/qfuvkyyskzwhwha/Stutter.mp4?dl=0

**Comment by LeeBamberTGC** [comment] 2018-04-23 23:03
The stutter looks related to the amount of polygons on screen, but do you see the same if you used a similar amount of entities but all the same entity (i.e. using the same texture over and over), as the texture bandwidth can cause GPU to stutter if there are too many textures to handle per render.  Can you experiment on this basis to confirm/reject the theory, thanks!

**Comment by tarkus1971** [comment] 2018-04-26 08:01
It seems to only happen the first time the editor camera "sees" the area it is pointing at, like it is calculating what to draw. Maybe if we had a Draw Distance Setting for the editor like we do in the Test Game mode would help with detailed levels rendering smoothly.

**Comment by LeeBamberTGC** [comment] 2018-04-26 10:04
Yes that sounds like texture bandwidth thrashing. Do you have a 2GB video memory card, or is your level crammed with lots of different large textures. Try going into SETUP.INI and changing "dividetexturesize=4" as this will make the textures loading in smaller for this test, thanks.

**Comment by tarkus1971** [comment] 2018-04-26 16:31
I have and Asus Nvidia GTX970 card with 2gb DDR5, so should be reasonably powerful. I will try the dividetexturesize and report back.

**Comment by tarkus1971** [comment] 2018-04-29 07:41
Yes, changing the dividetexturesize=4 worked for me, I see it was set to 1. I'm guessing 2 would be fine as well. Thanks.

**Comment by tarkus1971** [comment] 2018-05-01 17:19
ok Lee

**Comment by gg-Anubis** [comment] 2018-05-31 10:50
I would like to note that if using Animated entities, which have Playanimineditor = 1 the editor tends to slow down *when in view.
Maybe a new option to shut down all animations (no matter the variables in the FPE) in the editor is an option. Which makes all entities Playanimineditor == 0 in the editor.

**Comment by GraPhiX-Guru** [comment] 2018-05-31 10:52
Which makes all entities Playanimineditor == 0 in the editor.

no no no don't do that animation only works at the moment with Playanimineditor =1 I have raised this issue in the past

**Comment by gg-Anubis** [comment] 2018-05-31 11:07
I understand where you come from, i noticed the same behaviour before.
But if Lee solves the bug you mentioned.. it shouldn't matter.
Btw.. Issue #178 is closed.. isn't it solved yet?

**Comment by LeeBamberTGC** [comment] 2018-05-31 11:10
We are going to wait for the PublicPreview but we've done work on the memory side which reduces the footprint and could solve this map stutter issue on larger maps. Once this is confirmed we can close this issue.

**Comment by GraPhiX-Guru** [comment] 2018-05-31 11:26
no its not solved :( looks like I closed it by mistake with my last comment I have re opened it

**Comment by plemsoft** [comment] 2018-06-20 10:01
tarkus1971: Has this been fixed in the latest Public Preview ?

**Comment by plemsoft** [comment] 2019-06-12 12:54
This has been fixed , also the playanimineditor = 0 problems.
Ready from the next release :)

Please try to only post one problem/bug per issue , thanks :)

**Closed** 2019-06-14 12:41 UTC
Labels: bug, fixed

**Comment by plemsoft** [comment] 2019-06-17 09:07
@gg-Anubis @GraPhiX-Guru 

Also from the next update you will be able to use:

playanimineditor = 0
and 
startanimingame = 1

To only display the animations when the game is running, this should give you better editor speed.
