### ISSUE TITLE
MAX - 2022.02.18 - Preview Shows Scene

### ISSUE THREAD

**Issue by OldFlak** [TheGameCreators/GameGuruRepo#2104] opened 2022-02-14 01:37 UTC
We had this many moons ago - it is back again

![image](https://user-images.githubusercontent.com/12246318/153785810-3085cc5f-aa26-4802-bfb4-a76d60198dec.png)

**Comment by ArgentArts** [comment] 2022-02-14 03:05
This is happening with me as well.

**Comment by plemsoft** [comment] 2022-03-02 14:08
@OldFlak Do you still see this in the current version ? , we made some fixes that relates to this , thanks for your help :)

**Comment by OldFlak** [comment] 2022-03-04 09:05
@plemsoft Hi Preben, thanks for looking at this issue - Seems to be only showing fog now.

https://youtu.be/KgYdd0h7Bpo

**Comment by plemsoft** [comment] 2022-03-04 09:39
@OldFlak Strange im not able to reproduce it here no matter what i do ? , could you try to make a empty level that produce this result , could be some special setup ? , and e-mail it to me so im able to see what the problem is , thanks for your help :) plemsoft@plemsoft.com

**Comment by plemsoft** [comment] 2022-03-04 10:29
@OldFlak Yes thats it , i will see what i can do :)

**Comment by plemsoft** [comment] 2022-03-04 11:13
@OldFlak Found it fixed for the next build , not sure if lee merge anymore today so properly will be in weekend builds :)

**Comment by OldFlak** [comment] 2022-03-12 11:06
@plemsoft Thanks for looking into this Preben in 2022.03.11
Still seeing it on some items https://youtu.be/pdWxR6XQBD8

Not sure it is worth worrying about it tho :)

**Closed** 2022-04-19 07:37 UTC
Labels: bug, fixed, Max, High, UI
