### ISSUE TITLE
[GG CLASSIC] Strange issue for russian players of gameguru games -> Missing assets

### ISSUE THREAD

**Issue by Duchenkuke** [TheGameCreators/GameGuruRepo#2449] opened 2022-03-08 22:28 UTC
As my game also reaches to the russian market a bit, I now have several comfirmed reports of missing assets in the first level of my game.
Like, 2d sprites missing, wall textures missing and so on. The whole game has missing stuff here and there wich leads to big frustration among players, understandably.

As far as i can tell, this happens when there is a russian windows version installed.

I am in exchange with russian players and If there are more details, I will post them here.

It is important that I at least adress this once so maybe someday there can be a solution for this.

**Comment by LeeBamberTGC** [comment] 2022-06-13 13:07
@Duchenkuke Preben fixed something in the new June FIxes beta, and now allowed UNICODE folders to be recognized. This is almost certainly the cause :)  Please confirm when you get the beta/release :)

**Comment by Duchenkuke** [comment] 2022-06-13 15:57
I am pretty confident that this was the issue. Of course I will need actual russian players to confirm this but I will incorporate the changes into the latest dark skies build and then write some people so that they can hopefully confirm this :)

**Comment by LeeBamberTGC** [comment] 2022-06-15 13:01
@Duchenkuke No new files for this one, just code changes to ensure we can handle UNICODE folders.

**Comment by Duchenkuke** [comment] 2022-06-15 13:54
I dont understand :D How do I implement these changes into my game now ?

**Comment by Duchenkuke** [comment] 2022-06-15 14:04
If I cant update anything, then how can the standalone have this issue fixed also?

**Comment by LeeBamberTGC** [comment] 2022-06-15 14:17
@Duchenkuke You wait until the June FIxes release, then load your project and save standalone. The new standalone executable will include all latest fixes.

**Comment by Duchenkuke** [comment] 2022-06-15 14:22
okay thanks!

**Comment by Duchenkuke** [comment] 2022-06-15 14:23
I will gladly close this issue when the fix has been confirmed. I am waiting for some feedback on that at the moment.

**Comment by Duchenkuke** [comment] 2022-06-15 18:11
The Issue still remains for my tester.
I updated the game with the Public Preview Exe.

Missing walls etc, all over the place


https://cdn.discordapp.com/attachments/625029519237054465/986680824676122644/unknown.png
https://cdn.discordapp.com/attachments/625029519237054465/986681201760821249/unknown.png
https://cdn.discordapp.com/attachments/625029519237054465/986681731656613888/unknown.png

**Comment by LeeBamberTGC** [comment] 2022-06-16 12:17
@Duchenkuke I think the fix (from Preben) was related to UNICODE paths for texture loading. Are you saying this extends to loading the actual models themselves (i.e. missing models) as from the shots I do not know what should be there, is missing, etc? Any chance of a BEFORE and AFTER shot?

**Comment by Duchenkuke** [comment] 2022-06-16 13:13
the models are there in the standalone. These screenshots were sent to me by a russian player.
The models are missing completely.  He can fall of the map, and thats the reason he cant complete the game.

**Comment by LeeBamberTGC** [comment] 2022-06-16 13:15
@Duchenkuke Any chance you can identify one of these models and send it to me so I can make a blank map with it in, I can then study the file data and see why it might fail to load it compared to other models which load fine, thanks.

**Comment by Duchenkuke** [comment] 2022-06-16 13:16
yes, I can send at least 2 models. Hang on!

**Comment by Duchenkuke** [comment] 2022-06-16 13:20
[schild level 11.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8919169/schild.level.11.zip)

so this is one of the missing signs.

**Comment by Duchenkuke** [comment] 2022-06-16 13:25
[singlefaced brickwall.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8919216/singlefaced.brickwall.zip)

and this is the wall. Many walls in the bunker consist of this entity with various textures. its not the EXACT wall with that texture, but its the same entity, just in a different folder.

For me it is impossible to find the exact entity for that case. These walls are scatterd around in my 140 gb gg folder and finding it would take a long time.

**Comment by Duchenkuke** [comment] 2022-06-16 13:32
I am on it^^

**Comment by Duchenkuke** [comment] 2022-06-16 13:42
it has the exact same texture as the one thats missing

**Comment by Duchenkuke** [comment] 2022-06-16 14:34
Yes. 

entitybank\a1 custom walls 2020 singlefaced\Betonwand1

**Comment by LeeBamberTGC** [comment] 2022-06-16 14:36
Does the FPE sit in the folder like so:
entitybank\a1 custom walls 2020 singlefaced\Betonwand1\Betonwand.fpe

**Comment by Duchenkuke** [comment] 2022-06-16 15:04
![1](https://user-images.githubusercontent.com/35990507/174100627-a3863703-6c9c-46e5-bfe4-d9d2695076d5.JPG)

**Comment by LeeBamberTGC** [comment] 2022-06-16 15:13
@Duchenkuke I am not familiar with this, is this simply your real F drive:

![image](https://user-images.githubusercontent.com/35840583/174102356-75013f4b-1da5-4b64-b2ea-32842f9c663a.png)

Also, any chance you can zip up the whole of Betonwant1 folder, all those other files might have an impact on what happens when they are exported/used by the gamer.

**Comment by Duchenkuke** [comment] 2022-06-16 15:26
yea thats the name of my F drive. I have one drive for gg backups only.

Sure, here is the folder.

https://www.mediafire.com/file/uvjtbk24qy6np8i/Betonwand1.zip/file

**Comment by LeeBamberTGC** [comment] 2022-06-24 10:59
@Duchenkuke Nothing strange as the files go, so something very strange indeed. Also was not able to reproduce this asset disappearing from my side. As a test, try replacing one of these walls with the attached replacement entity and see if it shows up. Also, move this asset directly to the entitybank\user folder so we can start with a predictable path to the entity file.

[1818WALL.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8975639/1818WALL.zip)

**Comment by Duchenkuke** [comment] 2022-06-24 21:31
I can not reproduce or test this issue myself. We would need someone with a russian windows installation. (at least thats what I think) I doubt I can get the person to help again, he's not an official tester, rather a normal player. I dont wanna bother him too much. This problem will be around for a longer time I guess - its unfortunate. maybe I can build a standalone with the missing assets only and ask for another test run. That may work, yes. I will post here again if I got something to report.

**Comment by LeeBamberTGC** [comment] 2022-10-10 13:18
@Duchenkuke Its a rare one :)  I will be updating the repo soon and putting out some extra info on how to make your own builds direct from the code. It might give you an extra tool to make special builds that you can test with users in the future. Will close this soon, but let me know if it comes up again from another source as that would indicate an engine issue and less of a per-project issue.

**Comment by Duchenkuke** [comment] 2022-10-10 13:58
yea close it for now.

**Closed** 2022-10-10 14:03 UTC
Labels: bug, help wanted, GGClassic
