### ISSUE TITLE
Terrain Generator - when I try to "Generate Terrain and Open the Level Editor" Max just freezes!

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2899] opened 2022-04-20 08:59 UTC
Super urgent bug!

**Comment by plemsoft** [comment] 2022-04-20 09:17
@rvanner Did it happen on your system ? , what version are you using , do not happen on my system. Also tried on "experimental" and it worked ?

**Comment by rvanner** [comment] 2022-04-20 09:35
I did a reboot and it's working now. No idea how it got messed up. It was if the click on the button wasn't being recognised. I'll close this for now.

**Comment by rvanner** [comment] 2022-04-20 12:50
@plemsoft It just happened again to me.

In this screen I cannot click on the button, the windows circle is going round and round:

![image](https://user-images.githubusercontent.com/1503593/164234178-0d80b18c-cff9-4822-acb4-14f4ed77468d.png)

**Comment by rvanner** [comment] 2022-04-20 12:54
I'm having trouble reproducing it. Maybe just check the code and see if there's someway it can get into a lock up?

**Comment by plemsoft** [comment] 2022-04-21 07:05
@PaulSJ Ups looks like the above did not mention you :)

**Comment by plemsoft** [comment] 2022-04-21 07:38
@PaulSJ Looks like it happens when the CPU peaks ?
https://drive.google.com/file/d/13Vik28IeG9UmEgPl3SLdFMOl0DZ6Yeau/view?usp=sharing

**Comment by plemsoft** [comment] 2022-04-21 10:05
@PaulSJ Got it on video what happens!

Notice breakpoint at line 2688 , between 2 timeouts it never get called, terminate is always true, even on the new created threads ?
https://drive.google.com/file/d/13YlFV1C-s3aLP8j0myRcKmRfEM6tNrJH/view?usp=sharing

Hope your able to see what the problem is :)

**Comment by PaulSJ** [comment] 2022-04-21 11:12
@plemsoft It's something, but not enough to figure out what's happening. We need to see what happens after the threads are terminated, since that part is expected. Here's an outline of what should be happening

- Somehow the program gets to `timeout >= 300`
- `bForceUpdate` is changed which will cause a complete reset on the next loop
- `GGTerrain_Update()` gets called on the next loop, `CheckParams()` notices the change and calls `ResetChunks()`. This is where all the `bTerminate` get set to true, all the threads should stop, everything gets deleted
- Everything gets recreated with `pLODSet[0].Create()` and `pLODSet[1].Create()`, nothing could possibly be generating in this state.
- `UpdateChunks()` gets called immediately after, `if ( pNewLODs->IsGenerating() )` should be false, `if ( pCurrLODs->IsGenerating() )` should be false, `bUpdated` may or may not be true but it shouldn't matter because `GGTERRAIN_FLAG_REGENERATE_CHUNKS` should be set triggering an update. 
- All the `pOldChunk` pointers will be null causing a lot of new chunks to be created and added to the chunk generator with `ChunkGenerator::AddChunk( pNewChunk )`
- The chunks are now in a generating state and the threads will set them to finished with `pChunk->SetGenerating( 0 )` as and when they are done
- `GGTerrain_Update()` waits for the top level chunks to finish, or until timeout >= 300

I can't see any way for the chunks get terminated whilst GGTerrain_Update is waiting for the timeout. Only after the timeout hits does this process start again.

**Comment by PaulSJ** [comment] 2022-04-21 12:09
@plemsoft I've uploaded some changes to PJ-Branch11 that might fix this. The only possible thing I could think of is that the thread gets stuck waiting for work thinking there is nothing to do, so now that should never happen.

**Comment by plemsoft** [comment] 2022-04-21 13:49
@PaulSJ Thanks pulled your changes and it looks like you nailed it , gave it a good 15 min trying to get a timeout without success, i was normally able to get it within 3 min (stressing my CPU) . Great Work , @LeeBamberTGC PJ-Branch11 and my branch is ready to be merged :)

**Closed** 2022-04-22 12:50 UTC
Labels: bug, Fixed but need confirmation., Max, High, Terrain Generator
