### ISSUE TITLE
GGM (V1) - BUG - Multi-select is broken now (ctrl + left-click)

### ISSUE THREAD

**Issue by Kravenwolf** [TheGameCreators/GameGuruRepo#4579] opened 2023-04-28 09:28 UTC
A new issue that just popped up yesterday for me after the V1 update is the multi-select option (ctrl + left-click) doesn't work anymore. At least not all of the time. It works on some assets, sometimes. This was never an issue before the V1 build yesterday.

In the first video, watch the bottom-left side of the screen. You can see it's trying to multi-select, but after a frame or two, it gets rid of the previous selection while attempting to select a second object with it:

https://user-images.githubusercontent.com/103399301/235108674-d583c68f-9ece-46ce-88f5-6cdc3a39f462.mp4

I wanted to see if it was an issue with custom assets so I loaded in some stock ones, but as you can see, it works of some of my custom assets, then selecting a certain one deselects everything:

https://user-images.githubusercontent.com/103399301/235109606-acc13db0-c312-4be3-8615-130d11094f4b.mp4

One thing to note is most of these identical assets are copy/pasted assets. So maybe that has something to do with it? Many (the cubes) were copy/pasted assets from a group (using the rubber-band selection tool which seems to still be working fine).

**Comment by MonkeyFrogStudio** [comment] 2023-04-28 11:26
I'm experiencing the same thing on my end. But it seems that if I start with a certain object, CTRL+Left Click won't multiselect, but acts like a new selection. But if I start with a different object, then it works, even on the previous object that was not multiselecting. So, it's difficult to see what's causing the issue, but it's definitely not working like it should.

**Comment by LeeBamberTGC** [comment] 2023-06-19 14:28
@Kravenwolf Took a whlle to reproduce. The cause is that if you drop in two object copies, then sel;ect one, hold down SHIFT and select the second, a third copy is created illegally which goes on to mess up multi-selection.  Fixed in NEXT EXP build :)

**Closed** 2024-09-13 16:20 UTC
Labels: bug, Fixed but need confirmation., Max, High, Level Editor
