### ISSUE TITLE
GG Max - triggerzone unselectable when placed on locked assets

### ISSUE THREAD

**Issue by Ghost-l0l** [TheGameCreators/GameGuruRepo#2858] opened 2022-04-15 00:12 UTC
https://youtu.be/BFfSczwcc3I - that bug seems like nothing big, but when trying to build interior level it gets a bit irritating

**Comment by LeeBamberTGC** [comment] 2022-04-21 19:49
This was a bug caused by the camera drag being activated (i.e. missed the zone corner), but it would then not release the camera drag disabling most click logic. Fixed for next EXP build on Steam.

**Comment by LeeBamberTGC** [comment] 2022-04-21 19:50
![image](https://user-images.githubusercontent.com/35840583/164541522-d3e0f588-b883-44da-a8cd-4fa3f7739a4b.png)

**Comment by ZakJudges** [comment] 2022-05-11 11:11
Fixed as of latest experimental

**Closed by ZakJudges** 2022-05-11 11:11 UTC
Labels: bug, Fixed but need confirmation., Max, High, Object Placement
