### ISSUE TITLE
grass not populating

### ISSUE THREAD

**Issue by casigus** [TheGameCreators/GameGuruRepo#2765] opened 2022-04-06 17:55 UTC
![image](https://user-images.githubusercontent.com/68471279/162037850-65f2d2f9-621a-40da-bf45-6936e931d0fe.png)

the grass populate everywhere is broken.

**Comment by Necrym59** [comment] 2022-04-06 23:19
Depends on  the terain color too  - try turning off match terrain color

**Comment by dllllllllllb** [comment] 2022-04-07 08:27
@casigus It seems to be working correctly for me. What terrain are you trying to spray the flowers on? Does this happen only in this area, or you can't spray grass anywhere?

**Comment by ZakJudges** [comment] 2023-01-04 14:37
Closing this issue due to lack of info. As noted above, the problem is likely because the "Match Terrain Color" checkbox is enabled. If the problem persists, feel free to reopen and we can look into it :)

**Closed by ZakJudges** 2023-01-04 14:37 UTC
Labels: bug, Max, Waiting for more information., Medium
