### ISSUE TITLE
strange animation issue on the assault rifle

### ISSUE THREAD

**Issue by mav3r1ck198-1** [TheGameCreators/GameGuruRepo#2690] opened 2022-03-28 21:12 UTC
https://www.youtube.com/watch?v=VkgwsUCUO6g

**Comment by Granada1** [comment] 2022-03-28 23:11
If you are hitting the V key it’s the change fire mode animations. Single and auto fire

**Comment by LeeBamberTGC** [comment] 2022-03-30 11:18
@mav3r1ck198-1 This is by design, you can switch between primary and secondary modes.  Feel free to close this one.

**Comment by mav3r1ck198-1** [comment] 2022-03-30 16:54
Hi Lee, I appreciate that pressing the V key allows for a secondary use of that weapon, however if you watch the animation, you will see there is an error. The right hand appears as a static mesh, with an additional animated mesh overlaid. The same occurs with the gun itself. 
It makes it appear as if the normals are inverted. 

Sent from the all-new AOL app for Android 
 
  On Wed, 30 Mar 2022 at 12:18, Lee ***@***.***> wrote:   


@mav3r1ck198-1 This is by design, you can switch between primary and secondary modes. Feel free to close this one.

**Comment by LeeBamberTGC** [comment] 2023-09-07 22:33
Fixed a good while ago this one: )

**Closed by LeeBamberTGC** 2023-09-07 22:33 UTC
Labels: bug, Fixed but need confirmation., Answered, Max
