### ISSUE TITLE
Standalone going to Start Marker when you die and not Game Over Screen 

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#4692] opened 2023-06-02 21:34 UTC
As the title states ..
Standalone going to Start Marker when you die and not **Game Over** Screen.
Max only has one life which is fine as you have checkpoints but on death you should go to the **Game Over** Screen.
Currently it returns to the Start Marker equipped as you were when you died.

**Comment by Tum1370** [comment] 2023-06-03 05:52
We definitely need options for the life system. It should not be set just one way. 
I opened a post a long time ago regarding this. 
https://github.com/TheGameCreators/GameGuruRepo/issues/2484

**Comment by synchromesh62** [comment] 2023-06-03 10:14
> We definitely need options for the life system. It should not be set just one way. I opened a post a long time ago regarding this. #2484

Im ok with the one life and use checkpoints but when i do die i want to go the the **Game Over** Screen.
I end up back at the Start Marker with a Crowbar and flashlight that i do not obtain until well into the level and doors have been slammed shut so i cannot even get back to where i died even if i wanted to.

**Comment by Tum1370** [comment] 2023-06-03 10:18
The thing is though, Gameguru is a game maker, and there should always be options on how the dev wants the life system to work.
Currently, without lua scripts, there are no options.
The dev should be able to set whichever life / lives system they want to have.
Whether that be die, and respawn at checkpoint.
Die and Game Over.
Die, and waste another one of your set number of lives.

Maybe even a system, where you pick up something that will resurrect you if you die, if you have that item picked up.

The dev needs options, and not a set system.

**Comment by fearlesswee** [comment] 2023-06-03 15:22
Reposting this from the Discord;

Imo there was nothing wrong with the old lives system; if you wanted lives, well there you go they worked out of the box. If you wanted it to be "if you died even once you have to reload a previous save" then just set the starting lives count to 1 and there you go. If you for whatever reason want the psuedo-godmode we currently have, just set the lives count to an impossibly high number and hide the UI element for it, or just have a script that always resets your lives count. 

We had options, and those were taken away from us. There was nothing wrong with the lives system, and actively taking options away from us and deciding how our games should be for us isn't the job of a game maker software.

**Comment by Kitakazi** [comment] 2023-06-04 08:40
@fearlesswee 
@Tum1370 

That is a separate issue entirely.  Synchromesh is reporting a bug. The player should die and be taken to the game over screen.

**Comment by synchromesh62** [comment] 2023-06-04 10:26
Right now i dont even mind so much if it did take you back to the start marker as long as it restarts the level fresh. ( as if you just started )
Its pointless dying going back to the start marker if doors have been locked behind you etc before you died which is the case in my project. I would settle for a restart level on death Tickbox

**Comment by LeeBamberTGC** [comment] 2023-07-20 11:57
@Tum1370 Can you create a new issue that I can mark as a feature request to restore the multiple lives system. Just for clarity, the system was removed at the request of the community (who at the time regarded it as an outdated system and does not belong in a modern game).  On this occasion, the "deciding how our games should be for us isn't the job of a game maker software" probably does not apply :)

**Comment by LeeBamberTGC** [comment] 2023-07-20 12:13
@synchromesh62 Fixed in next EXP build. Turns out lives was internally set to 9999 for some reason, it would have taken a long time to see the game over screen :)

**Comment by LeeBamberTGC** [comment] 2023-08-01 18:45
@OobieDoob-Benoobie Are you using the latest EXP build with the above fix?

**Comment by OobieDoob-Benoobie** [comment] 2023-08-07 20:53
The issue is that waypoints are ignored now. Instead of respawning at the
last waypoint, the game is over.

It does send you to the title screen, but it shouldn't.

The game I'm creating has several levels and this is not ideal.

I figured it's probably a bug?

**Comment by fearlesswee** [comment] 2023-08-08 08:33
@OobieDoob-Benoobie This is because the way "checkpoints" work in GGC/GGM is that they would just save the player's location at the checkpoint, and then when the player dies the game would deduct 1 "life" and warp them back there, meaning any progress (killed enemies, obtained items/weapons/ammo, etc.) is "saved", and you can keep respawning until you ran out of lives, and got a game over. This was problematic when TGC "removed" lives by limitless, making it impossible to lose the game.

This has since been fixed; the player has one "life", and upon death they lose, and must reload a previous save. This creates the issue you're now seeing; checkpoints don't actually work like checkpoints do in most games; where they create an automatic save game, and when you die the game automatically loads the most recent autosave checkpoint. (Any progress you've made after reaching the checkpoint is not saved.) They're still using the "save player position and warp them there when they lose a life" behavior, but since the player only has one life, they never have a chance to be used.

This is probably best opened as a new feature request, but checkpoints should be updated to function as an actual "autosave" system in-line with the majority of games, or there should be options to restore the "player lives" mechanic, where the player has multiple lives.

At the moment you'll have to design your game(s) keeping in mind the fact that once the player dies, they'll lose any unsaved progress, and there is no autosaving.

**Comment by OobieDoob-Benoobie** [comment] 2023-08-08 19:38
WHOA. That's horrible and uncommonly non intuitive.
For TGC at least. (The more control we have over our creations, the better
no?)

In my game, you traverse several KM from start to finish per level.
I generally try to keep the player busy with combat or traversal puzzles.
So now if the player does not consciously and constantly stop and save,
(incredibly immersion breaking) when they eventually meet their doom, they
will potentially be sent back miles to redo what they've already
accomplished.
This is terrible.
It's unacceptable.

So could you please tell me where I can put in a request for a future
feature?

**Comment by synchromesh62** [comment] 2023-08-09 00:14
Add a **Save Gamestate** zone 
It will automatically save whenever you enter

**Closed** 2024-09-13 16:23 UTC
Labels: bug, Fixed but need confirmation., Max, High, SaveStandAlone
