### ISSUE TITLE
FBX Animation Importer Not Working 

### ISSUE THREAD

**Issue by DarthPickles666** [TheGameCreators/GameGuruRepo#2767] opened 2022-04-06 22:55 UTC
Hi there. 

I am trying to import custom animations for my own character, but no matter how many times I try, the FBX animations are not being recognised. I have tried with multiple characters and it is still the same issue. Granada has tried as well and has had no luck. Who can I send the files to that can look into this issue? 

Cheers

**Comment by Granada1** [comment] 2022-04-06 23:46
These are animation files downloaded from maximo, model with bones and skin . Animation files with no skin FBX

**Comment by Necrym59** [comment] 2022-04-07 02:36
Even if you get them in and animations are named the same as the character creator one thay will not work, i have already posted about this - its bacause of the way the new aminations are handled. I assume this will be address eventually. You can make a script for your indiviual characters though.

**Comment by ZakJudges** [comment] 2022-04-07 09:19
Hi @DarthPickles666, this is a known issue and will be dealt with in the future. A temporary workaround is to download the fbx animation with skin, and import it as a separate object. Then once you have all of the animations you need stored as dbo files, you can import your character and in the animation menu, load your animations using the dbo files you imported earlier.

If that fails, you can send the files you are having issues with to zak@thegamecreators.com and I will take a look :)

**Comment by ArgentArts** [comment] 2022-04-07 15:37
This definitely needs to be fixed. Obviously, people will want to use their own characters in their games at some point. MAX is very cool, but right now it's soldiers and zombies. And any game made with MAX will be soldiers and zombies. And many of us want to make our own games ... which would mean games that don't have both soldiers and zombies. ;)

**Comment by ZakJudges** [comment] 2022-04-27 10:33
@DarthPickles666 This has now been fixed and should be in Friday's update. After updating, could you let me know if the issue is fixed for you? Thanks :)

**Comment by DarthPickles666** [comment] 2022-05-09 16:15
Yep, just tried it, it seems to be fixed, the animations are definitely being recognised now

**Comment by ZakJudges** [comment] 2022-05-11 14:17
Thanks for confirming :) closing this issue

**Closed by ZakJudges** 2022-05-11 14:17 UTC
Labels: bug, Fixed but need confirmation., Max, High, Importer
