### ISSUE TITLE
Grey mess randomly shows up in game.

### ISSUE THREAD

**Issue by Retrogamebloke** [TheGameCreators/GameGuruRepo#2423] opened 2022-03-06 16:39 UTC
Every so often you will see a garbled grey mess of what looks like plains stuck in the level.
![image](https://user-images.githubusercontent.com/44620846/156932477-a60955c3-b63d-4429-937b-5367b13e6431.png)
It is fairly random, but I get it quite often on my level. It also tends to happen every update on first run.

https://user-images.githubusercontent.com/44620846/156932568-ebbad404-7afa-4e2b-9613-2e390ceb1085.mp4

https://user-images.githubusercontent.com/44620846/156932583-9bd81edf-9826-4e3c-bcc4-580d0f0008e5.mp4

https://user-images.githubusercontent.com/44620846/156932594-9baff858-e97f-4f3e-9397-5b7b426d55b3.mp4

A few vids of the same issue when I have seen it.

Just done a couple more tests, but vids are just too big to fit on vimeo. I include one (when the game is running a lot better which is rare and random) and a small gif of a second play when running slow. I found the same glitch near the end of the level, so think the weird gllitch could be the major cause of my speed woes.

https://vimeo.com/685195150
Running faster, still a little slow in places, but WAY better than when it slows.
![Max 2022 03 06 - 16 51 33 01 mp4-low](https://user-images.githubusercontent.com/44620846/156935321-6315a672-e582-4548-8453-8e426794b442.gif)
When running slow, found the grey glitch hidden near the end of the level.

https://user-images.githubusercontent.com/44620846/156939346-cf688724-f13f-43e2-aaaf-e0885bfe1bef.mp4

Fresh map same bug, bit closer now so can see it's the gun shot decals?

**Comment by Retrogamebloke** [comment] 2022-03-08 15:30
It's a tough one to reproduce at times. Ran several different levels a few times today and not seen it until I decided to actually start working on the level. Added a few bushes, scaled and positioned them and then saw it again on first run. Second run no probs, nor a third after placing another bush down.
I've removed my own media before this, but don't think it has any bearing on the issue after seeing it once on a brand new map on one test.
![image](https://user-images.githubusercontent.com/44620846/157269751-0cdf202c-67ac-4f01-92a6-7a5fdb936d9f.png)
![image](https://user-images.githubusercontent.com/44620846/157269832-ce4c4487-0313-4ce6-9df4-64b80dfa7be6.png)
Took some screenshots when it happened.

**Comment by dllllllllllb** [comment] 2022-03-10 14:18
Couldn't reproduce this one. It seemed like the water and bushes made this happen so I tried extremely modifying them and restarting the game many times but that didn't work. Then I played through our demos, but again didn't come across these artefacts. 

@LeeBamberTGC For one of my university project I had a similar issue. It was caused by me requesting to render a texture that was pointing to nothing. It created a large white artefacts that covered most of the screen, looked very similar to what we have here but in 2D :] 

@Retrogamebloke could you post your computer specifications, including your CPU, RAM capacity and GPU?
Also, if you come across these artefacts, please send me an email with that levels .fpm file. Email: maciej@thegamecreators.com

**Comment by Retrogamebloke** [comment] 2022-03-10 16:46
I have sent a demo and the map file. My system specs are as follows.
Ryzen 1700 8 core CPU@3ghz
Geforce 970 GTX 4 gig (3.5gig fast mem, .5 gig slow)
MSI Carbon Gaming Pro M/B x370 chipset
32 gig DDR4 memory
1 TB M2 Hard Disk
1TB sata drive
2TB 7200 RPM storage drive.

**Comment by dllllllllllb** [comment] 2022-03-11 16:40
@Retrogamebloke I tested your level multiple times, but I didn't come across the issue you're reporting.

@ZakJudges I'll forward you @Retrogamebloke level, please test it out when you find some time :]

**Comment by ZakJudges** [comment] 2022-03-12 15:45
Hi @Retrogamebloke 
I also wasn't able to reproduce this one. Could you verify your files using the updater, and see if the issue still occurs? :)

If so, could you send the map one more time? My email address is zak@thegamecreators.com
It would be best to back up and then save **after** the issue occurs. We might get lucky and be able to reproduce it that way. It looks like some sort of corruption of the bullet hole data getting sent to the gpu, which could be hard to fix without reproducing unfortunately

**Comment by Retrogamebloke** [comment] 2022-03-18 20:02
Ok, I'll check the files but do that often anyway :) If I get the bug again I will save the map afterwards and send it. There's no log files that may be of any use?

**Comment by rvanner** [comment] 2022-04-03 13:22
@Retrogamebloke Do you still see this issue? Just before Lee went off for a week's break he said this might be related to bullet hole vertex lists.

**Comment by rvanner** [comment] 2022-04-20 12:16
@LeeBamberTGC I had this appear on me a few weeks back. Could not re-produce it but it shows it's still lurking somewhere. Didn't you say it could be related to bullet hole buffers?
![image](https://user-images.githubusercontent.com/1503593/164228433-19dc6b65-26f0-4322-bbaa-79c0406650dc.png)

**Comment by LeeBamberTGC** [comment] 2022-04-20 12:21
@rvanner Oh yes it is still there being generally nasty. I can reproduce on my NUC with the Island Showdown level too :)

**Comment by PaulSJ** [comment] 2022-04-26 14:06
It could be related to GPU memory, but I would expect it to just slow down by paging data out to system memory, rather than corrupt things like this. Unfortunately I've not seen this happen so not sure how we can track it down.

**Comment by LeeBamberTGC** [comment] 2022-04-27 09:46
@PaulSJ I have reassigned this back to me as I can reproduce it on my NUC, and I suspect a driver esk issue caused by a mis-aligned structure or empty value, or non-filled buffer. Something of this kind.  I will focus my initial thoughts on the polygons that render bullets to the scene, as the texture matches that system.

**Comment by LeeBamberTGC** [comment] 2022-04-28 20:48
NOTE: Going to try RENDERDOC on NUC

**Comment by Retrogamebloke** [comment] 2022-04-30 01:31
Well at least you guys have seen it now. Not that is an easy one to fix I imagine. Just glad to see it's not just my machine that gets the issue. Can't really add any more from my end, other than it exists and severely drops performance whenever I see it. For my levels, it has been a serious issue and makes them very difficult to work with.

**Comment by LeeBamberTGC** [comment] 2023-04-05 16:32
@Retrogamebloke Can you confirm this has been fixed in recent updates, no longer able to reproduce with latest EXP build.

**Closed** 2024-04-06 12:14 UTC
Labels: bug, Fixed but need confirmation., Max, High, Rendering
