### ISSUE TITLE
GGMax EXP Build - Document Behavior Bug

### ISSUE THREAD

**Issue by NewWave2137** [TheGameCreators/GameGuruRepo#4673] opened 2023-05-28 11:34 UTC
Sometimes after checking the document, it doesn't want to disappear from the screen and just stays like you can see in the video no matter what you do, just "Q" sometimes does work sometimes not. 

https://youtu.be/zd9IcG6nTDY

**Comment by Kitakazi** [comment] 2023-05-30 04:21
Happens to me as well. 
It's also strange that you have to use E and then Q to close the image. Would like to be able to just use E to open and close.

**Comment by Blood-Moon-Interactive** [comment] 2023-06-03 01:11
This may be a duplicate of [#4863](https://github.com/TheGameCreators/GameGuruRepo/issues/4683), in which case it says that is fixed.

**Comment by Necrym59** [comment] 2023-06-05 07:01
Fixed

**Closed** 2023-08-25 18:52 UTC
