### ISSUE TITLE
script crashes max when browsing the behaviours

### ISSUE THREAD

**Issue by smallg2020** [TheGameCreators/GameGuruRepo#3374] opened 2022-06-29 13:49 UTC
not sure what is wrong with this as it works fine in classic but this crashes max to desktop when you try to browse it in the behaviour list
[thirst.zip](https://github.com/TheGameCreators/GameGuruRepo/files/9011110/thirst.zip)

**Comment by SampeyFS** [comment] 2022-06-29 14:29
it still crashes with this too

**Comment by ZakJudges** [comment] 2023-01-27 15:46
@smallg2020 Apologies for the late reply. 
I have confirmed the crash. It seems to be caused by the presence of '%' characters in the description, which causes ImGui to try to format into a different string. I will add a fix for the crash next week. But for now, just replace any '%' characters and it shouldn't crash :)

**Comment by ZakJudges** [comment] 2023-02-03 12:51
Hi @smallg2020 A new experimental build is available on Steam with the fix for the crash :)

**Comment by ZakJudges** [comment] 2023-02-16 09:32
Closing this issue as likely fixed. If the issue persists, feel free to reopen. Thanks

**Closed by ZakJudges** 2023-02-16 09:32 UTC
Labels: bug, Fixed but need confirmation., Max, LUA, CRASH!
