### ISSUE TITLE
GameGuru classic grenades throwing away from the aiming point. Throwing Grenades usually follow the center aim crosshairs whoever now it's shifted to the far right.

### ISSUE THREAD

**Issue by Hamada880** [TheGameCreators/GameGuruRepo#2942] opened 2022-04-23 07:55 UTC

**Comment by LeeBamberTGC** [comment] 2022-06-13 16:02
NOTE: Turns out this long standing bug was caused by the incorrect calc of the angle from the starting position of the thing to be thrown throwing off the correct angle. Arg!  Fixed for next beta when it has been uploaded.

**Comment by LeeBamberTGC** [comment] 2022-06-13 16:02
@Hamada880 When we go live on Tuesday can you test this and close if you feel it has been fixed, thanks!

**Comment by LeeBamberTGC** [comment] 2022-06-13 19:49
@Hamada880 Now uploaded to BETA and PUBLICPREVIEW :)

**Comment by Hamada880** [comment] 2022-06-16 12:13
Is the update pushed to steam ? Can't find it.

**Comment by LeeBamberTGC** [comment] 2022-06-16 12:19
@Hamada880 Not yet, it will be released on Friday around 4 PM :)

**Comment by Hamada880** [comment] 2022-06-16 12:24
Perfect, working well now.

**Closed** 2022-06-16 12:24 UTC
Labels: bug, Fixed but need confirmation., GGClassic

**Comment by Hamada880** [comment] 2022-06-17 02:40
Thanks so much Lee, I have tested it on the public review and it works fine. Will update the comments on Friday evening after testing the steam update.

**Comment by Hamada880** [comment] 2022-06-25 03:19
Confirming the grenades bug fixes, it's working fine after the latest update 👍
