### ISSUE TITLE
Terrain editor - Auto flatten interaction

### ISSUE THREAD

**Issue by dllllllllllb** [TheGameCreators/GameGuruRepo#2638] opened 2022-03-24 15:42 UTC
https://gyazo.com/cb304338d33b93bae7ba9ad63207384a

Steps to reproduce:
Place an object with autoflatten enabled
Have the object you just placed selected
Edit terrain
Go back to object tools

**Comment by ZakJudges** [comment] 2023-01-04 14:25
Closing this issue as could not reproduce, and there have been fixes to the autoflatten system since this issue was created

**Closed by ZakJudges** 2023-01-04 14:25 UTC
Labels: bug, Max, Medium, Level Editor
