### ISSUE TITLE
Import Sphere

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#1260] opened 2021-07-16 13:17 UTC
Import Sphere visible. not sure if its meant to be or still WIP.

**Comment by synchromesh62** [comment] 2021-07-16 13:18
![import](https://user-images.githubusercontent.com/35708217/125954212-3f0b62ea-549c-4485-8819-9186dea9d85c.png)

**Comment by 3coms** [comment] 2021-07-16 20:53
I'm experiencing a similar issue with a city model, the city is just one mesh, 19k polycount, and multitextured.
I had imported it from GGMax,

In addition, I'm having issues with that model (the city) and the collision, I'm being unable to walk certain spots, it is like I have some invisible wall in front of me that prevents me to go forward. I'm using "forcesimpleobstacle = 3" in the fpe file.
Remember that the city is just 1 mesh but multi-textured.
And something curious, the player footsteps are like over the concrete, except in certain small spots that it is like metallic, I had moved all the city far away, and there is nothing there, just the city, the light poles, trees, and so on.

PD: The obstacle in my case is invisible.

**Comment by 3coms** [comment] 2021-07-17 00:14
https://youtu.be/LKiGbKaTTPY

**Comment by 3coms** [comment] 2021-07-17 20:06
I've got something visible on my map, it is like a wall in the middle of my map.

![City_weird_wall_GGMax_pic01](https://user-images.githubusercontent.com/47690174/126048243-e8ac5a9e-7043-4b35-b437-aff170da20d7.png)

**Comment by 3coms** [comment] 2021-07-18 14:03
![City_weird_wall_GGMax_pic02](https://user-images.githubusercontent.com/47690174/126070219-e9860a46-158a-4c54-b932-c317d6fc4380.png)

**Comment by ZakJudges** [comment] 2021-07-20 08:11
@3coms Thanks for the info. So I can look into this, could you email the model to zakjudgestgc@gmaill.com? Or if the file is too large when compressed, a link to download would work too. Thanks!

**Comment by 3coms** [comment] 2021-07-20 12:10
@ZakJudges 
Hi, thanks for taking care of it.
The model is 97k, anyway, it is an old issue, and I already sent models to someone then.
The model has nothing to do, that sphere and wall are used as collision mesh for GG/GGMax, and for any reason, GGMax is rendering that geometries when it shouldn't do it, and even given collision, The issue here is why GGMax is doing that?, and the model has nothing to do since OldFlack and me, both are getting the same issue with different meshes, he is getting a sphere because most likely he is using Spheric collision, I'm getting the "wall" because I'm using box collision.

**Comment by LeeBamberTGC** [comment] 2021-07-20 12:18
@3coms Do you remember who you sent the model to?  Step one for Zak and myself is to reproduce it, and all the models we have import fine. I have just released the next internal build so it might actually be resolved in the latest one :)

**Comment by 3coms** [comment] 2021-07-20 13:17
@LeeBamberTGC 
I can't remember it, anyway, the issue was raised on the discord bug section.
![City_weird_wall_GGMax_OLDBUG_pic01](https://user-images.githubusercontent.com/47690174/126329211-e6ede777-8e23-4d0b-9ee9-669783b5c685.png)

Anyway, I would trit to upload the file to GoogleDrive, the issue here is my super-slow internet connection, so it is going to take a long time, I'll post the download link here.

Note: It is important to know that the mesh import fine, but when test the map is when the "collision wall" appears in the middle of the map, sometimes it is visible, sometimes does not, but always prevent me to walk around the map in certain spots.
And this happens with different meshes as you can see in the discord bug section picture I attached above.

Is almost important to remark that if I place the same mesh but manually (as X file using the standard way) then GGMax does no apply the textures right and does not list the material right so you can't set them in the material list, but I'm able to walk around all the map without any issue; do you understand the difference?
The issue is not the importer but the collision mesh GGMax is using to detect collision over the map, for any reason it is appearing in the middle of the map, just when I place the imported mesh (The city) over the map.

**Comment by 3coms** [comment] 2021-07-20 13:58
@ZakJudges  and @LeeBamberTGC 
Done, _City2 stuff_ already sent to you.
If you have any issue, please, let me know it. :)

**Comment by LeeBamberTGC** [comment] 2021-07-20 14:15
@ZakJudges Let me know if you get the files, thanks!

**Comment by 3coms** [comment] 2021-07-20 14:34
You both are welcome :)

**Comment by ZakJudges** [comment] 2021-07-20 14:47
@3coms I've tried out the model you sent over, whilst I didn't get a visible wall, I did encounter collision issues. So we will definitely look into that. Thanks :)

**Comment by 3coms** [comment] 2021-07-20 14:52
@ZakJudges 
Yes, as I said before sometimes is visible (rendered), and sometimes does not. :)
If you want to walk the tops, just set CollisionMode = 9 (convex hull) in the fpe file.

**Comment by 3coms** [comment] 2021-07-20 17:54
City2.X file and how GGMax behaves with.
Not collision issues using X file rather than the FBX imported from GGMax.

[https://youtu.be/ktqvKZybxsE](url)

Placing the X file among other files manually, using the GG standard way.
As you can notice There are not collision issues, but GGMax set the textures wrong, and the materials are listed wrong as well, that mesh has about 5 materials with their own name each one, no just 2 materials as listed.

**Comment by 3coms** [comment] 2021-07-20 18:03
If I make let's say 3 groups of objects (10 objects) in3ds max, and then, when done, I make 1 group with those 3 groups; when I place the composed_mesh in GGMax it just lists 2 or 3 materials rather than the 10 materials the mesh has.

If I make just 1 group with all the objects (10), when I place it in GGMax, it lists all the materials, but with the same name for all them, so you can't know who is who.

**Comment by 3coms** [comment] 2021-07-23 16:42
I think that "collision wall" is causing an extra collision calculation, even like running in a loop, that behavior causes insane ram waste, then you get "Level loaded" forever, till ram waste reaches 97%, so, you are forced to get out via TM. (please refer to the pic below)
I'm literally unable to run that map, and of course, with my "super-faster" internet connection, I'm unable to load the entire map assets to TGC. LOL

![Insane RAM waste on GGMax_2021_07_23_pic01](https://user-images.githubusercontent.com/47690174/126814283-63244a8c-f7e0-426c-b1c6-fcf0f29cfbab.png)

**Comment by LeeBamberTGC** [comment] 2021-11-16 04:22
Cannot reproduce this one. Is it still happening with stock art, or custom art?

**Closed** 2022-02-08 11:02 UTC
Labels: bug, Fixed but need confirmation., Max, High, Importer
