### ISSUE TITLE
GameGuru MAX-animation folder issue

### ISSUE THREAD

**Issue by Keepo1** [TheGameCreators/GameGuruRepo#4165] opened 2023-02-12 13:51 UTC
the Animation choice in character settings dosent open animation folder for the character.

**Comment by ZakJudges** [comment] 2023-03-24 13:51
Note on this issue: I couldn't find the root cause of this, but a workaround was to force detect the animation DBOs in RefreshEntityFolder. This will show the animation library, but will not have any thumbnails correctly displayed. The code that I added should be removed, once the original cause has been found, this is the code that I added:

```
// The animation library was not displaying any animations, sorted_files was not populated with the animation files
// This ensures that they are included
if (foldertype == 6 && pestrcasestr(file_s.Get(), ".dbo"))
	bValid = true;
```

**Comment by plemsoft** [comment] 2023-03-26 08:42
@ZakJudges Fixed now also display thumbs and preview.

**Closed** 2024-09-13 16:18 UTC
Labels: bug, Fixed but need confirmation., Max, High, UI
