### ISSUE TITLE
Project Crashing

### ISSUE THREAD

**Issue by Curiosityuk** [TheGameCreators/GameGuruRepo#3239] opened 2022-06-02 11:18 UTC
So, before the update my project was working fine.
Now I've updated it the thing won't load and I get a pop up saying
"Runtime error 7018"

Levels 1&2 won't load and show the error, but 3&4 do load

Has anyone any idea???

**Comment by ZakJudges** [comment] 2022-11-18 13:38
Hi @Curiosityuk, sorry for the late reply. Error 7018 means that an object has failed to load - this could be because the DBO was moved/deleted, or is not where Max expects it to be. 
If you are still experiencing this problem, you can email me a level that doesn't load, as well as any custom media that it may use, and I will try to see what the issue is. My email is zak@thegamecreators.com

**Comment by ZakJudges** [comment] 2023-01-03 09:12
Hi @Curiosityuk, I will close this issue now. If you continue to experience the crash, feel free to reopen the issue or email me at zak@thegamecreators.com

Thanks :)

**Closed by ZakJudges** 2023-01-03 09:12 UTC
Labels: bug, Max, Waiting for more information., High
