### ISSUE TITLE
Latest EXP Update crashing back to Desktop ?

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#3895] opened 2022-11-11 23:40 UTC
I Have asked about and Necrym59 has the same issue
If i try to add something to my current project or select something Max crashes back to Desktop.
All other versions work fine including the Steam DX12 Default

**Comment by Hamada880** [comment] 2022-11-12 03:59
Is it related to AMD crashes?

**Comment by synchromesh62** [comment] 2022-11-12 08:34
> Is it related to AMD crashes?

No this is since yesterday's updates and im Nvidia anyway

**Comment by ZakJudges** [comment] 2022-11-12 09:13
Hi @synchromesh62, I couldn't reproduce the crash using custom assets. Any chance you could send me a video/a model you have the issue with? Maybe I am doing something differently to you

**Comment by synchromesh62** [comment] 2022-11-12 09:51
> Hi @synchromesh62, I couldn't reproduce the crash using custom assets. Any chance you could send me a video/a model you have the issue with? Maybe I am doing something differently to you

Hi Zak
Here is one of the models in question .. works in all versions including the Steam Retail DX12 and was fine in the EXP up until yesterday.
[sign.zip](https://github.com/TheGameCreators/GameGuruRepo/files/9994693/sign.zip)
Necrym59 has the same issue with one of his .. Fine in all builds and now causes a crash when selected or placed.
[radsuit.zip](https://github.com/TheGameCreators/GameGuruRepo/files/9994694/radsuit.zip)

**Comment by synchromesh62** [comment] 2022-11-12 09:58
One thing that might stand out is that i think both these models were originally in a .X format and imported.
But i do have a lot of those that still work just fine ?

**Comment by ZakJudges** [comment] 2022-11-12 10:07
@synchromesh62 Thanks for the models, I think I found the issue. A new Steam experimental has been uploaded, could you check if it has fixed the crash for you? Thanks :)

**Comment by synchromesh62** [comment] 2022-11-12 10:25
> @synchromesh62 Thanks for the models, I think I found the issue. A new Steam experimental has been uploaded, could you check if it has fixed the crash for you? Thanks :)

Just checked and working perfectly for me now :) Just waiting on Necrym59 to confirm its good for him also.
Thanks Zak that's awesome.

**Comment by Necrym59** [comment] 2022-11-12 10:29
Yep all fixed here too Zac - Thanks... your worth more money :)

**Comment by synchromesh62** [comment] 2022-11-12 10:29
Necrym59 confirmed all working for him also.
LOL .. Necrym59 says he wishes Lee was as fast as you.
Thanks again mate that was a bit of a worry there.

**Comment by ZakJudges** [comment] 2022-11-12 10:44
Awesome, thank you both for reporting and confirming :) Closing this issue

**Closed by ZakJudges** 2022-11-12 10:44 UTC
Labels: bug, Urgent, Fixed but need confirmation., Max, CRASH!
