### ISSUE TITLE
AI - Rate of fire with machine guns and shotgun

### ISSUE THREAD

**Issue by dllllllllllb** [TheGameCreators/GameGuruRepo#2278] opened 2022-02-25 13:36 UTC
AIs rate of fire is ridiculously high when shooting machine guns, especially assault rifle and shotgun.

**Comment by LeeBamberTGC** [comment] 2022-03-08 14:04
@dllllllllllb I would like you to have more control of the weapon aspects of MAX so see if you can find the cause of why these weapons fire FAST and the pistol fires MODERATELY.

**Comment by dllllllllllb** [comment] 2022-03-09 16:09
@LeeBamberTGC This one took me a while, but I figured it out :] The issue is that the AK default fire mode, unlike the rest of the weapons, is set as automatic. In the darkai_shooteffect() the particles and sound effects are set to be looped because of it. 

For now, the AI only shoots a single shot, so I think disabling looping particles and sound effects for AK is a good call. Later when I get the hang of LUA, I could implement burst fire modes for the AI that hold automatic rifles :)

**Comment by LeeBamberTGC** [comment] 2022-03-09 16:21
@dllllllllllb Sounds good, do you want to send me the changed file(s), thanks!

**Comment by dllllllllllb** [comment] 2022-03-09 16:25
@LeeBamberTGC I didn't change any LUA scripts, just the darkai_shooteffect() function

**Comment by LeeBamberTGC** [comment] 2022-03-09 16:29
@dllllllllllb Great. Will be in the next internal build

**Closed** 2022-04-06 13:09 UTC
Labels: bug, Fixed but need confirmation., Max, High, AI
