### ISSUE TITLE
BUG GGMAX VERY LONG DELAY before objects become active in level. 

### ISSUE THREAD

**Issue by imothep85** [TheGameCreators/GameGuruRepo#5247] opened 2024-02-10 18:10 UTC
There is a LONG delay between clicking on a 3D object and the software's reaction to making the object active and selected. The problem is that you have to wait 5sec PER CLICK before the object can be positioned in the level, and you waste an ENORMOUS amount of time waiting for the object to be selected and active once you've clicked on it, and if you click in the wrong place.....it's back to work...
I waste a CRUCIAL amount of time, not to say a HUGE amount of time, waiting for objects to be selectable in real time and for them to be able to be moved in real time, without waiting a monstrous amount of time....it's horrible to have to wait and waste time, not to mention the fact that in the long run, it's extremely hard on the nerves...
This problem needs to be corrected as a matter of urgency, as it causes major development problems, especially when levels are filled with objects of all kinds, and certain modifications need to be made.

Thanks to all

**Comment by synchromesh62** [comment] 2024-02-10 20:57
What's it like to select and move stuff on an default map ?
Things will slow down in the editor if there is a huge amount of content and your level seems HUGE with caves, terrain mesh's and content.

**Comment by Blood-Moon-Interactive** [comment] 2024-02-10 21:31
Also might be helpful to provide machine specs, a video of the issue, maybe a sample model for Lee to examine. Are these all custom models or did they come with Max? Details like that rather than dramatic statements and hyperbole will lead to a resolution faster.

**Comment by imothep85** [comment] 2024-02-11 07:25
my PC is an intel I7700k cpu, Nvidia 1080ti 11gb, and 32gb ram, win10.
My models are all custom only the trees and grass are from max

**Comment by imothep85** [comment] 2024-02-11 10:13
A short video showing HOW slow ggmax is with customs objects, when clicked they are very very slow to become active. 
(this video works for only 2days)
https://streamable.com/id81b4

**Comment by synchromesh62** [comment] 2024-02-11 15:58
> A short video showing HOW slow ggmax is with customs objects, when clicked they are very very slow to become active. (this video works for only 2days) https://streamable.com/id81b4

Well that was not what i was expecting granted. I was expecting a juddery performance so not sure what would cause that delay except a huge amount of assets .. Even so you avoided the crucial question .. **What's it like to select and move stuff on an default map ?** This will confirm if its map related ( as in size and content ) or Max itself.

**Comment by imothep85** [comment] 2024-02-11 16:41
as you can see here, this is a default map from ggmax, 
it takes some time before the object once clicked become active and the user can interact with it...
its the same for every elements in default maps....and same on my game....so has i explained, if we miss the right object when clicked we have to re-click on the right object then do a change, for example a rotation BUT if we have to move the object we have to do another operation again...it's 5sec +5sec+5sec..... etc etc etc
as explained in the beginning of this post.

https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/68c93d6f-8c0c-4e69-8f3a-9f695871db0c

**Comment by synchromesh62** [comment] 2024-02-12 10:15
**SELECTIONABLE objects and interactivity has to be in real-time NOT with HUGE delays.**
They are ..
what your seeing is weird.
This is what i see.

https://github.com/TheGameCreators/GameGuruRepo/assets/35708217/419f605c-245d-486a-b82c-154cf15248d4

**Comment by imothep85** [comment] 2024-02-12 11:28
well as i explained and show in the videos is completely different.
i have HUGE delays before the objects become active

**Comment by LeeBamberTGC** [comment] 2024-02-12 16:58
@imothep85 Thanks for the videos, the zombie escape level is the real indicator as that level is quite small with just a few objects and you can clearly see the object being clicked, then a long delay before it is highlighted.  Your system specs look fine, and I am pretty sure this has not been reported elsewhere, so it is likely something systemic, we just need to figure out what is causing it. The behaviour that is frustrating you is NOT normal, and is a bug for sure.

Can you create an empty project with one carboard box dropped in, and then click that and move it in the video, I just want to make sure it is related to something during the click and not the number of objects in the scene or some kind of level complexity issue.  We can then add some debug info to find out where the slow part is.

Are you okay with me sending you a debug build and some instructions on how to use OPTICK, as that performance profiler will tell me pretty much what I need to know?

**Comment by imothep85** [comment] 2024-02-12 19:46
hare its a recorded short video, i created LOT of boxes in the default map and i can select them in real time and modify them without delay.

https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/13f914ce-69d8-4fb1-8a50-ca013c21eb15

**Comment by imothep85** [comment] 2024-02-12 19:58
and here some technical info when i run my game.
![info](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/997262cc-3764-46d8-bebb-7f3ec68b7a8f)

**Comment by imothep85** [comment] 2024-02-12 20:06
here another test with lot of coffins... i can select them in realtime

https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/47e1bf20-fa0d-4fe3-bb15-2ff4b9a0e204

**Comment by imothep85** [comment] 2024-02-12 20:23
and here another test with my 3d dunes, i make it giant to test and put lot of massive columns, and coffins everywhere, but no lags... i can select the objects in realtime.
https://streamable.com/zbeodj

**Comment by imothep85** [comment] 2024-02-12 20:39
In my game i add tons of lights, to create beautiful ambient spots in each scene.
Maybe the lights are the problem ?
![lights01](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/80303eb6-e547-4b6e-a93a-0826f9e79617)
![lights02](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/f8b3a25a-673d-4d51-8801-a823d74db1a4)
![lights03](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/a6eb07cc-7513-4ad5-a4d3-9ac5b9f85ff8)
![lights04](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/00f19ddd-951b-455f-9e78-6e6affde7bf6)
![lights05](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/4a0b8ec0-908a-4bec-97bf-c072f85e1688)
![lights06](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/ba09d4c3-15b5-4cbb-8dc5-197b645f96a6)
![lights07](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/492a182f-cab6-41c0-a733-21c1361cd245)

**Comment by imothep85** [comment] 2024-02-12 21:08
I'm removing the lights, but doesn't look that it's the problem...

**Comment by imothep85** [comment] 2024-02-12 21:23
I FOUND SOMETHING........
but i can't explain it because i'm not a developer, 
i did two video in this video i will show you something, 
when i CLICK on my cave massive stones i can click in real-time because they are LOCKED not editable, 
i locked them to prevent the object to be moved.

but ONCE i UNLOCK the objects, it become extremely slow to edit the objects properties

https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/0b066a1a-ab0d-48f9-b420-e17f7c705a2d


SO... LOCKED objects can be clicked in real-time, but not editable...
UNLOCKED objects are very SLOW to edit

**Comment by imothep85** [comment] 2024-02-12 21:25
and HERE the same cave with the UNLOCKED rocks, you can see that it's extremely slow when i click on the objects ....
https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/f0f4d6e7-4001-425c-8b2b-734c2ffb7d29

**Comment by Melburnian70** [comment] 2024-02-17 06:08
@LeeBamberTGC I just saw this ticket now and wanted to let you know the same thing is happening to me on some of my levels.

I only noticed this happening in the last week or two, so I wonder whether this has something to do with a recent update to the EXP build (which I'm on).

Another thing I noticed is that the delay doesn't happen when you drag-to-select objects - only when you click on them. See the video for a demonstration.

https://youtu.be/Bc3pG4sFZRw

Cheers,
Roberto

PS. my specs are : Acer Nitro 5 Gaming Laptop, 12th Gen Intel(R) Core(TM) i7-12700H 2.70 GHz, 16GB RAM, NVIDIA GeForce RTX 3050 Laptop GPU, Windows 11 Home

**Comment by Melburnian70** [comment] 2024-02-17 23:39
Ok, I think I fixed this by changing a OneDrive setting.

OneDrive was syncing everything in the ... _Documents > GameGuruApps > GameGuruMAX > Files_ folder to the cloud and only leaving a shortcut to them on my hard drive to save space. 

I right-clicked the _Files_ folder and chose 'Always keep on this device' and after a couple of hours of it copying the files back to my computer, I can now select objects without any delay.

@imothep85 could you try this to see if it helps?

**Comment by imothep85** [comment] 2024-02-18 05:31
what ??? can you explain in details, i don't use any cloud services from Google, where are those options, in Steam in gameguru max ???

**Comment by Melburnian70** [comment] 2024-02-18 08:35
OneDrive is built into Windows. I think it's turned on by default - although I have a Microsoft 365 subscription, so I don't know if that makes a difference. 

Here's some more information about it https://www.computerworld.com/article/3256907/microsoft-onedrive-cheat-sheet-backup-sync-share-files.html

If you right-click on the _Files_ folder inside _Documents > GameGuruApps > GameGuruMAX_ do you have the option to  'Always keep on this device'?

![always keep on device](https://github.com/TheGameCreators/GameGuruRepo/assets/2385698/031383c4-69db-4fe6-96d1-d6b0a98f993e)

**Comment by imothep85** [comment] 2024-02-18 09:06
as i said i dont use any cloyd services, one drive is deactivated on my windows

**Comment by Melburnian70** [comment] 2024-02-18 11:00
Ok. I thought this might be the reason, as I can't think of anything else that's changed with my system.

**Comment by imothep85** [comment] 2024-02-18 13:33
@LeeBamberTGC 
I tried, to remove every BIG objects in my level --> that changed nothing
I tried, to remove every Tree & Grass objects in my level --> that changed nothing

So i'm stuck & wait... for some good news i hope.

**Comment by LeeBamberTGC** [comment] 2024-02-19 21:42
@imothep85 Having trouble downloading your 1.5GB+ file from ONE.COM. Can you try uploading again, or choosing something like Google Drive which provides free upload/download will work with my system no worries.

**Comment by imothep85** [comment] 2024-02-19 22:33
How is that possible ??
everyone can download the file, even the technical team of one.com tried & checked the file download is no technical problem with that.

**Comment by LeeBamberTGC** [comment] 2024-02-19 22:42
@imothep85 I sent you an email on this earlier. Tried on Chrome and Microsoft Explorer, but both terminated before the download was completed.  Maybe spl;it the file into two zips and upload those, that might do it.

**Comment by imothep85** [comment] 2024-02-19 22:43
i sent you a new url now using wetransfer service

**Comment by Melburnian70** [comment] 2024-02-20 04:40
This started happening to me again. 

I think I've narrowed it down to creating groups. When I group objects and then drag them into the scene to create duplicates, I get the delay.

After I click all the groups in the scene one-by-one and ungroup them, the delay goes away.

**Comment by imothep85** [comment] 2024-02-20 10:39
yes witg the groups its always a delay but in my game i have no groups

**Comment by LeeBamberTGC** [comment] 2024-02-20 12:36
@imothep85 I have the file now and was able to reconstruct the loading of the level and navigate through it. Now the next step is for me to reproduce exactly what you are seeing.
1. When I load THE CAVE.FPM level, I see this: 
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/bbdadf91-5bc3-4b3b-a766-aa3a1f052c33)
2. As you can see, I have activated the FPS score and level editor details so I can see the resources used.
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/c312f0ff-9d80-4267-9e45-7f1a2082f933)
3. The takeaway is the GPU score should be around 16, but is in fact 126, the general reason is the amount of content in the level, with the largest user being the shadows being rendered.
4. That aside for the moment, the first thing I tried was to follow the original issue bug report "LONG delay between clicking on a 3D object and the software's reaction to making the object active and selected".  The view I have is the same as that stored in the level file so we can match our steps exactly. I clicked the 5 coffins in turn and they selected right away: 
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/1acc218b-09ff-4325-8bb3-5935be57e171)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/5cdc489c-e5ca-42af-97d1-42bad12dd781)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/6ebd79cc-e9cc-477c-bd32-79a9165e34d1)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/0d890004-b969-43fa-a769-68e5df625455)
5. There was no long delay between clicking and the object highlighting.  Now there IS A DELAY due to the high GPU framerate usage (126ms vs 16ms) which causes a click to be missed if you do it quickly.
6. When I switched shadows to minimum, the GPU score improves to 11ms:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/d82ee358-faea-4887-a1ce-28d968df3573)
7. When I do that, the clicking and the object highlighting is super instant.

Can you go through the steps I did above [4] through [7] and confirm without moving the camera, that after following the above steps to reduce the shadows you could click all 5 coffins instantly with ZERO LAG.  From this test we can proceed further.

**Comment by imothep85** [comment] 2024-02-20 12:55
The delay is still there, i tried that too before, no lights, no shadows etc all to the minimum it changes nothing

https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/3d50f3a1-d324-40ac-870d-a2327eefa4e1

**Comment by LeeBamberTGC** [comment] 2024-02-20 13:03
@imothep85 Can you switch on your FPS and level editor stats and present them similar to how I have them here so I can see what is taking the time:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/6681cd4f-9e1b-4eb0-8d85-4452ec0c826b)

Also, I noticed your camera angle was different to mine. Mine was from loading your THE CAVE.FPM level you sent me with no changes once loaded. It looks like you moved your camera to face the Coffins in your video. Can you load your level and leave the camera position and angle without moving it, so you can show an exact screen as the one I see, from there we can align your steps to reproduce, thanks!

**Comment by LeeBamberTGC** [comment] 2024-02-20 13:05
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/28617ce1-7e9d-4241-8554-ba585b6b9135)

**Comment by imothep85** [comment] 2024-02-20 13:12
i want to tell you this i never saw, found that fps editor profile it doesn't appear on my gameguru even if i click
![fps](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/47ada236-649d-4d96-a2d3-9c933593e168)

**Comment by imothep85** [comment] 2024-02-20 13:15
and my view, same as the file i sent you
![fps-view](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/13729030-b067-4129-8789-f6fda23b23ee)

**Comment by LeeBamberTGC** [comment] 2024-02-20 13:31
@imothep85 Thanks for the stats, interesting stuff. Looks like you have a decent GPU to render a high resolution and lots of shadows, much faster than my AMD card so I think we can discount that as the reason.  I did notice something that COULD be a clue which is our CPU scores.  Mine is better.  Can you take a shot in the camera pose when the level first starts similar to mine so I can see it with no shadows and nothing highlighted:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/5e51512c-e194-4abc-ae36-061047a4802b)

**Comment by LeeBamberTGC** [comment] 2024-02-20 13:31
@imothep85 And maybe zoom into the stats so I can read the values. As you can see, I can process the level editor in this state at 2.7ms per cycle.

**Comment by imothep85** [comment] 2024-02-20 13:39
![fps-view02](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/7f0545cc-904b-41ee-a77e-28f405f9a8c5)

**Comment by imothep85** [comment] 2024-02-20 13:41
the only stats i have are those i was showing you
![stats](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/df3f9562-b31c-41ea-a99f-f833b5824cc8)

**Comment by imothep85** [comment] 2024-02-20 13:44
My screen resolution is in 4k native.
![stats 02](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/d880dd48-86e5-4590-bb25-75c2915b3dfc)

**Comment by LeeBamberTGC** [comment] 2024-02-20 14:46
@imothep85 Indeed, looks like your CPU is about 4-5 times slower than mine, which might explain why I cannot reproduce if this is a CPU-bound issue. If the clicking of an object is a CPU-intensive task (most likely), then you would see a 4-5 (even 10-20) times slower response than on my PC, which might explain things a little.

First up, I like your level, very creative!  I also see it's very polygon-intensive, with single meshes at 30K triangles, high geometry static objects scattered across the horizon and sky, and most angles require 10 million polygons to be rendered, and that's just for the visible geometry, not counting the repeats from shadows and reflections. The bottom line is that you have presented one of the most intense levels I have seen created in MAX to date.

I am going to run some deeper OPTICK performance profiling with your level, and see if I can see some CPU wastage.  Even a small detection on my PC that gets fixed will mean a big gain on your PC (my guess).

P.S. Remind me what your CPU Make and Model is again, thanks!

**Comment by imothep85** [comment] 2024-02-20 14:56
my PC
winwos 10
CPU I7-7700k
ram 32gb corsair
Graphic card
Nvidia 1080TI 11gb
SSD 500gb nvme2
and other storages 2tb


i tried to remove the lights in my level, to reduce shadow and light quantity but it doesn't change anything.
can you tell me which object has 30.000k polygon?

**Comment by LeeBamberTGC** [comment] 2024-02-20 15:07
@imothep85 Some good news, I can certainly see a spike in CPU activity when selecting objects via OPTICK:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/7a6ac762-13d0-45b4-8804-e446b7f8ceee)

Bodes well for a solution if we can somehow spread the load of this work when selecting objects...

**Comment by LeeBamberTGC** [comment] 2024-02-20 16:52
@imothep85 New EXP build uploaded with optimization to the object select and release code. Turns out it was updating the collection list each time you released, and if you have a LOT of objects, this could cause a small delay on my PC, and I imagine a larger one on yours.  No more spikes, but let me know how the new build feels, thanks!

**Comment by imothep85** [comment] 2024-02-20 17:54
THANKS LEE i saw the update now i can select the objects again in real-time ! you can put this on SOLVED .
![621ba8e24f74c9cd5bc66495](https://github.com/TheGameCreators/GameGuruRepo/assets/8946215/a1b10c4a-f5dc-4f36-b005-3ada3c6ea175)

**Comment by LeeBamberTGC** [comment] 2024-02-20 19:27
AWESOME, thanks for the image ;)

**Closed by LeeBamberTGC** 2024-02-20 19:27 UTC
Labels: bug, Fixed but need confirmation., Max, Medium, Performance
