### ISSUE TITLE
Global Variables not holding value.

### ISSUE THREAD

**Issue by davetgc** [TheGameCreators/GameGuruRepo#4244] opened 2023-03-16 18:30 UTC
In the latest build, Globals created in the HUD editor aren't retaining their values. 

Once created, you can adjust the value, but they always return 0, in the HUD editor and in game.

![image](https://user-images.githubusercontent.com/99803873/225718793-ee95bd22-fa54-4225-b656-892a4b20d68d.png)

In the screenshot, the highlight global is Hunger and should be showing 100.

**Comment by LeeBamberTGC** [comment] 2023-04-12 17:28
@davetgc Closing this as cannot reproduce. If you see it in the next EXP build, feel free to reopen with a step by step from a fresh game project

**Closed by LeeBamberTGC** 2023-04-12 17:28 UTC
Labels: bug, Max, Waiting for more information., High, Huds
