### ISSUE TITLE
Some scripts don't work when loading game save

### ISSUE THREAD

**Issue by SampeyFS** [TheGameCreators/GameGuruRepo#5463] opened 2024-04-16 08:13 UTC
hi there is a bug in loading the save game some scripts don't work when loading the game save game for example the door doesn't open the lights stay on (entire game unpacked with standalone)

**Comment by davetgc** [comment] 2024-04-16 14:19
Can anyone provide a reliable way of replicating this please?

**Comment by SampeyFS** [comment] 2024-04-16 14:20
Yes, you know everything, I passed the project on to him @LeeBamberTGC

**Comment by synchromesh62** [comment] 2024-04-17 00:05
I can confirm there are issues with loading saves **in fact just loading a level 2** a lot of stuff fails that work just fine in the editor.
I tried to do a list but did not really know where to start and without creating a couple levels your familiar with i really don't know how Lee will be able to test it :(

**Comment by SampeyFS** [comment] 2024-04-17 06:25
Thank you for the confirmation :-)  :-) @synchromesh62

**Comment by synchromesh62** [comment] 2024-04-17 11:36
> Thank you for the confirmation :-) :-) @synchromesh62

Confirmation yes, But fixing it is something else. 
Saving a whole snapshot of every setting ( including what has already been activated ) must be an absolute nightmare even for Lee.

**Comment by LeeBamberTGC** [comment] 2024-04-17 14:17
@SampeyFS I now have your 2GB standalone "The hermit" game. Can you give me a detailed step by step what I need to do to see the issue, perhaps even a short video showing running the game and seeing the problem, thanks!

**Comment by SampeyFS** [comment] 2024-04-17 14:48
That project every now and then lua errors appear alone try to load my save you see that the scripts are not loaded they don't work every now and then lua errors alone are written

**Comment by C4ever08** [comment] 2024-04-21 22:58
I now also have two levels that throw errors. And its seems odd as all my other levels use the same scripts and no errors. I did take it upon myself to change the scripts out and save, then reloading and re applying scripts but it didn't work sadly. But if i take all scripts out of level the level works fine. I have also verified many times and went into EXP then back into Public with no luck hoping for a fix soon.

**Comment by LeeBamberTGC** [comment] 2024-04-22 11:24
@C4ever08 It is possible your issue is different from the one reported here. Can you create a new issue and post as much detail about your own level that throws script errors, and then add a link to that issue here so we can connect them in case they are related, thanks!

**Comment by SampeyFS** [comment] 2024-04-30 08:53
The problem is always present when loading the save, some lua scripts don't work consistently @LeeBamberTGC

**Comment by SampeyFS** [comment] 2024-05-01 08:08
https://youtu.be/eFi9b9c2EdI     ( Video of the save loading bug some scripts (lua) do not work when loading the game save )

**Comment by SampeyFS** [comment] 2024-05-01 08:09
https://www.youtube.com/watch?v=eFi9b9c2EdI

**Comment by SampeyFS** [comment] 2024-05-01 08:09
https://www.youtube.com/watch?v=eFi9b9c2EdI

**Comment by SampeyFS** [comment] 2024-05-03 07:54
hi how do I solve the timer problem and the day when it goes off the next day it does like this it seems like it can't move on to the next day watch the video

@LeeBamberTGC @Necrym59 

https://www.youtube.com/watch?v=RmpY8cbCvVs

**Comment by Necrym59** [comment] 2024-05-04 03:24
@SampeyFS The day change has been fixed ensure your using the latest workshop behavior

**Comment by SampeyFS** [comment] 2024-05-04 08:12
yes, thank you very much, it's the workshop that doesn't update well, but it works, thanks

**Comment by SampeyFS** [comment] 2024-05-06 13:15
I confirm that the problem comes from saving the game because when loading some lua scripts they don't work the first one that doesn't work is fish.lua and craft table.lua the lights stay on it happened that I loaded the save the game crashed and closed so the (bug) comes when the game saves so it's max  @LeeBamberTGC

**Comment by LeeBamberTGC** [comment] 2024-05-06 13:19
@SampeyFS Preben may have found an issue related to visibility checks with scripts not being thread-safe, should get a fix in the near future so keep an eye out for that one. May be some time before it makes it into the EXP build however,

**Comment by LeeBamberTGC** [comment] 2024-05-06 14:31
@SampeyFS Thanks for your standalone and save position files.  Was able to reproduce the script crash:
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/35840583/8cfcbd53-6cd8-495f-b887-12bb34d389e2)

@Necrym59 Maybe the info in the dialog will help you locate an issue with the script, but hold off until you get the update from Preben this week as he has found a major script threading issue that may be the cause of this (and other things).

**Comment by SampeyFS** [comment] 2024-05-06 15:18
Here's how it comes out, let's hope, come on, I'm glad I was of help!  :)

**Comment by Necrym59** [comment] 2024-05-06 21:15
@LeeBamberTGC 
Have fixed the stray distance check when npc is off mesh when roaming, updated workshop etc.

**Comment by SampeyFS** [comment] 2024-05-09 08:15
![Screenshot 2024-05-09 101109](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/5a155f21-ad2a-4b16-886a-7fcb5d87bc0e)
![Screenshot 2024-05-09 101035](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/f8135faa-e249-48d1-bc25-df55fab4d3ba)
![Screenshot 2024-05-09 101011](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/d3519f20-5359-4963-b866-1c13d4f66c51)


I tested the stability it seems excellent no crashes there is still the problem that when loading it doesn't load some scripts as you can see in the photos the first is fish.lua trader.lua @LeeBamberTGC

**Comment by SampeyFS** [comment] 2024-05-09 08:22
Now a crash happened, the game closed on its own and the bears are invisible

**Comment by SampeyFS** [comment] 2024-05-09 11:51
![Screenshot 2024-05-09 134828](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/9cf594fc-b4fb-48a2-8b3f-0221c28fbc6e)

Loading unpacked game with (standalone appearance of grass in the streets

**Comment by LeeBamberTGC** [comment] 2024-05-09 13:13
@SampeyFS How can the bears go invisible AFTER a crash?  Can you make a short video of the crash as you see it, thanks!

**Comment by SampeyFS** [comment] 2024-05-09 14:37
I solved that, I took them off and put them back on, now it works, the problem remains with the lua light lua scripts etc which are not loaded

**Comment by SampeyFS** [comment] 2024-05-09 15:03
I still have problems with the passage of the day I updated the workshop for me the work shop doesn't work well for me @Necrym59

**Comment by SampeyFS** [comment] 2024-05-09 15:16
![Screenshot 2024-05-09 171259](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/775f6db2-9385-4ca4-a01a-c2826d65e74e)

see the photo if you set it to 158 it works the transition would be 11 PM if you set the slider to 0: 0 0 it doesn't work it does the same thing as before I don't know why

**Comment by Necrym59** [comment] 2024-05-09 17:32
This is the latest version, it definatley works if not please give/show details as to what is actually happening.
[day_night_v15.zip](https://github.com/TheGameCreators/GameGuruRepo/files/15265559/day_night_v15.zip)

**Comment by SampeyFS** [comment] 2024-05-09 17:35
here you see that the workshop doesn't work mine is v14 this is v15 thanks anyway the workshop doesn't work

**Comment by Necrym59** [comment] 2024-05-09 17:45
Here is an updated one V16 this one works with the midday working correctly
[day_night_v16.zip](https://github.com/TheGameCreators/GameGuruRepo/files/15265784/day_night_v16.zip)

**Comment by SampeyFS** [comment] 2024-05-09 18:04
https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/d4ca210f-7b58-4ac9-893e-3555fe221e9c

This is version V16
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/bce13fc7-0c97-47db-a4ce-92a22d00d947)

**Comment by SampeyFS** [comment] 2024-05-09 18:29
Should I write (MyDayTime) this in Readout user Global?

**Comment by SampeyFS** [comment] 2024-05-09 18:31
![Screenshot 2024-05-09 203033](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/46410b33-0357-439d-9aa2-dcf2d8e6d00d)
![Screenshot 2024-05-09 203052](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/fcfe6bb9-7e90-4fcd-96f7-a669f47e7e32)

**Comment by Necrym59** [comment] 2024-05-09 18:42
No it shouldnt matter what name you use for your user global

**Comment by Necrym59** [comment] 2024-05-10 00:49
The Day/Night Behavior wasnt being reset correctly after a 24hr loop, this has been fixed in this version.
[day_night_v17.zip](https://github.com/TheGameCreators/GameGuruRepo/files/15269028/day_night_v17.zip)

**Comment by SampeyFS** [comment] 2024-05-10 07:41
![Screenshot 2024-05-10 093949](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/ddfbb171-da70-419a-b168-7638812d0ec3)
![Screenshot 2024-05-10 093958](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/035d7e8e-125d-4f8e-9145-e07b2ed9a61e)


Standalone Problem Grass bug on the road game imported from Standalone @LeeBamberTGC

**Comment by davetgc** [comment] 2024-05-10 10:38
@SampeyFS - How is this grass issue related to this post? "Some scripts don't work when loading game save"?

If you have a new issue, please start a new post.

Thanks.

**Comment by SampeyFS** [comment] 2024-05-10 10:40
@davetgc  It is always tied to standalone always the same

**Comment by Necrym59** [comment] 2024-05-11 02:10
The Day/Night Behavior 'Day' wasnt being reset correctly after a 7 day loop, this has been fixed in this version.
[day_night_v18.zip](https://github.com/TheGameCreators/GameGuruRepo/files/15281312/day_night_v18.zip)

**Comment by SampeyFS** [comment] 2024-05-11 07:33
thank you for the work you do

**Comment by SampeyFS** [comment] 2024-05-11 08:05
![Screenshot 2024-05-11 100230](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/7dbb2c45-3e76-427a-914d-521fc5ee397f)
![Screenshot 2024-05-11 100354](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/c4dab06d-5bf8-416c-a2f3-9f27dc749b8c)

there is a problem at 12 it didn't go off the next day as you can see it remained the same on Monday

**Comment by Necrym59** [comment] 2024-05-11 08:30
No it works perfectly here..
Give me a screen shot of your start settings and detail at what point it doesnt change over.
also cobfirm your using the correct version of the script

**Comment by SampeyFS** [comment] 2024-05-11 08:38
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/82a76e35-9f34-43b8-bf8d-13fe56a56383)
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/cdc1e011-c122-4024-83af-9934af60bd0e)

**Comment by SampeyFS** [comment] 2024-05-11 08:50
Now it works, you can see that it wasn't updated well when the sleep script comes out, would it be in the morning to switch to light?

**Comment by SampeyFS** [comment] 2024-05-12 10:27
I ask a question, is a script feasible to build a house (I don't understand lua) it's a question to build, I mean piece by piece pruning, roof, etc. @Necrym59

**Comment by Necrym59** [comment] 2024-05-12 21:03
@SampeyFS 
No, not at the present time. To do those types of things, we have to create a resource class system then we have to organise a grid system for placement.

**Comment by LeeBamberTGC** [comment] 2024-05-13 14:14
@SampeyFS Looks like this thread has changed conversation to the Day Night system which Necrym is the author. I am happy for this conversation to continue here, and let me know if the original reason for this issue being posted has been solved and I can close this one down.  My own tests to create a simple level with door and key, save as standalone and then run and save a game position at various states all reload the game position perfectly with all states restored when using stock objects and scripts.

**Comment by SampeyFS** [comment] 2024-05-13 14:19
No lee the scripts when loading the save don't work and you find grass on the road scripts that don't work when loading there are many the first fish.lua the lights stay on try with my project make a save and then reload the save and see what happens

(lua scripts are not loaded on save) @LeeBamberTGC

**Comment by SampeyFS** [comment] 2024-05-13 14:19
![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/f8264ceb-c581-4a25-ba74-37305734e656)

![image](https://github.com/TheGameCreators/GameGuruRepo/assets/108415264/03914c94-acf2-471a-9933-a1456931a830)

**Comment by SampeyFS** [comment] 2024-05-13 14:20
load save games

**Comment by SampeyFS** [comment] 2024-05-13 14:21
necry  issue has been resolved

**Comment by LeeBamberTGC** [comment] 2024-06-04 15:05
@SampeyFS As it has been some time and new Necrym scripts have been employed, can zip up and send me a standalone of the game you show in your video, along with that last slot save game too. I can then reload your game save position and reproduce what you see. Your latest video did not show the grass in the path, so if you still see that then produce a new video here that shows loading the save game and seeing the grass in the path along with the spinning fishes, thanks!

**Comment by SampeyFS** [comment] 2024-06-04 15:09
ok i upload the game

**Comment by LeeBamberTGC** [comment] 2024-08-14 15:06
@SampeyFS More fixes in the latest DEVTEST, let me know if this improves things. In the meantime I will check out your latest standalone example you provided about the trees.

**Comment by SampeyFS** [comment] 2024-08-14 15:28
It seems to work, the problem with the Butterflies (animals) script remains, if you look at them when loading the save you can see that the lua loads poorly, they walk without the wings dying Try with a test map and you see that the butterflies don't work well when loading the save

**Comment by LeeBamberTGC** [comment] 2024-08-26 16:25
@SampeyFS Fixed for the next DEVTEST build.

**Comment by SampeyFS** [comment] 2024-08-26 16:32
![Desktop Screenshot 2024 08 26 - 18 29 08 34](https://github.com/user-attachments/assets/3de0cf91-4e61-4970-bffc-16effd4c1f00)
![Desktop Screenshot 2024 08 26 - 18 29 12 77](https://github.com/user-attachments/assets/1d7866ff-6b93-4c06-aa22-0588cface19e)

Now they work with the new Build you can see them by extracting with standalone thanks @LeeBamberTGC

**Comment by LeeBamberTGC** [comment] 2024-08-26 16:37
@SampeyFS Great news thanks, also uploaded a new DEVTEST with the butterfly fix too.

**Closed** 2024-10-11 23:31 UTC
Labels: bug, Fixed but need confirmation., Max, High, LUA
