### ISSUE TITLE
Grouped objects don't retain their proper angles

### ISSUE THREAD

**Issue by rvanner** [TheGameCreators/GameGuruRepo#2119] opened 2022-02-15 15:35 UTC
See this video, one of the walls goes out of line.
https://youtu.be/5bSn57aUHyo

**Comment by LeeBamberTGC** [comment] 2022-02-16 13:55
@rvanner Not able to reproduce. Spent a good ten minutes, always my walls behaved:

![image](https://user-images.githubusercontent.com/35840583/154279028-b2853a86-0a60-4bee-9d7e-c5c7205209bd.png)

Please do this from scratch, or send me an FPM so I can see how the objects are oriented, on the off chance I can reproduce at this end.

**Comment by rvanner** [comment] 2022-02-16 15:07
@LeeBamberTGC I have the condition when this happens. If you click and hold a group and then press R to rotate it, the object you are clicking on will not rotate with the rest properly.

**Comment by LeeBamberTGC** [comment] 2022-02-21 14:10
@rvanner This issue now duplicated, so closing this one and new one picks up where this left off as the new one is newer: https://github.com/TheGameCreators/GameGuruRepo/issues/1761

**Closed by LeeBamberTGC** 2022-02-21 14:10 UTC
Labels: bug, help wanted, invalid, Max, High, Groups
