### ISSUE TITLE
Latest DX12 Build ( No Capable Adapter found )

### ISSUE THREAD

**Issue by synchromesh62** [TheGameCreators/GameGuruRepo#3681] opened 2022-09-07 00:55 UTC
As the heading states ... Latest DX12 Build ( No Capable Adapter found )
Rolling back to Public works fine.
AMD RX580 latest Adrenaline Drivers.
Running Windows 11 up to date.

**Comment by LeeBamberTGC** [comment] 2022-09-07 12:42
@synchromesh62 Can you send me a screenshot of how this error manifests, thanks!  The EXP build was updated last night with the first experimental test version of the new DX12 engine. Works on mine, but I think we have a ways to go when we move from DX11 to DX12 :)

**Comment by synchromesh62** [comment] 2022-09-07 14:59
> @synchromesh62 Can you send me a screenshot of how this error manifests, thanks! The EXP build was updated last night with the first experimental test version of the new DX12 engine. Works on mine, but I think we have a ways to go when we move from DX11 to DX12 :)

Hi Lee ... Attached a vid but not a lot to see.
Its pretty instant as soon as i try to launch from the Taskbar. 
https://youtu.be/-6vgbh5AFjc
Hope it helps :)

**Comment by LeeBamberTGC** [comment] 2022-09-07 15:28
@synchromesh62 Thanks for the vid, helped me find the line of code that it stops at :)  Do you know if your GPU supports these adapter modes:

        D3D_FEATURE_LEVEL_12_0	= 0xc000,
        D3D_FEATURE_LEVEL_12_1	= 0xc100,
        D3D_FEATURE_LEVEL_12_2	= 0xc200

MAX engine is needing D3D_FEATURE_LEVEL_12_1 to proceed.

**Comment by synchromesh62** [comment] 2022-09-07 16:06
> @synchromesh62 Thanks for the vid, helped me find the line of code that it stops at :) Do you know if your GPU supports these adapter modes:
> 
> ```
>     D3D_FEATURE_LEVEL_12_0	= 0xc000,
>     D3D_FEATURE_LEVEL_12_1	= 0xc100,
>     D3D_FEATURE_LEVEL_12_2	= 0xc200
> ```
> 
> MAX engine is needing D3D_FEATURE_LEVEL_12_1 to proceed.

I will have to investigate further but it is a DX12 card. 
If its not 12.1 then that's me out of the running for some time :(

**Comment by synchromesh62** [comment] 2022-09-07 17:25
@LeeBamberTGC 
Looks like No to that ..

![DX12](https://user-images.githubusercontent.com/35708217/188941188-1fcc4928-d5de-40f5-ac46-32eda58c4b8e.png)

**Comment by LeeBamberTGC** [comment] 2022-09-07 17:38
@synchromesh62 Looks like DX12_1 came in around 2016 (6 years ago).  This is currently used as Wicked Engine sets this requirement as the current (default) minimum. I can scale back to DX12_0 and lose whatever _1 provides, or we could set a min spec at DX12_1. I suppose it depends what _1 is adding to the pie :)  I would rather not alientate DX12 users who have as DX12 card, I do not think they will mind losing features to gain support for their card. Worst case, current DX11 users would find the latest version does not work for them - ouch!

**Comment by synchromesh62** [comment] 2022-09-07 17:43
> @synchromesh62 Looks like DX12_1 came in around 2016 (6 years ago). This is currently used as Wicked Engine sets this requirement as the current (default) minimum. I can scale back to DX12_0 and lose whatever _1 provides, or we could set a min spec at DX12_1. I suppose it depends what _1 is adding to the pie :) I would rather not alientate DX12 users who have as DX12 card, I do not think they will mind losing features to gain support for their card. Worst case, current DX11 users would find the latest version does not work for them - ouch!

Well at the moment is only me it seems. Maybe see if others report the same .. As long as the minimum spec Nvidia 970 GTX runs with DX12.1 then even i cannot really complain.

**Comment by LeeBamberTGC** [comment] 2022-09-07 17:52
@synchromesh62 Yes GTX 970 was the first NVIDIA card to fully support DX12_1 (back then the advanced DX12) :)  I will run some experiments to see what we lose when we knock it back to vanilla DX12_0

**Comment by GraPhiX-Guru** [comment] 2022-09-07 19:07
Looks like DX12 Ultimate (12.1) is only available to RX6000 series of AMD cards, Nvidia RTX cards have it as standard.

A bit of information on DX12 (12.1) https://www.pocket-lint.com/games/news/pc-gaming/160907-what-is-directx

**Comment by AmenMoses** [comment] 2022-09-07 19:19
Why can't the supported level be auto-detected and only turn on the 12_1 functionality if the card supports it?

That way the 12_0 owners will still be supported but will just lose out on some features.

**Comment by synchromesh62** [comment] 2022-09-07 19:32
> Why can't the supported level be auto-detected and only turn on the 12_1 functionality if the card supports it?
> 
> That way the 12_0 owners will still be supported but will just lose out on some features.

That would be ideal .. 
Right now when the DX12 version goes live i will not be able to run it and a new card is out of the question for me at the moment.

**Comment by Tam51** [comment] 2022-09-07 19:38
I have AMD RX480 so looks like I won't be able to use it if it goes to DX12 and it's the same here a new card is out of the question for me at the moment
![DX12](https://user-images.githubusercontent.com/93008801/188962342-048708f4-595a-4afc-a5f4-60a7d4462c87.jpg)

**Comment by plemsoft** [comment] 2022-09-08 08:32
@synchromesh62 @Tam51 Could you try to download wicked engine , and let me know if its able to run ?
https://store.steampowered.com/app/1967460/Wicked_Engine/

@LeeBamberTGC I think Janos has added support for D3D_FEATURE_LEVEL_12_0 in the latest repo :)

**Comment by plemsoft** [comment] 2022-09-08 09:34
@LeeBamberTGC TGC wicked repo already set capabilities = based on the _12_1 features if available. CONSERVATIVE_RASTERIZATION,RASTERIZER_ORDERED_VIEWS
So just adding this should work :)

`
...
// ignore software adapter and check device creation succeeds
if (SUCCEEDED(D3D12CreateDevice(dxgiAdapter1.Get(), D3D_FEATURE_LEVEL_12_1, __uuidof(ID3D12Device), nullptr)))
{
	break;
}
...
//Add
if (SUCCEEDED(D3D12CreateDevice(dxgiAdapter1.Get(), D3D_FEATURE_LEVEL_12_0, __uuidof(ID3D12Device), nullptr)))
{
	break;
}

`

**Comment by Tam51** [comment] 2022-09-08 10:23
> > @synchromesh62 @Tam51 Could you try to download wicked engine , and let me know if its able to run ? https://store.steampowered.com/app/1967460/Wicked_Engine/
> > @LeeBamberTGC I think Janos has added support for D3D_FEATURE_LEVEL_12_0 in the latest repo :)
> 
> Hi Preben Yes i am able to run the steam version of Wicked

Hi yes I'm able to run the steam version of Wicked engine

**Comment by LeeBamberTGC** [comment] 2022-09-08 12:18
Hi All, some great feedback here. Looks like we are going to be able to support ALL DX12 cards :)

**Comment by synchromesh62** [comment] 2022-09-08 12:49
> 

Well i was excited but hit a downer :(
message replaced with this one ?

![F1](https://user-images.githubusercontent.com/35708217/189125903-f4621433-bc7d-4e5a-a04f-4220dcef9540.png)

**Comment by LeeBamberTGC** [comment] 2022-09-08 13:32
@synchromesh62 Okay, new EXP build, Second time's a charm..

**Comment by synchromesh62** [comment] 2022-09-08 14:00
> @synchromesh62 Okay, new EXP build, Second time's a charm..

AND WE HAVE A WINNER !!
Awesome ..Thanks Lee and Preben .. Beginning to think i was gonna lose out then :)

**Comment by Granada1** [comment] 2022-09-08 14:04
Great team wok guys 👍

**Comment by LeeBamberTGC** [comment] 2022-09-08 14:59
@synchromesh62 Can you make a short video loading one of the demo levels, thanks!

**Comment by synchromesh62** [comment] 2022-09-08 15:20
> @synchromesh62 Can you make a short video loading one of the demo levels, thanks!

Here ya go Lee
Loading a stock map ... 
The same thing happens from the Hub when i try to edit a map like it just cannot finish loading.
However tried a couple new biomes and saved and they reloaded fine ?
https://youtu.be/I3w9essM58U

**Comment by LeeBamberTGC** [comment] 2022-09-08 15:46
@synchromesh62 Can you go through the HUB and load the SWITCH ESCAPE demo, and then test game. I do not test the Load Level direct from the editor so this might be another kind of bug.

**Comment by LeeBamberTGC** [comment] 2022-09-08 16:48
@synchromesh62 Hmm, looks like the GPU is hitting something nasty and crashing, probably a bug at this point in some of the code running graphics but will be hard to log this one.  I am looking to buy the same card as you so will need the exact model and brand. I was looking on eBay, can you find a UK listing that matches your card exactly, thanks: https://www.ebay.co.uk/sch/i.html?_from=R40&_trksid=p2380057.m570.l1313&_nkw=AMD+RX580&_sacat=0

**Comment by synchromesh62** [comment] 2022-09-08 19:02
Hi Lee 
This is the exact card i have
MSI-Radeon RX580 Armour 8G OC Graphics Card.
This one is at a low bit. others listed are around the £150 to £200 mark.
It seems a lot for just my one report .. Perhaps open up the experimental first to anyone without the need for the password or find a user with the same card .. Ideally before jumping the gun it may pay to get more reports of the issue from AMD users. 

https://www.ebay.co.uk/itm/374240578200?epid=8009472402&hash=item57227a0a98:g:rggAAOSwShljFIgh&amdata=enc%3AAQAHAAAAoC6iEiKggZiD1RptqQw36IpfbLmpU9npKggNEN0Q7qyuu3b1PeU%2FMGYQKGW2vmH5yuNBX5Ojh0h1u9EjP3AvobUFF4ariguKBl1%2BAnIh3z%2BAsFKoeGgPDdSBppGDqZIf%2BB0dMX8nNIzvkEE919oLRMZZ6wNyOsjLpW1Gzv1wo%2BrTMr02uigNtv%2BVWDFMbETu%2BETJ%2FdoJYzUJD8bHL%2FLXN4o%3D%7Ctkp%3ABk9SR86hlefjYA

**Comment by LeeBamberTGC** [comment] 2022-09-08 19:51
@synchromesh62 I may get a good deal so put in a bid. I do need an AMD card anyway and the low-end DX12 is a good min spec to have around.

The trickyt part is finding the line of code causing the silent crash out.  I have attached a DEBUG build of the latest. Make a backup and use these files to overwrite, it might provide an error message with more info. Send a shot if so.

Link: https://drive.google.com/file/d/1Ifvzm_4tw4EiYsMQNhm01q-7D_RQ76iO/view?usp=sharing

**Comment by AmenMoses** [comment] 2022-09-08 20:31
Missed a trick there, I'd have said "I'll send you my RX580 if you buy me a replacement RTX 2070"

**Comment by synchromesh62** [comment] 2022-09-08 20:46
@LeeBamberTGC 
Getting a XCOMP140D.DLL was not found error using the debug
Tried downloading a couple but no luck. Can you point me to the required version ?

**Comment by LeeBamberTGC** [comment] 2022-09-09 16:12
@synchromesh62 Looks like you would need the debug DLLs. You will need to install the REDIST files for VC 140 (the debug ones). I get them when installing Visual Studio 2017 community edition, but maybe you can find just the REDIST debug one.

I am winning the bid at £92 right now, do you think that is a good price for yours?  Happy to cancel if you want to sell yours for that price, I doubt that could buy you a 2070 but it might help take a bite out of the cost.

**Comment by synchromesh62** [comment] 2022-09-09 19:21
> @synchromesh62 Looks like you would need the debug DLLs. You will need to install the REDIST files for VC 140 (the debug ones). I get them when installing Visual Studio 2017 community edition, but maybe you can find just the REDIST debug one.
> 
> I am winning the bid at £92 right now, do you think that is a good price for yours? Happy to cancel if you want to sell yours for that price, I doubt that could buy you a 2070 but it might help take a bite out of the cost.

Its an awkward position for me to be in ... Not sure how many use the experimental but my Biggest worry right now is mine is the only report of this issue. This could mean my card is faulty ( in which case i could not sell it anyway ) 
Its also a worry for me you purchase that card on Ebay and it works just fine for you again meaning its my card with the issue and you just wasted good money on purchasing one.

When DX12 goes live and if there are still no reports then that would confirm it is indeed probably my card..
However if there are suddenly 20 reports of maps not loading or crashing from AMD users then it would at least confirm its something in Max. They can always roll back if this is the case until its sorted but at least it would not just be my report :)

**Comment by AmenMoses** [comment] 2022-09-10 09:57
Do you have the latest drivers installed?

It's possible that you are the only user of the experimental build with that particular card though.

**Comment by synchromesh62** [comment] 2022-09-10 10:53
> 

Yes the first thing i tried even before reporting was to double check i had the latest Adrenaline Drives installed and Windows 11 was fully updated. However when i did update from Win10 to Win 11 i did it over a period of a few days on a **separate** Drive   until i mirrored my Win10 setup and just swapped them so i do still have that drive as a backup. What i will try is putting it back in and testing from Win10.
Its a good idea .. Pretty much the only thing i have not tried. Thanks Amen :)

**Comment by synchromesh62** [comment] 2022-09-10 12:08
@LeeBamberTGC 
Ok not so good news for me unfortunately ... So i replaced my Win 11 drive with my Win 10 and although i got the exact same issue i did get a debug prompt from the AMD software that does not appear in Windows 11. 
As the Video below shows it would appear to be my card so i think your safe to cancel the purchase on Ebay. 
https://youtu.be/8h8TI1g1PxM

**Comment by LeeBamberTGC** [comment] 2022-09-10 16:13
@synchromesh62 I have canceled the bid for now. Would be interested to learn if any more AMD DX12_0 cards out there have the exact same issue of initially running then crashing out.

**Comment by synchromesh62** [comment] 2022-09-10 19:23
> @synchromesh62 I have canceled the bid for now. Would be interested to learn if any more AMD DX12_0 cards out there have the exact same issue of initially running then crashing out.

Hopefully its just me ... 
No others so far but if there is a prob it will likely show up when DX12 goes live.

**Comment by earthling45** [comment] 2022-09-11 10:59
I think that there are going to be others too, after reading up on this there seems to be many who experience time outs while gaming with AMD cards.
https://appuals.com/amd-driver-timeout-windows/

**Comment by earthling45** [comment] 2022-09-11 11:05
When i did run afterburner in the background and run the horseshoe bend demo, my cpu was maxed out during loading for a short time.
I think (though not sure of course) that occurs during the creation of the physics nav mesh, this might cause it?

**Comment by AmenMoses** [comment] 2022-09-11 13:44
Lot's of things to try in that link earthing45 posted, I think the last couple of things it suggests will be most likely to be the fix.

**Comment by LeeBamberTGC** [comment] 2022-09-12 18:16
NOTE: Just an update. I am resolved to getting this card and reproducing here, this will ensure I can fix the correct thing and confirm the fix too (I suspect it will also fix other similarly silent random GPU-related crashes too).

**Comment by ZakJudges** [comment] 2023-02-16 09:38
closing this issue, was from DX12 verision

**Closed by ZakJudges** 2023-02-16 09:38 UTC
Labels: bug, help wanted, Urgent, Fixed but need confirmation., Max, High
