### ISSUE TITLE
Guide character file does not match

### ISSUE THREAD

**Issue by igor-gouveia** [TheGameCreators/GameGuruRepo#2867] opened 2022-04-15 15:22 UTC
The file in "GameGuru MAX\Guides\Characters" directory does not match with the .dbo file used in game guru max. The name and rotation of bones are different. I appreciate if you can fix this so the community can create custom parts.

I renamed the bones but the rotation is still different.
![image](https://user-images.githubusercontent.com/55865487/163588638-60aa9920-758c-4951-8dbf-4221b60e2e5b.png)

Thank you very much for your attention!

**Comment by Necrym59** [comment] 2022-04-17 03:21
So whats wrong with it :) rather handsome i think.

**Comment by rvanner** [comment] 2022-04-19 10:41
@bond1mjb Can you check and see if these files need updating?

**Comment by bond1mjb** [comment] 2022-04-19 14:26
@rvanner @igor-gouveia     I unzipped the "base female bldner.rar" file in the "GameGuru MAX\Guides\Characters" directory and imported the FBX file, and also checked it out in blender and all looks good here on my end.  @igor-gouveia  Could you explain in more detail how to reproduce the problem in your screenshot?
![fbximport](https://user-images.githubusercontent.com/87768878/164026817-abb41a04-885e-42ea-974c-d9f76ceebd36.jpg)

![blend](https://user-images.githubusercontent.com/87768878/164026873-e6c64898-52d2-4ab4-8143-a5eeb8341d25.jpg)

**Comment by igor-gouveia** [comment] 2022-04-19 14:34
The 3d model skeleton doesn't match when you remove the animations and import the animations .dbo file which is in the "GameGuru MAX\Guides\Characters" directory

When you do this you will see that not all bones work, because their name is wrong

When you rename all bones in the skeleton for example from "Bip01 Ponytail1" to "Bip01_Ponytail1", all bones work, but it looks like I showed.

**Comment by igor-gouveia** [comment] 2022-04-19 14:37
About the last post, sorry the correct directory where are the animations to import is "GameGuru MAX\Files\charactercreatorplus\parts\adult female" directory, and the file name with the animations is "default animations.dbo"

**Comment by bond1mjb** [comment] 2022-04-19 15:38
@igor-gouveia Ok I see what you are trying to do  We are using the .X format for all character and animation exports, and the exporters we use automatically replace all spaces with underscores in the bone names.   

About the rotations being wrong.   Gameguru MAX uses a left-handed, Y-up coordinate system, while 3ds Max (and Blender) uses a right-handed, Z-up coordinate system.   When we export the characters and animations, the exporter automatically converts the coordinate system into what GGMAX uses.

The reason the rotations are wrong is because the base character is provided in the original right-handed coordinate system, while the animation DBO files have already undergone the conversion to the left-handed coordinate system that MAX uses.   

I know that doesn't really help, but this character was originally made in 3ds Max, converted to Blender, and provided as a template for users to see how the character was constructed.   To use any of the animations files, the character would first need to be exported using an exporter that supports the conversion from right-handed -->left-handed coordinate systems.   

To use the animation files, I think the only way at the moment is to first export the character to .X format, then import into GGMAX and apply the animations.   That way both the character and animations will be in the same coordinate system.

**Comment by ZakJudges** [comment] 2023-01-27 13:37
This is likely fixed now as part of work on #3487

**Closed** 2023-02-16 09:26 UTC
Labels: bug, Fixed but need confirmation., Max, Medium, Assets
