### ISSUE TITLE
MAX - Bug - EXP build - Cant connect levels with 'next level' in storyboard editor

### ISSUE THREAD

**Issue by GavinIssooocoool** [TheGameCreators/GameGuruRepo#4500] opened 2023-04-19 14:50 UTC
When i try to connect my levels in the storyboard editor it doesnt work, ive tried copying the levels but that didnt work either. Please help!!

**Comment by davetgc** [comment] 2023-04-22 15:13
Can you please try verifying MAX files on Steam.

**Comment by GavinIssooocoool** [comment] 2023-04-22 16:33
Yea that was the first thing i did when this started, i tried again earlier but it still didnt work. usually if i make a copy of the level it let me connect them but not for these 2. Also, this started happening when i exported my game standalone if that helps

**Comment by GavinIssooocoool** [comment] 2023-04-22 23:04
Heres an example of whats happening, just kinda cancels out

https://user-images.githubusercontent.com/32985460/233811225-ba85790b-351b-41d7-b920-fe31f096bba3.mp4

**Comment by plemsoft** [comment] 2023-04-24 14:55
@GavinIssooocoool Thanks for reporting this issue, could you zip you the project folder like "c:\Users\USERNAME\Documents\GameGuruApps\GameGuruMAX\Files\projectbank\PROJECTNAME" and e-mail me a download link e-mail plemsoft@gmail.com , this will allow me to see what the problem is , Thanks for your help :)

Please mention this issue number in the e-mail: 4500

**Comment by plemsoft** [comment] 2023-04-25 07:45
@GavinIssooocoool Thanks for the e-mail , this has been fixed and will be in the next EXP build :)

**Comment by GavinIssooocoool** [comment] 2023-04-25 19:32
Alright, thanks!!!

**Closed** 2023-04-25 19:33 UTC
Labels: bug, Fixed but need confirmation., Max, High, Storyboard Editor
