### ISSUE TITLE
Can not download GGmax files.  ( File list failed to parse )

### ISSUE THREAD

**Issue by Pcskiller** [TheGameCreators/GameGuruRepo#907] opened 2021-02-28 17:31 UTC
I have downloaded the latest small installer.exe
as soon as i want to download GGMax files i get an error. :.. File list failed to parse
https://forum.game-guru.com/thread/222488#msg2638413

**Comment by rvanner** [comment] 2021-03-15 15:47
@Pcskiller Is this still an issue for you? Have you tried the latest version of the installer?

**Comment by rvanner** [comment] 2021-03-15 15:55
@Pcskiller Is this still an issue for you with the latest Tiny Installer?

**Comment by Pcskiller** [comment] 2021-03-15 16:05
Hi. i am at the work right now, i get of in about 2 hours, Wil download the
installer again and test. but up to the point were i have reported it, i
have not tested again, do not know if there were a new installer over the
last week or two.

**Comment by rvanner** [comment] 2021-03-15 16:27
@Pcskiller  OK, I look forward to hearing back from you. If it does fail, can you make a video of what happens?

**Comment by Pcskiller** [comment] 2021-03-15 16:35
ok. i will

**Comment by GraPhiX-Guru** [comment] 2021-03-22 12:04
I can confirm this error on another system this system is based in UK

**Comment by GraPhiX-Guru** [comment] 2021-03-22 16:05
@Pcskiller  can you try the install again i think the issue is now fixed

**Comment by Pcskiller** [comment] 2021-03-23 08:16
Thank you so much it is downloading as i am typing here right now.
Please Say thanks to anyone who had an input to this problem

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by rvanner** [comment] 2021-03-23 08:20
Great to hear! I am marking this as fixed now.

**Comment by Pcskiller** [comment] 2021-03-23 13:32
Great, thanks.

**Closed** 2021-08-14 09:34 UTC
Labels: fixed, Max
